### ISSUE TITLE
Rename "Video" to "Streaming Video" or "Digital Video"

### ISSUE THREAD

**Issue by slknight** [CARLI/vufind#101]
Video is confusing as it could mean VHS or Movie.

Some word to indicate online availability needs to be in the name of the format.

**Comment by gibsonjc** [comment]
CARLI's custom formats from VuFind 0.6 (https://www.carli.illinois.edu/products-services/i-share/opac/vf-formats) (with a few new additions) have now been implemented in VuFind 3 and there is a "Digital Video" format.
