### ISSUE TITLE
Sensor Image format problematic

### ISSUE THREAD

**Issue by slknight** [CARLI/vufind#102]
From a patron perspective, "Sensor Image" is meaningless

But that's a minor issue.

The majority of items are ariel photos or GIS data, but there are also these times that seem unrelated to geography or imaging

Many of the odd records are 16 mm film. examples
https://vufind3-test.carli.illinois.edu/all/vf-eiu/Record/213749926
https://vufind3-test.carli.illinois.edu/all/vf-eiu/Record/252808406#details

VHS 
https://vufind3-test.carli.illinois.edu/all/vf-eiu/Record/200286859#description

Game/Kit
https://vufind3-test.carli.illinois.edu/all/vf-eiu/Record/250367819#description

This format type appears to be pulling from the 933 field.
933             |a Remote-sensing image  |1 NyRoXCO  

Noticed film or other records as Sensor Image from UIC, SIE, GSU, OAK, NLU,

**Comment by gibsonjc** [comment]
"Sensor Image" was a default format in the out-of-the-box VuFind 3 software. CARLI custom formats are in place now so this term should not be appearing anywhere.
