### ISSUE TITLE
blank gif placeholder image instead of "No Image Available"

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#103]
For cover images, can we use the 1x1 blank gif placeholder image like in the current version of VuFind instead of the "No Image Available"?

EIU - (moved this suggestion from #61 :  slknight - Looking Good! Since I'm fussy, can we get a blank placeholder image instead of the "No Image Available" one? I like the 1x1 blank gif in the current version better.)

**Comment by bgant** [comment]
TIU - Do we know if in VuFind 3 we'd have the ability to hide "no image available" image? I imagined that the image placeholder would disappear for libraries who didn't purchase images (like it currently does now).

**Comment by bgant** [comment]
Revisit after Syndetics is up and running.

**Comment by gibsonjc** [comment]
TIU- If we don't pay for images, is it still possible to hide the "no image available" image? Could we have this hidden until we get cover images straightened out?

RT 89662

**Comment by gibsonjc** [comment]
TIU - is there a timeline for developing a solution for hiding the "no image available"? This issue seems to be a critical one for us to begin using VuFind 3. We received a quote for the cost of image subscription, but we won't be able to subscribe to this service longterm.

**Comment by gibsonjc** [comment]
I just realized there were two Issues for the same problem, so I'm consolidating to the older one and closing newer Issue #144 as a duplicate.

In the config.ini, in the [Content] stanza:

> ;  Otherwise, you can use noCoverAvailableImage to specify a
; path relative to the base of your theme directory for a static image to display.
noCoverAvailableImage = images/noCover2.gif

Please get the blank image from VuFind 0.6 (called 1x1.gif) and copy it to vufind3 and point to it in the config.ini to replace this default, wordy noCover2.gif.

**Comment by cedelis** [comment]
Ready for testing on DEVEL. If all looks well, I can then promote to TEST.

**Comment by gibsonjc** [comment]
Yes, looks good to me, please move to TEST!

**Comment by dgree1** [comment]
Looks fine in test to me.

**Comment by gibsonjc** [comment]
Ready to move to Production. This looks good to me in the Results list display. (It makes for a rather empty-looking Similar Items tab section sometimes, but I'm going to create a new Issue to turn that feature off anyway.)
