### ISSUE TITLE
Index MFHDs along with BIBs

### ISSUE THREAD

**Issue by cedelis** [CARLI/vufind#108]
Information such as Location and Call Number is found in MFHD records. Features such as faceting and search results display (not incl. Detailed Record display where MFHD information is generally available) are dependent on these fields being indexed rather than looked up in realtime.

**Comment by gibsonjc** [comment]
@cedelis Is indexing of MFHDs needed for this information regardless of if we use the NCIP driver or the (modified) Voyager Restful driver?

**Comment by cedelis** [comment]
I should have specified that not all of the MFHD would need to be indexed, just Call Number and Location (for now).

**Comment by gibsonjc** [comment]
Closing; this has been done.
