### ISSUE TITLE
Clear Cache Directories on Reboot

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#109]
The following command may need to be added to an /etc/init.d/vufind script to clear out the cache directories when the Apache server is rebooted:

for i in `ls -d vf-* all/vf-*`; do
    rm -rf ${i}/cache && mkdir ${i}/cache && chown www-data ${i}/cache;
done

**Comment by cedelis** [comment]
Added utility script to cron job.
commit 1a61fc3b68c228a67b34ba855997b22a14847a7f

**Comment by dmcmpbll** [comment]
What can I do to help test this?

**Comment by bgant** [comment]
Here's some more background...

On June 21st the server stopped returning search results. Rebooting the server had no effect. Delis ran the command above to clear out the "cache" in all the library instances to restore service.

I don't know the implications of clearing the cache, so we need to know what that really means for the users.

Regardless, if the service stops working we need to be able to restart it or reboot the server to get things working again. So the /etc/init.d/vufind script is probably the best place to automatically clear things out that could be causing the service to fail.

**Comment by cedelis** [comment]
When template code is updated (via git), it's always a good idea to clear out the cache. I don't think it's directly related to apache or server restarts. That being said, clearing out the cache more often, e.g., during reboots, isn't a bad idea.

**Comment by gibsonjc** [comment]
This should have been closed some time ago...  Closing.
