### ISSUE TITLE
"Descriptive content provided by Syndetics..." display note

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#112]
The final note after Syndetics content “Descriptive content provided by Syndetics, a Bowker service” is lacking in 3.0 for the Author note. Was this something we added to VuFind 0.6 to help explain the origin of the content when Syndetics matching goes wrong?

[The Terms of Service link is also missing.]

Author Note/Summary note example:
0.6: http://vufind.carli.illinois.edu/all/vf/Record/1586784/Description
3.0: https://vufind3-devel.carli.illinois.edu/all/vf-aru/Record/250247558#description

NS 6/23

**Comment by gibsonjc** [comment]
Example of note missing from Reviews:
0.6 example: http://vufind.carli.illinois.edu/all/vf/Record/1355846/Reviews
3.0 example: https://vufind3-devel.carli.illinois.edu/all/vf-aru/Record/250106359#reviews

**Comment by gibsonjc** [comment]
This was resolved with the work on #113 and #114 . Closing!

**Comment by gibsonjc** [comment]
I was wrong about closing this one... It looks like we got the note to display in the new Summaries and TOCs in #113 and #114, but it is still not displaying for Authors or Reviews.  
@cedelis Can it be added in the same way to those?

Examples:
https://i-share-devel.carli.illinois.edu/all/vf-uiu/Record/335461105#reviews
https://i-share-test.carli.illinois.edu/all/vf-uiu/Record/274953845#reviews
"painted panorama" (OCoLC)43868010

https://i-share-devel.carli.illinois.edu/all/vf-aru/Record/276933342#description
https://i-share-test.carli.illinois.edu/all/vf-aru/Record/276933342#description
"Communicating effectively : tools for educational leaders" (OCoLC)52477099

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
@nmswanson Could you have a look at the above and other examples and let us know if this looks good to you?  Thanks!

**Comment by nmswanson** [comment]
These look good! "Descriptive content provided by Syndetics™, a Bowker service" is displaying on test but not devel. 

This seems fine, but I just want to point out one difference between New VuFind and 0.6 in regard to the Summary and Author Notes. In New VuFind, the Summary now displays higher on the page, ahead of the Physical Description/Bibliography/ISBN, but Author Notes display after them. In 0.6, both Summary and Author Notes displayed after this information. 

[https://i-share-test.carli.illinois.edu/all/vf-aru/Record/276933342#description](https://i-share-test.carli.illinois.edu/all/vf-aru/Record/276933342#description)
[https://vufind.carli.illinois.edu/all/vf/Record/1586784/Description](https://vufind.carli.illinois.edu/all/vf/Record/1586784/Description)

**Comment by gibsonjc** [comment]
Thanks, @nmswanson !  This is ready for Prod!  
Side note: We can likely address the order of field display with the other field display improvements we are working on.

**Comment by cedelis** [comment]
In PROD
