### ISSUE TITLE
Add SFX results

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#123]
UIU - I was looking at University of Chicago's VuFind and was wondering if it is possible to add in the SFX results to the display of results (both brief and full) like University of Chicago has: (see 1 and 2 in this results list) https://catalog.lib.uchicago.edu/vufind/Search/Results?lookfor=american+journal+of+psychology&type=Title . If it is possible, I know that UIUC Library would be very supportive of having this feature added.

**Comment by gibsonjc** [comment]
From https://vufind.org/wiki/configuration:openurls

Configuring Link Resolvers

"See the [OpenURL] section of config.ini for the available settings for interacting with link resolvers. VuFind can operate in a simple mode where OpenURLs are linked to an external link resolver, and it also supports an “embedded” mode for certain resolvers in which resolver results can be embedded directly into the VuFind results. To support embedded mode for a new resolver, you can implement a custom link resolver driver."

**Comment by gibsonjc** [comment]
Done on devel.  Currently checking into the options configurable in the config.ini.

**Comment by gibsonjc** [comment]
Initial set up complete but see also #146 and #152 about further configuration options.

Also, I think the definition for ISSN will need to be changed because ISSN is too broad both for searching and for SFX linking purposes.

**Comment by dgree1** [comment]
Jessica, do you need any more testing on this issue 123?
The SFX committee  is available to test or help as they are able.

**Comment by gibsonjc** [comment]
SFX buttons display in the results list and the single record page.  Closing this older Issue.
