### ISSUE TITLE
Add libs and remove libs from drop-down menu

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#125]
On vufind3, vufind3-test, and vufind3-devel, on the main page drop-down menu,

Please add the three new libs to the list:

Black Hawk College - bhc
Meadville Lombard Theological School - mls
South Suburban College - ssc

Please remove these two libraries from the list that are no longer in I-Share:

Harrington College of Design - hcd
Kendall College  - ken

**Comment by cedelis** [comment]
In production.
