### ISSUE TITLE
clicking "more" in the Narrow Search list produces error

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#128]
If you click on "more" beneath any of the categories displayed in the Narrow Search list, you are taken to a new page where the word 'false' is displayed.

Replication steps:
1. Do a search
2. On the results page, click on any of the "more" links from the Narrow Search list
3. A blank page with the word "false" is displayed.  The URL in the browser address bar now reads:
javascript:moreFacets('narrowGroupHidden-format')

**Comment by cedelis** [comment]
After pulling down the latest code from vufind.org, this bug no longer exists. I'm pretty sure it was fixed by the VuFind dev team.

**Comment by gibsonjc** [comment]
This is fixed on devel but not on prod or test, so I think I'll open this back up to keep track of that.

**Comment by gibsonjc** [comment]
Closing; done on all servers.
