### ISSUE TITLE
Results list display with "Search Result Highlighting" in Subjects is annoying and confusing

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#135]
CTU - In the Results list where there are subjects, I find the " at beginning and end of subjects to be annoying and confusing.. Further, there is no punctuation between heading and subheading in subjects in Results list. I'd rather have subjects completely deleted in Results list as they currently are in VuFind.

**Comment by gibsonjc** [comment]
This is due to Search Result Highlighting showing where the search terms were found in the record.  https://vufind.org/wiki/configuration:highlighting

**Comment by gibsonjc** [comment]
![screen shot 2016-10-19 at 9 31 32 am](https://cloud.githubusercontent.com/assets/17598357/19524031/0212f3e2-95e2-11e6-9773-ddae1f879a9c.png)

**Comment by cedelis** [comment]
Highlighting has been removed. In devel.

**Comment by cedelis** [comment]
Highlighting reinstated.

**Comment by gibsonjc** [comment]
ONU - When you do a search, the search results page seems cluttered and distracting with the search term highlighted multiple times for every result.  Do we really need a partial excerpt from the table of comments showing where my search word was found?

**Comment by gibsonjc** [comment]
MIL - personally prefer cleaner look of search results screen on current VF version, though I appreciate the attempt to highlight where the search term(s) are being found (TOC, subjects, etc.).

**Comment by gibsonjc** [comment]
Turns out this was a duplicate of #72 . We have decided to leave the highlighting feature on and "as is" for now. Closing.
