### ISSUE TITLE
245 $n and $p should display in results list

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#136]
ISU - In VuFind 3, the subfields ‡n and ‡p in the 245 title field do not appear in the results set. In our current VuFind 0.6, these subfields do appear in results sets.  Having the additional subfield title data in the Results display will enable a user to distinguish between items, otherwise they have to click into each item.

Units of study in argument, information, and narrative writing. ‡n Grade 6 / ‡c Lucy Calkins with Colleagues from the Reading and Writing Project.

In VuFind 3:
https://vufind3.carli.illinois.edu/vf-isu/Search/Results?lookfor=Units+of+study+in+argument%2C+information%2C+and+narrative+writing.&type=Title&limit=20&sort=relevance

VuFind 0.6:
https://vufind.carli.illinois.edu/vf-isu/Search/Home?lookfor=units+of+study+in+argument&type=title&start_over=1&submit=Find&search=new

Fruits basket. ‡n Volume 16 / ‡c by Natsuki Takaya ; [translation, Alethea Nibley and Athena Nibley ; English adaptation, Lianne Sentar ; retouch and lettering, Dongjin Oh ; production artist, Jihye "Sophia" Hong]

In VuFind 3:
https://vufind3.carli.illinois.edu/vf-isu/Search/Results?lookfor=fruits+basket&type=Title&limit=20&sort=relevance

VuFind 0.6:
https://vufind.carli.illinois.edu/vf-isu/Search/Home?lookfor=fruits+basket&type=title&start_over=1&submit=Find&search=new

Avatar: ‡b the last airbender. ‡p The rift / ‡c Gene Luen Yang, script ; Gurihiru, art & cover ; Michael Heisler, lettering

VuFind 3:
https://vufind3.carli.illinois.edu/vf-isu/Search/Results?lookfor=avatar+last+airbender+&type=Title&limit=20&sort=relevance

VuFind 0.6:
https://vufind.carli.illinois.edu/vf-isu/Search/Home?lookfor=Avatar%3A+the+last+airbender&type=title&start_over=1&submit=Find&search=new

**Comment by gibsonjc** [comment]
Research:  I think I can explain why 245np do not display in the results list, but I'm not sure how to change it.

The results list is generated by 
/themes/bootstrap3/templates/RecordDriver/SolrDefault/result-list.phtml
Which contains function getTitleHtml starting at line 24:

    <?=$this->recordLink()->getUrl($this->driver)?>" class="title getFull" data-view="  
    <?=$this->params->getOptions()->getListViewOption() ?>">
              <?=$this->record($this->driver)->getTitleHtml()?>



Which is defined in /module/VuFind/src/VuFind/View/Helper/Root/Record.php at line 333 as:

     /**
     * Get HTML to render a title.
     *
     * @param int $maxLength Maximum length of non-highlighted title.
     *
     * @return string
     */
    public function getTitleHtml($maxLength = 180)
    {
        $highlightedTitle = $this->driver->tryMethod('getHighlightedTitle');
        $title = trim($this->driver->tryMethod('getTitle'));
        if (!empty($highlightedTitle)) {
            $highlight = $this->getView()->plugin('highlight');
            $addEllipsis = $this->getView()->plugin('addEllipsis');
            return $highlight($addEllipsis($highlightedTitle, $title));
        }
        if (!empty($title)) {
            $escapeHtml = $this->getView()->plugin('escapeHtml');
            $truncate = $this->getView()->plugin('truncate');
            return $escapeHtml($truncate($title, $maxLength));
        }
        $transEsc = $this->getView()->plugin('transEsc');
        return $transEsc('Title not available');
    }

Which refers to getTitle and getHighlightedTitle both in
/module/VuFind/src/VuFind/RecordDriver/SolrDefault.php

line 652:

    public function getHighlightedTitle()
    {
        // Don't check for highlighted values if highlighting is disabled:
        if (!$this->highlight) {
            return '';
        }
        return (isset($this->highlightDetails['title'][0]))
            ? $this->highlightDetails['title'][0] : '';
    }

line 1361:

    public function getTitle()
    {
        return isset($this->fields['title']) ?
            $this->fields['title'] : '';
    }

Which both look at the 'title' field.

And 'title' is defined in our local marc_dedup_local.properties and marc_dedup_uc.properties files as 245ab

**Comment by nmswanson** [comment]
Technical Services Committee-
245 $n and $p in bib record should display in results list.
Details: In New VuFind, $n and $p do not display in results list. Adding the display of this field will make it easier to choose the correct record the first time instead of having to click on each individual record, especially since there is no ability to click on "Next Record." The result list should display in $a, $b, $n and $p order regardless of how they are entered within the 245.  

Annual Project Recommendation no.9

**Comment by nmswanson** [comment]
Technical Services Committee-
Display bib 245 $a, $b, $n, $p in proper order in results list. 
Details: In New VuFind, the 245 $a, $b, $n, $p are not sorting in the correct order, which causes the results to be incorrectly sorted. The same title and year, but different editions, should appear next to each. Currently, if a title is cataloged with the exact same title, but differs in edition statement, it does not display below the other as it previously did in VuFind 0.6.  

Annual Project Recommendation no.18

**Comment by gibsonjc** [comment]
@cedelis The URL examples in the original entry for this Issue are still good examples in TEST and Prod.  

Ideally, in the Results list the Title would display the 245 $a $b $n $p subfields in that order.  
Right now in New VuFind it is only displaying the 245 $a $b in the Results list.

**Comment by cedelis** [comment]
@gibsonjc Unfortunately, I would need to update our indexing properties to include 245  $n and $p for 'title'.  This would require a complete re-index.

Or, instead, I could configure VuFind to show 'title_full' instead of 'title' in the Results list. I have temporarily made this change to DEVEL. Not sure if that would be better or worse than what's there now. It seems better for this example, anyway:

https://i-share-devel.carli.illinois.edu/vf-isu/Search/Results?lookfor=Units+of+study+in+argument%2C+information%2C+and+narrative+writing.&type=Title&limit=20&sort=relevance

What do you think? Is showing 'title_full' instead of 'title' acceptable? Or do we need to re-index with a new 'title' definition (which includes $n and $p)?

**Comment by cedelis** [comment]
@gibsonjc EDIT: I moved this change to the TEST server (need DEVEL to do other work):

https://i-share-test.carli.illinois.edu/vf-isu/Search/Results?lookfor=Units+of+study+in+argument%2C+information%2C+and+narrative+writing.&type=Title&limit=20&sort=relevance

**Comment by gibsonjc** [comment]
@cedelis Thanks.  Hmmm, 'title_full' helps to display the $np but it also includes the 245$c, which we don't need to show because it is already showing on the next line in the Results list (and it nice there because the author is a clickable link).

I have reservations about changing 'title' to include $n and $p because I don't know all of the places that the 'title' field may be being used.  For example, if we did add $np to 'title', I think the single record page would display 245 $abnpnp because the template is adding the $np to that page's display in another way.

We may just need to create a new title field just for the Results list with 245 $abnp. Let me ponder this a bit more.

**Comment by gibsonjc** [comment]
Coming back to this one.  I wonder if we can use the method that /SolrDefault/core.phtml does in Line 35 

`<h3 property="name"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>`

to append on the getTitleSection info in /SolrDefault/result-list.phtml Line 24

`          <?=$this->record($this->driver)->getTitleHtml()?>
`

getTitleSection conveniently pulls out the 245$np which is exactly what we want to display in the Results list after the hotlinked 245$ab.

I can't figure out where getTitleHtml is defined, but it appears to be the 245$ab.  I wonder if it is using index fields or just pulling out the 245 field and subfields.  Can you find it anywhere? 

(Let me know if this idea is bananas.)

in Phase 2 of #265

**Comment by cedelis** [comment]
In TEST

@gibsonjc Your idea is not bananas at all. It's a great one! And it appears to do just the trick, e.g., 

https://i-share-test.carli.illinois.edu/vf-isu/Search/Results?lookfor=units+of+study+in+argument&type=Title&limit=20&sort=relevance

Here's the "gold standard" in version 0.6: https://vufind.carli.illinois.edu/vf-isu/Search/Home?lookfor=units+of+study+in+argument&type=title&start_over=1&submit=Find&search=new

**Comment by gibsonjc** [comment]
This looks good, Ready for Prod!

**Comment by cedelis** [comment]
In PROD
