### ISSUE TITLE
Change email "From" settings in config.ini (vufind3-devel)

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#139]
After the Feb. 15 meeting discussions, and after looking at what prod does now, I think we want to make a few changes in the [Mail] stanza of the config.ini on vufind3-devel. 

1. Automatically assign user's email to the To field.

; Should we put the logged-in user's address in the "to" field by default?
user_email_in_to = false

**Change to true**

2. Prepopulate the From field.

; Populate the "from" field with this value if user_email_in_from is false and/or no
; user is logged in:
;default_from = "no-reply@myuniversity.edu"

**Uncomment and change to noreply@carli.illinois.edu**

3.  Hide the From field altogether in the form.

; Should we hide the "from" field in email forms? If no from field is visible, emails
; will be sent based on user_email_in_from and default_from above, with the email
; setting from the [Site] section used as a last resort.
disable_from = false

**Change to true.  If the From address is pre-filled with what we want, it doesn't need to display, does it?**

**Comment by cedelis** [comment]
Changes made. In devel.

**Comment by cedelis** [comment]
Oops. I shouldn't have closed this. I should simply change label to 'ready for testing'.

**Comment by gibsonjc** [comment]
Closing; done on all servers.
