### ISSUE TITLE
Change display text when multiple call numbers in config.ini (vufind3-devel)

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#140]
At our meetings, we didn't like seeing one call number when multiple call numbers were present, but this is easily configurable in the [Item_Status] stanza:

[Item_Status]
; Usually, there is only one location or call number for each item; however, when
; multiple values are found, there are several possible behaviors:
;     first = display the first value found, ignore the rest
;     all   = show all of the values found, separated by commas
;     msg   = show a message like "Multiple Call Numbers" or "Multiple Locations"
;     group = show availability statuses for each location on a separate line,
;             followed by callnumber information (valid for multiple_locations only)
multiple_call_nos = first
multiple_locations = msg

Change multiple_call_nos = first to **multiple_call_nos = msg**

**Comment by cedelis** [comment]
Changes made. In devel.

**Comment by gibsonjc** [comment]
Closing; done on all servers.
