### ISSUE TITLE
Disable comments in config.ini (vufind3-devel)

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#141]
[Social]
; Comments may be "enabled" or "disabled" (default = "enabled")
comments = enabled

change to **comments = disabled**

**Comment by cedelis** [comment]
Changes made. In devel.

**Comment by dmcmpbll** [comment]
Yes, the Comments tab is removed from both the local view and the All I-Share view versions of vufind3-devel.

**Comment by gibsonjc** [comment]
Closing; done on all servers.
