### ISSUE TITLE
Hide the three "Browse by" options on the main page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#142]
At our Feb. 8 meeting we decided to hide/comment out from display the three "Browse by" options on the front page (such as vufind3-devel.carli.illinois.edu/vf-eiu):

Browse by Call Number
Browse by Language
Browse by Format

In Issue #56, Chris did something similar to hide only the Call Number one, but I'm not clear which file that was in.  Now we want all three suppressed.

**Comment by gibsonjc** [comment]
Ed says he can do this in the templates if that is the right place, but he isn't in the list of Assignees yet. I'll ask to get him added to this project.

**Comment by cedelis** [comment]
Please hold off on assigning this to Ed for now. It might be possible another way (need to check).

**Comment by cedelis** [comment]
But are we keeping the "Browse the Catalog" functionality?

**Comment by gibsonjc** [comment]
I've read through the config.ini and searches.ini and didn't find any options there, if that helps. :)

No changes to "Browse the Catalog" in this Issue.  This is just about not displaying the three "Browse by" options that are prominent on the *front* page.

**Comment by cedelis** [comment]
Done. In devel.

**Comment by gibsonjc** [comment]
For the record, which file did you have to edit to suppress these?

**Comment by cedelis** [comment]
https://github.com/CARLI/vufind/commit/0aced84d915391fe947f2bc4621f5d69026f01fd

**Comment by gibsonjc** [comment]
Closing; done on all servers.
