### ISSUE TITLE
display SFX (OpenURL) link settings to be in holdings data

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#152]
In the [Open URL] stanza, there is a setting to indicate where to display the Open URL links.  We'd like to have it display in the holdings data area as well as the search results (the "Get full text" link, or the SFX button if that is able to be set up in Issue #146 ).

; The following settings control where OpenURL links are displayed:
show_in_results = true      ; include in search results
show_in_record = false      ; include in core record metadata
show_in_holdings = false    ; include in holdings tab of record view

change to 

show_in_holdings = true    ; include in holdings tab of record view

**Comment by gibsonjc** [comment]
I noticed while reading the display templates that in /usr/local/vufind/themes/carli/templates/RecordTab/holdingsils.phtml there is a section commented out by CARLI which I think may have been done to block the unwanted displays of links with the label "Internet" well before we tried configuring the OpenURL settings for SFX (and under the days of the NCIP driver)?  So if you change the config.ini setting and nothing happens, maybe this is related since it says "openUrl"?

<! CARLI BEGIN comment out openUrlActive data !>

<! CARLI END comment out openUrlActive data !>

**Comment by gibsonjc** [comment]
SIE - It appears that you have to be at a list to see the link for Get full text.  I did a search on Journal of medicinal chemistry and got a list.
https://vufind3.carli.illinois.edu/vf-sie/Search/Results?lookfor=journal+of+medicinal+chemistry&type=AllFields&limit=20&sort=relevance
When I click on no. 1, the Journal of medicinal chemistry (a record for a print journal, that we also have electronic access to), I no longer see the Get Full text link.  I would have to go back to the list to be able to access the electronic version.  I’m not sure our patrons would remember to go back to the list.

**Comment by gibsonjc** [comment]
TRN - there is no link whatsoever to SFX on the record page (e.g. https://vufind3.carli.illinois.edu/vf-trn/Record/TRNdb.12834), which is especially problematic when we have electronic holdings available. I find the absence of an SFX link on the record page to be most problematic, as it will cause our users to believe we do not have content available that is, in fact, available (and that we’re paying for). [While we make use of the SFX A-Z list for title lookups, we need the SFX links in the catalog for those titles that have records so students who stumble across them know what is actually available.]

**Comment by slknight** [comment]
Working as a text link. Graphical SFX buttons would be preferable if possible.

![image](https://user-images.githubusercontent.com/15163837/28471608-52d56086-6e03-11e7-91c6-ca4b1bb9898f.png)

**Comment by dgree1** [comment]
Yes, me too see in holding rec. 
Ex. https://vufind3-test.carli.illinois.edu/vf-trn/Record/TRNdb.12834

or https://vufind3-test.carli.illinois.edu/vf-whe/Record/WHEdb.434590

Agree the graphical button would be preferable. Or even changing the text "Internet" to something like "Find it?" or "Get it full text?"

And tested for library NOT on SFX and link and "Internet" not show, 
ex. https://vufind3-test.carli.illinois.edu/vf-uic/Record/UICdb.699887

Thanks!

**Comment by gibsonjc** [comment]
When a bib generates an SFX "Get full text" link and also has a standalone bib 856$u in it, it appears to only display the "Get full text" link in the Internet section, which I think is good (I'm hoping that the presence of the "Get full text" link means that the bib 856$u doesn't display there on purpose?).
Example: https://vufind3-test.carli.illinois.edu/vf-uiu/Record/UIUdb.8212940

But when a bib does not generate an SFX "Get full text" link (UIC doesn't have SFX) and has a standalone 856 field, that 856$u appears in the Internet section, and I'm not sure that we want that because we want MFHD 856 fields to display all the needed information.
Example: https://vufind3-test.carli.illinois.edu/vf-uic/Record/UICdb.2359664

More testing needed.  I am going to set up some examples on TEST of the different variations to try to make sure we aren't missing anything with this "Internet" section since it may contain link resolver links or 856 fields...

(Side notes: 1. desire for graphical SFX buttons is a different Issue #146 and will not be addressed here.  2. Changing the word "Internet" to something else will also be a new Issue and will not be addressed here.)

**Comment by dgree1** [comment]
Jessica, do you need anything more from me about making a new Issue for
"2. Changing the word "Internet" to something else will also be a new Issue..."

Denise

**Comment by gibsonjc** [comment]
We have accomplished the purpose of this Issue: to get SFX links to display on the single record page in the Holding tab. Let's move this to Production and then work on the other unintended results of this change on new Issues (which I will create shortly):

1. Right now by default that means with the label "Internet"
2. any Bib 856s will also display with label "Internet" in the local catalogs
3. #225
