### ISSUE TITLE
Table of Contents displays puts each subfield in a new bullet

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#155]
It seems to be separating each subfield into a new line after a bullet.  

Example:

https://vufind3-devel.carli.illinois.edu/vf-uiu/Record/UIUdb.4948655#toc
 
Here is the 505 00 field from the record:
 
‡g The ‡t role of the father : an introduction / ‡r Michael E. Lamb, ‡r Catherine S. Tamis-Lemonda -- ‡t Two dimensions of fatherhood : a history of the good dad-bad dad complex / ‡r Elizabeth H. Pleck -- ‡t African American and African Caribbean fathers : level, quality, and meaning of involvement / ‡r Jaipaul L. Roopnarine -- ‡t Latino fathers : uncharted territory in need of much exploration / ‡r Natasha J. Cabrera, ‡r Cynthia Garcia Coll -- ‡t Social science and public policy perspectives on fatherhood in the European Union / ‡r Margaret O'Brien -- ‡t Fathering in Japanese, Chinese, and Korean cultures : a review of the research literature / ‡r David W. Shwalb...[et al.] -- ‡t Fathers in forager, farmer, and pastoral cultures / ‡r Barry S. Hewlett -- ‡t Fathers in family context : effects of marital quality and marital conflict / ‡r E. Mark Cummings, ‡r Marcie C. Goeke-Morey, ‡r Jessica Raymond -- ‡t Paternal involvement by U.S. residential fathers : levels, sources, and consequences / ‡r Joseph H. Pleck, ‡r Brian P. Masciadrelli -- ‡g The ‡t development and significance of father-child relationships in two-parent families / ‡r Michael E. Lamb, ‡r Charlie Lewis -- ‡t Fathering and children's peer relationships / ‡r Ross D. Parke ... [et al.] -- ‡g The ‡t effects of divorce on fathers and children : nonresidential fathers and stepfathers / ‡r Paul R. Amato, ‡r Julie M. Sobolewski -- ‡t Fathers in fragile families / ‡r Sara McLanahan, ‡r Marcia S. Carlson -- ‡t Gay fathers / ‡r Charlotte J. Patterson -- ‡t Fathers in violent homes / ‡r George W. Holden, ‡r Ted Barker -- ‡t Intervention : changing the nature and extent of father involvement / ‡r Brent A. McBride, ‡r Mary M. Lutz -- ‡g The ‡t impact of workplace practices on father involvement / ‡r Graeme Russell, ‡r Carl Philip Hwang.
 
![screen shot 2017-03-03 at 1 18 32 pm](https://cloud.githubusercontent.com/assets/17598357/23565630/0668211e-0014-11e7-8098-970c832d5248.png)

**Comment by gibsonjc** [comment]
What would be a preferred display for this 505 field data?  

One option might be to take out the bullets and allow all data to display in a long string with its natural punctuation.

**Comment by gibsonjc** [comment]
From NS: An ideal fix would be for line breaks to only occur when two consecutive hyphens appear in the string.

Ex. 1 with line breaks at two consecutive hyphens in Enhanced contents notes (505 second indicator 0):

505 00 ‡g The ‡t role of the father : an introduction / ‡r Michael E. Lamb, ‡r Catherine S. Tamis-Lemonda -- ‡t Two dimensions of fatherhood : a history of the good dad-bad dad complex / ‡r Elizabeth H. Pleck -- ‡t African American and African Caribbean fathers : level, quality, and meaning of involvement / ‡r Jaipaul L. Roopnarine

Display:

- The role of the father : an introduction / Michael E. Lamb, Catherine S. Tamis-Lemonda
- Two dimensions of fatherhood : a history of the good dad-bad dad complex / Elizabeth H. Pleck
- African American and African Caribbean fathers : level, quality, and meaning of involvement / Jaipaul L. Roopnarine

Ex. 2 with line breaks at two consecutive hyphens in Basic contents notes (505 second indicator blank):

505	0_ ‡a pt. 1. Carbon -- pt. 2. Nitrogen -- pt. 3. Sulphur -- pt. 4. Metals.
			
Display:
- pt. 1. Carbon
- pt. 2. Nitrogen
- pt. 3. Sulphur
- pt. 4. Metals

**Comment by gibsonjc** [comment]
possible template at /usr/local/vufind/themes/bootstrap3/templates/RecordTab/toc.phtml

**Comment by gibsonjc** [comment]
LFC - open call 12/15/2017 - Enhanced TOCs in 505 are worse than unenhanced TOCs in 505.  Enhanced have even more bullets.

**Comment by gibsonjc** [comment]
Handled by the getTOC function in SolrMARC.php?

**Comment by gibsonjc** [comment]
Preferred behavior: line breaks (new bullets) only occur when two consecutive hyphens appear in the string

(examples above)

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Ready for Prod

Other examples that were improved:
https://i-share-test.carli.illinois.edu/vf-whe/Record/WHEdb.816222#toc
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.8268592#toc
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.1467568#toc

**Comment by cedelis** [comment]
In PROD.
