### ISSUE TITLE
Remove "Interlibrary Loan" wording from "Cancel Selected Requests" prompt

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#156]
When you click the button to cancel selected requests from the “Requested Items” tab, the prompt contains the words “Interlibrary Loan”.

"Do you wish to cancel your selected interlibrary loan requests?”

Update the wording to say “Do you wish to cancel your selected requests?”

![screen shot 2017-03-03 at 1 30 28 pm](https://cloud.githubusercontent.com/assets/17598357/23566000/a5b175a8-0015-11e7-9455-e4f95824a913.png)

**Comment by gibsonjc** [comment]
UIC - We had asked that any instance of "Interlibrary Loan" be removed from I-Share since this can cause confusion among users, especially those who use ILLiad/OCLC. The "Interlibrary Loan" text also still appears in the "Requested Items" area if you don't have any transactions pending. If the text could be wiped out completely  or replaced with "I-Share requests" that would lessen patron confusion.  RT96877

**Comment by cedelis** [comment]
Ready for Testing

**Comment by gibsonjc** [comment]
@cedelis Looks good, also ready for Prod!

**Comment by cedelis** [comment]
In production
