### ISSUE TITLE
 Remove "Interlibrary Loan" wording from display when no requests in Your Account

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#157]
When you have no requests placed,  the wording under the “Requested Items” header says:

“You do not have any interlibrary requests placed.”

Change it to say “You do not have any requests placed.”

![screen shot 2017-03-03 at 1 33 23 pm](https://cloud.githubusercontent.com/assets/17598357/23566094/0bf2441e-0016-11e7-933e-558bf153daec.png)

**Comment by gibsonjc** [comment]
UIC - 12/15/2017 open call

**Comment by cedelis** [comment]
This was an easy fix: override languages/en.ini setting:

You do not have any interlibrary loan requests placed = "You do not have any requests placed"

**Comment by gibsonjc** [comment]
This looks good to me. Ready for Prod!

**Comment by gibsonjc** [comment]
This Issue was closed but I do not see the change on Production so I am reopening it.  

On 1/11/2018 the wording is still "You do not have any interlibrary loan requests placed."
On TEST the wording is correct "You do not have any requests placed."

**Comment by gibsonjc** [comment]
Production is showing the correct wording "You do not have any requests placed." today (not sure what I saw before), so I will close this Issue again.  Sorry for false alarm.
