### ISSUE TITLE
Change error message when record cannot be displayed

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#158]
The “error has occurred” warning that users see when a there’s a record problem in VuFind3, such as when the record ID is not found, says to contact noreply@carli.illinois.edu.
 
![screen shot 2017-03-03 at 1 39 31 pm](https://cloud.githubusercontent.com/assets/17598357/23566293/e42e09a8-0016-11e7-8c14-b8099c991f86.png)

The similar VuFind 0.6 error message does not include an email address; it says to contact the library but doesn’t give further directions.

![screen shot 2017-03-03 at 1 40 55 pm](https://cloud.githubusercontent.com/assets/17598357/23566352/172d1948-0017-11e7-981b-1384ec3cc778.png)

Change the VuFind 3 error message to read:

An error has occurred.
Data not available for display.
Note: titles added by the library today will not display in this catalog until tomorrow.
Please contact the Library for assistance.

**Comment by cedelis** [comment]
Ready to test (on vufind3-devel server)

**Comment by gibsonjc** [comment]
Close but not quite there yet.  These two lines:

**Please contact the Library Reference Department for assistance.
noreply@carli.illinois.edu**

need to be replaced with this one line:

**Please contact the Library for assistance.**

You can check the output with any invalid record number, like:
https://vufind3-devel.carli.illinois.edu/vf-onu/Record/11111111111111111

![screen shot 2017-06-23 at 1 33 07 pm](https://user-images.githubusercontent.com/17598357/27495683-a0589946-5818-11e7-80f0-e78fbc519f7c.png)

**Comment by cedelis** [comment]
Changed:

Please contact the Library Reference Department for assistance.

to:

Please contact the Library for assistance.

**Comment by gibsonjc** [comment]
Looks good on test; ready for prod

**Comment by cedelis** [comment]
Pulled carli-release-3.1.3 changes into Prod server.
