### ISSUE TITLE
change fine print in "Cite this" pop up box

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#159]
Current text reads:

Warning: These citations may not always be 100% accurate.

Change text to:

These citations may not conform precisely to your selected citation style. Please use this display as a guideline and modify as needed.

**Comment by gibsonjc** [comment]
LFC

**Comment by gibsonjc** [comment]
In languages/en.ini:

change the entry for

Warning: These citations may not always be 100% accurate = "Warning: These citations may not always be 100% accurate"

to

Warning: These citations may not always be 100% accurate = "These citations may not conform precisely to your selected citation style. Please use this display as a guideline and modify as needed."

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
@cedelis It looks like there is an extra period at the very end of the text after the word
**needed..**  

If you can remove that, this will be ready for Prod :)
![screen shot 2018-10-31 at 9 24 09 am](https://user-images.githubusercontent.com/17598357/47794682-e8270a80-dcee-11e8-96ba-f37816b9fd53.png)

**Comment by cedelis** [comment]
In PROD.
