### ISSUE TITLE
"Live Status Unavailable"

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#161]
A gray availability box icon with the words "Live Status Unavailable" appears after the blue Format box icon(s) on the Search Results page if the record is Format=Electronic and the Bib does not have an 856 field or SFX link (OpenURL; "Get full text" link) to present and there is no Voyager Item Record status to display.

And, it isn't limited to Format=Electronic:
Number 5 in the search results here is Book and Microform (no Electronic) but says Live Status Unavailable:
https://vufind3-devel.carli.illinois.edu/vf-eiu/Search/Results?sort=callnumber-sort&filter%5B%5D=format%3A%22Book%22&filter%5B%5D=format%3A%22Microform%22&type=AllFields
MFHD but no Voyager Item.

**Comment by gibsonjc** [comment]
Examples:
https://vufind3-devel.carli.illinois.edu/vf-eiu/Search/Results?sort=callnumber-sort&page=8&filter%5B%5D=format%3A%22Electronic%22&type=AllFields
![screen shot 2017-03-08 at 10 01 07 am](https://cloud.githubusercontent.com/assets/17598357/23711781/7627a83c-03e6-11e7-95d1-fc3ea7854aa0.png)

**Comment by gibsonjc** [comment]
I removed my original comment that we'd want this message suppressed from display at all times because if live item status is broken, we would want to know that.  Hopefully we can find a way to suppress it when it appears because there is not a Voyager Item Record.

**Comment by gibsonjc** [comment]
Correction, it isn't limited to Format=Electronic:
Number 5 in the search results here is Book and Microform (no Electronic) but says Live Status Unavailable:
https://vufind3-devel.carli.illinois.edu/vf-eiu/Search/Results?sort=callnumber-sort&filter%5B%5D=format%3A%22Book%22&filter%5B%5D=format%3A%22Microform%22&type=AllFields
MFHD but no Voyager Item.

Interesting Side note:
Number 18 here says nothing. Bib is unsuppressed; MFHD is suppressed; no Item in Voyager:
https://vufind3-devel.carli.illinois.edu/vf-eiu/Search/Results?sort=callnumber-sort&type=AllFields&filter%5B%5D=format%3A%22Movie%22

**Comment by gibsonjc** [comment]
SIC - RT 96245
I was testing the new VuFind and came across a strange button that
prompted me to investigate what is happening.

Here is a sample result set:
https://i-share-test.carli.illinois.edu/vf-sic/Search/Results?lookfor=american+history+in+video&type=AllFields&filter%5B%5D=collection%3A%22SICdb_wwvid%22

There is a button appearing on records 1, 3, 4 on the results list with
a live status unavailable label. When I open up the detailed record, the
holdings info is OK (looks like that URL is pulled from the MFHD 856)
but I found that the records with status unavailable labed do not have
an 856 in the bib. I am not sure how this happened as these records were
all Alexander street press records and as far as I know, the bibs should
all have 856 fields.

I guess this is a clean up project that needs to get done because the
label is misleading and if I were a typical patron, I probably would
never look at the detailed record when seeing that label.
Perhaps the button could be relabeled?

**Comment by gibsonjc** [comment]
I did more testing on this.  The "Live Status Unavailable" indicator displays in the Results list for a title when:

1.  the BIB does not have an 856 field
2. there is not an SFX button presented (no BIB 022 field or 022 field present did not match)
3. a MFHD exists attached to the BIB (it doesn't matter if it has an 856 field or not)
4. there is no Item record

_Notes to self:_
Evidence/example: 
"The kinetochore : from molecular discoveries to cancer therapy"
https://i-share-test.carli.illinois.edu/vf-eiu/Record/EIUdb.1008192

Evidence/example where 1, 3, and 4 are True but 2 is False and it doesn't display: 
"Industry circular"
https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.581652

**Comment by nmswanson** [comment]
As a consequence of fixing issue 207, this status now displays with more frequency.

BEN suggestions- 

To a student or patron it is likely the wording "unavailable" would be interpreted as the ebook is unavailable. How about something like " Unable to determine status", or "Status Undetermined" or just display "Status". I'm sure you all can come up with something less confusing than unavailable. 

I looked at the Github issue 207. The developer is spot on with regards to the unintended consequences! 
"I've removed the code that checks for empty 856 URLs; so now the availability status always displays. 
However, there is going to be a side-effect (unintended consequence?) for doing so. 
E.g., compare TEST vs. PROD and notice how in TEST there is now potential for statuses to take on the value of 'Live Status Unavailable'. Is this an acceptable tradeoff?"
BEN- In my opinion NO, this is not an acceptable tradeoff.

RT100134

**Comment by cedelis** [comment]
We can change the "Live Status Unknown" message to something else via the languages/en.ini file.

To be more precise, we can change the translation of the internal code "status_unknown_message" from "Live Status Unknown" to a different value with this setting:

https://github.com/CARLI/vufind/blob/master/languages/en.ini#L918

So, the question then becomes, what is an acceptable value?

**Comment by gibsonjc** [comment]
@cedelis Let's try this:
change
status_unknown_message = "Live Status Unavailable"
to
status_unknown_message = "Status Unknown"
on TEST.  Thanks!

**Comment by cedelis** [comment]
@gibsonjc Seems like a reasonable value to me (for status_unknown_message to be "Status Unknown"  ;-)

In TEST.

**Comment by dmcmpbll** [comment]
Would New VuFind actually know if the "Live Status" was broken, or would it only know if it is unknown since login/an external site is usually required?

**Comment by cedelis** [comment]
@dmcmpbll  (NOTE: I edited this Wed Jun 27 4:14PM CDT): 

This is a driver-specific question. It appears that status_unknown_message is only being used/set with Voyager drivers:

https://github.com/vufind-org/vufind/search?q=use_unknown_message&unscoped_q=use_unknown_message

There are two SQL queries that the Voyager driver uses to retrieve Holdings information. The first one, getStatusSQL(), which is the standard query: https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/ILS/Driver/Voyager.php#L357

and the second query, getStatusNoItemsSQL(), which is used to retrieve Holdings information for bibs without items: https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/ILS/Driver/Voyager.php#L413

If there are results for the second query (bibs without items), then the status_unknown_message can display.

Does this help answer your question and/or concerns?

**Comment by cedelis** [comment]
In our discussion this morning, we decided to change the translation of "Status Unknown" to an empty string "". This isn't perfect as it does reveal the background color of the label (looks like a little gray rectangle. But it's "better" than "Status Unknown," I think. We can create another issue to attempt at removing this display altogether.

**Comment by gibsonjc** [comment]
This is currently on TEST.

Adding some screenshots "for the record":

BEFORE:
![screen shot 2018-07-03 at 9 24 59 am](https://user-images.githubusercontent.com/17598357/42225828-0f2b7fee-7ea3-11e8-91d3-988cbe5cf523.png)

AFTER:
![screen shot 2018-07-03 at 9 24 49 am](https://user-images.githubusercontent.com/17598357/42225835-1408ca8a-7ea3-11e8-8624-554ec27bf4ad.png)

**Comment by cedelis** [comment]
In PROD.
