### ISSUE TITLE
call number option in "Browse the Catalog" is LC only

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#163]
The call number option in "Browse the Catalog" only lists LC call numbers (letter and description) and cannot be used to browse DDC, Gov, or Other call number types.

**Comment by gibsonjc** [comment]
Is this true, or is it because only A-Z are listed as options?  I found this in the config.ini:

> ; This section controls the behavior of the Browse module.  The result_limit
; setting controls the maximum number of results that may display in any given
; result box on the Browse screen.  You can set to -1 for no limit; however,
; setting a very high (or no) limit may result in "out of memory" errors if you
; have a large index!
[Browse]
result_limit    = 100
tag             = true      ; allow browsing of Tags
!BROWSE_DEWEY!
!BROWSE_LCC!
author          = true      ; allow browsing of authors
topic           = true      ; allow browsing of subject headings
genre           = true      ; allow browsing of genre subdivisions
region          = true      ; allow browsing of region subdivisions
era             = true      ; allow browsing of era subdivisions
; You can use this setting to change the default alphabet provided for browsing:
;alphabet_letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

If we changed this to 
alphabet_letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
would the browse work for alpha and numeric?

Giving this the "could be simple" label but understanding it might not be!

**Comment by cedelis** [comment]
No, this is not "simple."  

Setting alphabet_letters seems to have no effect for Call Number browsing. I'm guessing it is being ignored completely.

For all other Browse searches, however, this setting does seem to take effect. In fact, it appears that VuFind is already either:  a) prepending the digits, in the case of Era; b) or appending the digits, for all others. (code: https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/Controller/BrowseController.php#L688
 )

So, if I set alphabet_letters to include the digits, you will see two sets of them:

https://vufind3-devel.carli.illinois.edu/vf-uiu/Browse/Topic?findby=alphabetical&query_field=topic_facet

In summary, VuFind has Call Number Browse support for Dewey and/or LC. That's it.

I've temporarily set UIU's dev instance to the settings below, which offer both Dewey and LC:


[Browse]
result_limit    = 100
tag             = true      ; allow browsing of Tags
dewey           = true     ; allow browsing of Dewey Decimal call numbers

lcc             = true      ; allow browsing of LC call numbers

author          = true      ; allow browsing of authors
topic           = true      ; allow browsing of subject headings
genre           = true      ; allow browsing of genre subdivisions
region          = true      ; allow browsing of region subdivisions
era             = true      ; allow browsing of era subdivisions
; You can use this setting to change the default alphabet provided for browsing:
alphabet_letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"

**Comment by cedelis** [comment]
With respect to the two Call Number Browse options (LC and Dewey) in VuFind, there is obviously an indexing component, where decisions are made as to how each one is indexed (and searched). These are configured via the following settings (any changes to these require a COMPLETE re-index of Solr, i.e., it's an expensive change):

callnumber-first = 852h[0], callnumber_map.properties, first
callnumber-subject = custom, getCallNumberSubject(852h), callnumber_subject_map.properties
callnumber-label = custom, getCallNumberLabel(852h)
callnumber-sort = custom, getLCSortable(852hi)
callnumber-raw = 852hi

#dewey-hundreds = custom, getDeweyNumber(852h, 100), ddc22_map.properties(hundreds)
#dewey-tens = custom, getDeweyNumber(852h, 10), ddc22_map.properties(tens)
#dewey-ones = custom, getDeweyNumber(852h, 1), ddc22_map.properties(ones)
#dewey-full = custom, getDeweySearchable(852h)
#dewey-sort = custom, getDeweySortable(852h)
#dewey-raw = 852hi

The other Call Number search types, e.g., Topic and Era, are "simpler" and depend on a single field:

topic = custom, getAllSubfields(600:610:611:630:650:653:656, " ")
era = custom, getAllSubfields(648, " ")

This might explain why Call Number is different from the other types of Browsing searches. It is also probably the reason why it ignores the alphabet_letters parameter (instead, it depends on the more complex indexing options).

Chris

**Comment by gibsonjc** [comment]
> So, if I set alphabet_letters to include the digits, you will see two sets of them:
https://vufind3-devel.carli.illinois.edu/vf-uiu/Browse/Topic?findby=alphabetical&query_field=topic_facet
alphabet_letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"

@cedelis You can undo this temp change to uiu and devel.  It makes no sense to have 0-9 show up in the Alphabetic lists, that's not going to help anything.  Thanks for trying it out!  I'll think on this some more.

**Comment by gibsonjc** [comment]
At the 8/2 meeting, we discussed suppressing the "Browse the Catalog" Call Number function because it is limited to a single classification scheme and instead redirecting it to the "Browse Alphabetically" by Call Number function page since Alphabrowse treats all call number data the same regardless of classification system.

https ://vufind3.carli.illinois.edu/vf-xxx/Alphabrowse/Home **?source=lcc**

**Comment by gibsonjc** [comment]
LAC - Is there a way to change the new browse feature in the New VuFind from LC to Dewey call numbers for our local collection?   RT 96647

**Comment by gibsonjc** [comment]
@cedelis Can you look into what it would take to change the Call Number link on the "Browse the Catalog" page (Ex: https://i-share.carli.illinois.edu/vf-cod/Browse/Home)
![screen shot 2018-02-27 at 3 59 11 pm](https://user-images.githubusercontent.com/17598357/36757532-7a040f36-1bd7-11e8-84b9-edb69689dced.png)

from 
https://i-share.carli.illinois.edu/vf-xxx/Browse/LCC
to
https://i-share.carli.illinois.edu/vf-xxx/Alphabrowse/Home?source=lcc
so that when users click "Call Number" on the "Browse by Catalog" page  they get taken to the "Browse Alphabetically" By Call Number page (preset to search by call number thanks to the source parameter) instead?

**Comment by cedelis** [comment]
@gibsonjc The easiest thing would be to use apache "magic" (modrewrite) to do this behind the scenes.

**Comment by cedelis** [comment]
In Test.

**Comment by gibsonjc** [comment]
This redirect is working as expected in all local catalogs /vf-xxx/ and is in Production now.

I won't close this yet because "Browse the Catalog" is still present in the I-Share uc /all/vf/ and /all/vf-xxx catalogs and is browsing LC numbers only.  "Browse Alphabetically" is not an option in the I-Share uc /all/vf/ and /all/vf-xxx/ catalogs.  @cedelis Is this because we do not/cannot have the special index needed to use "Browse Alphabetically" in the I-Share uc?  Our only option  in the I-Share uc might be to suppress the display of the "Browse the Catalog" Call Number option?

**Comment by cedelis** [comment]
@gibsonjc Not sure what to do about this because Alphabrowse is set up to work in the local catalogs only. In order for the Alphabrowse feature to work in the I-Share (/all/vf) catalog, we would need to create a separate Alphabrowse index for it (do not confuse this index w/ Solr; it's its own separate index). I do not know offhand if this would be a difficult (or easy) thing to do; I would need to analyze further. In the interim -- and perhaps if creating Alphabrowse index for I-Share is either difficult/unwanted/etc.-- I suppose we could consider the alternative of removing the "Call Number" facet from "Browse the Catalog".

**Comment by gibsonjc** [comment]
@cedelis I think that removing/suppressing the "Call Number" facet from "Browse the Catalog" in the I-Share catalogs (that is /all/vf/ **and** /all/vf-xxx/ ) is the best option at the moment.  We can look into if Alphabrowse index for the uc is a good idea or not later.  Thanks!

**Comment by cedelis** [comment]
This option has been disabled for /all/vf/ and /all/vf-xxx/ in Test.

**Comment by gibsonjc** [comment]
Removal of "Call Number" facet from "Browse the Catalog" in /all/vf/ and /all/vf-xxx/ looked as I expected.

**Comment by cedelis** [comment]
In prod. No reference to commit since it was a change to our custom scripts (outside of this git repo).
