### ISSUE TITLE
call number limit in Advanced Search is LC only

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#164]
The call number limit on the Advanced Search page only lists LC call numbers (letter and description) and cannot be used to limit to DDC, Gov, or Other call number types.

**Comment by slknight** [comment]
I did some test searches in the UIUC catalog for 636.8 and then limited to S. It gets 1 result. The book has both an LC and Dewey number in he holdings.  Maybe this could search 050 and 082 as well as the holdings?

![image](https://user-images.githubusercontent.com/15163837/28580940-8712f23e-7126-11e7-8799-c292ac49d0cd.png)

**Comment by gibsonjc** [comment]
LNC - On Advanced Search, Limit to call numbers contains only LCC identifiers. We’re mixed LCC and DDC right now, although our plan is to convert everything to LCC.

**Comment by gibsonjc** [comment]
I think we can easily remove the Call Number Limit in facets.ini:

; These facets will be displayed as limiters on the advanced search search screen
; NOTE: To make changes take effect immediately, you may need to clear VuFind's
; cache after changing this section.
[Advanced]
callnumber-first = "Call Number"
language         = Language
format = Format

**Comment by gibsonjc** [comment]
DPU - DePaul University Library is a primarily Dewey call number library and as the staff here have been looking at the new VuFind 4 test instance they have been asking whether there are options to either:  a)      Switch the call number classification in the Advanced Screen to Dewey classification  b)      Remove the option Limit to the LC Call Number Classification from the Advanced search screen

**Comment by cedelis** [comment]
Just wanted to add: 

Call Number limits are based on the "callnumber-first" Solr field, which is currently defined in https://github.com/CARLI/vufind/blob/carli-master/import/marc_dedup_local.properties#L55

and the mapping of this is defined in https://github.com/CARLI/vufind/blob/carli-master/import/translation_maps/callnumber_map.properties

**Comment by gibsonjc** [comment]
Let's try to remove the Call Number limit option from the Advanced Search screen.  Is it enough to simply comment out its line in facets.ini @cedelis ?

; These facets will be displayed as limiters on the advanced search search screen
; NOTE: To make changes take effect immediately, you may need to clear VuFind's
; cache after changing this section.
[Advanced]
**callnumber-first = "Call Number"**
language = Language
format = Format

**Comment by cedelis** [comment]
Ready for Testing.

diff:

diff --git a/LOCAL_VF_TEMPLATE/config/vufind/facets.ini b/LOCAL_VF_TEMPLATE/config/vufind/facets.ini
index 088a3e6..996fab4 100644
--- a/LOCAL_VF_TEMPLATE/config/vufind/facets.ini
+++ b/LOCAL_VF_TEMPLATE/config/vufind/facets.ini
@@ -127,7 +127,7 @@ topic_facet = "Related Subjects"
 ; NOTE: To make changes take effect immediately, you may need to clear VuFind's
 ; cache after changing this section.
 [Advanced]
-callnumber-first = "Call Number"
+;callnumber-first = "Call Number"
 language         = Language
 format           = Format
 ;hierarchy_top_title   = Collections
@@ -193,7 +193,7 @@ special_facets   = "illustrated,daterange,checkboxes"
 ; These facets will be displayed on the Home Page.  If this section is omitted,
 ; the [Advanced] section will be used instead.
 [HomePage]
-callnumber-first = "Call Number"
+;callnumber-first = "Call Number"
 language         = Language
 format           = Format
 ;hierarchy_top_title   = Collections
@@ -209,7 +209,8 @@ facet_limit      = 20
 [Visual_Settings]
 ; Which two facetable fields should be used for creating the visual results?
 ; See VisualFacets recommendation module in searches.ini for more details.
-visual_facets = "callnumber-first,topic_facet"
+;visual_facets = "callnumber-first,topic_facet"
+visual_facets = "topic_facet"

 ; If you rename a facet field, you can map the old value to a new value in this
 ; section to ensure that legacy URLs continue to function.

**Comment by gibsonjc** [comment]
Good, ready for Prod!
This already looks to be in prod, actually.
