### ISSUE TITLE
call number option in "Browse Alphabetically" is mislabeled with (LC)

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#166]
Change label in drop-down "By Call Number (LC)" to remove the (LC) since this browse function works against the set of all alpha-numeric call numbers.

![screen shot 2017-03-20 at 11 05 59 am](https://cloud.githubusercontent.com/assets/17598357/24109008/5e4b8bcc-0d5d-11e7-878c-8b247a1392d2.png)

**Comment by cedelis** [comment]
In vufind3-devel

**Comment by gibsonjc** [comment]
Looks good on test; ready for prod

**Comment by cedelis** [comment]
Pulled carli-release-3.1.3 changes into Prod server.
