### ISSUE TITLE
E-Item links from Course Reserves do not display

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#167]
Example:

https://vufind3-devel.carli.illinois.edu/vf-uiu/Search/Reserves  and in drop down menu for courses select "LIS 528 Adult Popular Lit...",  click find. 

There's only one title:  https://vufind3-devel.carli.illinois.edu/vf-uiu/Search/Reserves?course=11214&submit=Find&inst=&dept=  

Which goes to https://vufind3-devel.carli.illinois.edu/vf-uiu/Record/UIUdb.8139199  but there's no link to the electronic reserves in the holdings or bib area.

In 0.6 you can see the link to the e-item at: 
https://vufind.carli.illinois.edu/vf-uiu/Record/uiu_8139199   

Another example:

https://vufind3-devel.carli.illinois.edu/vf-sfm/Search/Reserves and in drop down menu for courses select "426: Conceptual Basis of Nursing III Theory", click find.

There are many E-Item titles https://vufind3-devel.carli.illinois.edu/vf-sfm/Search/Reserves?course=134&submit=Find&inst=&dept= 

choose one like "Compartment Syndrome" https://vufind3-devel.carli.illinois.edu/vf-sfm/Record/SFMdb.5976 but there's no link to the electronic reserves in the holdings or bib area.

In 0.6 you can see the link to the e-item at:
https://vufind.carli.illinois.edu/vf-sfm/Record/sfm_5976

**Comment by gibsonjc** [comment]
On 3/24 in email to vu-it:

Here's what appears to be happening.

Even though Course Reserves is a "specialized" search (different from "regular" searches, e.g., All Fields, Title, Author, etc.), the actual Detailed Record page for Course Reserves is loaded as if it were a "regular" search result, i.e., it uses the same exact code. And, unfortunately, this code does NOT appear to be looking up any EITEM information.

Here's the SQL it ultimately uses (sorry about it not being in a standard SQL string; instead this comes from a PHP object's representation of the SQL).

******************************\Voyager::ngetHoldingItemsSQLarray (
  'expressions' =>
  array (
    0 => 'BIB_ITEM.BIB_ID',
    1 => 'MFHD_ITEM.MFHD_ID',
    2 => 'ITEM_BARCODE.ITEM_BARCODE',
    3 => 'ITEM.ITEM_ID',
    4 => 'ITEM.ON_RESERVE',
    5 => 'ITEM.ITEM_SEQUENCE_NUMBER',
    6 => 'ITEM.RECALLS_PLACED',
    7 => 'ITEM.HOLDS_PLACED',
    8 => 'ITEM_STATUS_TYPE.ITEM_STATUS_DESC as status',
    9 => 'MFHD_DATA.RECORD_SEGMENT',
    10 => 'MFHD_ITEM.ITEM_ENUM',
    11 => 'NVL(LOCATION.LOCATION_DISPLAY_NAME, LOCATION.LOCATION_NAME) as location',
    12 => 'ITEM.TEMP_LOCATION',
    13 => 'ITEM.PERM_LOCATION',
    14 => 'MFHD_MASTER.DISPLAY_CALL_NO as callnumber',
    15 => 'to_char(CIRC_TRANSACTIONS.CURRENT_DUE_DATE, \'MM-DD-YY\') as duedate',
    16 => '(SELECT TO_CHAR(MAX(CIRC_TRANS_ARCHIVE.DISCHARGE_DATE), \'MM-DD-YY HH24:MI\') FROM SFMDB.CIRC_TRANS_ARCHIVE WHERE CIRC_TRANS_ARCHIVE.ITEM_ID = ITEM.ITEM_ID) RETURNDATE',
    17 => 'ITEM.ITEM_SEQUENCE_NUMBER',
    18 => '(SELECT SORT_GROUP_LOCATION.SEQUENCE_NUMBER FROM SFMDB.SORT_GROUP, SFMDB.SORT_GROUP_LOCATION WHERE SORT_GROUP.SORT_GROUP_DEFAULT = \'Y\' AND SORT_GROUP_LOCATION.SORT_GROUP_ID = SORT_GROUP.SORT_GROUP_ID AND SORT_GROUP_LOCATION.LOCATION_ID = ITEM.PERM_LOCATION) SORT_SEQ',
  ),
  'from' =>
  array (
    0 => 'SFMDB.BIB_ITEM',
    1 => 'SFMDB.ITEM',
    2 => 'SFMDB.ITEM_STATUS_TYPE',
    3 => 'SFMDB.ITEM_STATUS',
    4 => 'SFMDB.LOCATION',
    5 => 'SFMDB.MFHD_ITEM',
    6 => 'SFMDB.MFHD_MASTER',
    7 => 'SFMDB.MFHD_DATA',
    8 => 'SFMDB.CIRC_TRANSACTIONS',
    9 => 'SFMDB.ITEM_BARCODE',
  ),
  'where' =>
  array (
    0 => 'BIB_ITEM.BIB_ID = :id',
    1 => 'BIB_ITEM.ITEM_ID = ITEM.ITEM_ID',
    2 => 'ITEM.ITEM_ID = ITEM_STATUS.ITEM_ID',
    3 => 'ITEM_STATUS.ITEM_STATUS = ITEM_STATUS_TYPE.ITEM_STATUS_TYPE',
    4 => 'ITEM_BARCODE.ITEM_ID (+)= ITEM.ITEM_ID',
    5 => 'LOCATION.LOCATION_ID = ITEM.PERM_LOCATION',
    6 => 'CIRC_TRANSACTIONS.ITEM_ID (+)= ITEM.ITEM_ID',
    7 => 'MFHD_ITEM.ITEM_ID = ITEM.ITEM_ID',
    8 => 'MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID',
    9 => 'MFHD_DATA.MFHD_ID = MFHD_ITEM.MFHD_ID',
    10 => 'MFHD_MASTER.SUPPRESS_IN_OPAC=\'N\'',
  ),
  'order' =>
  array (
    0 => 'ITEM.ITEM_SEQUENCE_NUMBER',
    1 => 'MFHD_DATA.MFHD_ID',
    2 => 'MFHD_DATA.SEQNUM',
  ),
  'bind' =>
  array (
    ':id' => '5976',
  ),
)
******************************

Also, it appears that the SIE record  https://vufind3-devel.carli.illinois.edu/vf-sie/Record/SIEdb.806283 is actually getting its "E-Resource" link from the MFHD, not the EITEM table.

Therefore, in order to show Course Reserves e-item links, we would need to make enhancements to the VoyagerRestful driver.

**Comment by tschwitz** [comment]
If you find you have to modify the SQL, then you would create a join between EITEM and MFHD_ITEM on MFHD_ID. The field containing the URL is EITEM.LINK.

I tried to rebuild the SQL you showed above, but I'm actually puzzled how it retrieves results at all, given that only six libraries have data in the SORT_GROUP and SORT_GROUP_LOCATION tables.

**Comment by cedelis** [comment]
The SORT_GROUP and SORT_GROUP_LOCATION tables are only used to populate a column value called SORT_SEQ using a subquery. So, in our case, this will always be a NULL or empty value. This isn't really significant to the overall query.

I was able to log the actual SQL query being used, which should help illustrate this:

SELECT
    BIB_ITEM.BIB_ID,
    MFHD_ITEM.MFHD_ID,
    ITEM_BARCODE.ITEM_BARCODE,
    ITEM.ITEM_ID,
    ITEM.ON_RESERVE,
    ITEM.ITEM_SEQUENCE_NUMBER,
    ITEM.RECALLS_PLACED,
    ITEM.HOLDS_PLACED,
    ITEM_STATUS_TYPE.ITEM_STATUS_DESC as status,
    MFHD_DATA.RECORD_SEGMENT,
    MFHD_ITEM.ITEM_ENUM,
    NVL(LOCATION.LOCATION_DISPLAY_NAME, LOCATION.LOCATION_NAME) as location,
    ITEM.TEMP_LOCATION, ITEM.PERM_LOCATION,
    MFHD_MASTER.DISPLAY_CALL_NO as callnumber,
    to_char(CIRC_TRANSACTIONS.CURRENT_DUE_DATE, \'MM-DD-YY\') as duedate,
    (SELECT TO_CHAR(MAX(CIRC_TRANS_ARCHIVE.DISCHARGE_DATE), \'MM-DD-YY HH24:MI\') FROM SFMDB.CIRC_TRANS_ARCHIVE WHERE CIRC_TRANS_ARCHIVE.ITEM_ID = ITEM.ITEM_ID) RETURNDATE,
    ITEM.ITEM_SEQUENCE_NUMBER,
    (SELECT SORT_GROUP_LOCATION.SEQUENCE_NUMBER FROM SFMDB.SORT_GROUP, SFMDB.SORT_GROUP_LOCATION WHERE SORT_GROUP.SORT_GROUP_DEFAULT = \'Y\' AND SORT_GROUP_LOCATION.SORT_GROUP_ID = SORT_GROUP.SORT_GROUP_ID AND SORT_GROUP_LOCATION.LOCATION_ID = ITEM.PERM_LOCATION) SORT_SEQ,
    ITEM.ITEM_TYPE_ID,
    ITEM.TEMP_ITEM_TYPE_ID

FROM
    SFMDB.BIB_ITEM,
    SFMDB.ITEM,
    SFMDB.ITEM_STATUS_TYPE,
    SFMDB.ITEM_STATUS,
    SFMDB.LOCATION,
    SFMDB.MFHD_ITEM,
    SFMDB.MFHD_MASTER,
    SFMDB.MFHD_DATA,
    SFMDB.CIRC_TRANSACTIONS,
    SFMDB.ITEM_BARCODE

WHERE
    BIB_ITEM.BIB_ID = :id
    AND BIB_ITEM.ITEM_ID = ITEM.ITEM_ID
    AND ITEM.ITEM_ID = ITEM_STATUS.ITEM_ID
    AND ITEM_STATUS.ITEM_STATUS = ITEM_STATUS_TYPE.ITEM_STATUS_TYPE
    AND ITEM_BARCODE.ITEM_ID (+)= ITEM.ITEM_ID
    AND LOCATION.LOCATION_ID = ITEM.PERM_LOCATION
    AND CIRC_TRANSACTIONS.ITEM_ID (+)= ITEM.ITEM_ID
    AND MFHD_ITEM.ITEM_ID = ITEM.ITEM_ID
    AND MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID
    AND MFHD_DATA.MFHD_ID = MFHD_ITEM.MFHD_ID
    AND MFHD_MASTER.SUPPRESS_IN_OPAC=\'N\' ORDER BY ITEM.ITEM_SEQUENCE_NUMBER, MFHD_DATA.MFHD_ID, MFHD_DATA.SEQNUM



The code itself builds the SQL indirectly using various objects. Here are the objects it uses to build the query:  https://github.com/CARLI/vufind/blob/carli_master_branch/module/VuFind/src/VuFind/ILS/Driver/Voyager.php#L603

Chris

**Comment by cedelis** [comment]
I'm looking at this issue again.

We still need to somehow enhance the SQL so that it includes EITEM information.

Can someone improve upon it? @tschwitz ? @fellowsgl ? @dmcmpbll ?

The SQL below (which returns no rows) is used in the SFMdb.5976 example:

SELECT
    BIB_ITEM.BIB_ID,
    MFHD_ITEM.MFHD_ID,
    ITEM_BARCODE.ITEM_BARCODE,
    ITEM.ITEM_ID,
    ITEM.ON_RESERVE,
    ITEM.ITEM_SEQUENCE_NUMBER,
    ITEM.RECALLS_PLACED,
    ITEM.HOLDS_PLACED,
    ITEM_STATUS_TYPE.ITEM_STATUS_DESC as status,
    MFHD_DATA.RECORD_SEGMENT,
    MFHD_ITEM.ITEM_ENUM,
    NVL(LOCATION.LOCATION_DISPLAY_NAME, LOCATION.LOCATION_NAME) as location,
    ITEM.TEMP_LOCATION,
    ITEM.PERM_LOCATION,
    MFHD_MASTER.DISPLAY_CALL_NO as callnumber,
    to_char(CIRC_TRANSACTIONS.CURRENT_DUE_DATE, 'MM-DD-YY') as duedate,
    CASE WHEN ITEM_STATUS_TYPE.ITEM_STATUS_DESC = 'Discharged' THEN ( SELECT TO_CHAR(MAX(CIRC_TRANS_ARCHIVE.DISCHARGE_DATE), 'MM-DD-YY HH24:MI') FROM SFMDB.CIRC_TRANS_ARCHIVE WHERE CIRC_TRANS_ARCHIVE.ITEM_ID = ITEM.ITEM_ID) ELSE NULL END RETURNDATE,
    ITEM.ITEM_SEQUENCE_NUMBER,
    (SELECT SORT_GROUP_LOCATION.SEQUENCE_NUMBER FROM SFMDB.SORT_GROUP, SFMDB.SORT_GROUP_LOCATION WHERE SORT_GROUP.SORT_GROUP_DEFAULT = 'Y' AND SORT_GROUP_LOCATION.SORT_GROUP_ID = SORT_GROUP.SORT_GROUP_ID AND SORT_GROUP_LOCATION.LOCATION_ID = ITEM.PERM_LOCATION) SORT_SEQ,
    ITEM.ITEM_TYPE_ID,
    ITEM.TEMP_ITEM_TYPE_ID FROM SFMDB.BIB_ITEM,
    SFMDB.ITEM,
    SFMDB.ITEM_STATUS_TYPE,
    SFMDB.ITEM_STATUS,
    SFMDB.LOCATION,
    SFMDB.MFHD_ITEM,
    SFMDB.MFHD_MASTER,
    SFMDB.MFHD_DATA,
    SFMDB.CIRC_TRANSACTIONS,
    SFMDB.ITEM_BARCODE
 WHERE
    BIB_ITEM.BIB_ID = 5976
    AND BIB_ITEM.ITEM_ID = ITEM.ITEM_ID
    AND ITEM.ITEM_ID = ITEM_STATUS.ITEM_ID
    AND ITEM_STATUS.ITEM_STATUS = ITEM_STATUS_TYPE.ITEM_STATUS_TYPE
    AND ITEM_BARCODE.ITEM_ID (+)= ITEM.ITEM_ID
    AND LOCATION.LOCATION_ID = ITEM.PERM_LOCATION
    AND CIRC_TRANSACTIONS.ITEM_ID (+)= ITEM.ITEM_ID
    AND MFHD_ITEM.ITEM_ID = ITEM.ITEM_ID
    AND MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID
    AND MFHD_DATA.MFHD_ID = MFHD_ITEM.MFHD_ID
    AND MFHD_MASTER.SUPPRESS_IN_OPAC='N'
ORDER BY ITEM.ITEM_SEQUENCE_NUMBER, MFHD_DATA.MFHD_ID, MFHD_DATA.SEQNUM
;



The SQL below (which also returns no rows) is used in the SIEdb.806283 example:


SELECT
    BIB_ITEM.BIB_ID,
    MFHD_ITEM.MFHD_ID,
    ITEM_BARCODE.ITEM_BARCODE,
    ITEM.ITEM_ID,
    ITEM.ON_RESERVE,
    ITEM.ITEM_SEQUENCE_NUMBER,
    ITEM.RECALLS_PLACED,
    ITEM.HOLDS_PLACED,
    ITEM_STATUS_TYPE.ITEM_STATUS_DESC as status,
    MFHD_DATA.RECORD_SEGMENT,
    MFHD_ITEM.ITEM_ENUM,
    NVL(LOCATION.LOCATION_DISPLAY_NAME, LOCATION.LOCATION_NAME) as location,
    ITEM.TEMP_LOCATION,
    ITEM.PERM_LOCATION,
    MFHD_MASTER.DISPLAY_CALL_NO as callnumber,
    to_char(CIRC_TRANSACTIONS.CURRENT_DUE_DATE, 'MM-DD-YY') as duedate,
    CASE WHEN ITEM_STATUS_TYPE.ITEM_STATUS_DESC = 'Discharged' THEN ( SELECT TO_CHAR(MAX(CIRC_TRANS_ARCHIVE.DISCHARGE_DATE), 'MM-DD-YY HH24:MI') FROM SIEDB.CIRC_TRANS_ARCHIVE WHERE CIRC_TRANS_ARCHIVE.ITEM_ID = ITEM.ITEM_ID) ELSE NULL END RETURNDATE,
    ITEM.ITEM_SEQUENCE_NUMBER,
    (SELECT SORT_GROUP_LOCATION.SEQUENCE_NUMBER FROM SIEDB.SORT_GROUP, SIEDB.SORT_GROUP_LOCATION WHERE SORT_GROUP.SORT_GROUP_DEFAULT = 'Y' AND SORT_GROUP_LOCATION.SORT_GROUP_ID = SORT_GROUP.SORT_GROUP_ID AND SORT_GROUP_LOCATION.LOCATION_ID = ITEM.PERM_LOCATION) SORT_SEQ,
    ITEM.ITEM_TYPE_ID,
    ITEM.TEMP_ITEM_TYPE_ID FROM SIEDB.BIB_ITEM,
    SIEDB.ITEM,
    SIEDB.ITEM_STATUS_TYPE,
    SIEDB.ITEM_STATUS,
    SIEDB.LOCATION,
    SIEDB.MFHD_ITEM,
    SIEDB.MFHD_MASTER,
    SIEDB.MFHD_DATA,
    SIEDB.CIRC_TRANSACTIONS,
    SIEDB.ITEM_BARCODE
 WHERE
    BIB_ITEM.BIB_ID = 806283
    AND BIB_ITEM.ITEM_ID = ITEM.ITEM_ID
    AND ITEM.ITEM_ID = ITEM_STATUS.ITEM_ID
    AND ITEM_STATUS.ITEM_STATUS = ITEM_STATUS_TYPE.ITEM_STATUS_TYPE
    AND ITEM_BARCODE.ITEM_ID (+)= ITEM.ITEM_ID
    AND LOCATION.LOCATION_ID = ITEM.PERM_LOCATION
    AND CIRC_TRANSACTIONS.ITEM_ID (+)= ITEM.ITEM_ID
    AND MFHD_ITEM.ITEM_ID = ITEM.ITEM_ID
    AND MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID
    AND MFHD_DATA.MFHD_ID = MFHD_ITEM.MFHD_ID
    AND MFHD_MASTER.SUPPRESS_IN_OPAC='N'
ORDER BY ITEM.ITEM_SEQUENCE_NUMBER, MFHD_DATA.MFHD_ID, MFHD_DATA.SEQNUM
;

**Comment by fellowsgl** [comment]
Here is my first cut at sql to return the eitem.  It has all the fields the item query returns with my best guess at values for fields that don't have equivalents in the eitem context.

SELECT
BIB_MFHD.BIB_ID,
BIB_MFHD.MFHD_ID,
' ' as ITEM_BARCODE,
EITEM.EITEM_ID as ITEM_ID,
'Y' as ON_RESERVE,
EITEM.SEQUENCE as ITEM_SEQUENCE_NUMBER1,
0 as RECALLS_PLACED,
0 as HOLDS_PLACED,
'eitem' as status,
MFHD_DATA.RECORD_SEGMENT,
EITEM.ENUMERATION as ITEM_ENUM,
' ' as location,
NULL as TEMP_LOCATION,
NULL as PERM_LOCATION,
MFHD_MASTER.DISPLAY_CALL_NO as callnumber,
NULL as duedate,
NULL as RETURNDATE,
EITEM.SEQUENCE as ITEM_SEQUENCE_NUMBER2,
0 as SORT_SEQ,
NULL as ITEM_TYPE_ID,
NULL as TEMP_ITEM_TYPE_ID FROM
SFMDB.BIB_MFHD,
SFMDB.EITEM,
SFMDB.MFHD_MASTER,
SFMDB.MFHD_DATA
WHERE
BIB_MFHD.BIB_ID = 5976
AND BIB_MFHD.MFHD_ID = EITEM.MFHD_ID
AND MFHD_MASTER.MFHD_ID = BIB_MFHD.MFHD_ID
AND MFHD_DATA.MFHD_ID = BIB_MFHD.MFHD_ID
AND MFHD_MASTER.SUPPRESS_IN_OPAC='N'
ORDER BY ITEM_SEQUENCE_NUMBER1, MFHD_DATA.MFHD_ID, MFHD_DATA.SEQNUM
;

**Comment by nmswanson** [comment]
PRK - Help! We have brought up new VuFind and just hit our first hurdle. Our ereserves links are not in the new system.

Here's an example, on reserve for OTA111.
Old VuFInd Record
[https://vufind.carli.illinois.edu/vf-prk/Record/prk_116943](https://vufind.carli.illinois.edu/vf-prk/Record/prk_116943)

New VuFind Record
[https://i-share.carli.illinois.edu/vf-prk/Record/PRKdb.116943](https://i-share.carli.illinois.edu/vf-prk/Record/PRKdb.116943)

**Comment by cedelis** [comment]
Added a (tweaked) version of Gordon's SQL from May into TEST.

**Comment by cedelis** [comment]
In production
