### ISSUE TITLE
UB Fines/Fees not showing in Your Account Fines section

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#168]
(Examples with specific accounts and items in vu-it email on 3/27.)

Email from @cedelis on 3/27:
In the Checked Out Items tab, there is some information related to these Fines:

You have 614.95 in Universal Borrowing fines. The limit for your patron group is 200.00.
yet the Fines tab does not list any.

The reason that the Checked Out Items tab was able to determine this is because in the VoyagerRestful Driver, a VXWS call is made to obtain this information.

HOWEVER, in the Fines tab, the VoyagerRestful Driver does NOT make a VXWS call. Instead, it relies on its parent class, Voyager, to perform the getMyFines() function call, in which is makes a direct SQL call to Oracle. My guess is that the SQL in the Voyager driver is not "UB aware" (as it looks up only the local Voyager table and does not join the VOYAGER_DATABASES table. See below the actual SQL it uses).

It probably makes sense for me to override the getMyFines() Driver method so that it makes a call the VXWS (which *is* UB aware) instead of direct Oracle SQL calls.

*****************************Voyager::getFineSQLarray (
  'expressions' =>
  array (
    0 => 'FINE_FEE_TYPE.FINE_FEE_DESC',
    1 => 'PATRON.PATRON_ID',
    2 => 'FINE_FEE.FINE_FEE_AMOUNT',
    3 => 'FINE_FEE.FINE_FEE_BALANCE',
    4 => 'to_char(FINE_FEE.CREATE_DATE, \'MM-DD-YY HH:MI:SS\') as CREATEDATE',
    5 => 'to_char(FINE_FEE.ORIG_CHARGE_DATE, \'MM-DD-YY\') as CHARGEDATE',
    6 => 'to_char(FINE_FEE.DUE_DATE, \'MM-DD-YY\') as DUEDATE',
    7 => 'BIB_ITEM.BIB_ID',
  ),
  'from' =>
  array (
    0 => 'AUGDB.FINE_FEE',
    1 => 'AUGDB.FINE_FEE_TYPE',
    2 => 'AUGDB.PATRON',
    3 => 'AUGDB.BIB_ITEM',
  ),
  'where' =>
  array (
    0 => 'PATRON.PATRON_ID = :id',
    1 => 'FINE_FEE.FINE_FEE_TYPE = FINE_FEE_TYPE.FINE_FEE_TYPE',
    2 => 'FINE_FEE.PATRON_ID  = PATRON.PATRON_ID',
    3 => 'FINE_FEE.ITEM_ID = BIB_ITEM.ITEM_ID(+)',
    4 => 'FINE_FEE.FINE_FEE_BALANCE > 0',
  ),
  'bind' =>
  array (
    ':id' => '284773',
  ),
)
******************************

**Comment by cedelis** [comment]
Commit 5f3998add528816419993c7cab1c68d336d25bad

**Comment by dmcmpbll** [comment]
While the amounts showing are correct, the titles are incorrect. I'll send screenshots to the email list (since they contain patron information).

**Comment by cedelis** [comment]
Thanks for finding this, @dmcmpbll 

I saw that VuFind was injecting 'title' information using the RecordDriver (SolrDefault) in the Controller instead of using the value returned from our ILS Driver (CARLI::VoyagerRestful). 

I decided to use a different variable name, title2, instead for our purposes.

commit b26fe15485ec1ab9601c6b1e1a2d4cc3132efc6e

**Comment by dmcmpbll** [comment]
That fix seems to have corrected the title display on the fines tab.
Both the local fines and the I-Share fines I've checked are displaying as I expected.

**Comment by gibsonjc** [comment]
I re-checked this on prod and test with the example provided on the email list and the correct titles and fines are displaying, so this has been done and I will close this Issue.
