### ISSUE TITLE
Can order of holdings in I-Share not be alphabetical

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#171]
Without a "request first available option", the alphabetical listing of institutional holdings in I-Share  means that requests maybe be disproportionately placed at institutions in the top of the list. Could we randomize the listing of holdings?

**Comment by cedelis** [comment]
I have randomized the holdings. However, I still show the catalog owner's library at the top of the list, e.g., in UIU's catalog (/all/vf-uiu/), UIU will be shown at the top and the rest will be randomized.

**Comment by gibsonjc** [comment]
Closing; done on all servers.
