### ISSUE TITLE
Item status display hierarchy

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#172]
The item statuses that display when there are multiple statuses do not match what we are accustomed to with the Voyager item status hierarchy.  

For examples:  items with Overdue and Lost statuses displays as Overdue when Lost would be preferred

We need to determine what is controlling this display hierarchy and then we can figure out how to adjust it.

**Comment by gibsonjc** [comment]
possible locations for information:

[Status Rankings] stanza in [VoyagerRestful.ini](https://github.com/CARLI/vufind/blob/master/config/vufind/VoyagerRestful.ini)  

[Item_Status] stanza in [config.ini](https://github.com/CARLI/vufind/blob/master/config/vufind/config.ini)

**Comment by gibsonjc** [comment]
Also related: In VuFind 0.6 and Voyager, items with a status of "Damaged" "Circulation Review" and "Cataloging Review" are able to be requested.  In vufind3-devel, the Request link does not display for any item where the status is not "Available", so this would be a significant change in requestability.

**Comment by dmcmpbll** [comment]
To double-check: since Devel and Prod are understandably in slightly different configurations, I should test these statuses on Devel, correct?

**Comment by gibsonjc** [comment]
@dmcmpbll yes, I think starting on DEVEL is ok. thanks!

**Comment by dmcmpbll** [comment]
The [Status Rankings] stanza in VoyagerRestful.ini looks very promising.
Are we currently using the default as show in the link that Jessica linked to above, or has ours been modified to include more statuses?

**Comment by cedelis** [comment]
@dmcmpbll 

We are currently using the default settings for StatusRankings:

; Status rankings can be used to either promote or demote certain item statuses when
; determining the status to be displayed. The lower the rank, the higher the
; priority. The sample values below make "Missing" most important and drop request
; statuses below others so that e.g. "On Hold" is displayed instead of
; "Hold Request".
[StatusRankings]
;Missing = 0
;Recall Request = 99
;Hold Request = 99


We do not use the default settings for Item_Status. Instead, we changed the value of multiple_call_nos from first to msg:


 This section controls how item status information is presented in search results.
[Item_Status]
; Usually, there is only one location or call number for each item; however, when
; multiple values are found, there are several possible behaviors:
;     first = display the first value found, ignore the rest
;     all   = show all of the values found, separated by commas
;     msg   = show a message like "Multiple Call Numbers" or "Multiple Locations"
;     group = show availability statuses for each location on a separate line,
;             followed by callnumber information (valid for multiple_locations only)
;multiple_call_nos = first
multiple_call_nos = msg ; CARLI
multiple_locations = msg

**Comment by dmcmpbll** [comment]
Here's my first draft at ranking status display order.
Comments on this order?

Debbie Draft RANK | ITEM_STATUS_TYPE-ITEM_STATUS_DESC
1 | 14-Lost--System Applied
2 | 13-Lost--Library Applied
3 | 17-Withdrawn
4 | 12-Missing
5 | 5-Recall Request
6 | 4-Overdue
7 | 3-Renewed
8 | 15-Claims Returned
9 | 2-Charged
10 | 7-On Hold
11 | 10-In Transit On Hold
12 | 9-In Transit Discharged
13 | 6-Hold Request
14 | 8-In Transit
15 | 23-Call Slip Request
16 | 22-In Process
17 | 16-Damaged
18 | 18-At Bindery
19 | 21-Scheduled
20 | 24-Short Loan Request
21 | 25-Remote Storage Request
22 | 11-Discharged
23 | 1-Not Charged
24 | 19-Cataloging Review
25 | 20-Circulation Review

**Comment by dmcmpbll** [comment]
SAI- It might be confusing for patrons who try and renew, especially because you can often renew an overdue item, but not a "lost" item. As of now in the new VuFind "lost" items (both ours and I-Share) only show up as overdue and don't indicate they have gone in to lost status. 

RT 99531

**Comment by dmcmpbll** [comment]
I've updated my suggested ranking to put "Recall Request" as the highest priority status.

Debbie Draft RANK | ITEM_STATUS_TYPE-ITEM_STATUS_DESC
1 | 5-Recall Request
2 | 14-Lost--System Applied
3 | 13-Lost--Library Applied
4 | 17-Withdrawn
5 | 12-Missing
6 | 4-Overdue
7 | 3-Renewed
8 | 15-Claims Returned
9 | 2-Charged
10 | 7-On Hold
11 | 10-In Transit On Hold
12 | 9-In Transit Discharged
13 | 6-Hold Request
14 | 8-In Transit
15 | 23-Call Slip Request
16 | 22-In Process
17 | 16-Damaged
18 | 18-At Bindery
19 | 21-Scheduled
20 | 24-Short Loan Request
21 | 25-Remote Storage Request
22 | 11-Discharged
23 | 1-Not Charged
24 | 19-Cataloging Review (does not usually show in OPAC)
25 | 20-Circulation Review (does not usually show in OPAC)

**Comment by dmcmpbll** [comment]
EIU- "Lost-System Applied" should be a priority-displayed status.

RT 100075

**Comment by gibsonjc** [comment]
@cedelis Can you change the [StatusRanking] stanza in VoyagerRestful.ini to the following list on DEVEL or TEST so we can see how this works?  Thanks!

```
; Status rankings can be used to either promote or demote certain item statuses when
; determining the status to be displayed. The lower the rank, the higher the
; priority. The sample values below make "Missing" most important and drop request
; statuses below others so that e.g. "On Hold" is displayed instead of
; "Hold Request".
;[StatusRankings]
;Missing = 0
;Recall Request = 99
;Hold Request = 99
[StatusRankings]
Recall Request = 1
Lost--System Applied = 2
Lost--Library Applied = 3
Withdrawn = 4
Missing = 5
Overdue =6 
Renewed = 7
Claims Returned = 8
Charged = 9
On Hold = 10
In Transit On Hold = 11
In Transit Discharged = 12
Hold Request = 13
In Transit = 14
Call Slip Request = 15
In Process = 16
Damaged = 17
At Bindery = 18
Scheduled = 19
Short Loan Request = 20
Remote Storage Request = 21
Discharged = 22
Not Charged = 23
Cataloging Review = 24
Circulation Review = 25
```

**Comment by cedelis** [comment]
@gibsonjc I made this change to DEVEL.

**Comment by dmcmpbll** [comment]
Can you tell if there is a second status priority list that controls the display in the checked out items list?

I've begun double-checking that the hierarchy above has been implemented accurately, and initial testing shows the status in the item record view is being adjusted, but the status in the checked out items list is not yet being adjusted.

https://i-share-devel.carli.illinois.edu/vf-mil/Record/MILdb.117505 

Item record view:
![itemrecord](https://user-images.githubusercontent.com/20848151/44755566-559a9d00-aaec-11e8-9967-0a181a5a3fa1.PNG)

Charged items list:
![chargeditems](https://user-images.githubusercontent.com/20848151/44755572-592e2400-aaec-11e8-8e76-1ec43014ac9a.PNG)

I will finish checking the hierarchy for the Item Record View display, and report back when completed.

**Comment by cedelis** [comment]
commit a90ced547f80dd6773d9826841386d9bac10c94b

**Comment by dmcmpbll** [comment]
Does this commit mean the status hierarchy list was also applied on the Charged Items list on devel?

**Comment by cedelis** [comment]
@dmcmpbll It was for a brief moment. I created a separate branch for this issue on DEVEL. I then switched branches to work on other stuff. When I am able to, I will merge this into TEST and change the status of this issue to "Ready for Testing"

**Comment by cedelis** [comment]
in TEST.

**Comment by dmcmpbll** [comment]
I have run through all of the scenarios I'd checked on devel also on test. 
It looks good to me!

**Comment by cedelis** [comment]
In PROD.
