### ISSUE TITLE
In Results list, change red "Checked Out" to "Not Available"

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#173]
In the Results list, there is an availability icon. "Available" is green, and "Checked Out" is red.  Rename the red one to "Not Available".  This matches 0.6 and is more accurate than showing "Checked Out" when the item is actually missing.

**Comment by gibsonjc** [comment]
ISU - major concern that Milner Library has before making a switch to VuFind3

**Comment by gibsonjc** [comment]
KNX provided another example where a bib with a MFHD (it's an on order MFHD from Acq, so it only contains 852$b hslnewbks) and an Item with status "In Process" (and without a barcode) displays as "Checked Out" in the results list.  It would be more accurate to have it say "Not Available" in the Results list.
Example: https://vufind3.carli.illinois.edu/vf-knx/Record/KNXdb.305459
![screen shot 2017-07-25 at 12 59 12 pm](https://user-images.githubusercontent.com/17598357/28586494-ae67e778-7139-11e7-95fd-6874e5db1701.png)

**Comment by gibsonjc** [comment]
"Checked Out" is now displaying as "Not Available" in the results list as desired in TEST and PROD.  Ready for Prod.

**Comment by gibsonjc** [comment]
@cedelis For future reference, can you note as a comment here what change you made in which file(s) to accomplish this wording change? Thanks!

**Comment by cedelis** [comment]
Add to languages/en.ini, the following translation:

Checked Out = "Not Available"
