### ISSUE TITLE
EBL records missing holdings in vufind3

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#174]
In the aggregated I-Share uc, I can find bibs that appear to be the EBL bibs if I search for the string carli.eblib.com, and it looks like there should be an EBL holding because they have an 035 with EBL number, but no MFHD.  This is true of records that are part of a match set and those that don't match any other records.

**Comment by cedelis** [comment]
Since we cannot rely on BIB IDs for deduped records (324919989, 324920890) to remain consistent in the future, I am going to translate the two above examples into Title searches:


https://vufind3-devel.carli.illinois.edu/all/vf/Search/Results?lookfor=%22The+sociolinguistics+of+written%22&type=Title&limit=20&sort=relevance

https://vufind3-devel.carli.illinois.edu/all/vf/Search/Results?lookfor=%22Professional+Perspectives+on+Fixed+Income+Portfolio+Management%22&type=Title

**Comment by gibsonjc** [comment]
GF reported on 6/2:   The EBL bibs loaded into OAI last night and they did load into vufind3 UC.  However, holdings do not display and there is no bib id on the results page, but there is an EBL 035 in the staff view.  See

Personality in Adulthood, Second Edition A Five-Factor Theory Perspective
https://vufind3.carli.illinois.edu/all/vf/Record/328370661

https://vufind3.carli.illinois.edu/all/vf/Search/Results?lookfor=Personality+in+Adulthood%2C+Second+Edition&type=Title&limit=20&sort=relevance

**Comment by cedelis** [comment]
One-liner fix.

**Comment by gibsonjc** [comment]
Today, holdings for CARLI eBooks are appearing in the VuFind 3 production I-Share union catalog. A search for carli.ebib.com 
https://vufind3.carli.illinois.edu/all/vf/Search/Results?lookfor=carli.eblib.com&type=AllFields&limit=20&sort=relevance 
yields 3833 records, some of which are part of appropriate match sets.  The 035 field (EBL)nnnnn appears in the bibliographic record.  CARLI eBooks does not currently appear in the Institution facet, which seems correct since it is not an institution.  Just noting it for the record.

3846 EBL records also appear in each local production catalog.  (Do blank search and look for CARLI eBooks in list of Locations.)

The original report of holdings not appearing has been corrected, so I will close this Issue.


Additional information:

_Test:_
Today, the same search in test uc yields only 32 records because these records aren't in test; we are refreshing test from production next week, so will double-check after the refresh.
https://vufind3-test.carli.illinois.edu/all/vf/Search/Results?lookfor=carli.eblib.com&type=AllFields&limit=20&sort=relevance

3846 EBL records also appear in local test catalogs.  (Do blank search and look for CARLI eBooks in list of Locations.)

_Devel:_
The same search in devel uc yields only 15 records because these records haven't been loaded there.  Just noting this difference for the record.
https://vufind3-devel.carli.illinois.edu/all/vf/Search/Results?lookfor=carli.eblib.com&type=AllFields&limit=20&sort=relevance

3846 EBL records also appear in local devel catalogs.  (Do blank search and look for CARLI eBooks in list of Locations.)
