### ISSUE TITLE
Excerpt tab

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#177]
I notice that the All I-Share view has an "Excerpt" tab, that the local view does not. 

Should the Excerpt tab be turned off for the I-Share view (as in, would it ever have content?)

Local view: https://vufind3-devel.carli.illinois.edu/vf-uiu/Record/UIUdb.4979165 
I-Share view: https://vufind3-devel.carli.illinois.edu/all/vf-uiu/Record/302262091

**Comment by gibsonjc** [comment]
In Issue #61 , Syndetic subscriptions as of July 1, 2016 have been implemented in all local catalogs and I-Share (for CARLI's subscriptions) for
    author notes
    cover images
    first chapters (excerpts)
    reviews

Last we knew, CARLI/I-Share has a subscription for Excerpts but UIU does not, that's why the tab appears in one but not the other.
