### ISSUE TITLE
Staff View tab says Loading... but never displays MARC record

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#178]
As of 5/12 on -temp and -test, the "Staff View" tab in the holdings area does not display the MARC record.  It is working correctly on -devel.

**Comment by gibsonjc** [comment]
On 5/15 the Staff View tab is showing the MARC records again on temp and test.  Do we know what changed?

**Comment by cedelis** [comment]
I noticed a php5-xsl package needed to be installed (which I added to our wiki):

apt-get install php5-xsl

I did this today. It now works!

**Comment by gibsonjc** [comment]
Great! Closing!
