### ISSUE TITLE
staff view tab does not display MARC on devel

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#179]
Since devel was refreshed earlier this week, does it need the same fix as Issue #178 ?

"a php5-xsl package needed to be installed"

Or is this a new problem related to the update to 3.1.3?

**Comment by cedelis** [comment]
The php5-xsl library was missing. I had to install it again. Now it works again.

**Comment by gibsonjc** [comment]
Agreed! Closing.
