### ISSUE TITLE
Notes and data fields in MFHDs do not display in Holdings tab

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/vufind#18]
JIRA issue created by: Jessica Gibson (gibsonjc)
Originally opened: 2016-01-28 09:03 AM

Default VuFind 2.x doesn't seem to display any of the data fields (summary or detailed holdings) or public notes fields from the Voyager MFHD record.  I haven't yet found that there are options to turn on to display more of this information, or maybe we aren't providing it the data it needs to display?  

The VuFind2 demo and Villanova's own public catalog don't seem to display much more of this kind of information either (maybe they don't have this data?), although they do have a "Volume Holdings:" line coming from somewhere that looks like a summary one would find in a MFHD 866 field (Example: https://library.villanova.edu/Find/Record/1501304).

For VuFind 0.6, we developed a custom specification for the holdings displays to include information from the MFHD and the Item record.  The current summary of that is at http://www.carli.illinois.edu/products-services/i-share/opac/vf-hldg-cfg ; I also have the documentation on the original specs.  I'm not advocating that we have to do the exact same thing as in 0.6, but one cannot deny that there is a ton of holdings information missing from this default Holdings display tab in version 2.x.

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-01-28 09:18 AM

Examples:

https://vufind2.carli.illinois.edu/vf-nby/Record/(NBYdb)650624
http://vufind.carli.illinois.edu/vf-nby/Record/nby_650624

https://vufind2.carli.illinois.edu/vf-nby/Record/(NBYdb)74332
http://vufind.carli.illinois.edu/vf-nby/Record/nby_74332

https://vufind2.carli.illinois.edu/vf-uiu/Record/(UIUdb)4391882
http://vufind.carli.illinois.edu/vf-uiu/Record/uiu_4391882

**Comment by patrickzurek** [comment]
JIRA User: Chris Delis (cedelis)
JIRA Timestamp: 2016-02-23 02:11 PM

Jessica,

I think the goal here is to see how we can make the best use out of the NCIP protocol, since that is what we are using to retrieve Holdings information.

This means we have the following XML schema definition (xsd) at our disposal:

    http://www.niso.org/schemas/ncip/v2_02/ncip_v2_02.xsd

In the latest release of this schema, I notice an element called ItemNote. It seems appropriate to me to fill this in with Notes information, at the very least. There can be multiple ItemNotes per each Item, therefore we could create one for each data field we would like to display. But there wouldn't be a way to distinguish between one from another (they would all be grouped as a single data item). Does this seem like a logical path to follow? What do you think?

If we were to go this route, I would need to know which MFHD fields and subfields to display. Edit: I now realize you supplied the following URL: http://www.carli.illinois.edu/products-services/i-share/opac/vf-hldg-cfg

I wonder if prepended the text with a label might be useful?


NEVER MIND!!!! (I'm going to delete this comment soon)

I found out that ItemNote is its own "thing." I see mention of it in the Voyager RESTful web services data. But in the examples in this Issue, this setting is always "0", e.g.,

       <item href="http://voyager-pooled-test.carli.illinois.edu:19913/uiu/vxws/record/4391882/items/8517599">
          <itemData id="303" name="permLocation" code="stx">Main Stacks</itemData>
          <itemData id="0" name="tempLocation"/>
          <itemData id="303" name="location" code="stx">Main Stacks</itemData>
          <itemData name="callNumber">917.305 JOU1</itemData>
          <itemData name="copy">c. 1</itemData>
          <itemData name="itemBarcode">30112075445715</itemData>
          <itemData name="enumeration">v.25</itemData>
          <itemData name="chron">(2002)</itemData>
          <itemData name="year"/>
          <itemData name="caption"/>
          <itemData name="freeText"/>
          <itemData name="typeCode">38</itemData>
          <itemData name="typeDesc">SERIAL2</itemData>
          <itemData name="tempType">0</itemData>
          <itemData name="itemStatus">In Process</itemData>
          <itemData name="spineLabel"/>
          <itemData name="itemNote">0</itemData>
          <itemData name="onReserve">N</itemData>
        </item>

Blech... I'm back to the drawing board...

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-04-05 12:50 PM

config.ini has the following settings that may or may not be related:

; Text fields such as notes gathered from items to be displayed in each
; holdings group in the display order.
; The default list is 'notes', 'summary', 'supplements' and 'indexes'.
; Note that displayed information depends on what the ILS driver returns.
;holdings_text_fields[] = 'notes'
;holdings_text_fields[] = 'summary'

These are the right types of data (notes, summary holdings, supplements, indexes) but they aren't in our Item Records; they are in our MFHDs.

**Comment by patrickzurek** [comment]
JIRA User: Chris Delis (cedelis)
JIRA Timestamp: 2016-04-05 01:49 PM

The following two comments are important:

; The default list is 'notes', 'summary', 'supplements' and 'indexes'.


which means that they are already 'enabled'.

; Note that displayed information depends on what the ILS driver returns.

which reminds us that the ILS driver we are using (XCNCIP2) does not return this information therefore it does not display ;-)

**Comment by patrickzurek** [comment]
JIRA User: Chris Delis (cedelis)
JIRA Timestamp: 2016-04-08 11:01 AM

root@vufind2-test:/usr/local/vufind2# git diff ad7ed1f6f9986f2d9bf557ccfe20d589e5e04bd9 themes/bootprint3/templates/RecordTab/holdingsils.phtml
diff --git a/themes/bootprint3/templates/RecordTab/holdingsils.phtml b/themes/bootprint3/templates/RecordTab/holdingsils.phtml
index f01f84f..1adc9c5 100644
--- a/themes/bootprint3/templates/RecordTab/holdingsils.phtml
+++ b/themes/bootprint3/templates/RecordTab/holdingsils.phtml
@@ -39,6 +39,7 @@
 <? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
     <a class="placehold modal-link" title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc('tit
 <? endif; ?>
+
 <? foreach ($holdings as $holding): ?>
 <h3>

**Comment by gibsonjc** [comment]
SIE - These are all journals. None of the summary holdings are displaying, just the location of the holdings.

https://vufind3.carli.illinois.edu/vf-sie/Record/(SIEdb)523316
Chemistry: a European journal

https://vufind3.carli.illinois.edu/vf-sie/Record/(SIEdb)76631
Journal of medicinal chemistry

https://vufind3.carli.illinois.edu/vf-sie/Record/(SIEdb)512740
Journal of physical chemistry. A, Molecules …

**Comment by gibsonjc** [comment]
ISU - History note—ISU/Milner removed MFHD 853/863 pairs shortly after migrating to Voyager.  As I understand that decision, it was taken to solve the type of patron display that I now see in VuFind3 – that is item-level information displayed in very long lists.  I expect the absence of 853/863 pairs in our data impacts some of the following display issues.

None of the information contained in the MFHD (apart from the 856 $u) appears to display.  
The most critical consequence, and one that must be fixed prior to release, is the loss of the display of summary holdings data, and in our case, that is found in the MFHD 866 $a.   In VuFind3 the user is without any summary of the library’s holdings, and instead is dependent upon scanning/searching the display of data from each item record in long lists.  

VuFind3 journal example: https://vufind3.carli.illinois.edu/vf-isu/Record/(ISUdb)119527
Current VuFind display: https://vufind.carli.illinois.edu/vf-isu/Record/isu_119527

Examples of other data present in the MFHD that should display but isn’t: Lacks notes (also in the 866 $a); summary holdings for Indexes (868) and Supplements (867); public notes that convey cancellation data, limited retention data, shelved-by data, etc. (852 $z)
