### ISSUE TITLE
Update to version 3.1.3

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#180]
Copied from 5/18 email so we can keep track of current status on all servers:

On devel:
...created a new branch, carli-release-3.1.3:
https://github.com/CARLI/vufind/tree/carli-release-3.1.3
This new branch contains the latest merge of VuFind's latest release, tagged v3.1.3:
https://github.com/vufind-org/vufind/commits/v3.1.3

Once we determine that everything continues to function correctly on vufind3-devel, then it should be as simple as checking out this new carli-release-3.1.3 branch on vufind3-test

Version 3.1.3 doesn't appear to be a very significant upgrade/merge. Only two files conflicted and the remedy was very simple/trivial to do.

**Comment by gibsonjc** [comment]
I think update to 3.1.3 has this been completed on test and prod now?

**Comment by cedelis** [comment]
Yes, we are on version 3.1.3 now.
