### ISSUE TITLE
Change email address in "System Under Maintenance" message

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#181]
Change the noreply@carli.illinois.edu email address in the "System Under Maintenance" pop-up.

![systemundermaintenance](https://cloud.githubusercontent.com/assets/20848151/26636948/c448c2e6-45e3-11e7-876b-590fe6cf790a.PNG)

**Comment by cedelis** [comment]
Change noreply@carli.illinois.edu to what exactly?

**Comment by gibsonjc** [comment]
Change noreply@carli.illinois.edu to support@carli.illinois.edu

**Comment by cedelis** [comment]
In vufind3-devel.


diff --git a/LOCAL_VF_TEMPLATE/config/vufind/config.ini b/LOCAL_VF_TEMPLATE/config/vufind/config.ini
index 07da8bd..beeef24 100644
--- a/LOCAL_VF_TEMPLATE/config/vufind/config.ini
+++ b/LOCAL_VF_TEMPLATE/config/vufind/config.ini
@@ -19,7 +19,7 @@ autoConfigure = true
 ; Base URL is normally auto-detected, but this setting is used when autodetection is
 ; not possible (i.e. during sitemap generation at the command line).
 url             = http://!VUFIND_SERVER!
-email           = noreply@carli.illinois.edu
+email           = support@carli.illinois.edu
 title           = "Library Catalog"
 ; This is the default theme for non-mobile devices (or all devices if mobile_theme
 ; is disabled below). Available standard themes:
@@ -394,7 +394,7 @@ maximum_recipients = 1
 ; Populate the "from" field with this value if user_email_in_from is false and/or no
 ; user is logged in:
 ;default_from = "no-reply@myuniversity.edu"
-default_from = "noreply@carli.illinois.edu" ; CARLI
+default_from = "support@carli.illinois.edu" ; CARLI
 ; Should we hide the "from" field in email forms? If no from field is visible, emails
 ; will be sent based on user_email_in_from and default_from above, with the email
 ; setting from the [Site] section used as a last resort.

**Comment by gibsonjc** [comment]
Looks good on test; ready for prod

**Comment by cedelis** [comment]
Pulled carli-release-3.1.3 changes into Prod server.
