### ISSUE TITLE
Shibboleth/barcode changes?

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#183]
The first time a Shibboleth login occurs (Intstitutional Login), VuFind prompts the patron to enter their barcode/last name so that it can be profiled with the netid/password.

What happens if the patron enters the wrong barcode/misspells their name?
What happens if the patrons' barcode/name is later changed in Voyager?

**Comment by cedelis** [comment]
If they enter wrong barcode or last name, the profiling should fail and the patron should be prompted again. The same should occur if any changes were to occur later on the backend system (Voyager).
This should be tested and verified, of course.

**Comment by gibsonjc** [comment]
I confirm that I could not enter an incorrect barcode or last name when performing the profile step.  If I did, it would not log me in or complete the profiling.  It gave me an error about invalid login.

**Comment by dmcmpbll** [comment]
After creating my account, when I changed my barcode and logged in the next time, I was prompted to re-enter my barcode/last name to view my Voyager data.

Same for changing my last name.

Seems to be working as anticipated.

**Comment by gibsonjc** [comment]
Thanks for the testing @dmcmpbll , this is what we were anticipating would happen. I'll close this Issue!
