### ISSUE TITLE
not all NBY records are present in vufind3 local

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#188]
NBY - It appears that not all of our collection has been loaded. I find only about 10%. Will the rest be added?
Having the entire collection available will help in evaluating call number browsing and other features more effectively.

**Comment by gibsonjc** [comment]
https://www.carli.illinois.edu/products-services/i-share/stats/16_stat8 says NBYdb should have at least 945,935 bib records as of last count (last July 1st?).  I don't think this includes the HathiTrust set.

When I do a search for everything in vufind3 I get 101,616:
https://vufind3.carli.illinois.edu/vf-nby/Search/Results?lookfor=&type=AllFields

In vufind3-test, I get 1,450,974: (there HathiTrust bibs in this results list as well which I do not expect to see here)
https://vufind3-test.carli.illinois.edu/vf-nby/Search/Results?lookfor=&type=AllFields

In vufind3-devel, I get 100,270:
https://vufind3-devel.carli.illinois.edu/vf-nby/Search/Results?lookfor=&type=AllFields

**Comment by cedelis** [comment]
There is definitely a discrepancy, but the numbers mentioned above do include EBL and HathiTrust records, I believe.

The actual bib counts between production and test are 97770 and 324725.

We are looking into the matter.

cedelis@vufind3-prod$ wget -q -O- 'http://localhost:8080/solr/biblio/select?q=*:*&fq=institution:"NBYdb"' | xmllint --format - | grep numFound

  &lt;result name="response" numFound="97770" start="0"&gt;

cedelis@vufind3-test$ wget -q -O- 'http://localhost:8080/solr/biblio/select?q=*:*&fq=institution:"NBYdb"' | xmllint --format - | grep numFound

  &lt;result name="response" numFound="324725" start="0"&gt;

**Comment by gibsonjc** [comment]
We've discovered a bug in the solrmarc loading process that caused most of Newberry's records not to load into VuFind 3.  When the load hit a particular malformed character in one record, it caused the whole load to die rather than skipping that record and continuing to load the rest of the records.  Our developer is working on this bug with the solrmarc developers, and we hope to have it corrected and all records reloaded into VuFind by the end of June.  Fixing this problem will also benefit all users of solrmarc, not just CARLI.

**Comment by gibsonjc** [comment]
Reindex completed on devel and swapped to production the evening of June 29. All updates ran successfully overnight.  All NBY records now appear in vufind3.carli.illinois.edu. Closing.
