### ISSUE TITLE
API or XML for UIUC

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#189]
In VuFind 0.6, we provide UIUC (and anyone else who might request it) a "&view=xml" URL flag that displays search results in XML. This is much easier for them to parse than screen-scraping:

   https://vufind.carli.illinois.edu/vf-uiu/Search/Home?lookfor=shakespeare&type=author&view=xml

They would like this type of functionality with our new VuFind server. Ideally, if there is an existing API we can use, let's use that instead of creating a custom XML feed.

Here is a blurb about API's from the vufind.org website:
"VuFind has many APIs to interact with the search, data and many other features. You can syndicate your record data with other institutions via an OAI server. You can search using vufind's algorithms via OpenSearch. And if you want complete access to your indexed data, you can interact with Solr, VuFind's backend search and index engine."

Documentation about API's on the vufind.org website appears to reference version 4.x, but I assume there could be other API's available in version 3.x:

   https://vufind.org/wiki/development:apis

**Comment by cedelis** [comment]
Just an FYI:

The following documentation about APIs is for version 4.x only. There is no such functionality present in 3.x or earlier.

The API branch of code was only recently added to master:

https://github.com/vufind-org/vufind/commits/master/module/VuFindApi/src/VuFindApi

**Comment by bgant** [comment]
Principia College would also like access to the VuFind 4.x API when it becomes available (see RT #89872).

**Comment by gibsonjc** [comment]
Replied to EIU on RT 95628.
Sent email to Michael Norman at UIUC.
Replied to PRC on RT 89872.

Documented availability on TEST at https://www.carli.illinois.edu/products-services/i-share/opac/new-vufind-faq#api

**Comment by gibsonjc** [comment]
On April 10, 2018, Michael Norman said in an email to us that UIUC plans to use the built-in VuFind API with their Easy Search Bento.  No additional development work appears to be needed, so I will close this Issue.
