### ISSUE TITLE
Most Recently checked-in issues from Acquisitions do not display

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/vufind#19]
JIRA issue created by: Jessica Gibson (gibsonjc)
Originally opened: 2016-01-25 01:37 PM

Latest issues checked-in from Voyager Acquisitions do not display anywhere.

At the end of the /usr/local/vufind2/themes/bootprint3/templates/RecordTab/holdingsils.phtml file there is a section that references "Most Recent Received Issues"

Example: New york times magazine at MIL has many issues 
https://vufind2-test.carli.illinois.edu/vf-mil/Record/%28MILdb%29150109 
(VS. the things appearing under the label "Latest Issues:" http://vufind.carli.illinois.edu/vf-mil/Record/mil_150109)

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-01-28 09:19 AM

Another example:

https://vufind2.carli.illinois.edu/vf-nby/Record/(NBYdb)74332
http://vufind.carli.illinois.edu/vf-nby/Record/nby_74332

**Comment by gibsonjc** [comment]
ISU - Serial check-in data does not display.  Serials in our db with an unsuppressed 2per MFHD should always display the current issues – that is, those that have been checked-in and set to ‘display in opac’ in Voyager Acquisitions.

VuFind3 serial example: https://vufind3.carli.illinois.edu/vf-isu/Record/(ISUdb)181789
Current VuFind display: https://vufind.carli.illinois.edu/vf-isu/Record/isu_181789
