### ISSUE TITLE
Sort Call Number search results by call number rather than relevance

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#190]
When doing a call number search, currently the default sort of the results is "Relevance".  Can this be changed to "Call Number" sort for call number searches?

**Comment by gibsonjc** [comment]
This looks like it is controlled in the [DefaultSortingByType] stanza of searches.ini.  Can we simply uncomment this entry for CallNumber so that it is active to make a Call Number search default to sorting by call number instead of relevance?

; This section allows you to specify the default sort order for specific types of
; searches.  Each key in this section should correspond with a key in the
; [Basic_Searches] section above.  Each value should correspond with a key in the
; [Sorting] section above.  Any search type that is not listed here will be sorted
; using the default_sort setting in the [General] section above.
[DefaultSortingByType]
;CallNumber = callnumber-sort

**Comment by gibsonjc** [comment]
MIL - I still don’t understand how a call number search can be sorted by relevance.  What is the system using to determine that PS3556 .O645 is more relevant than PS3556 .A76 when searching PS3556? Librarian 2: This seems to be working better, but it still defaults to relevance rather than pure call # order.

**Comment by cedelis** [comment]
I agree that Relevance sorting is not very useful for Call Number searches.

I think it makes sense to default to "Sort by Call Number" (callnumber-sort), which is accomplished by editing config/searches.ini:

; This section allows you to specify the default sort order for specific types of
; searches.  Each key in this section should correspond with a key in the
; [Basic_Searches] section above.  Each value should correspond with a key in the
; [Sorting] section above.  Any search type that is not listed here will be sorted
; using the default_sort setting in the [General] section above.
[DefaultSortingByType]
CallNumber = callnumber-sort

**Comment by cedelis** [comment]
In DEVEL and TEST.

**Comment by slknight** [comment]
Still defaulting to relevance with a completely naive browser. Checked in Firefox, Chrome, and IE.

There seems to be a cookie or something in play though, because if the user switches to call number sort, that holds through restarting the browser.

![image](https://user-images.githubusercontent.com/15163837/28470994-30ba9dd8-6e01-11e7-90c8-1a8bdfa6ab4c.png)

**Comment by cedelis** [comment]
@slknight I cannot replicate this, I'm afraid.

I've attached 3 screenshots: 1) initial page at EIU's local catalog; 2) After having entered Call Number search values (before clicking Find button); 3) The Search Results confirming that the default Sort is by Call Number. 

Can you compare the URL strings in the browser at the various steps?

Thanks

![part1](https://user-images.githubusercontent.com/6808751/28472283-9794f8ce-6e05-11e7-85e2-0feaa4b18ea0.png)

![part2](https://user-images.githubusercontent.com/6808751/28472295-a25658fc-6e05-11e7-979f-49c69a9a759d.png)

![part3](https://user-images.githubusercontent.com/6808751/28472303-a91b21e0-6e05-11e7-8f18-e09709e4ed9c.png)

**Comment by slknight** [comment]
I can't duplicate it now either, so let's call is a temporary glitch.

**Comment by dgree1** [comment]
New default sort working well in my tests in vufind3-test.carli.illinois.edu with three different libraries.

**Comment by gibsonjc** [comment]
@cedelis Ok to move call number sort change to production!
