### ISSUE TITLE
can all bib/MFHD 5XX fields display, at least at local level

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#193]
NBY - At this point for the Newberry to use this interface as its catalog we would need the following: 1. This was sent last year (#80717)
I've noticed that in the "More details" display for bibliographic records in VuFind that only some of our 5XX fields display. I've looked over the VuFind Record document for the More details tab and find missing 5XX tags, that for us, contain information about characteristics or associations that are of interest to our staff and users. While the "Staff Display" helps, many users are unaware of its usefulness and have difficulty in interpreting the information.

These are the tags we use that don't display. I've included a bib number example.
But there are also other 5XX fields that we are likely to use.
Would it be easier to make all  5XX available for display, at least at the local level?

Fields and example records in NBYdb:

505  - bib 863716
508
510
515  - bib 111220
524  - bib 142878
525  - bib 93383
530  - bib 193833
541  in both bib and MFHD this should display if the first indicator is 1  - bib 826575
541  in both bib and MFHD this should NOTdisplay if the first indicator is 0 or blank  - MFHD 970608
544  - bib 128677
545  subfield $b doesn't display  - bib 142878
550  - bib 279104
561  - bib 119168
562  - bib 399546
563  - bib 131852
581  used but can't locate the records.
583  - bib 864964
585 - bib 820442
588

**Comment by nmswanson** [comment]
Technical Services Committee-
Display MFHD tags 541, 561, 562, 563, and 583 as “notes” in the holdings display of the local catalog.
Details: Libraries use these fields to add copy-specific notes that are beneficial to users. These notes should display alongside holdings information in local catalogs.

Annual Project Recommendation no.8

**Comment by nmswanson** [comment]
PRC- Will the MFHD 541 fields be displayed in the future?

Ex. The bolshevik persecution of Christianity. 
Main Author: McCullagh, Francis. 
Published: New York, E.P. Dutton, 1924. 

MFHD: 541 1_ ‡a David Anderson Collection on the Russian Revolution

VF 0.6 displayis label "Source of material" before data:
[https://vufind.carli.illinois.edu/vf-prc/Record/prc_109536 ](https://vufind.carli.illinois.edu/vf-prc/Record/prc_109536 )

New VF: [https://i-share.carli.illinois.edu/vf-prc/Record/PRCdb.109536](https://i-share.carli.illinois.edu/vf-prc/Record/PRCdb.109536)

RT100705

Note: VuFind 0.6 displayed MFHD 541**abcdefhno3

**Comment by gibsonjc** [comment]
Several of these requested fields were added to **Bib** record displays in Phase 1 on 1/11/2019 as part of Issue #265 :

510$abc3
515$a
524$a3- Local only
525$a - Local only
541$abcdefno3 - Local only with indicator display logic
544$abcden3 - Local only
545$abu - Local only
550$a
561$a3 - Local only
562$abcd3 - Local only
563$a3 - Local only
581$a3 - Local only
583$abcdefhijklnouz3 - Local only
585$a3 - Local only

(505 was already present in Table of Contents tab)

588 is more of a cataloger's note and will not be displayed to the public in New VuFind.

508 and 530 are pending.

**Comment by gibsonjc** [comment]
Bib 508 is now displaying after #402 .  Bib 530 still pending.

**Comment by gibsonjc** [comment]
MFHD fields 506, 538, 541, 561, 562, 563, 583, 843, 845 display in holdings tab and ready for testing.

**Comment by gibsonjc** [comment]
MFHD fields 506, 538, 541 (Ind1=1 only), 561, 562, 563, 583, 843, 845 all display in holdings tab with the closing of #355 

BIB 530 currently displays under the label "Physical Description" because it is part of the default definition for "physical" (along with 300), but we are planning to remove that when we reindex.  We will need to decide if we want to display 530 in its own field or in the general Notes field (with 500).  Since all of the other fields in this Issue are addressed, I am going to close this and we will address BIB 530 elsewhere.
