### ISSUE TITLE
better descriptions of Export options

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#197]
SXU - Is there going to be a better description of the available export options? Using RefWorks and EndNote is fine, but it doesn’t help folks using other popular tools such as Zotero and Mendeley … they need to know the actual format if you don’t include the names beside the options.

**Comment by gibsonjc** [comment]
https://www.zotero.org/support/getting_stuff_into_your_library
https://www.mendeley.com/

From config.ini:

> ;This section controls which record export methods are displayed on the Record
> ; view screen.  Note that some options may be disabled for records that do not
> ; support them, regardless of the setting chosen here.  You can edit the separate
> ; export.ini file to add new export formats and change the behavior of existing ones.
> [Export]
> RefWorks = true
> EndNote = true
> EndNoteWeb = true
> MARC = false
> MARCXML = false
> RDF = false
> BibTeX = false
> RIS = false

export.ini "controls the formats which can be used to export data" and also controls the label (and order) that displays in the dropdown (section name used unless label is specifically defined).

**Comment by bgant** [comment]
I found the following info which is useful (scroll to the bottom):  
http://vufind.2307425.n4.nabble.com/Zotero-Mendeley-td4662791.html

I recommend that we go ahead and enabled BibTex and RDF in the config.ini on all servers so users know that those two options exist.

I am checking to see if we should copy the BibTex stanza in the export.ini and add two new ones named Zotero and Mendeley (with the same BibTex settings). Then users know exactly which "Export Record" format to choose instead of figuring out that BibTex is the one they want.

**Comment by bgant** [comment]
SXU agrees with setting "BibTeX = true" and "RDF = true" in the config.ini. 

They also agree with adding [Zotero] and [Mendeley] stanzas to the export.ini using the BibTeX settings and setting them to "true" in the config.ini as well.

**Comment by gibsonjc** [comment]
I believe the changes needed here are as follows:

1. In config.ini, please change these two options from "false" to "true"
RDF = false
BibTeX = false

2. The second part of the needed changes seems to involve three parts: 
Editing the export.ini to copy the [BibTeX] stanza twice, renaming one [Zotero] and one [Mendeley], 

then adding 
Zotero = true
Mendeley = true
to the [Export] stanza in config.ini, 

and then setting up the CARLI script to distribute the custom export.ini file (because I don't think that file has been customized previously).

**Comment by gibsonjc** [comment]
TIU - Another question we have about VuFind 3 is about citation data exported to Zotero. Our Reference Librarians have been instructing our users to use the Classic WebVoyage interface when building their Zotero library because when they try to use VuFind the data has punctuation added to the fields (Looks like the ISBD slashes and colons). Looks like VuFind 3 is also pulling in the punctuation when exporting to Zotero. Can anything be done for this?

[moved this report to a new Issue #238 ]

**Comment by cedelis** [comment]
@gibsonjc , I agree with step 1 above (enabling RDF and BibTeX support). However, I don't believe Zotero or Mendeley depend (or even make use of) the Export options; instead, they rely on browser plugins which integrate with their respective products (I've tested this myself, for both Zotero and Mendeley). As for TIU's issue with the "data exported to Zotero" and its data having "punctuation added to the fields," that's a different issue, I think.

**Comment by gibsonjc** [comment]
@cedelis Ok, to start, please change the config.ini as in step 1 to enable the additional two formats and let's at least see what that looks like.  Thanks!

**Comment by cedelis** [comment]
Done! Ready for Testing.

**Comment by slknight** [comment]
I would suggest having this open in a new window if possible. 

I can confirm that Mendeley uses a screen scraper. Screenshot pasted below. Mendeley appears to be working as expected.

![image](https://user-images.githubusercontent.com/15163837/28468232-f2ef6366-6df7-11e7-9992-9192dc8d7fa4.png)

**Comment by gibsonjc** [comment]
@slknight Can you elaborate on what you mean by "I would suggest having this open in a new window if possible."  Do you mean the "Export Record" drop down or ?  (I've never seen it open a window, it seems to download a file or auto import it into Zotero or similar.)  Thanks!

**Comment by slknight** [comment]
The behavior I'm seeing may be unique to my overly-customized Firefox. Please recruit other Firefox users to be sure.

What happens for me in Firefox 54 on Win 7 when I click on Export to RDF is that the XML file opens in the browser. It opens in _self, so there is no way to get back to the catalog record without hitting the back button. 

In Chrome I get a download, which I assume is the expected behavior.

Refworks and Endnote open in a new window, which is good.

**Comment by slknight** [comment]
I tested RDF menu link on a fresh install of Firefox 54 on a fresh install of Win7. The XML opens in the browser without opening a new window.

**Comment by gibsonjc** [comment]
Enabling the RDF and BibTeX export options is Ready for Production.
