### ISSUE TITLE
SFX "Get full text" links appear in I-Share /all/vf/ Results List but do not work

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#198]
Example:
Results 1-4 at: https://vufind3.carli.illinois.edu/all/vf/Search/Results?lookfor=american+libraries&type=Title&limit=20&sort=relevance

**Comment by gibsonjc** [comment]
"Get full text" links to SFX should not display in the VuFind 3 I-Share uc.  If possible, please turn off these links from display or hide them.  

Seems similiar to Issue #152 but that's for local catalogs.  This is for the uc so slightly different settings are required:

In the [Open URL] stanza, there is a setting to indicate where to display the Open URL links. We'd like to have it display in the holdings data area only for the VuFind 3 uc but NOT in the search results (the "Get full text" link, or the SFX button if that is able to be set up in Issue #146 ).

; The following settings control where OpenURL links are displayed:
show_in_results = true ; include in search results
show_in_record = false ; include in core record metadata
show_in_holdings = false ; include in holdings tab of record view

change to

show_in_results = false ; include in search results
show_in_holdings = true ; include in holdings tab of record view

**Comment by cedelis** [comment]
It appears that the "Open URL" functionality is making use of the bib's 856 data. This is most likely not what we want to display to the user in the "uc" catalog. I believe the deduped record aggregates all of the matching (source) records' 856 data which results in a collection of URLs (many/most of which) are library-dependent). I will supply a screen shot of an example. This doesn't appear to be a "could be simple" issue and will require more research.

**Comment by cedelis** [comment]
This is the reason we previously commented out the "Open URL" links (this question was asked in a different issue: https://github.com/CARLI/vufind/issues/152#issuecomment-283770373 ). I've temporarily un-commented-out this section so you could see the screen shots below:

![openurl_using_bib856](https://user-images.githubusercontent.com/6808751/28040077-28034dae-658a-11e7-9f09-1ba79192f268.png)
![bib856](https://user-images.githubusercontent.com/6808751/28040084-30712074-658a-11e7-9569-2c30eeba2862.png)

**Comment by slknight** [comment]
SFX link is still there and still going to a 404

![image](https://user-images.githubusercontent.com/15163837/28468571-fd82225e-6df8-11e7-8cea-8b35f7c4d5fc.png)

**Comment by cedelis** [comment]
@slknight Thanks for testing and confirming the issue still persists on the Sesrch Results page. I believe it has been removed from the Detailed Record page, at least. Keeping this issue open.

**Comment by dgree1** [comment]
Jessica, is there research needed? What exactly? 
Denise

**Comment by gibsonjc** [comment]
I introduced multiple things in this Issue by referencing two changes in the config.ini (and then making a further reference to #152 ), so I've changed the Issue subject to limit this one to the Results List in the I-Share uc.  I don't see any evidence in the commit of the config.ini changes being tried yet, but I might be missing something.  I want to know if we can eliminate the "Get full text" links from the results page in the I-Share uc with a simple config.ini change or not.  (This is independent of the Holdings tab OpenURL displays that have been commented out for the aforementioned reasons.)

@cedelis Can we see what it looks like if you change the [OpenURL] stanza in config.ini for the I-Share uc as follows:

; The following settings control where OpenURL links are displayed:
show_in_results = true ; include in search results
show_in_record = false ; include in core record metadata
show_in_holdings = false ; include in holdings tab of record view

change to

show_in_results = false ; include in search results
show_in_holdings = true ; include in holdings tab of record view

Thanks very much!

**Comment by cedelis** [comment]
@gibsonjc The "show_in_results = false" setting seems to work, but the "show_in_holdings = false" did not for whatever reason (guessing a bug somewhere in vufind). In any case, I have put in a workaround in the 'carli' template that will comment-out OpenURLs in /all/vf

**Comment by slknight** [comment]
Confirming this is suppressed in /all/vf/
![image](https://user-images.githubusercontent.com/15163837/28578335-1341cc6a-711f-11e7-81ca-c45c4cb25104.png)


Active in /all/vf-XXX and directing to the correct SFX instance

![image](https://user-images.githubusercontent.com/15163837/28578355-21fe8d4c-711f-11e7-9378-746ffe0e3555.png)

Inactive for UIC and UIS as expected

![image](https://user-images.githubusercontent.com/15163837/28578396-3e19c8ac-711f-11e7-94a4-2825eca0ee4d.png)

**Comment by gibsonjc** [comment]
@cedelis Ok thanks, I think I'm following now!  As of this morning in vufind3-test:

- I do not see "Get full text" links to SFX (that go to the 404 not found) in the results list of an /all/vf/ search ->_YAY, the scope of this Issue 198 appears to be fixed to eliminate those 404 errors. I will do a bit more testing today before declaring this Ready for Prod to make sure we didn't miss anything._ 

- I do see bib 856 fields displaying in the results list of an /all/vf/ search ->_BOO, but this is Issue #54 so we'll move any discussion of that over there..._

- I do not see an Internet section in the Holdings tab of /all/vf/  (so no links to SFX or bib 856 fields) ->_YAY, I assume this is due to the "workaround in the 'carli' template that will comment-out OpenURLs in /all/vf".  This didn't have a current Issue because it was in place from a long time ago._

**Comment by dgree1** [comment]
Confirm tests, 
For ex. no SFX links https://vufind3-test.carli.illinois.edu/all/vf/Record/281528072
Same title in NIU has links
https://vufind3-test.carli.illinois.edu/vf-niu/Record/NIUdb.773895

**Comment by gibsonjc** [comment]
Ready for production
