### ISSUE TITLE
View email address in Your Profile

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#199]
ICC - will there be a way to see in “Your Profile” in the account area to see your email --- preferably the one that courtesy/ overdue / fine emails get sent to?

**Comment by gibsonjc** [comment]
VuFind 0.6 shows:
Name: [First Middle Last]
Address: [all lines in patron for Street, then City, State, Zip]
Email:

VuFind 3 shows:
First name:
Last name: 
Preferred Library: 
Address 1: [line 1 only, it seems]
Zip:
City:
Group: [patron group]

**Comment by nmswanson** [comment]
JKM- Please add a category for email in the Profile page.

**Comment by gibsonjc** [comment]
As of today, New VuFind currently displays:

First Name: 
Last Name: 
Preferred Pick Up Library:
Preferred Pick Up Location:
Address 1: [line 1 only, it seems]
Zip:
City:
Group: [patron group]

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
This Issue has widened in scope to also include which mailing address is shown in the Profile: Permanent or Temporary, and how/if HOLD MAIL should play into display.

**Comment by gibsonjc** [comment]
New SQL in place as of 2/18 and initial testing went well.
As of today, awaiting more complete testing and testing of the new logic that will not display empty temp addresses.

**Comment by gibsonjc** [comment]
All agreed in email that this is Ready for Prod

**Comment by cedelis** [comment]
In PROD
