### ISSUE TITLE
custom help text on login page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#202]
Is it possible to include custom help text on the login page for each library using ILS authentication describing what their library barcode is or where to find it? See Issue #201

**Comment by gibsonjc** [comment]
The barcode/last name boxes to login are in a pop-up made with javascript if you click to it with the "Login" link in the upper right corner, but an actual login page can also be accessed at 
https://vufind3.carli.illinois.edu/vf-knx/MyResearch/ 
Libraries may create links to this login page directly, and this is the page you are taken to when you log OUT of VuFind 3 in a non-Shibboleth institution, so any solution will need to have custom text in both versions of the "page".
cc: @eschell

**Comment by gibsonjc** [comment]
TIU - Is it possible to customize the login window? Right now it asks for barcode and our users are confused by "barcode" but understand "campus id" number (which is only 6 digits). Our other vufind customization has a note field for TIU users to use their student id.

**Comment by gibsonjc** [comment]
@eschell Would you say that we know how to handle this customization request now? If so, can you please comment a bit about the resolution (what you did, which files are affected, etc.) as to how this customizable text is being handled?  Thanks!

**Comment by eschell** [comment]
I added an extra field to loginfields.phtml in the theme templates just before the login form. That extra field will pull from the individual institution theme config.php file to populate with text, if any. I've also added this as an option on the VuFind customization form as well.

**Comment by gibsonjc** [comment]
[VuFind 3 Customization form](https://www.carli.illinois.edu/vufind3-customization) has been released and has this option.  Closing.
