### ISSUE TITLE
One MFHD with holdings displays twice as if two MFHDs

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#203]
SIE - Serial holdings are still not showing up correctly.  See holdings  for Facts on file: https://vufind3.carli.illinois.edu/vf-sie/Record/SIEdb.374518
We have 2 holdings records: 1 for the book collection and a suppressed holding record that was for the Ref collection.  **I’m not sure why the holdings are showing up twice** and what all those copy numbers are.  We only have copy ones.
APSS yearbook holdings show up the same way: 
https://vufind3.carli.illinois.edu/vf-sie/Record/SIEdb.741462
We only have 1 holding record, and all our copies are copy ones.

See also Issue #169

**Comment by gibsonjc** [comment]
TRN - There are multiple holdings appearing on everything that has multiple volumes (e.g. https://vufind3.carli.illinois.edu/vf-trn/Record/TRNdb.1158, https://vufind3.carli.illinois.edu/vf-trn/Record/TRNdb.59121) and the copy numbers are completely messed up (all of the items attached to those records are correctly entered in Voyager as copy 1). It’s a confusing mess. My students will have no idea what to do with that.

**Comment by gibsonjc** [comment]
DOM - In looking at our journal display in VuFind3, it appears as all our journal holdings appear twice. What would be causing this and is there something we can do o fix this? The Journal of Applied Psychology is an example, but every journal I have tried has a double holding entry.
https://vufind3.carli.illinois.edu/vf-dom/Record/DOMdb.54094

**Comment by cedelis** [comment]
Interesting that TEST lists them only once:

https://vufind3-test.carli.illinois.edu/vf-dom/Record/DOMdb.54094

**Comment by dmcmpbll** [comment]
Might this be similar to the difference in display that I reported in https://github.com/CARLI/vufind/issues/242, so may not be a serials issue specifically?

> However, the titles look different between devel and prod, and between test and prod. (test and devel look the same). The basic data on the items as listed above appears unchanged between test/devel/prod.

**Comment by gibsonjc** [comment]
None of these examples are displaying two anymore.  This is great, but it would be nice to know why.  Was it due to work on #246  or #242 or something else entirely?

**Comment by cedelis** [comment]
It was fixed in commit 48ad65c652e0aa951da1b1c5fdb03576fa728048
