### ISSUE TITLE
UB items cannot be renewed

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#206]
Reports suggest that local items can be renewed by a user in the local database, but UB items cannot be renewed.  

Error message received: “This item could not be renewed: Not Renewed”

The same UB items were able to be renewed successfully in VuFind 0.6.

**Comment by cedelis** [comment]
Fix applied to vufind3-devel.

**Comment by gibsonjc** [comment]
@cedelis Please apply this fix to vufind3-test and we'll do a final check there.

**Comment by dmcmpbll** [comment]
In vufind3-test, my tests this afternoon show that UB items are able to be renewed.

**Comment by dgree1** [comment]
For me too. In https://vufind3-test.carli.illinois.edu/vf-uiu/MyResearch/CheckedOut

**Comment by gibsonjc** [comment]
Ready to move to production

**Comment by cedelis** [comment]
Pulled carli-release-3.1.3 changes into Prod server.
