### ISSUE TITLE
Presence of bib 856 field seems to suppress Available/Checked Out indicator in results list

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#207]
TRN - Some items mysteriously do not display the Available/Checked Out notation on my search results page (e.g. https://vufind3.carli.illinois.edu/vf-trn/Search/Results?lookfor=judaism&type=AllFields&limit=20&sort=relevance, https://vufind3.carli.illinois.edu/vf-trn/Search/Results?lookfor=jewish&type=AllFields&limit=20&sort=relevance), even though that information is available within the record. 

In both cases that I have noted thus far (TRNdb.89475 and TRNdb.88840), there are links (in these cases, to the table of contents) that display on the search results screen; is that mucking things up?

**Comment by gibsonjc** [comment]
MIL - why does the availability not show up next to the format (book) icon when these extra links appear, as it does for the other books on my search results screen (search for “nutrition”)?

**Comment by dgree1** [comment]
Here's another example. 
https://vufind3-test.carli.illinois.edu/vf-bhc/Record/BHCdb.27253

Has links to Table of Contents, Bio info, etc. 
The call number isn't showing either, weird! In both vuf3 test and prod. 
https://vufind3.carli.illinois.edu/vf-bhc/Record/BHCdb.27253

Different bib for same title:
https://vufind3.carli.illinois.edu/vf-bhc/Record/BHCdb.11836

Key word search done to find these titles: mary todd

**Comment by gibsonjc** [comment]
KIS - For some reason the item that is shown (Cambridge companion to crime fiction) is not showing as being available [...] Our item record shows that we have 1 copy and the item is not charged. We have seen this same issue with other titles in our collection. Other books that have copy 1 and are not charged show up as being available in the new VU find.

Example:
https://vufind4.carli.illinois.edu/vf-kis/Search/Results?lookfor=cambridge+companion+to+crime+fiction&type=AllFields&limit=20&sort=relevance
https://vufind4.carli.illinois.edu/vf-kis/Record/KISdb.110020

**Comment by gibsonjc** [comment]
GSU - Replication Steps: New VuFind
Go to https://i-share.carli.illinois.edu/vf-gsu/ (New VuFind)
Search for the title Someone to watch over me
Receive 4 results
Review hit number 2 says Book
Click on to see more details
Notice Copy 1 says Overdue 03-01-2018

https://i-share.carli.illinois.edu/vf-gsu/Search/Results?lookfor=someone+to+watch+over+me&type=Title&limit=20&sort=relevance

RT 98074

**Comment by gibsonjc** [comment]
RSH - Many records like the one below are for print resources with a related URL to online access.  However, when a link appears in the brief record, the cue for “Available” does not display.  Not all our members have access to the database for the full text.  It appears confusing then for the end-user as to whether print is available unless the full record is opened.

Is this on the dockit  for investigation, and possible change?
https://i-share.carli.illinois.edu/vf-rsh/Record/RSHdb.99549 
Impact of foodservice operational practices on patient satisfaction / 
by Brioni, Florencia Raquel, 
Published 2013 
Subjects: '; “...Rush University Medical Center. Department of Food and Nutrition Services....”
Call Number: WX 168 B858i 2013
Located: Special Collections 
Download full text
Manuscript

**Comment by nmswanson** [comment]
SAI - When doing this search : 
https://i-share.carli.illinois.edu/vf-sai/Search/Results?lookfor=weil%2C+simone&type=Author 

Some items show the availability status, and others do not on the search 
results page -- is there a reason for this? 
My guess is that the system is pulling the links to descriptions/table of 
content links and placing those in the results page, not leaving room for 
the availability status?? 

RT99409

[Additional notes about search results:
From the search list: https://i-share.carli.illinois.edu/vf-sai/Search/Results?lookfor=weil%2C+simone&type=Author
 
War and the Iliad is charged but does not display Not Available: https://i-share.carli.illinois.edu/vf-sai/Record/SAIdb.84637. 
It is a book with 856 41 $3 Table of contents $u http://www.loc.gov/catdir/toc/ecip056/2005000251.html 

Gravity and grace is renewed but does not display Not Available: https://i-share.carli.illinois.edu/vf-sai/Record/SAIdb.17969. 
It is a book with: 
856 41 $3 Table of contents $u http://catdir.loc.gov/catdir/toc/fy0612/2002031674.html 
856 42 $z Publisher description $u http://catdir.loc.gov/catdir/enhancements/fy0701/2002031674-d.html 

On violence : a reader is available but does not display Available: https://i-share.carli.illinois.edu/vf-sai/Record/SAIdb.109828. 
It is a book with: 
856 41 $3 Table of contents only $u http://catdir.loc.gov/catdir/toc/ecip0717/2007019209.html  

Urinary continence and sexual function after robotic radical prostatectomy: https://i-share.carli.illinois.edu/vf-sai/Record/SAIdb.322543
is an eBook with:
856 40 $u http://proxy.artic.edu/login?url=http://link.springer.com/10.1007/978-3-319-39448-0 $y Available to SAIC students, faculty and staff]

**Comment by gibsonjc** [comment]
TIU - RT 99852 It seems that the green available button is usually there, but not always. The first item in this results list does not have it, but when you click on the item it says it is available. This is confusing for students who are just scrolling and looking for available books.
Example: 
https://i-share.carli.illinois.edu/vf-tiu/Search/Results?lookfor=through+the+darkly&type=AllFields

**Comment by gibsonjc** [comment]
Newly prioritized issue.  On the Results page, when a Bib 856 field is present, the system seems to  hide the Status/Availability icon that usually appears after the blue Format Icon.

We want the Status/Availability icon to display on the Results page at all times when it is possible; we do not want it suppressed for any reason.  Is there any logic that might be affecting this display of information in the Results page templates?

**Comment by cedelis** [comment]
In TEST.

I've removed the code that checks for empty 856 URLs; so now the availability status always displays.

However, there is going to be a side-effect (unintended consequence?) for doing so. 

E.g., compare TEST vs. PROD and notice how in TEST there is now potential for statuses to take on the value of 'Live Status Unavailable'. Is this an acceptable tradeoff?

https://i-share-test.carli.illinois.edu/vf-sai/Search/Results?lookfor=weil%2C+simone&type=Author
https://i-share.carli.illinois.edu/vf-sai/Search/Results?lookfor=weil%2C+simone&type=Author

code ref:

https://github.com/CARLI/vufind/blob/carli-release-4.1/themes/bootstrap3/templates/RecordDriver/SolrDefault/result-list.phtml#L143

**Comment by cedelis** [comment]
In PROD.
