### ISSUE TITLE
Search box autocomplete feature

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#209]
TRN - The autocomplete suggestions take longer to appear that my users are accustomed to (like in EBSCO databases), so I’m not sure that function is going to be helpful. Also, when I typed social work into the search box for all I-Share libraries, the system suggested Socialism : what it means for man (46 questions and answers about the social position of workers in the USSR) /, which is rather far off the mark. It would be better to have no suggestions than to have nonsensical offerings.

**Comment by gibsonjc** [comment]
https://vufind.org/wiki/configuration:autocomplete

**Comment by bgant** [comment]
It seems like we have reached a point where it is time to disable features in VuFind 3.x that people do not find useful. We can always turn those features back on temporarily in Test if other libraries want to try them out again.

I recommend disabling this feature for now.

**Comment by gibsonjc** [comment]
IWU - autofill form in the standard search box seems to always cover up the first result. Poor design.

**Comment by gibsonjc** [comment]
MIL - suggested search results is very aggressive and often block my view of the actual results.

**Comment by gibsonjc** [comment]
We decided to disable the autocomplete feature in the search box entirely for now.

In searches.ini, change

[Autocomplete]
; Set this to false to disable all autocomplete behavior
enabled = true

to 

enabled =false

**Comment by gibsonjc** [comment]
The autocomplete is off in TEST and off in PROD already.  Both are working in that the "Loading..." message and dropdown do not appear, which is what we want.  Ready for Prod.
