### ISSUE TITLE
UC "Call Number" and "Located" fields

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#211]
When doing UC searches, the "Call Number:" and "Located:" fields briefly appear in each record with the word "Loading..." next to them. They are then hidden from the user when the Search Results page finishes loading.

For performance reasons, I just wanted to check to see if those fields are actually being populated by separate system calls to Solr or Oracle before they are hidden.

If so, eventually disabling those calls could be a way to improve performance.

**Comment by gibsonjc** [comment]
@cedelis Is this still the case or of concern?  I can't seem to see any myself when searching in I-Share /all/vf/ or /all/vf-abc/

(If not, we can close this Issue.)

**Comment by gibsonjc** [comment]
Chris said he was not concerned about this so Closing.
