### ISSUE TITLE
Patron record suspension does not list library where suspended

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#212]
When a patron's record is suspended, the alert in VuFind3 does not denote which library has applied the suspension.

On VuFind3-devel, I have suspended my account at both SAI (6-30-17) and MRT (7-13-17).

When reviewing my Checked Out Items, I can see that my account is listed as suspended, but not where. The suspension date listed is the furthest date (the MRT suspension).

![furthestsuspensiondate](https://user-images.githubusercontent.com/20848151/27403220-4e176b92-568f-11e7-892d-6c8ebda48d8f.PNG)

[moved this section to Issue #213 -JG]

**Comment by gibsonjc** [comment]
I think #230 "Block/Suspension messages do not show to which library they were applied" covers this one.  Closing as duplicate.
