### ISSUE TITLE
Suspension at non-home library should not prevent transactions at all libraries

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#213]
[moved second section of Issue #212 to new Issue here]

On VuFind3-devel,  @dmcmpbll has suspended her account at both SAI (6-30-17) and MRT (7-13-17).

When I attempt a renewal of a UIU item despite my suspensions at MRT and SAI, I was a little surprised my UIU renewal did not go through (I got a new popup with the suspensions listed in 2 colors). UIU does not "block local transaction" for I-Share infractions; and even if they did, I believe suspensions are in a different category. Such as- **when the home library suspends, the patron is suspended everywhere. When another I-Share library suspends, the patron is only suspended at that library.**

![suspensionafterrenewalattempt](https://user-images.githubusercontent.com/20848151/27403454-151d724a-5690-11e7-91b2-9ff6dcab12d7.PNG)

**Comment by dmcmpbll** [comment]
I will do more testing on how suspensions currently work and will respond here (to make sure my memory is accurate).

Also, I'm not sure it's necessarily a bad thing that suspensions are applied universally. If suspended at any library means suspended at all, that would prompt faster reaction on the part of the patron and would make the "please suspend your patron" letters that some libraries send unnecessary. 

However, would be a change in how things currently function, and not sure about how libraries feel about letting other libraries fully suspend their patrons from all privileges.

**Comment by dmcmpbll** [comment]
Used a BHC test patron in Voyager-test and associated VuFind records
https://vufind-test.carli.illinois.edu/all/vf/Record/13788072 
https://vufind3-test.carli.illinois.edu/all/vf-bhc/Record/299780553
Book is held by UIU and by SVC; UIU copy is in a non-requestable location.

Workflow:
1) Request SVC copy of book; cancel request.
2) Suspend patron in BHC.
3) (Attempt) request SVC copy of book.
4) Unsuspend patron in BHC.
5) Suspend patron at UIU (who has second copy of book).
6) (Attempt) request SVC copy of book.

In VuFind 0.6, when home library suspends, patron is suspended everywhere. When other I-Share library suspends, patron is only suspended at that I-Share library. While suspended at UIU, patron could request SVC book and renew MIL item. The OPAC is acting in accordance with Voyager.

In VuFind 3, when home library suspends, patron is suspended everywhere. When other I-Share library suspends, patron OPAC activity is suspended everywhere. While suspended at UIU, patron could not request SVC book or renew MIL item. The OPAC is more restrictive than Voyager.

**Comment by gibsonjc** [comment]
@cedelis is this fix for the change in suspension behavior on DEVEL or TEST or both? Thanks!

**Comment by cedelis** [comment]
@gibsonjc It's on both now. I've merged all changes into carli-release.3.1.4 on vufind3-test.

**Comment by dmcmpbll** [comment]
Have re-tested workflow from above using a COD patron, using same title:
https://vufind3-test.carli.illinois.edu/all/vf-cod/Record/299780553 

1. Request SVC copy of book; cancel request.
2. Suspend patron in COD.
3. (Attempt) request SVC copy of book.
4. Unsuspend patron in COD.
5. Suspend patron at UIU (who has second copy of book).
6. (Attempt) request SVC copy of book.

VuFind3-test worked as expected with Voyager. 
The OPAC is the same level of permissive as Voyager allows.

**Comment by gibsonjc** [comment]
Ready for production
