### ISSUE TITLE
Year of Publication facet is buried

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#219]
IWU - Date range is quite useful and commonly used.  It is buried all the way at the bottom on the right.

![screen shot 2017-06-23 at 10 18 49 am](https://user-images.githubusercontent.com/17598357/27488649-65a75014-57fd-11e7-9d91-44177e3658e9.png)

**Comment by gibsonjc** [comment]
Order of facets controlled by [facets.ini](https://github.com/CARLI/vufind/blob/master/config/vufind/facets.ini)

**Comment by gibsonjc** [comment]
SIC - move up the year of publication facet.  Currently the year of publication facet is the last facet displayed requiring a lot of scrolling.  This is an often used facet.

**Comment by dgree1** [comment]
SFX committee members ask about status of this issue. IIT and SIC librarians wondering if had any local control on order of facets. Would like to bump up publication date facet.

**Comment by gibsonjc** [comment]
KIS - Move the Year of Publication slider up near the top of the facet list. Maybe after the Format facet.  RT 98013

**Comment by gibsonjc** [comment]
This was resolved with issue #71 on Oct. 16, 2018. Closing.
