### ISSUE TITLE
Some titles listed twice in Checked Out Items list for some patrons

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#221]
Occasionally in vufind3-prod/test/devel, the same title will be listed twice in a patron's Checked Out items list, once with a shortened hyperlinked title and no library ownership name, and then again with a non-hyperlinked full title and the library's ownership name.

![listtwice](https://user-images.githubusercontent.com/20848151/27739768-585a1bee-5d75-11e7-8e37-f10a7e48439d.PNG)

**Comment by gibsonjc** [comment]
@dmcmpbll do you have any example patrons/items with this problem you can send information about to the vu-it list?  Thanks!

**Comment by dmcmpbll** [comment]
Thanks Jessica! I've sent an email to vu-it with 2 examples.

**Comment by dmcmpbll** [comment]
Noting this exists in VuFind4-devel as well:

![doublelist171026](https://user-images.githubusercontent.com/20848151/32074164-2723a806-ba5e-11e7-8516-b82e1986a807.PNG)

**Comment by dmcmpbll** [comment]
The above past example from devel for "Arrival" is no longer double-displaying, and the other examples from my past emails are no longer available. Similarly, I am unable to find any additional, current examples of this issue to report. 
I think we can close this ticket.
