### ISSUE TITLE
Some results have "Get full text" link when they should not

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#225]
RSH - In the database for the  Library of Rush University Medical Center, several records that are for print resources should not indicate “Get full text” in brief record. The link goes to SFX instructions – very confusing.  

Title examples:
2-D page map analysis : methods and protocols  **RSHdb.109192**
https://vufind3.carli.illinois.edu/vf-rsh/Search/Results?lookfor=2-D+page+map+analysis+%3A+methods+and+protocols&type=Title&limit=20&sort=relevance

Veterinary infection : molecular diagnostics and high-throughput strategies  **RSHdb.103693** https://vufind3.carli.illinois.edu/vf-rsh/Search/Results?lookfor=Veterinary+infection+%3A+molecular+diagnostics+and+high-throughput+strategies&type=Title&limit=20&sort=relevance

How to overcome the antibiotic crisis : facts, challenges, technologies and future perspectives  **RSHdb.113397**
https://vufind3.carli.illinois.edu/vf-rsh/Search/Results?lookfor=How+to+overcome+the+antibiotic+crisis&type=Title&limit=20&sort=relevance

**Comment by gibsonjc** [comment]
This unwanted behavior may be related to #205 .  What is triggering the "Get full text" link to display, and when it does display, what governs the content of the search link that it builds?

**Comment by dgree1** [comment]
Possibly the SFX link is being triggered by a MARC fields related to series or serials in a more technical sense. 
Above example Veterinary Infection has these 490 fields in bib: 

490 | 1 |   | |a Methods in molecular biology, 
  |x 1064-3745 ; 
  |v 1247
-- | -- | -- | --
1 |   | |a Springer protocols

"How to overcome the antibiotic..." similarly has 

490 | 1 |   | |a Current topics in microbiology and immunology, 
  |x 0070-217X ; 
  |v volume 398
-- | -- | -- | --


and the 2-D Map analysis has 

490 | 1 |   | |a Methods in molecular biology, 
  |x 1064-3745 ; 
  |v 1384
-- | -- | -- | --
1 |   | |a Springer protocols, 
  |x 1949-2448

**Comment by cedelis** [comment]
OpenURL links are built based on Format. See the following comment for details:

https://github.com/CARLI/vufind/issues/205#issuecomment-316803179

**Comment by cedelis** [comment]
OpenURL links are displayed according to the following documentation:

https://vufind.org/wiki/configuration:openurls#defining_openurl_rules

By default,  "OpenURLs for any record returning anything but false for getCleanISSN" will display.

Here is the relevant getCleanISSN() method:

https://github.com/vufind-org/vufind/blob/d5a020a7bbadb1f9b5d16b6706ffa23e3c14fd7b/module/VuFind/src/VuFind/RecordDriver/SolrDefault.php#L402

which references getISSNs():

https://github.com/vufind-org/vufind/blob/d5a020a7bbadb1f9b5d16b6706ffa23e3c14fd7b/module/VuFind/src/VuFind/RecordDriver/SolrDefault.php#L713

and the issn is indexed via our import.properties file: https://github.com/CARLI/vufind/blob/carli_master_branch/import/marc.properties#L82

with a current value of:

issn = 022a:440x:490x:730x:773x:776x:780x:785x

**Comment by gibsonjc** [comment]
A few thoughts/questions:

1) https://vufind.org/wiki/configuration:openurls#defining_openurl_rules says that "Custom [record driver](https://vufind.org/wiki/development:plugins:record_drivers) code can be used to control whether or not specific types of records provide OpenURLs."  Vague!

2) I believe the default definition of "issn" in marc.properties is as broad as it is for general searching of ISSN data, but for SFX linking purposes in these Open URL searches we want for it to be much more narrow and only link out to things with an ISSN in 022a.  I'm not sure how to balance those two different things, unless that can be done by 1) above?

3) On TEST where you have fixed #205 , the "Get full text" links to these three example Books aren't passing any ISSNs in the URL that is sent to SFX (see below).  But based on my shaky understanding,  this is occurring because getCleanISSN is "true" for these records due to the presence of the series ISSNs in 490x?  This takes me right back to 2) above because I don't think we want this to generate the "Get full text" link for something that is format Book.  

Veterinary infection biology:
http://sfx.carli.illinois.edu/sfxrsh?url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2FEndeavor%3Agenerator&rft.title=Veterinary+infection+biology+%3A+molecular+diagnostics+and+high-throughput+strategies++%2F&rft.date=2014&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&rft.genre=book&rft.btitle=Veterinary+infection+biology+%3A+molecular+diagnostics+and+high-throughput+strategies++%2F&rft.series=Methods+in+molecular+biology+%28Clifton%2C+N.J.%29+%3B&rft.au=&rft.pub=Humana+Press%2C&rft.edition=&rft.isbn=1493920030

2D page map analysis:
http://sfx.carli.illinois.edu/sfxrsh?url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2FEndeavor%3Agenerator&rft.title=2-D+page+map+analysis+%3A+methods+and+protocols+%2F&rft.date=2015&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&rft.genre=book&rft.btitle=2-D+page+map+analysis+%3A+methods+and+protocols+%2F&rft.series=Methods+in+molecular+biology+%28Clifton%2C+N.J.%29+%3B&rft.au=&rft.pub=Humana+Press%2C&rft.edition=&rft.isbn=1493932543

How to overcome the antibiotic crisis:
http://sfx.carli.illinois.edu/sfxrsh?url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2FEndeavor%3Agenerator&rft.title=How+to+overcome+the+antibiotic+crisis+%3A+facts%2C+challenges%2C+technologies+and+future+perspectives+%2F&rft.date=2017&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&rft.genre=book&rft.btitle=How+to+overcome+the+antibiotic+crisis+%3A+facts%2C+challenges%2C+technologies+and+future+perspectives+%2F&rft.series=Current+topics+in+microbiology+and+immunology+%3B&rft.au=&rft.pub=Springer%2C&rft.edition=&rft.isbn=3319492829

4) Do we want VuFind 3 to generate "Get full text" links only for items that have format Journal/Magazine?  Is that too restrictive?  Would that negatively impact libraries that have enabled ebooks in SFX?

**Comment by gibsonjc** [comment]
Previous examples are in the local catalog; here is an example seeing a "Get full text" link when it isn't useful in the I-Share uc: I'm logged as UIU and I view this record https://vufind3-test.carli.illinois.edu/all/vf-uiu/Record/323458429 which has a one UIC MFHD, but I am offered the "Get full text" link to UIU's SFX where the resource is not found.  

"Get full text" is also presented in the Results list for this title when in the /all/vf-uiu/ view: https://vufind3-test.carli.illinois.edu/all/vf-uiu/Search/Results?filter%5B%5D=format%3A%22Electronic%22&filter%5B%5D=format%3A%22Journal+%2F+Magazine%22&lookfor=american+libraries&type=Title

I note that VuFind 0.6 does not present the SFX button for this same title. How does VuFind 0.6 know when to present the SFX button? Is it doing some pre-checking for ISSN or something?

**Comment by dgree1** [comment]
Jessica, do you need any more testing on this issue 225? 
The SFX committee  is available to test or help as they are able.

**Comment by gibsonjc** [comment]
@dgree1 Now that the ISSN indexes have been updated in New VuFind to only 022a and 022l (no longer including 440x, 490x, 730x, 773x, 776x, 780x, 785x), can you help with retesting this Issue?  Thanks!

**Comment by dgree1** [comment]
Looks fine so far using examples in earlier comments. Will keep testing.

**Comment by dgree1** [comment]
Looks good after further testing.

**Comment by gibsonjc** [comment]
With New VuFind 4.1 on Dec. 12, 2017, ISSN indexes have been updated in New VuFind to only 022a and 022l (no longer including 440x, 490x, 730x, 773x, 776x, 780x, 785x) and this seems to have solved the problem reported on this Issue that links were appeared when they were not expected to appear (and didn't then link to full text).  Closing this Issue.
