### ISSUE TITLE
update Syndetic Solution subscriptions as of July 1, 2017

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#228]
Remove/change/add subscriptions as needed on prod, test, and devel

**Comment by fellowsgl** [comment]
Schools not renewing Syndetics subscriptions: ARU, CTU, LFC, ONU, ROU, USF

**Comment by tschwitz** [comment]
Tested all six with the same titles that have images for subscribers.
All six have no images present.
Looks good.

**Comment by gibsonjc** [comment]
@cedelis The FY18 spreadsheet SyndeticsSubscribersFY18.xls is available on the internal staff wiki  (can send link/file in email if needed).  Has that been accounted for in VuFind 3?  The create_local_vufind_instances.sh script on test and devel seems to still be referring to FY17 
`my $SYNDETICS_SUBSCRIPTIONS_FILE="${VUFIND_LOCAL_DIR}/carli_scripts/SyndeticsSubscribersFY17.txt"` so I wasn't sure.

In a brief glance at the spreadsheet, it looks like NCC also didn't renew anything, and that some other institutions changed which services they subscribe to, for example.

**Comment by cedelis** [comment]
@gibsonjc I can't find the SyndeticsSubscribersFY18.xls on the internal staff wiki. Please send me the link or file. Thanks

**Comment by cedelis** [comment]
@gibsonjc Thanks for the SyndeticsSubscribersFY18.xls file. I've updated vufind3-devel and vufind3-test with these new settings.

**Comment by gibsonjc** [comment]
Those that I've spot-checked look good, Syndetics changes are Ready for Prod.
