### ISSUE TITLE
update SFX libraries list

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#229]
Some libraries have dropped SFX.  Update VuFind 3 prod, test, and devel as needed.

**Comment by fellowsgl** [comment]
Schools that have dropped SFX as of July 1: BHC, JJC,JKM,  NPU, TRT

**Comment by cedelis** [comment]
Those five libraries are already configured without SFX support.

**Comment by gibsonjc** [comment]
Just out of curiosity, where is this controlled? I thought it was in create_local_vufind_instances.sh but I don't see these institutions (BHC, JJC,JKM, NPU, TRT) listed on test or devel in the thing that I thought indicated no SFX:
`my %no_sfx = (
"aug" => 1,
"ben" => 1,
"col" => 1,
"con" => 1,
"csc" => 1,
"dac" => 1,
"dom" => 1,
"dpu" => 1,
"hrt" => 1,
"icc" => 1,
"iec" => 1,
"ims" => 1,
"ken" => 1,
"kis" => 1,
"lew" => 1,
"mon" => 1,
"mck" => 1,
"ncc" => 1,
"oak" => 1,
"onu" => 1,
"prk" => 1,
"rou" => 1,
"sai" => 1,
"sfm" => 1,
"sxu" => 1,
"uic" => 1,
"uis" => 1,
"tiu" => 1,
"wrh" => 1,`

**Comment by cedelis** [comment]
@gibsonjc yes, that is where SFX subscriptions are controlled.

I've added the 5 libraries to the no_sfx list, and then re-created the vufind instances:

cedelis@vufind3-devel:/usr/local/vufind/carli_scripts$ git diff
diff --git a/create_local_vufind_instances.sh b/create_local_vufind_instances.sh
index bfc3dd7..44549be 100755
--- a/create_local_vufind_instances.sh
+++ b/create_local_vufind_instances.sh
@@ -157,6 +157,7 @@ my %shibboleth = (
 my %no_sfx = (
 "aug" => 1,
 "ben" => 1,
+"bhc" => 1,
 "col" => 1,
 "con" => 1,
 "csc" => 1,
@@ -167,12 +168,15 @@ my %no_sfx = (
 "icc" => 1,
 "iec" => 1,
 "ims" => 1,
+"jjc" => 1,
+"jkm" => 1,
 "ken" => 1,
 "kis" => 1,
 "lew" => 1,
 "mon" => 1,
 "mck" => 1,
 "ncc" => 1,
+"npu" => 1,
 "oak" => 1,
 "onu" => 1,
 "prk" => 1,
@@ -180,6 +184,7 @@ my %no_sfx = (
 "sai" => 1,
 "sfm" => 1,
 "sxu" => 1,
+"trt" => 1,
 "uic" => 1,
 "uis" => 1,
 "tiu" => 1,

**Comment by gibsonjc** [comment]
Spot checking SFX links or not looks good, Ready for Prod
