### ISSUE TITLE
Want multiple holdings sorted alphabetically by Location Name

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#232]
ISU - major concern that Milner Library has before making a switch to VuFind3.  For items with multiple locations we need to be able to display them alphabetically by location [in the Holdings tab area]

Example from 0.6: https://vufind.carli.illinois.edu/vf-isu/Record/isu_194168 
vs. https://vufind3.carli.illinois.edu/vf-isu/Record/ISUdb.194168

**Comment by gibsonjc** [comment]
Seems to sort by Call Number (including prefix) first
then alphabetically by Location Code or OPAC Display Name?
then by MFHD ID or create date?

Needs more testing to figure out the lower sort levels.
I'm a bit surprised that the prefix would be included in a call number sort as well.

**Comment by nmswanson** [comment]
ISU-Additional examples: 
VF0.6: https://vufind.carli.illinois.edu/vf-isu/Record/isu_79277
New VF: https://i-share.carli.illinois.edu/vf-isu/Record/ISUdb.79277

email 4/19/18

**Comment by gibsonjc** [comment]
@cedelis What is current sort mechanism to display multiple MFHDs?  
Do we have the ability to change it to alphabetical by Location Name (or anything else)?

**Comment by cedelis** [comment]
@gibsonjc Currently, everything is grouped by MFHD ID. There is no sorting. Looking into sorting by Location Name...

**Comment by cedelis** [comment]
I believe they are now sorted by Location Name (preserving Institution sort in the "I-Share" catalog). They are still grouped by MFHD ID, so there's a possibility that there will be duplicate Location Names, (as was the case before making this change; this is not a defect, but done for a reason that I can't think of at the moment).

In TEST

**Comment by gibsonjc** [comment]
Looks good. Ready for Prod.

A good example that has multiple libraries with multiple holdings each is title "Harry Potter and the Chamber of Secrets" Book, First edition, 1999, (OCoLC)ocm40043650
https://i-share-test.carli.illinois.edu/all/vf-uiu/Record/327837132

**Comment by cedelis** [comment]
In PROD
