### ISSUE TITLE
Do not want to see each Item listed individually

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#233]
ISU - major concern that Milner Library has before making a switch to VuFind3. We would prefer to see a range of items listed v.1(1900)-v.100(1999) rather than each item individually

**Comment by nmswanson** [comment]
ISU - Change in metadata has copies displaying differently.  Our preference would be to not have individual items display.

Copy 1 (v.117) 	Available Request Item
Copy 1 (v.115(1998:Jan.-June)) 	Available Request Item

[Record page](https://i-share.carli.illinois.edu/vf-isu/Record/ISUdb.177875) and [Screenshot](https://s3.amazonaws.com/files.formstack.com/uploads/2990514/61834415/396383923/61834415_image2.png)

4/19/18 email page 24

[MFHD contains 866 summary statements that display under Volume holdings, ahead of copy-specific items in VF display]

**Comment by gibsonjc** [comment]
This code received from UofC to collapse the list of Items when there are over 5 and present the "View more items" and "Hide items" links is working well and Ready for Prod.

**Comment by cedelis** [comment]
In PROD.
