### ISSUE TITLE
Standardize link text to electronic resources on the Results page of local catalogs

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#234]
MIL - Things we view as obstacles to adopting VF3--eBooks- mixed language for connecting to eBooks is confusing. Example: keyword searched for “nutrition” and there are many results marked “Book” “Electronic.” 

To connect to some ([CARLI eBooks like “Nutrition for Dummies) it has a link on the results screen that says “Connect to eBook](https://i-share.carli.illinois.edu/vf-mil/Search/Results?lookfor=nutrition+for+dummies&type=AllFields&limit=20&sort=relevance).”  

To connect to an [Ebsco eBook, “Hypertension and nutrition,” the link is “Get full text](https://i-share.carli.illinois.edu/vf-mil/Search/Results?lookfor=hypertension+and+nutrition&type=AllFields&limit=20&sort=relevance).”  

For [Springer eBooks, such as “Nutrition and Metabolism,” the link says “Available Online to Millikin Users: Click Here](https://i-share.carli.illinois.edu/vf-mil/Search/Results?lookfor=nutrition+and+metabolism&type=AllFields&limit=20&sort=relevance).”  

Can’t this be standardized?  In the current catalog, the language is “get it online” for any e-item, whether Springer, Ebsco, GPO, etc.

**Comment by gibsonjc** [comment]
The difference in link text is due to the fact that these links are coming from different places.
- Nutrition for dummies: bib 856 with $y Connect to eBook
- Hypertension and nutrition: has bib 856 but without any other display subfields (so “Get full text” is the default, I think?)
- Nutrition and Metabolism: bib 856 with $z Available Online to Millikin Users: Click Here

**Comment by gibsonjc** [comment]
For further context, the results page (local catalogs only) display spec for 856 fields in VuFind 0.6 was:
- Only Bibliographic 856 fields with first indicator 1, 4 or 7 AND second indicator 0 or 1 are included on the VuFind Results page.

1. The linking text for one Bibliographic 856 field is "Get it online".
1. If more than one 856 field with appropriate indicators exists in the Bibliographic record, 
the first 856 that has appropriate indicators is the link from the “Get it online” text and a 
hyperlinked "(More...)" leads the user to the Record page to access all 856 fields.

- If the Bibliographic 856 field has the text “table of contents” in any subfield, it is not included on 
the VuFind Results page regardless of indicators.

- The presence of the Bibliographic 856 field does not suppress the display of the call number.

- If the SFX button will display (because the ISSN in the 022$a of the Bibliographic record matches the ISSN of an active object in the library’s SFX KnowledgeBase), the Results page will not display a “Get it online” link even if a Bibliographic 856 field(s) is present.

- Future development: if the SFX (or other link resolver) button OR the “Get it online” link displays, 
the red “Not available” status will be suppressed even if the Item is unavailable.

**Comment by dgree1** [comment]
What research is needed? SFX committee might help.

**Comment by gibsonjc** [comment]
IWU- RT 99180
It looks like a link displays on the results list if there is a url in the
856 field on the Bib record. If the url is in the MFHD, then you do not see
the link unless you click on the full record.

We have quite a few bad links in our bib records which we need to cleanup.
Most of these are links to book images, tables of contents, and links to
resources which do not include our proxy string. So, is it possible to mass
delete all of the 856 links in our bib records? If so, is it also possible
to then copy all of our 856 links from the MFHD to the Bib record so that
they will display on the results list?

Is there any plan to change what link displays on the results list from the
Bib to the MFHD?

**Comment by cedelis** [comment]
@gibsonjc @dgree1 , can you share example bibs containing more than one 856:

"If more than one 856 field with appropriate indicators exists in the Bibliographic record,
the first 856 that has appropriate indicators is the link from the “Get it online” text and a
hyperlinked "(More...)" leads the user to the Record page to access all 856 fields."

??

Thanks!

**Comment by gibsonjc** [comment]
Here's one with quite a few:
https://i-share.carli.illinois.edu/vf-knx/Record/KNXdb.304425 

Here is one with a couple:
https://i-share.carli.illinois.edu/vf-knx/Record/KNXdb.304767

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
Problem Report 1:
I am finding some inconsistencies in behavior with the SFX button vs. Bib 856 fields on TEST.  My initial search is showing search results in which the SFX button displays and the bib 856s are suppressed. This is good and expected behavior because the SFX button should take precedence over 856s.  

![screen shot 2018-09-25 at 3 09 50 pm](https://user-images.githubusercontent.com/17598357/46040119-148aae00-c0d5-11e8-80aa-39abda0145e6.png)

However, when I click into a record to view it, then click the Back button in my browser to get back to the results list, I see both the SFX button and bib 856 links for the same record like this:

![screen shot 2018-09-25 at 3 10 30 pm](https://user-images.githubusercontent.com/17598357/46040230-5c113a00-c0d5-11e8-9491-fe3daf36352a.png)

If I reload the results page with my browser reload button, the Bib 856 links go away and I only see the SFX button (correctly) just like in the first image!

Another example: https://i-share-test.carli.illinois.edu/vf-mil/Search/Results?lookfor=Journal+of+agricultural+and+food+chemistry&type=JournalTitle&limit=20&sort=relevance

Replication steps:

1. Do a search like https://i-share-test.carli.illinois.edu/vf-knx/Search/Results?lookfor=American+journal+of+archaeology&type=JournalTitle&limit=20&sort=relevance 
2. Click on the first title to view the record
3. Click the back button. Now the results list shows bib 856 fields with the SFX button.

**Comment by gibsonjc** [comment]
Problem Report 2: When a Bib 856 link does display in the Results list (based on the spec above from 7/20), the text should read "Get it online" (instead of "Get full text")

**Comment by cedelis** [comment]
@gibsonjc , I believe I have addressed Problem Reports 1 & 2 in TEST.

**Comment by dgree1** [comment]
Looks good to me. Consistent text now. 
Denise

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD.
