### ISSUE TITLE
Only links to the resource should appear in the results list

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#235]
MIL - I don’t think “extra links need to show up on the search results screen (e.g., on [“Nutrition: a Very Short Introduction](https://i-share.carli.illinois.edu/vf-mil/Search/Results?lookfor=nutrition+a+very+short&type=AllFields&limit=20&sort=relevance)”, links to TOC, Publisher Description, and Contributor biographical information show up under the call number and location)…these sort of links should be saved for the item screen.

**Comment by gibsonjc** [comment]
For further context, the results page (local catalogs only) display spec for 856 fields in VuFind 0.6 was:
- Only Bibliographic 856 fields with first indicator 1, 4 or 7 AND second indicator 0 or 1 are included on the VuFind Results page.

1. The linking text for one Bibliographic 856 field is "Get it online".
1. If more than one 856 field with appropriate indicators exists in the Bibliographic record, 
the first 856 that has appropriate indicators is the link from the “Get it online” text and a 
hyperlinked "(More...)" leads the user to the Record page to access all 856 fields.

- If the Bibliographic 856 field has the text “table of contents” in any subfield, it is not included on 
the VuFind Results page regardless of indicators.

- The presence of the Bibliographic 856 field does not suppress the display of the call number.

- If the SFX button will display (because the ISSN in the 022$a of the Bibliographic record matches the ISSN of an active object in the library’s SFX KnowledgeBase), the Results page will not display a “Get it online” link even if a Bibliographic 856 field(s) is present.

- Future development: if the SFX (or other link resolver) button OR the “Get it online” link displays, 
the red “Not available” status will be suppressed even if the Item is unavailable.

**Comment by gibsonjc** [comment]
KNX - I noticed something different between the old and the new VuFind in the way the display looks in a results list related to links to full text. It looks like the "get full text" link is displayed if there is any URL in the bib record's 856.

New VuFind
https://i-share.carli.illinois.edu/vf-knx/Search/Results?lookfor=journal+of+american+history&type=JournalTitle&limit=20&sort=relevance

In this case, we don't have any content available for the ejournal. The link displayed goes to JSTOR (from the 856 in the bib).

In VuFind 0.6
https://vufind.carli.illinois.edu/vf-knx/Search/Home?lookfor=american+literature&type=title&start_over=1&submit=Find&filter[]=format:%22Journal%20/%20Magazine%22 
the 856 links in the bib do not display in the results list

This is going to be misleading for our users, especially when they encounter the "get full text" links that don't lead them to full text that they have access to. Could the results display be designed to show the "get full text" links using the URL(s) from the Holdings records instead of the bib records?

![screen shot 2018-06-28 at 3 07 58 pm](https://user-images.githubusercontent.com/17598357/42058142-17898a8a-7ae5-11e8-9ee1-c953d1b8eb6e.png)

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD.
