### ISSUE TITLE
Need note to display when there are no holdings attached to a bib

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#239]
When a bib record exists but has no MFHDs attached, the Holdings tab area should display a general message about it.  Can we have the following message display?

**The catalog cannot display location or copy information at this time. Please ask a library staff member for assistance.**

_Research:_

In VuFind 0.6, the message in the local catalog is different from the message in the I-Share catalog:

https://vufind.carli.illinois.edu/vf-uiu/Record/uiu_638524 
The catalog cannot display location or copy information at this time. Please ask a library staff member for assistance, or try again later.

https://vufind.carli.illinois.edu/all/vf/Record/21778#name_UIU_638524 
No location or availability information is available about this title from the University of Illinois at Urbana-Champaign library catalog.

I don't think that these messages display in VuFind 0.6 when there is simply a connection problem with displaying the data from a local catalog, I think that the little spinner spins but nothing displays, but I could be wrong about that.

In VuFind 3 right now, it says nothing in either the local or uc, it only displays the Institution Name with nothing underneath it:

https://vufind3.carli.illinois.edu/vf-uiu/Record/UIUdb.638524

https://vufind3.carli.illinois.edu/all/vf-uiu/Search/Results?lookfor=Making+money+%3A+winning+the+battle+for+middle+class+financial+success&type=Title&limit=20&sort=relevance

I don't believe that it is necessary to have two different messages, one in the local and one in the uc, so I think we can start by just having the same one in both.

**Comment by slknight** [comment]
EIU has a form that users fill out to request these materials that references the status messages in the catalog. http://www.library.eiu.edu/requests/on-order.html

Exact text for no MFHD is 

The catalog cannot display location or copy information at this time. Please ask a library staff member for assistance, or try again later.

**Comment by slknight** [comment]
I asked John Whistler about this, and we believe that #224 will eliminate this issue in the UC. Items without MFHDs should be marked "nouc" and therefore suppressed in the UC.

**Comment by gibsonjc** [comment]
@slknight Just fyi, #224 is for test and devel which we are in the process of removing nouc's from; nouc records have already been removed from production VuFind 3 uc. "On Order" MFHD display is a separate Issue-to-be, coming soon based on library feedback [EDIT: #245 ].  I created this Issue because a default message needs to display when there is no MFHD to display.

**Comment by gibsonjc** [comment]
@cedelis I'm not sure about the status of this Issue.  Is the following possible?  

When a bib record exists but has no MFHDs attached, the Holdings tab area should display a general message: 

**The catalog cannot display location or copy information at this time. Please ask a library staff member for assistance.**

**Comment by cedelis** [comment]
Ready for TEST, e.g., https://i-share-test.carli.illinois.edu/all/vf-uiu/Record/UIUdb.638524

**Comment by slknight** [comment]
Looks good to me

https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.1531767
https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.1531746

I really like that the form link is in the results display. Nice!

![image](https://user-images.githubusercontent.com/15163837/35737716-1442382e-07f2-11e8-9966-4a852714d6c8.png)

I pulled an on-order report for titles ordered on Jan 24 to find these examples. If anyone wants more titles for testing I've got a couple dozen identified.

**Comment by gibsonjc** [comment]
@slknight I can't promise that that link will always be there as it is now, that's something else, but thanks for looking.

**Comment by gibsonjc** [comment]
@cedelis Looks goos, this is ready for Prod!

**Comment by cedelis** [comment]
In production
