### ISSUE TITLE
"Discharged" status is not available for request

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#240]
In VuFind3-test, items with a "Discharged" status are not available for request, where as Voyager does allow "Discharged" status materials to be requested.

VuFind3: https://vufind3-test.carli.illinois.edu/all/vf-cod/Record/284574999, see TRT items.
VuFind0.6: https://vufind-test.carli.illinois.edu/all/vf/Record/13471038#name_TRT_108761

**Comment by gibsonjc** [comment]
@dmcmpbll I don't think "Discharged" is the only status that does not behave requestability-wise as Voyager does.  I am moving the following text from #172 that seems related:

In VuFind 0.6 and Voyager, items with a status of "Damaged" "Circulation Review" and "Cataloging Review" are able to be requested. In vufind3-devel, the Request link does not display for any item where the status is not "Available", so this is a significant change in requestability.

Would you be able to take a look at all statuses to make a comprehensive list of requestability differences so we can address them all at once?

**Comment by dmcmpbll** [comment]
I have checked the request link availability all of the item statuses. There are 4 that are not requestable in VuFind3 that are requestable in VuFind 0.6/Voyager.

I don't know that it is necessarily "bad" that items with these statuses are not requestable in VuFind3, but it is something that is inconsistent with how the OPAC currently works (and libraries would need to be made aware if the behavior will change).

The 4 statuses are:
11-Discharged
16-Damaged
19-Cataloging Review
20-Circulation Review

For examples in devel, look at the COD title for these while logged in as UIU:
11-https://vufind3-devel.carli.illinois.edu/all/vf-uiu/Record/329409048
16-https://vufind3-devel.carli.illinois.edu/all/vf-uiu/Record/329662174
19-https://vufind3-devel.carli.illinois.edu/all/vf-uiu/Record/330862204
20-https://vufind3-devel.carli.illinois.edu/all/vf-uiu/Record/330183361

I have a spreadsheet with all statuses including screenshots that I can share to the vu-it email list if desired.

**Comment by cedelis** [comment]
@dmcmpbll There is a mechanism in the Voyager Driver (a method named determineAvailability, which I can override) which will allow me to treat those 4 statuses as if they were available ('Not Charged'). However, the status will show up as 'Available' instead of the actual status (Discharged, Damaged, etc.)

I've put this in place on DEVEL in case you wanted to look it over. Not sure if this is acceptable, though.

**Comment by dmcmpbll** [comment]
Discharged status items should be requestable, so it would be good to have that one adjusted.

For Damaged, Cat Review, and Circ Review, I'm still torn in that I don't know that it is necessarily "bad" that items with these statuses are not requestable in VuFind3 because those statuses mean something is going on with the item.  But it is something that is inconsistent with how the OPAC currently works and libraries would need to be made aware if the behavior will change; record cleanup would most likely be needed.

Do we decide by having the OPAC match what Voyager will allow?
--If yes, then please update all four to show the mask of "Available".
Right now the four examples above are still showing their more detailed status, instead of being masked to "Available".

**Comment by dmcmpbll** [comment]
With the complicated workflow needed to process requests for "Damaged" material in Voyager, I recommend that the Damaged status NOT be masked by the "determineAvailability override" to Available. The other three should be set to "Available."

11-Discharged  - yes, set to "Available"
16-Damaged - no, leave as "Damaged" status display, so not available.
19-Cataloging Review - yes, set to "Available"
20-Circulation Review - yes, set to "Available"

**Comment by gibsonjc** [comment]
I don't think that "Damaged" has been changed back to NOT showing as Available (if I'm looking in the right file), so I think that change recommendations is still to be acted on, but correct me if I'm wrong!

@dmcmpbll The "all" uc examples above have changed in VuFind 4 since VuFind 3 because "all" was rebuilt.  Do you have title name examples or local catalog example (where IDs shouldn't change) of Discharged, Damaged, Cataloging Review, and Circulation Review on TEST that we can use?

**Comment by cedelis** [comment]
@gibsonjc "Damaged" is currently configured to have a status of 'Not Charged':

https://github.com/CARLI/vufind/blob/carli-master/module/CARLI/src/CARLI/ILS/Driver/VoyagerRestful.php#L23

In fact, the following four statuses are treated as if they were 'Not Charged'

            case 'Discharged':
            case 'Damaged':
            case 'Cataloging Review':
            case 'Circulation Review':


Is that what we want? If not, please advise.

**Comment by gibsonjc** [comment]
@cedelis Sorry, my double negatives were confusing!  Above on Oct. 5, Debbie commented and recommended that "Damaged" be reverted back to the way it was (to display as Damaged and not be requestable).  

Keep the other three (Discharged, Cataloging Review, Circulations Review) as you have changed them.  Thanks!

**Comment by cedelis** [comment]
Done. 
Commit ba46bd131b1b1e762ee96668a344cd655f62a599

**Comment by dmcmpbll** [comment]
Examples in the WHE-test local catalog
11-Discharged: https://i-share-test.carli.illinois.edu/vf-whe/Record/WHEdb.1586 (6 copies; one is this status)
16-Damaged: https://i-share-test.carli.illinois.edu/vf-whe/Record/WHEdb.98923 (copies; one is this status)
19-Cataloging Review: https://i-share-test.carli.illinois.edu/vf-whe/Record/WHEdb.45331 (one copy)
20-Circulation Review: https://i-share-test.carli.illinois.edu/vf-whe/Record/WHEdb.564488 (one copy)

**Comment by gibsonjc** [comment]
This display change looks good to me using the examples in WHEdb.

@dmcmpbll did you want to retest that items with Discharged, Cat Review, and Circ Review can be requested and Damaged cannot?  Please comment here either way to let us know. (Side note: the Damaged behavior change is probably a good one for the What are the Differences? web page!) Thanks!

If that testing goes as expected, or if you do not think it needs more testing, then this is Ready for Prod.

**Comment by dmcmpbll** [comment]
Yes, I did a few more tests and this is ready for prod!
