### ISSUE TITLE
automate location translation file updates

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#241]
See email thread 7/19-20 and 7/26 Subj: "location translations files for VuFind 3".

Ready for production and documentation on the staff wiki.

**Comment by gibsonjc** [comment]
@cedelis This was closed with the batch last week which I think means that the mechanisms have been moved to prod but I do not yet see documentation on the staff wiki page for VuFind 3.1 about how this location feed works so I am reopening this Issue until that has been done.

**Comment by cedelis** [comment]
@gibsonjc I've amended the staff wiki to include this information.

**Comment by gibsonjc** [comment]
@cedelis Looks good, thanks! Closing again!
