### ISSUE TITLE
Would like 520$c to display in More Details

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#243]
MIL - From RT 93252
VuFind 3 Example: https://vufind3.carli.illinois.edu/vf-mil/Record/MILdb.421839#description

Recently, we’ve noticed that, on the “More Details” tab in VU Find, the summary information is getting cut off. Specifically, the name/source of the summary is being left out. The double dash suggesting there is a source appears, but the source itself is gone. See for example https://vufind.carli.illinois.edu/vf-mil/Record/mil_421839/Description or https://vufind.carli.illinois.edu/vf-mil/Record/mil_421903/Description.

Some investigation by our cataloger revealed that OCLC has changed the way they include this data in the 520 subfield – the source of the review is now stored in a separate subfield (‡c), and that field is not set up to display in VU Find, so whenever we import an OCLC bib that uses this new format, VU Find shows a review with no source details.

Is it possible to change VU Find so that this new subfield is displayed at the end of the summary?

**Comment by gibsonjc** [comment]
Only 520 $a is available in the default configuration:

module/VuFind/src/VuFind/View/Helper/Root/RecordDataFormatterFactory.php:
`$spec->setLine('Summary', 'getSummary');`

module/VuFind/src/VuFind/RecordDriver/SolrDefault.php:
`    public function getSummary()`
`   {`
`      // We need to return an array, so if we have a description, turn it into an`
`        // array as needed (it should be a flat string according to the default`
`       // schema, but we might as well support the array case just to be on the safe`
`        // side:`
`        if (isset($this->fields['description'])`
`            && !empty($this->fields['description'])`
`        ) {`
`            return is_array($this->fields['description'])`
`                ? $this->fields['description'] : [$this->fields['description']];`
`       }`
`       // If we got this far, no description was found:`
`        return [];`
`    }`

"description" is not defined in any marc.properties files.

module/VuFind/src/VuFind/RecordDriver/SolrMarc.php:
`    protected function getFieldArray($field, $subfields = null, $concat = true,`
`        $separator = ' '`
`    ) {`
`        // Default to subfield a if nothing is specified.`
`        if (!is_array($subfields)) {`
`            $subfields = ['a'];`
`        }`
...
`    public function getSummary()`
`    {`
`        return $this->getFieldArray('520');`
`    }`

**Comment by gibsonjc** [comment]
I think we could add the 520 $c by changing to this:

module/VuFind/src/VuFind/RecordDriver/SolrMarc.php:
`    public function getSummary()`
`    {`
`        return $this->getFieldArray('520', ['a', 'c'], true);`
`    }`

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
@cedelis Great! Can you adjust this function a bit more so we can see how this looks and works?  (If it's good, I have a whole bunch of edits and additions like this that I will be sending you shortly.) Thanks!

`public function getSummary()`
`{`
`return $this->getFieldArray('520', ['3', 'a', 'b', 'c'], true);`
`}`

**Comment by gibsonjc** [comment]
This works great.  The order of the subfields being displayed is controlled by their placement in the MARC record, not this list, which is perfect. Ready for Prod

**Comment by cedelis** [comment]
In PROD
