### ISSUE TITLE
CD-ROM format facet request

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#244]
CD-ROM format facet request:

(RecType=m and 008/23=q) OR (007/00=c AND 007/01=o) OR (007/00=c AND 007/04=g) OR (006/00=m AND 006/06=q) OR 245h=”computer file” OR 337a=”computer” OR 337b=c OR 338b=“computer disc” 
OR 338b=cd OR (300c=4/3/4 in. OR 12 cm) OR (the terms “computer laser optical disc” OR “computer optical disc” OR “computer disc” appear in 300a, 300b)

AND
The term “CD-ROM…” appears in 300a, 300b, 300e, 338$3, 538a, 690a, 753a

**Comment by gibsonjc** [comment]
@nmswanson We are working on getting this into VuFind 4 on a short timeframe and have some questions about your spec:

1. You wrote: **300c=4/3/4**
Is this a typo?  Do you mean all combinations of "4 3/4" like we did in a previous format specification?

2. You wrote: **CD-ROM…** 
Does this mean a substring, a literal ellipsis, a wildcard for anything that starts CD-ROM*, something else?  Clarification would be appreciated!

3. How is the final AND clause to be applied?  Specifically, where should the parentheses be in the gigantic boolean query? 

4.  Please confirm, does this 
"The term “CD-ROM…” appears in 300a, 300b, 300e, 338$3, 538a, 690a, 753a"
mean that the term "CD-ROM..." needs to be in **all** of the following fields or **any one** of the following fields: 300a,300b,300e,338$3,538a,690a,753a. 


Below is Chris's first attempt at the coding, which we assume is not quite right yet. Answers to the above questions will help!  Thanks much!

      String _007_04 = getFirstFieldValLowerCase(record, "007[4]");

      Set set_337a = new LinkedHashSet();
      addSubfieldDataToSet(record, set_337a, "337", "a");

      Set set_337b = new LinkedHashSet();
      addSubfieldDataToSet(record, set_337b, "337", "b");

      Set set_338b = new LinkedHashSet();
      addSubfieldDataToSet(record, set_338b, "338", "b");

      Set set_300ab = new LinkedHashSet();
      addSubfieldDataToSet(record, set_300ab, "300", "a");
      addSubfieldDataToSet(record, set_300ab, "300", "b");

      Set set_300abe_3383_538a_690a_753a = new LinkedHashSet();
      addSubfieldDataToSet(record, set_300abe_3383_538a_690a_753a, "300", "a");
      addSubfieldDataToSet(record, set_300abe_3383_538a_690a_753a, "300", "b");
      addSubfieldDataToSet(record, set_300abe_3383_538a_690a_753a, "300", "e");
      addSubfieldDataToSet(record, set_300abe_3383_538a_690a_753a, "338", "3");
      addSubfieldDataToSet(record, set_300abe_3383_538a_690a_753a, "538", "a");
      addSubfieldDataToSet(record, set_300abe_3383_538a_690a_753a, "690", "a");
      addSubfieldDataToSet(record, set_300abe_3383_538a_690a_753a, "753", "a");


      if (
           (
              (itemEquals(recType,"m") && itemEquals(_008_23,"q"))
                 ||
              (_007_00.equals("c") && _007_01.equals("o"))
                 ||
              (_007_00.equals("c") && _007_04.equals("g"))
                 ||
              (_006_00.equals("m") && _006_06.equals("q"))
                 ||
              setItemContains(set_gmd, "computer file")
                 ||
              setItemContains(set_337a, "computer")
                 ||
              setItemContains(set_337b, "c")
                 ||
              setItemContains(set_338b, "computer disc")
                 ||
              (setItemContains(set_300c, "12 cm") || setItemContains(set_300c, "4 3/4") || setItemContains(set_300c, "4 ¾") || setItemContains(set_300c, "4¾") ||  setItemContains(set_300c, "4 ³/₄") || setItemContains(set_300c, "4³/₄"))
                 ||
              (setItemContains(set_300ab, "computer laser optical disc") || setItemContains(set_300ab, "computer optical disc") || setItemContains(set_300ab, "computer disc"))
           )
           &&
           (
              setItemContains(set_300abe_3383_538a_690a_753a, "CD-ROM…")
           )

        ) {
           result.add("CD-ROM");
        }

**Comment by nmswanson** [comment]
1.	Yes, that was a typo. I mean all combinations of "4 3/4".

<You wrote: 300c=4/3/4
Is this a typo? Do you mean all combinations of "4 3/4" like we did in a previous format specification?>

2.	There will likely be other data before or after "CD-ROM" within the fields is all I meant. I wasn't sure how to indicate that, but we are specifically looking within those fields for "CD-ROM".

<You wrote: CD-ROM…
Does this mean a substring, a literal ellipsis, a wildcard for anything that starts CD-ROM*, something else? Clarification would be appreciated!>

 3. From what I can see, it looks like Chris did this the way I was thinking:

(
(RecType=m and 008/23=q) OR (007/00=c AND 007/01=o) OR (007/00=c AND 007/04=g) OR (006/00=m AND 006/06=q) OR 245h=”computer file” OR 337a=”computer” OR 337b=c OR 338b=“computer disc” 
OR 338b=cd OR (300c=4 3/4 in. OR 12 cm) OR (the terms “computer laser optical disc” OR “computer optical disc” OR “computer disc” appear in 300a, 300b)

AND

(The term “CD-ROM…” appears in any one of the following fields: 300a, 300b, 300e, 338$3, 538a, 690a, 753a)
)

<How is the final AND clause to be applied? Specifically, where should the parentheses be in the gigantic boolean query?
CD-ROM needs to appear in any one of the following fields: 300a, 300b, 300e, 338$3, 538a, 690a, 753a>

4.  CD-ROM needs to appear in any one of the following fields: 300a, 300b, 300e, 338$3, 538a, 690a, 753a

<Please confirm, does this
"The term “CD-ROM…” appears in 300a, 300b, 300e, 338$3, 538a, 690a, 753a"
mean that the term "CD-ROM..." needs to be in all of the following fields or any one of the following fields: 300a,300b,300e,338$3,538a,690a,753a.>

**Comment by cedelis** [comment]
commit 6e9fa652a21bbd51c16a5e6f8e8d336ddfe4a9cf

**Comment by gibsonjc** [comment]
This new format was incorporated into the release of VuFind 4.1.  Closing.

**Comment by tschwitz** [comment]
I know this is closed, but I'm curious about whether 300$e should be examined as well.

Thinking about this with respect to [RT97737](https://support.carli.illinois.edu/Ticket/Display.html?id=97737).

Nevermind. I see that it's there.

**Comment by nmswanson** [comment]
The 300e is included in CD-ROM and also Audio CD.
