### ISSUE TITLE
Alphabrowse not displaying "see also" references in prod

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#248]
Production isn't showing "see also" references:
https://vufind3.carli.illinois.edu/vf-jud/Alphabrowse/Home?source=author&from=twain%2C+mark

But TEST is:
https://vufind3-test.carli.illinois.edu/vf-jud/Alphabrowse/Home?source=author&from=twain%2C+mark

**Comment by cedelis** [comment]
@gibsonjc This is not a code issue. Instead, it's a processing error. The authority index on vufind3-prod is basically empty, which means that for whatever reason (it was re-imaged and not re-initialized?) the initial import data is not there. I've set up a full reindexing for tonight, therefore the problem should be resolved tomorrow.

**Comment by cedelis** [comment]
@gibsonjc After having rebuilt the authority index, 'see also' references seem to be appearing again. Chris

**Comment by gibsonjc** [comment]
I concur that this is working correctly now in PROD, TEST, and DEVEL.  Closing.

Some examples:
https://vufind3.carli.illinois.edu/vf-eiu/Alphabrowse/Home?source=author&from=rowling%2C+j

https://vufind3.carli.illinois.edu/vf-uiu/Alphabrowse/Home?source=topic&from=Americana

https://vufind3.carli.illinois.edu/vf-niu/Alphabrowse/Home?source=author&from=king%2C+stephen
