### ISSUE TITLE
Results page for "Browse Alphabetically by call number" still says LC in heading

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#250]
Remove the (LC) from the column heading after Call Number:

![screen shot 2017-08-04 at 2 45 04 pm](https://user-images.githubusercontent.com/17598357/28984472-b93630e6-7923-11e7-99a5-05dfd57e30a4.png)

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
Looks good, ready for Prod!

**Comment by cedelis** [comment]
In Prod.
