### ISSUE TITLE
Author-related search redirects from record page don't work

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#256]
The system automatically hotlinks the Main Author, Corporate Author, and Other Author in the display on the single record page.  Those hotlinks seem to be designed to run a search on the author name (much like the hotlinked Subjects do just below it), but the search for authors always returns an error.

Examples:

https://vufind3.carli.illinois.edu/vf-uiu/Record/UIUdb.3556566
click on American Library Association, which takes you to
https://vufind3.carli.illinois.edu/vf-uiu/Author/Home?author=American+Library+Association.
that is displaying error.

https://vufind3.carli.illinois.edu/vf-uiu/Record/UIUdb.7191374
click on Sandberg, Sheryl. which takes you to
https://vufind3.carli.illinois.edu/vf-uiu/Author/Home?author=Sandberg%2C+Sheryl.
that is displaying error.

**Comment by gibsonjc** [comment]
What is this /vf-xxx/Author/ page that exists, anyway?
https://vufind3.carli.illinois.edu/vf-uiu/Author/
Here I can enter a name in the second smaller search box Author Results for: Sandberg, Sheryl and get
https://vufind3.carli.illinois.edu/vf-uiu/Author/Search?lookfor=Sandberg%2C+Sheryl
but when I click on Sandberg, Sheryl in this list, it takes me to the error page again
https://vufind3.carli.illinois.edu/vf-uiu/Author/Home?author=Sandberg%2C+Sheryl

**Comment by cedelis** [comment]
@gibsonjc Interestingly enough, I get error messages in the vufind demo too: https://vufind.org/demo/Author/Home?author=American+Library+Association.

**Comment by cedelis** [comment]
@gibsonjc OK, at least I figured out how to solve the errors. I had to enable a Zend configuration for the Http module in vufind/config.ini:

; Default HTTP settings can be loaded here. These values will be passed to
; the \Zend\Http\Client's setOptions method.
[Http]
sslcapath = "/etc/ssl/certs" ; e.g. for Debian systems

**Comment by gibsonjc** [comment]
Ok, that's progress. Now it displays results instead of an error page. And wow, it automatically pulls in information from Wikipedia at the top of the results page.

Relevant default settings are probably these:

**config.ini**
; You can select from Wikipedia
; See also the AuthorInfo recommendation module setting in searches.ini; this
; includes notes on improving the accuracy of Wikipedia retrievals.
; Note for Windows users: If using Wikipedia, you may need to increase your Apache
; heap size settings.  For details, see: http://vufind.org/jira/browse/VUFIND-630
authors         = Wikipedia

**searches.ini**
; Available modules recommended for use in the top area:
;
(snip)
; AuthorInfo:[use_viaf]
;       Load author information from external providers based on the current search
;       and the "authors" setting in the [Content] section of config.ini.
;       The [use_viaf] setting may be set to true to use the VIAF web service in
;       combination with your Solr authority index to pick more appropriate authors;
;       this defaults to false if unset.  If you do not have local authority records
;       to draw on, the OCLC FAST data works well with the [use_viaf] option; see:
;       https://vufind.org/wiki/indexing:open_data_sources#oclc_fast
(snip)
; These settings control the top and side recommendations within the special Author
; module (the page accessed by clicking on an author's name within the search
; results).  The Author module ignores the default_top_recommend and
; default_side_recommend settings and only uses this section.
[AuthorModuleRecommendations]
;top[] = TopFacets:ResultsTop
;side[] = SideFacets:Results:CheckboxFacets
top[] = AuthorInfo
side[] = "ExpandFacets:Author"

**Comment by gibsonjc** [comment]
Since the original problem has been corrected, I'm going to close this issue.  (Whether or not we want the wikipedia data to display with an Author search is another question altogether!)
