### ISSUE TITLE
Collapse "Holds & Recalls" Tab into Requested Items Tab

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#259]
In VuFind3, the "Holds and Recalls" tab was collapsed into the "Requested Items" tab (back in 10/2016).

Could this be redone for VuFind4?

VuFind3 screenshot:
![vufind3screenshot](https://user-images.githubusercontent.com/20848151/32070420-de083378-ba51-11e7-9be0-950544c73e05.png)

VuFind4 screenshot:
![vufind4screenshot](https://user-images.githubusercontent.com/20848151/32070429-e4a18194-ba51-11e7-93d1-a46028a86ade.png)

**Comment by dmcmpbll** [comment]
Once this ticket is completed, look into the ABA info. display issue (where Voyager has the correct BIB_ID information behind the scenes, but displays the patron's home library's bib information for the BIB_ID, instead of the item's home library's bib information for the BIB_ID.

See RT 96440

**Comment by gibsonjc** [comment]
@cedelis Can you take a look at this and see if combining the "Holds & Recalls" section in Your Account again is something we might be able to fix this week before any libraries go live? Debbie and I are afraid this will cause users concern and confusion when it is displaying items they have never heard of.  Debbie is working on setting up an example in Devel for you to work with and will share info via email.

**Comment by cedelis** [comment]
Commit 0c656ef46c8bab7ad0f05c699fe8375ae80cfa9c applied.
