### ISSUE TITLE
Cover images not showing in Requested Items list

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#260]
In VuFind4-devel, cover images are not showing in the Requested Items list. 
Instead of showing (or deliberately not showing/being blank), there is a link that says “Cover image” that connects to a generic URL.

![coverimageblank](https://user-images.githubusercontent.com/20848151/32182107-edbb69c4-bd63-11e7-8f56-fe604174759f.png)

**Comment by gibsonjc** [comment]
UIC - Book cover image is not displaying after I request an item (I'm looking at "Requested Items" area and see a broken image symbol. Would it make sense to NOT display book cover images in this area?  RT96877

**Comment by gibsonjc** [comment]
I don't know if we need cover images here or not.  If actual cover images cannot be easily displayed on this screen, I think that's ok, but then let's replace the generic "Cover Image" link with the same blank.gif that displays when there is no cover image in regular results lists.

**Comment by cedelis** [comment]
Ready for Testing.

Our ILS driver, VoyagerRestful, never returns the bib ID in the getMyILLRequests() routine.
Therefore we should never attempt to show a cover image (since it will always fail).

**Comment by dmcmpbll** [comment]
The test is on test, correct?

If so, it looks good. The cover image placeholder is not displaying in my requested items list.

![image](https://user-images.githubusercontent.com/20848151/35896119-522979d6-0b80-11e8-832a-3d2cd536fa02.png)

**Comment by gibsonjc** [comment]
Thanks @dmcmpbll !  I think that this works fine as is without the blank cover image placeholder gif after all since a cover image will never ever display in this list.  Ready for Prod.

**Comment by cedelis** [comment]
In prod
