### ISSUE TITLE
public log files for vufind4

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#261]
We need to generate, anonymize, and post vufind4 logs to https://www.carli.illinois.edu/logs/ and https://i-share.carli.illinois.edu/acrlstats/

**Comment by dmcmpbll** [comment]
Will we also begin generating them for here?: https://www.carli.illinois.edu/logs/

**Comment by gibsonjc** [comment]
https://www.carli.illinois.edu/logs/ files for January-May were posted June 2 and will remain posted until August 1. June and beyond will be posted for two months on the regular schedule.

https://i-share.carli.illinois.edu/acrlstats/ files still need to be done.

**Comment by fellowsgl** [comment]
The older than 60 days logs have been removed
