### ISSUE TITLE
customize "Local Catalog Only" search box choice

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#270]
SWI - I've just submitted a customization form for the new VuFind. I didn't see an option to change this language in the window. Could we change this from: Local Catalog Only, to: SWIC Library Only

**Comment by gibsonjc** [comment]
IMS - Is there a way in the pull down menu in VuFind that the wording could be "IMSA Catalog Only" instead of "Local" catalog only?

**Comment by gibsonjc** [comment]
LFC - we would like to request as an enhancement that in the basic search screen, for the second drop-down menu, that the "Local Catalog Only" option reflect the selected library's name and/or academic institution's name.

**Comment by eschell** [comment]
I could add a variable in /themes/carli/templates/search/searchbox.phtml that leave 'Local Catalog Only' as the default but if something else is set in the individual institution theme config.php file it uses that instead.

**Comment by gibsonjc** [comment]
@eschell Yes, please look into this and lets see if it is sustainable.  This is currently customizable in 0.6: https://www.carli.illinois.edu/products-services/i-share/opac/VuFcustom (number 7)

**Comment by gibsonjc** [comment]
KIS - the drop down will say Kishwaukee only not local catalog only right?  RT 98013

**Comment by gibsonjc** [comment]
Variable added 4/6. Awaiting addition of customization form option.

**Comment by gibsonjc** [comment]
Option now available on customization form.  Closing.
