### ISSUE TITLE
Sort items on Checked Out Items page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#274]
NPU - [On the Checked Out Items page] The ability to sort by due date and/or title would be awesome (but might not be possible)

**Comment by gibsonjc** [comment]
EIU - While logged into "your account," checked out items default sort is by local library then by due date, hence, any I-share borrowed items do not get listed until the locally borrowed items are exhausted. Primary sort should be due date regardless of supplying library.

RT 98580

**Comment by nmswanson** [comment]
SAI - Checked out Items order -- currently the order of items checked out/due
is by institution. This makes it hard for people to see what is coming due
first and for those with lots of books checked out, requires them to scroll
and search ALOT.

RT 99380

**Comment by dmcmpbll** [comment]
UIU- Is it possible for patrons to view their checked out items arranged (toggled) by due dates in New VuFind 4.1? The previous version of VuFind allowed (still allows) patrons to arrange by Title, Library, Due (date), and Status.

RT 99535

**Comment by nmswanson** [comment]
LNC- I was wondering if it would be possible to add the option of sorting 
checked out items by due date to VuFind 4. On the old VuFind this was 
available and is very useful. Thank you! 

RT99600

**Comment by gibsonjc** [comment]
UIU - We went live with VuFInd 4.1 on May 21st. Our users are starting to encounter and send in suggestions for improvements. One of the most frequent ones we are getting involves sorting checked out items in their My Account. Several have asked for the capability to sort on Due Date while others want the ability to sort alphabetically.

Here is one comment:

"I have a long list of Checked Out Items from various I-Share libraries, and the new systems lists books by library names alphabetically rather than due dates. It's actually very inconvenient for a user like me to check, renew, and return books in time. I've "found" an overdue book on Page 9--which would've been on top of the list in the old system..."

If we could give option to sort the results, that could help in these situations but I don't know if VuFind 4.1 has that capability. The might have been a customization we created for the older VuFind 0.6 version.

**Comment by Rolfing-Library** [comment]
TIU - We would also like to see the ability to sort books by due date. Ideally, it should default to due date - not home library and then I-Share libraries. b

**Comment by gibsonjc** [comment]
I received a reply from Demian to the question I posed on the vufind list:

> All of the user transactions are retrieved from the ILS driver here:
https://github.com/vufind-org/vufind/blob/master/module/VuFind/src/VuFind/Controller/MyResearchController.php#L1194
... then the pagination controls are applied to the array. 
>
> If you introduce a custom sort function to reorder the array prior to pagination, that should meet your need. It might also be possible to add a new parameter to the ILS method to allow sorting inside the ILS driver, but the ability to do this will vary by ILS, so it may be simpler (though of course less efficient) to do the work in the controller.
>
> I would certainly welcome a pull request to add a new option to the [Social] section of config.ini to define sort options and the necessary UI controls and sort logic to implement the behavior... and, of course, I'm happy to offer more advice if this is not enough to get you started.

**Comment by dmcmpbll** [comment]
WHE would like the ability to sort by due date, and would prefer due date to be the default-applied sort.

RT 100996

**Comment by nmswanson** [comment]
LFC- A faculty member with 2+ pages of checked out items noticed that the sort order is not by those due first. Can that be changed?
RT101490

**Comment by dgree1** [comment]
ROU- faculty member request due to long list of items checked out from several I-Share libs. 
RT 101536

**Comment by cedelis** [comment]
in TEST.

**Comment by dmcmpbll** [comment]
This is a great start! 
If a patron has more than 50 items checked out, their charged items are listed on multiple pages of 50 items each.

Is there a way to:
1) Show all of their charged items on one page?
OR
2) Have the sorting apply across all of the patron's charged items instead of being applied to the 50 items listed on the page they are viewing when the sort is changed?

I will send a private message with an example.

**Comment by cedelis** [comment]
@dmcmpbll I didn't realize Checked-out items was paged. My mistake. This most likely means that a client-side solution will probably not work. I think I need to scrap this version and work on a server-side solution.

Edit (Aug 27 2018 4:58 PM CST): Since the Voyager API is returning all of the charged item results, anyway, it might make more sense to just show all of the results on one page instead of paging through them 50 at a time. I've configured VuFind to show all charged items at once and have put this back into "Ready for Testing" status.

**Comment by cedelis** [comment]
This is (again) "Ready for Testing"

We now page through all of the checked out items on the client-side 50 at-a-time.

**Comment by cedelis** [comment]
In PROD.
