### ISSUE TITLE
SFX "Get full text" links no longer showing on record page in version 4.1

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#279]
We worked on getting SFX full text links to display on the record page on Issue #152 (has screenshots of what it looked like) which has been closed, but the problem has resurfaced in version 4.1.

In VuFind 3.1.4, SFX Get Full Text links were showing in the "Internet" section of the Holdings tab.  The "Internet" section is no longer displaying in any Holdings tab that I can find.

Example:
In these search results, all of the items with a "Get full text" link listed on the results page should be showing the same "Get full text" link in the Holdings tab as well:

https://i-share.carli.illinois.edu/vf-uiu/Search/Results?filter%5B%5D=format%3A%22Electronic%22&filter%5B%5D=collection%3A%22UIUdb_eresour-nc%22&filter%5B%5D=format%3A%22Journal+%2F+Magazine%22&lookfor=cats&type=AllFields

**Comment by cedelis** [comment]
Commit 5570ed4ae631e247710ac5df8f0350ebbaba643f

**Comment by gibsonjc** [comment]
I looked at some SFX libraries tonight and saw the Internet section with the SFX link (now custom button) displaying in records that also were also showing it on the results list.

Unless @dgree1 sees any major problems, I think this is Ready for Prod.

**Comment by dgree1** [comment]
I agree, ready for Prod.
