### ISSUE TITLE
Enhancement to make "due time" on checked out items tab more obvious

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#283]
IIT - [On the Checked Out Items tab/page] Having the due time listed on the checked out items tab is valuable for patrons at libraries where overdue fines are assessed for materials.

Making the "due time" portion of the due date more evident to patrons would be great.

Would it be possible to:
- Move the due time to its own line below the Due Date, so both are listed separately, 
OR, adjust the label for the "Due Date:" line to be "Due Date/Due Time:" so patrons more obviously know to check for the time in that line as well.

- Switch the due time from military timing to having AM/PM labels (so patrons more obviously notice the time as a time)

current screenshot of a checked out items tab:
![image](https://user-images.githubusercontent.com/20848151/34268503-90b5d83e-e646-11e7-881d-2878270bf361.png)

**Comment by gibsonjc** [comment]
@cedelis While you are working with Checked Out Item data displays for #332 , can you have a look at this one?  

Let's keep the date and time on a single line and change the label to:
**Due Date and Time:**

I'm not sure if changing the time format from military to AM/PM is possible given the way the data are returned from the Voyager API, so if it isn't, at least adjusting the label will be an improvement!

**Comment by cedelis** [comment]
In TEST

**Comment by dgree1** [comment]
What did you change? Looks same to me. See attached. 
![datedueoct1](https://user-images.githubusercontent.com/29785703/46313179-bfdfab00-c58c-11e8-8b37-3e8b8456d83c.GIF)

**Comment by dgree1** [comment]
Oh never mind, it was changing time display and including AM or PM.

**Comment by dmcmpbll** [comment]
Yes, this looks good to me on TEST.
And what is shown matches what is in Voyager.

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD.
