### ISSUE TITLE
Add additional preference setting for preferred pick-up library

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#284]
Add an additional preference setting to allow patrons to set another I-Share library as their default pick-up library. Some patrons may live closer to another I-Share library than their home library, and may wish to pick up there.

In https://github.com/CARLI/vufind/issues/89#event-1398743049, if the patron's home library has more than one pick-up location, the patron can set their preferred default pick-up location _at their home library only_ in their account profile.

**Comment by gibsonjc** [comment]
UIU - I just noticed a difference in the setup options for preferred library in the new VuFind: UIUC people can choose only UIUC pickup locations-they can do it for individual requests, but not as a saved preference.  Many staff in the Prairie Research Institute are permanently located at field stations that are much closer to other I-Share Libraries than UIUC. In VF.6, they are able to set a preference to pick up at any I Share library.

RT 101337

**Comment by gibsonjc** [comment]
@cedelis This enhancement needs research. Let us know what you think or if you have any questions!

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
On TEST, I have tested this on myself and as a user from ELM.  My preferences were saved as expected in my New VuFind Profile and showed my preference as the default during a Request (which I could also adjust in the Request pop-up box).  I placed some ABC, AAB, and ABB requests, and I also filled some of those requests at the lending library and confirmed that the preferred library and location were communicated with the request in the Call Slip client.

**Comment by dmcmpbll** [comment]
I have also tested this and found that the correct pickup library/location information was passed in to Voyager with the call slip, and the requests processed/routed as expected. 
My preference settings were correctly retained from one login to the next.

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD
