### ISSUE TITLE
New Items list search functionality enhancement?

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#289]
Is there a way to make it more evident that you have to click "Find" before the New Items lists will display?
I assumed clicking the "yesterday", "Past 5 days", "Past 30 days" would do the search for me, rather then also needing to click Find.

Is there a way to either add wording to make it more evident you need to click "Find", 
Or to make clicking on the date range the submission?

https://i-share.carli.illinois.edu/vf-uiu/Search/NewItem

**Comment by gibsonjc** [comment]
@eschell Can you experiment with adding a line of explanatory text to the NewItem page 
(i.e. https://i-share.carli.illinois.edu/vf-uiu/Search/NewItem) 
for all catalog instances that reads:

Select a range, then click the Find button.

**Comment by eschell** [comment]
How about something like this:

https://vufind4-mockup.carli.illinois.edu/vf-uiu/Search/NewItem

**Comment by gibsonjc** [comment]
Looks good!
![screen shot 2018-02-22 at 1 44 56 pm](https://user-images.githubusercontent.com/17598357/36560566-b0a62cfe-17d6-11e8-93ff-f70459390f7f.png)
This was fixed with the customization updates on 2/23. Closing.
