### ISSUE TITLE
Fines in Your Account display the wrong total

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#29]
When there is more than one line of Fines/Fees but some of them represent payments that should reduce the total owed, the display does not subtract that properly.  Instead, it adds every line to create an incorrect total.

**Comment by gibsonjc** [comment]
![screen shot 2016-04-14 at 8 08 48 am](https://cloud.githubusercontent.com/assets/17598357/14537301/fdda0bc4-023b-11e6-85ab-bf211257ec97.png)
![screen shot 2016-04-14 at 8 10 44 am](https://cloud.githubusercontent.com/assets/17598357/14537306/0489f4f2-023c-11e6-8a8e-3e49f1d45cfb.png)

**Comment by cedelis** [comment]
I had to rewrite a lot of themes/bootprint3/templates/myresearch/fines.phtml 
It's a small template file, but it's mostly customized now.
