### ISSUE TITLE
Footer too close to content above

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#290]
On several pages, the CARLI footer does not leave any space between the content above it and its dark horizontal line, making the content at the very bottom of the page look very cramped.  This occurs in all local catalog views and all union catalog views.  

@eschell Can some space be added before the footer line?

Examples:
https://i-share.carli.illinois.edu/all/vf/Browse/Home
https://i-share.carli.illinois.edu/all/vf/Search/Advanced
https://i-share.carli.illinois.edu/all/vf-uiu/Search/NewItem
https://i-share.carli.illinois.edu/vf-eiu/Search/Results?lookfor=cat&type=AllFields&limit=20&sort=relevance

![screen shot 2018-01-23 at 10 35 09 am](https://user-images.githubusercontent.com/17598357/35287930-1e980734-0029-11e8-96f2-fcb44379ec04.png)

**Comment by eschell** [comment]
Yes. I'll work on this and try and get it into production sometime this week.

Ed

**Comment by gibsonjc** [comment]
Fix in production 1/30/2018. Closing.
