### ISSUE TITLE
Ampersand for LAC displaying incorrectly in Pick-up library list

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#292]
Ampersand for LAC displaying as incorrectly in Pick-up library list when placing a request:
(Illinois Math & Science Academy is fine though!)

![screen shot 2018-01-24 at 5 23 28 pm](https://user-images.githubusercontent.com/17598357/35362571-7a2746ac-012b-11e8-997a-d66b621b4458.png)

**Comment by cedelis** [comment]
@gibsonjc I am no longer able to reproduce this scenario. Are you able to?

**Comment by gibsonjc** [comment]
Today IMS still has an ampersand (that displays correctly) but LAC has "and".  Given that they use both versions on their own website http://www.lc.edu/discover/ , it is probably fine to use "and" in the dropdown name to avoid the problem altogether!  Let's close this!
![screen shot 2018-02-19 at 2 48 29 pm](https://user-images.githubusercontent.com/17598357/36396535-54c57466-1584-11e8-9a25-3eef5c5cdce6.png)

**Comment by gibsonjc** [comment]
Reopening. The problem displaying the ampersand in the drop-down list of libraries for item pick-up is back again for IMS, showing 
![screen shot 2018-07-19 at 9 44 25 am](https://user-images.githubusercontent.com/17598357/42949890-7502691c-8b38-11e8-9103-3ddeda1a435e.png)
but LAC is fine because it uses "and" instead.

**Comment by cedelis** [comment]
Changed "&amp;" to "&" in languages.ini for both LAC and IMS

In TEST.

**Comment by gibsonjc** [comment]
The Pick-Up Library list is displaying **Illinois Math & Science Academy** now.
The Pick-Up Library list also contains 
**Lewis and Clark Community College**
and
**Spertus Institute of Jewish Learning & Leadership**
Ready for Prod.

**Comment by cedelis** [comment]
In PROD.
