### ISSUE TITLE
Preferred Library displaying in Your Account is confusing if you haven't set it yet

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#294]
IIT - All of our users have the Galvin circ desk [IIT-Galvin Circulation Desk] as their default pickup location when they [place a request but] haven't selected a pickup location in their profile, which is how it should be. 

However, when they open their profile settings the Downtown Campus location [DTC SERVICE DESK] appears to be selected (I believe because it is first on the list). 

![screen shot 2018-01-29 at 1 24 27 pm](https://user-images.githubusercontent.com/17598357/35529804-c6e326bc-04f7-11e8-90e9-c0446d07e437.png)

Perhaps there is a way to make the default location [IIT-Galvin Circulation Desk] [pre-]selected in the profiles OR make it clear that a selection has not been made?

**Comment by gibsonjc** [comment]
Ideally, the system default pick-up location [IIT-Galvin Circulation Desk] would be the one displayed when you go into Your Account Profile the first time.  But if it can't be, can the selection be a blank line to show that a Preferred location hasn't been set?  

IIT has three locations, and I think Katie @katieediger is right that it's defaulting to show the first alphabetically (based on the OPAC Display Name in Voyager Sys Admin) before a user goes in and purposefully selects and Saves a location.

![screen shot 2018-01-29 at 1 21 50 pm](https://user-images.githubusercontent.com/17598357/35529941-30eb503e-04f8-11e8-9fab-9fb2236f9cae.png)

**Comment by dgree1** [comment]
Let me know if I can assist with this issue. The SFX Systems comm. discussed it 2/14 and agreed this is a big deal for I-Share libs with multiple Circ desks, branch libraries, more than one campus and the like.

**Comment by gibsonjc** [comment]
@cedelis Ideally, the Voyager system default pick-up location will be the one displayed when one goes into Your Account Profile the first time (and thereafter until you change it to something else).  Currently it seems to be defaulting to the first one alphabetically, which isn't always the system default one.  (See IIT example above.)

If it can't be set to the system default, can the selection be a blank line to show that a Preferred location hasn't been set by the user in their account yet?  Thanks!

**Comment by cedelis** [comment]
In Test.

**Comment by dgree1** [comment]
Chris, did you set the default to be the system default one? 
That's what it looked like in 
https://i-share-test.carli.illinois.edu/all/vf-iit/MyResearch/Profile 

thanks.

**Comment by cedelis** [comment]
@dgree1 It appears that this feature only works for "valid" patrons.

The API call I make, UBPickupLibService, depends on a "valid" patron. The example you gave me (offline) was a patron who was "blocked from making requests:"

response to UBPickupLibService:

<?xml version="1.0" encoding="UTF-8"?>
<ser:voyagerServiceData xmlns:ser="http://www.endinfosys.com/Voyager/serviceParameters"><ser:messages><ser:message type="blocked" errorCode="com.endinfosys.voyager.requests.exceptions.PatronRequestsException.PatronBlockedException" blockCode="patronBlocked">Patron is blocked from making requests.</ser:message></ser:messages></ser:voyagerServiceData>'


I'm not sure if there's a way around this. Another solution I can attempt --if this is a deal-breaker-- is to *not* use such an API call in realtime and instead hard-code the system-wide default pickup library on a per-library basis. Do these defaults change often?

**Comment by gibsonjc** [comment]
If the patron isn't "valid", they can't place a request anyway, so the default pick-up location seems like it might be the least of their worries!

If the patron record is expired, I tested that once the patron record was made to be unexpired, the default pick-up location worked as expected or it honored their choice if they'd made one (as in, it didn't reset it when they were unexpired), so that is good.

Rather than creating a workaround here just for invalid patrons, I would rather we utilize the native mechanisms for identifying the default pick-up location to use even if those require the patron to be valid to work.  If this presents a huge problem, we can always revisit this situation down the road.

Ready for prod!

**Comment by cedelis** [comment]
In production.
