### ISSUE TITLE
Neutralize default green accents

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#297]
Discovered while investigating suggestion on RT 95599.  Please investigate making these defaults a neutral color.

1. The highlighted selections on the “Browse the catalog” page default to green.
Example:
https://i-share.carli.illinois.edu/vf-elm/Browse/Home 

It may be easy to customize this to be the same color as the highlighted Narrow Search option, ifso, we can do that. If it is possible to just make this a more neutral color, that’s also an option.

Side note: what is with the highlighting after a level has been chosen and turns green, but if I put my mouse back over it, it washes out to white on light gray and can’t be read?  That's really awful.

2. The date slider squares under Year of Publication “facet” at the bottom of the Narrow Search Facets on the results list page are green.
Example:
https://i-share.carli.illinois.edu/vf-elm/Search/Results?lookfor=cat&type=AllFields 

3.  The date slider squares under Year of Publication on the Advanced Search page are green.
Example: 
https://i-share.carli.illinois.edu/vf-elm/Search/Advanced 

4. The highlighted page number at the bottom of the results list page is green
Example:
https://i-share.carli.illinois.edu/vf-elm/Search/Results?lookfor=cat&type=AllFields 

5. The highlighted New Items “button” is green in two different ways on 
https://i-share.carli.illinois.edu/vf-elm/Search/NewItem 
When you first go to the page, Yesterday is green text on white.  If you click it or a different button, it’s white text on dark green.

**Comment by eschell** [comment]
Take a look at the test of the changes:

1. https://vufind4-mockup.carli.illinois.edu/vf-elm/Browse/Home
2. https://vufind4-mockup.carli.illinois.edu/vf-elm/Search/Results?lookfor=cat&type=AllFields
3. https://vufind4-mockup.carli.illinois.edu/vf-elm/Search/Advanced
4. https://vufind4-mockup.carli.illinois.edu/vf-elm/Search/Results?lookfor=cat&type=AllFields
5. https://vufind4-mockup.carli.illinois.edu/vf-elm/Search/NewItem

**Comment by gibsonjc** [comment]
@eschell These changes to remove the green accents look good to me, thank you!  Please move them along at your convenience!

**Comment by eschell** [comment]
These changes have been moved to production.
