### ISSUE TITLE
Items at libraries that don't allow local requests say "Not Charged" instead of "Available"

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#298]
NCC - We noticed that all the other schools' records have the status "Available," while ours is "Not Charged."

RT 97879

**Comment by gibsonjc** [comment]
@dmcmpbll suggests a reason with some examples:  the difference I think is that NCC doesn't allow local call slip, so the status mapping/display is different.

MIL allows local call slip, so it's mapped to "Available":
https://i-share.carli.illinois.edu/vf-mil/Record/MILdb.385986

NCC does not allow local call slip, so it's showing base status of "Not charged":
https://i-share.carli.illinois.edu/vf-ncc/Record/NCCdb.100797

**Comment by cedelis** [comment]
The default text for available items (ones which may be Requested) is "Available" (hard-coded in the RecordTab/holdingsils.phtml template).

For items which are *not* available, the actual status value (which comes from Voyager) is used for the text, which happens to be "Not Charged" for the example cited in this issue.

This could be changed. But to what, exactly? A hard-coded string? Does this need to be a library-specific setting? Another idea: we could create a translation mapping for "Not Charged" -> "Available" ( vf-xxx/languages/en.ini ).

**Comment by gibsonjc** [comment]
> The default text for available items (ones which may be Requested) is "Available" (hard-coded in the RecordTab/holdingsils.phtml template).
>
> For items which are not available, the actual status value (which comes from Voyager) is used for the text, which happens to be "Not Charged" for the example cited in this issue.
>
> This could be changed. But to what, exactly? A hard-coded string? Does this need to be a library-specific setting? Another idea: we could create a translation mapping for "Not Charged" -> "Available" ( vf-xxx/languages/en.ini ).

@cedelis I like this simple idea of a translation mapping for "Not Charged" -> "Available".  Could you try this on DEVEL and we can see what it looks like?

**Comment by cedelis** [comment]
@gibsonjc Yes, adding a translation mapping works:

https://i-share-devel.carli.illinois.edu/vf-ncc/Record/NCCdb.100797

**Comment by gibsonjc** [comment]
Thanks!  Hmmm, it does change the words from "Not Charged" to "Available" on the single record page, but might have the unintended consequence of duplicating the item line display.  See how there is now one Copy 1 with no status and another Copy 1 with "Available" in red text on 
https://i-share-devel.carli.illinois.edu/vf-ncc/Record/NCCdb.100797 ?  
<img width="693" alt="screen shot 2018-06-08 at 10 36 29 am" src="https://user-images.githubusercontent.com/17598357/41167192-d8a02186-6b07-11e8-9b6b-09287375f16c.png">

But there is only one Copy 1 line as seen in TEST and PROD
https://i-share-test.carli.illinois.edu/vf-ncc/Record/NCCdb.100797
https://i-share.carli.illinois.edu/vf-ncc/Record/NCCdb.100797

I also just realized that "Not Charged" was in RED text as well when we would want it to be GREEN text (and now with the translation the word "Available" is in RED when we'd want it to be GREEN).

This seems to be on the right track but might be more involved than just the translation of the text!

**Comment by cedelis** [comment]
@gibsonjc This is a red herring. The change I made only translates text; it does not affect any other data associated with Holdings.

It's more likely related to Issue #242 or some other Holdings related issue.

**Comment by gibsonjc** [comment]
Ok, yes, that extra line was a red herring due some extra code on DEVEL that was being tested before #242 was solved.  Once it was removed the display returned to a single line!

So, yes, the translation of the words works great, but I'm not sure if we need the words ["Not Charged" translated now to "Available"] to be in GREEN text instead of RED.  I will consult with others.

**Comment by gibsonjc** [comment]
At our meeting on 6/14, the decision was made to translate the words "Not Charged" to "Available" even though "Available" will be in red font.  If the color of the word "Available" presents a problem, we can attempt to address the color in a new, future Issue.

@cedelis Please translate "Not Charged" to "Available" on TEST and let us know when it is ready for final testing.  Thanks!

**Comment by cedelis** [comment]
In TEST

**Comment by cedelis** [comment]
in PROD

**Comment by gibsonjc** [comment]
No action to take, just leaving a note here that ILC is concerned about Available being red instead of green in RT 102400.
