### ISSUE TITLE
Can copy number display come from MFHD 852 $t

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#299]
We improved the Copy number display in Issue #169 from being a hidden-and-not-useful sequence number to the Voyager Item record's Copy number, but ideally, we'd like to be able to display the Copy number found in the MFHD 852 $t instead of the Voyager Item record Copy number.

**Comment by gibsonjc** [comment]
WHE - I also believe that ideally, copy number should come from the MFHD 852 $t as it apparently did in VuFind 0.6.   RT 96009

**Comment by cedelis** [comment]
In Test.

**Comment by gibsonjc** [comment]
Here is an example where using the MFHD copy number is an big improvement:

https://i-share.carli.illinois.edu/vf-whe/Record/WHEdb.906627
https://i-share-test.carli.illinois.edu/vf-whe/Record/WHEdb.906627
(Note that in TEST three items are in the same location, but only two are in the same location on PROD)
https://vufind.carli.illinois.edu/vf-whe/Record/whe_906627

**Comment by cedelis** [comment]
This fix was put into production this morning (along w/ another fix).
