### ISSUE TITLE
change the green default background

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/vufind#3]
JIRA issue created by: Jessica Gibson (gibsonjc)
Originally opened: 2016-03-24 11:37 AM

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-03-25 09:34 AM

Brandon says:

No need to worry about the compiled css files in bootstrap:

https://bootstrapbay.com/blog/customize-bootstrap/

**Comment by patrickzurek** [comment]
JIRA User: Brandon Gant (bgant)
JIRA Timestamp: 2016-03-25 10:19 AM

Checking to see if I can leave comments now...

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-04-04 12:41 PM

We gave Ed access to my vufind2-gibson server and he is working on the green.

**Comment by gibsonjc** [comment]
On May 5, Ed completed work on vufind2-test to change the default green background to white.  He also updated the dropdown menu page from green to white and inserted the CARLI I-Share logo in the header.
