### ISSUE TITLE
Update default wording for newly created list

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#301]
When someone creates a list in New VuFind and the list contains no items, the terminology at the top of the new list says, "You do not have any saved resources. Perform a search and use the Add to Favorites button to save items."

VuFind 0.6 called the "save" option- "Add to Favorites."
New VuFind calls the "save" option- "Save to List."

Can the default wording when a new list is created be updated to reflect this?

**Screenshots:**
1) New VuFind's blank list default wording:
![image](https://user-images.githubusercontent.com/20848151/37492311-e3648cd2-286e-11e8-9c5b-dba2f2e72352.png)

2) New VuFind's results list showing wording "Save to List." 
![image](https://user-images.githubusercontent.com/20848151/37492381-1e21ccd6-286f-11e8-9df2-85ea75a961cd.png)

3) VuFind 0.6 results list showing wording "Add to Favorites."
![image](https://user-images.githubusercontent.com/20848151/37492358-0d611b72-286f-11e8-96ec-e58690956338.png)

**Comment by gibsonjc** [comment]
@dmcmpbll New VuFind seems to consistently use the word List or Items in the following places: 

"Save to List" with a yellow star (results list and single record page)
"Your Lists" "Create a List" "Edit List" "Delete List" (Your Account)
"Saved Items" with a yellow star (Your Account) 

Are you suggesting that all of these instances of "List" should be changed to "Favorites"?  
Is there some indication that users don't know what Lists are in New VuFind?

The only place I see the word "Favorites" is when you choose "Save to List".  The default List name for all users (before they create any of their own named Lists) is called "Favorites".

**Comment by dmcmpbll** [comment]
Sorry for any confusion, I'm suggesting that we update the help-text wording that appears when someone creates a new list in New VuFind to say "Save to List" instead of "Add to Favorites".

**Comment by dmcmpbll** [comment]
![image](https://user-images.githubusercontent.com/20848151/37917382-e6892a26-30e3-11e8-878f-3fb7d1043585.png)

**Comment by gibsonjc** [comment]
Got it!  You want the text that displays in an empty list 

You do not have any saved resources. Perform a search and use the **Add to Favorites** button to save items.

changed to

You do not have any saved resources. Perform a search and use the **Save to List** button to save items.

**Comment by gibsonjc** [comment]
In /languages/en.ini please change this variable to this wording:

You do not have any saved resources = "You do not have any saved resources. Perform a search and use the Save to List button to save items."

**Comment by cedelis** [comment]
In Test.

**Comment by dmcmpbll** [comment]
I think it looks good on test.

![image](https://user-images.githubusercontent.com/20848151/39063973-5de15a14-4492-11e8-96af-7bbf6f2c4fc1.png)

**Comment by gibsonjc** [comment]
Ready for Prod!
