### ISSUE TITLE
Suppressed Course Reserves bibs display in general search results

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#302]
UIC- RT 98136 We have some older records for electronic reserves that are suppressed from our OPAC but seem to be showing in VuFind 4. If you perform an "All Fields" search for "eres website" you'll find 901 records. An example of an individual record is bib #1954631. I tried another suppressed record for a regular book (bib #601782) and it didn't show in VuFind 4.

A Course Reserves bib that is OPAC suppressed:
https://i-share.carli.illinois.edu/vf-uic/Record/UICdb.3713223
displays in search results:
https://i-share.carli.illinois.edu/vf-uic/Search/Results?lookfor=%22CYN+531+ERes+Website%22&type=AllFields&limit=20&sort=relevance

**Comment by gibsonjc** [comment]
@cedelis You were commenting on #258 ("Course Reserves showing inactive lists") but this problem of suppressed Course Reserves items showing up in regular search results is a different problem, so I've created a new Issue here for that.

**Comment by gibsonjc** [comment]
Text moved from #258 :

3/23 - This was tested and put into production today. After tonight's record updates, this issue should be resolved (early tomorrow).

Here's an example to test/verify (a Course Reserves bib that is OPAC suppressed):

Accessible: https://i-share-test.carli.illinois.edu/vf-uic/Record/UICdb.3713223

But not searchable: https://i-share-test.carli.illinois.edu/vf-uic/Search/Results?lookfor=%22CYN+531+ERes+Website%22&type=AllFields&limit=20&sort=relevance

Today, on PROD:

Accessible: https://i-share.carli.illinois.edu/vf-uic/Record/UICdb.3713223

But IS (incorrectly) searchable: https://i-share.carli.illinois.edu/vf-uic/Search/Results?lookfor=%22CYN+531+ERes+Website%22&type=AllFields&limit=20&sort=relevance

Tomorrow, on PROD, it should be:

Accessible: https://i-share.carli.illinois.edu/vf-uic/Record/UICdb.3713223

But not searchable: https://i-share.carli.illinois.edu/vf-uic/Search/Results?lookfor=%22CYN+531+ERes+Website%22&type=AllFields&limit=20&sort=relevance

**Comment by gibsonjc** [comment]
This change was backed out this morning because it had the unintended consequence of breaking the Advanced Search function.

**Comment by gibsonjc** [comment]
Suppressed Course Reserves fix ready for Prod.

**Comment by cedelis** [comment]
In prod, commit 96f5d9dcdf21148a044feb754b1db93d0e6070ff
