### ISSUE TITLE
Customize "Library Catalog Profile" page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#305]
SIC - We use Shibboleth for VuFind authentication but the very first time a user tries to access Vufind4, users are asked to establish a catalog profile with their barcode and last name (this is to link the Vufind authentication to the Voyager backend).

Is any of the text customizable on this page?

![sic_profile_page](https://user-images.githubusercontent.com/17598357/38149978-6894c444-3422-11e8-9337-6f125fd5eadc.jpg)

It would be helpful to state that this is only for first time users and that in subsequent sessions the user will be able to use their SIUC Network ID and password to access their library account. Also, I would love to be able to tell our users what information they have to use for the barcode field which is a label not user anywhere else in our system.

**Comment by nmswanson** [comment]
JKM- Would it be possible to add [customized text to the profile page if not using single sign-on?]

RT99919 - includes customized text request and profile page URL.

**Comment by dmcmpbll** [comment]
ILC is also interested in being able to customize the "one-time" profiling page that patrons see when logging in for the first time using their single-sign-on credentials--- specifically to be able to tell patrons how/where to locate their barcode number.

RT 99873

**Comment by gibsonjc** [comment]
Customization option is now live on https://www.carli.illinois.edu/newvufind-shibboleth-login-customization. Closing.
