### ISSUE TITLE
need more export options from My List

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#306]
KNX - There is no way to get a list in plain text format of items saved in My List. Also, for the export feature from My List, will you be adding options for RIS format and/or Zotero? (RIS is close to plain text, though not exactly; plain text is preferable.) 

RT 98459

**Comment by gibsonjc** [comment]
I believe if we change the options we want to be exportable to **record,bulk** instead of just **true** the same export options will appear on the single record page and the My List page (which appears to be have bulk options by default).  (See also #300 about turning on bulk options.)

https://github.com/vufind-org/vufind/blob/c02b20dd4a628bd83a062b91cd49c56f0ecb2eca/config/vufind/config.ini#L1302

CARLI's config.ini:
```
; This section controls the availability of export methods.
;
; Each entry may be a comma-separated list of contexts in which the export
; option will be presented. Valid options:
;
; bulk - Included in batch export contexts
; record - Included in single-record export contexts
;
; If you simply set a field to true, only "record" mode will be enabled.
; If you set a field to false, all export contexts will be disabled.
;
; Note that some options may be disabled for records that do not support them,
; regardless of the setting chosen here.  You can edit the separate export.ini
; file to add new export formats and change the behavior of existing ones.
[Export]
RefWorks = "record,bulk"
EndNote = "record,bulk"
EndNoteWeb = "record,bulk"
MARC = false
MARCXML = false
RDF = true ; CARLI
BibTeX = true ; CARLI
RIS = false
```

We should also enable RIS format for export with **record,bulk** as there is no harm in adding it.
So, change the last three lines above to:
```
RDF = "record,bulk" ; CARLI
BibTeX = "record,bulk" ; CARLI
RIS = "record,bulk" ; CARLI
```

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
These new Export options seem to work as I expected from the Results page list or from a Saved list in Your Account except for trying to Export more than one record at a time **in RDF**.  One record exported in RDF works fine, more than one record exported to RDF always produces an error like this:

![screen shot 2018-06-14 at 2 35 37 pm](https://user-images.githubusercontent.com/17598357/41434081-4859093e-6fe0-11e8-8eae-579ca9b360db.png)

It occurs with Firefox and Chrome.

Replication steps:
Do a search on TEST
On results page, check multiple items
Click Export > RDF >Export > Download file

@cedelis Since exporting one record in RDF does seem to work correctly, on TEST please change
RDF = "record,bulk" ; CARLI
to
RDF = true ; CARLI
so I can double-check this still works as expected before we ok for prod.  Thanks!

**Comment by cedelis** [comment]
@gibsonjc : I made the change (RDF = true).

**Comment by cedelis** [comment]
In PROD.
