### ISSUE TITLE
change number of I-Share libraries to 90 in footer

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#310]
@eschell New VuFind Production, Test, Devel, and vufind4-mockup all still say 86 libraries in the footer. Please change to 90.

**Comment by gibsonjc** [comment]
This appears to be changed to 90 now, so I'll close this Issue. Thanks!

**Comment by gibsonjc** [comment]
This is needed on the index page https://i-share.carli.illinois.edu

This is on TEST but not on Production, so I'm reopening the Issue until it is.  (I thought it was good on Prod when I looked before but who knows, I might have been looking in the wrong place!)

**Comment by cedelis** [comment]
In prod.
