### ISSUE TITLE
Display more data from Voyager Item record

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#313]
EIU - It appears that New VuFind does not display data from the Voyager item record’s chronology field.  Can this be added? 

Here is an example of a serial that uses only the chronology field to identify issues.
https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.670182

The second example below is a case where both enumeration and chronology are needed to identify items.
https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.497552

**Comment by gibsonjc** [comment]
The Item enumeration data that are displaying is coming from MFHD_ITEM.ITEM_ENUM

Can we also make MFHD_ITEM.CHRON data display here after MFHD_ITEM.ITEM_ENUM, if present?

So then example https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.670182
which currently looks like before:
  Copy 1
  Copy 1
  Copy 1
would show this after:
  Copy 1  (2014-2015)
  Copy 1  (2013-2014)
  Copy 1  (2012-2013)

and this example https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.497552
which currently looks like this before:
  Copy 1 (v.80)
  Copy 1 (v.80)
  Copy 1 (v.80)
would show this after:
  Copy 1 (v.80 2009 Dec 15)
  Copy 1 (v.80 2009 Dec. 1)
  Copy 1 (v.80 2009 Nov. 15)

**Comment by gibsonjc** [comment]
Ideally, we'd like the data to display a bit differently, too, like this:

Copy # MFHD_ITEM.ITEM_ENUM (MFHD_ITEM.CHRON)

Examples of above "after" examples:

Copy 1 (2014-2015)
Copy 1 v.80 (2009 Dec 15)

changing the parentheses () that are being included by VuFind--I assume, because they are NOT in the Item record data--to only appear around MFHD_ITEM.CHRON data when present, and otherwise don't display parentheses.

**Comment by cedelis** [comment]
This is now in TEST.

**Comment by gibsonjc** [comment]
More Item data looks GREAT! Ready for Prod!

**Comment by cedelis** [comment]
In Prod.

**Comment by gibsonjc** [comment]
Reopening this Issue because the work done to display the chronology data along with the enumeration data from the Item record is no longer working.

See original examples from above now only showing enumeration data again:
https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.670182
https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.497552

and a new example: 
https://i-share.carli.illinois.edu/vf-uiu/Record/UIUdb.989310  (UIU - RT 100697)

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Chronology data is displaying again after the adjusted section of SQL was put back in, this is ready for Prod!

**Comment by cedelis** [comment]
In Prod (again).
