### ISSUE TITLE
Number of I-Share libraries on splash page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#315]
![screen shot 2018-04-25 at 8 39 59 am](https://user-images.githubusercontent.com/17598357/39249448-5118d2fa-4864-11e8-93fb-3fe290746549.png)

The choose-a-library splash page at 
https://i-share.carli.illinois.edu/
says 86 libraries at the bottom and needs to be changed to 90 libraries on DEVEL, TEST, and PROD (probably vufind4-MOCKUP also, although I see that one is out of sync and different from the others in that is presents a button for Classic when All I-Share Libraries is chosen when the other do not, and it's link to "What are the differences?" has not been updated).

**Comment by eschell** [comment]
that file is found at /var/www/html/index.html I updated it on vufind4-mockup but as you mention that one is out of sync.

Since this file is not part of the git repo I can see how the various versions are out of sync.

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
Splash page looks good, ready for Prod

**Comment by cedelis** [comment]
In PROD.
