### ISSUE TITLE
Improve the "Saved Searches" label in Your Account

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#316]
UIC - 4/25/2018 conference call - They asked about search history, thinking that New VuFind did not offer search history anymore.  They didn't realize that the search history is in Your Account under "Saved Searches".  It is there and records your searches for that session.  This is where you can perform the action to Save that search, and where you can find the saved search in future.  They suggested that the label was not informative enough, but did not have a specific recommendation for what to change it to.  They'll let us know if they do.

**Comment by gibsonjc** [comment]
Random thoughts:

Recent Searches do appear to be limited to your current session.

Hoping this wording is in languages/en.ini:
history_saved_searches = "Saved Searches"

Maybe call it "Saved Searches and History"?
"Saved Searches and Search History" might be too long for the sidebar in Your Account.

@dmcmpbll Do you have any suggestions or do you wish to ask the Instruction Committee?

![screen shot 2018-04-26 at 2 30 40 pm](https://user-images.githubusercontent.com/17598357/39327726-752d8082-495e-11e8-8515-3979004261ba.png)

**Comment by dmcmpbll** [comment]
Looks like the sidebar wraps at 35 characters (from a test using a saved list name).

My first thought for phrasing is "Recent and Saved Searches"

I will query the Instruction Committee to see if they have recommendations.

**Comment by dmcmpbll** [comment]
Instruction Committee had votes for:

Recent and Saved Searches
Saved Searches and Recent History
Saved Searches/Recent History

**Comment by gibsonjc** [comment]
In languages/en.ini, please change 
history_saved_searches = "Saved Searches"
to 
history_saved_searches = "Recent and Saved Searches"

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
I think this is Ready for Prod.  
This isn't perfect, but I'm willing to live with the duplicate headings of "**Recent** and Saved Searches" followed by "**Recent** Searches" on this page because it makes the label in the right-hand menu more accurate.  If there is a lot of confusion about this, we can try to address it in future.

![screen shot 2018-06-15 at 11 20 21 am](https://user-images.githubusercontent.com/17598357/41478719-5f221f8a-708e-11e8-9657-be17feac37ce.png)

**Comment by cedelis** [comment]
In PROD.
