### ISSUE TITLE
"Internet" section of Holdings tab shows Bib 856 data

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#317]
The "Internet" subsection of the Holdings tab on the single record page displays the SFX button, or if that's not available (or a library doesn't have SFX), Bib 856 data, or if that's not available, the subsection doesn't display at all.  

There is a setting in config.ini : 
; This setting controls whether we should display an OpenURL link INSTEAD OF other
; URLs associated with a record (true) or IN ADDITION TO other URLs (false).
replace_other_urls = true

We'd like to modify this behavior so that only SFX buttons display here (when appropriate according to the current SFX button generation logic), and never display of Bib 856s here at all times.

Examples where Bib 856s should stop displaying:
https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.1515179
https://i-share.carli.illinois.edu/vf-uiu/Record/UIUdb.4904630
https://i-share.carli.illinois.edu/vf-niu/Record/NIUdb.2727947

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
I do not see any change in TEST from production.  I might not have described this well enough.

https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.4904630
https://i-share.carli.illinois.edu/vf-uiu/Record/UIUdb.4904630

https://i-share-test.carli.illinois.edu/vf-niu/Record/NIUdb.2727947
https://i-share.carli.illinois.edu/vf-niu/Record/NIUdb.2727947

The config.ini already has replace_other_urls = true which is fine and should not be changed.  I was just pointing out that this is the only thing I can find that controls this area, but it doesn't do exactly what we want.  What we want to do is something more: we want to suppress Bib 856s from displaying in the Internet section at all times.  The SFX button should continue to display in the Internet section, but no Bib 856s ever should.

**Comment by cedelis** [comment]
In TEST (again).

**Comment by gibsonjc** [comment]
This looks good on TEST, it is ready for PROD.  
Whatever you did seems to have suppressed or removed the "Internet" label from the top of the Holdings tab altogether.  As it turns out, we like it being gone very much, so please don't bring it back!  Having "Internet" removed also resolves #314 , so we don't need to worry about changing the label wording to something else and can close it as a result of this work.

**Comment by cedelis** [comment]
In Prod.
