### ISSUE TITLE
investigate using a Local Call Slip method and a UB method instead of just UB method for everything

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#318]
Reopen investigation to see if we must use UB mechanisms for both local and UB requests.

**Comment by cedelis** [comment]
This is now on TEST.

Commit 30219a2b4178a447055cc9e2252a27b94ad91e59

**Comment by cedelis** [comment]
commit 30219a2b4178a447055cc9e2252a27b94ad91e59

**Comment by cedelis** [comment]
In PROD.
