### ISSUE TITLE
Linking functions use record IDs but record IDs are not persistent in I-Share union catalog

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#322]
In the I-Share union catalog, the record ID numbers are not persistent.  In New VuFind, the functions for Cite this, Text this, Email this, Export record, and Save to List all use the record ID to link back to the item.

Example:  
https://i-share.carli.illinois.edu/all/vf-eiu/Record/274664087

Can these functions be adjusted to use the 035 field instead?

Can the 035 field be used to go directly to a record rather than running a search for the 035 data?

**Comment by gibsonjc** [comment]
In the I-Share union catalog views /all/vf/ or /all/vf-xxx/, the Cite-Text-Email-Export-Save functions at the very top of the record link to the union catalog record ID, which will not be persistent.  

However, the Cite-Text-Email-Export-Save functions present with each Holding link to the local catalog record for that library's holding via Voyager Bib ID which will be persistent (for as long as we use Voyager, unless the local catalog record is removed).

Given this situation, should we remove the Cite-Text-Email-Export-Save functions at the very top of the record in the union catalog views /all/vf/ and /all/vf-xxx/?  We need to do some testing as to how that affects a user who is affiliated with and logged into one institution but saving records from another institution.

**Comment by gibsonjc** [comment]
Let's remove the Cite-Text-Email-Export-Save functions at the very top of the record in the union catalog views /all/vf/ and /all/vf-xxx/ on TEST and see how that works.  As I mentioned, we need to do some testing as to how that affects a user who is affiliated with and logged into one institution but saving records from another institution.

**Comment by cedelis** [comment]
In TEST.

**Comment by cedelis** [comment]
In PROD.
