### ISSUE TITLE
Add "Show local catalog results only/Show all libraries" option

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#326]
SIC - Add a similar "Results for…"  feature (like the one currently available in VuFind 0.6) to promote easy toggling back and forth between the local and the union catalogs.  

If a user is in the I-Share union catalog, it is not currently easy to narrow to your local library’s holdings only.  The Institution facet lists results by number of libraries that hold an item so your institution may be anywhere in that list. Or you can change the catalog dropdown choice to local only and rerun the search.

If a user is in the local catalog, the only way to get to the I-Share catalog right now is to change the catalog dropdown choice after the search box and rerun the search.

In VuFind 0.6 it looks like this:
![screen shot 2018-05-25 at 1 40 24 pm](https://user-images.githubusercontent.com/17598357/40561001-3c9f5554-6021-11e8-9c2c-72fc385cade1.png)
![screen shot 2018-05-25 at 1 40 32 pm](https://user-images.githubusercontent.com/17598357/40561003-4010cc54-6021-11e8-944a-2aa5b916e4af.png)

**Comment by gibsonjc** [comment]
@cedelis Marking this as priority for now so you can think on this and let us know if you have any ideas for a similar kind of implementation. 

Users in the local catalog can now repeat their search with no results in the I-Share catalog (#281).
And users in the I-Share catalog can use the Institution facet to get to a local catalog, but that might require a few clicks to drill down to their institution since the facet list is presented by number of hits.

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
"Show results for" toggle seems to be working at expected; Ready for Prod

**Comment by cedelis** [comment]
In PROD
