### ISSUE TITLE
Location facet sort order

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#327]
TIU - We have come across a specific question regarding location limits in the new vu-find.

In the current instance [0.6], it appears that location limits are "in descending order by the number of records to which they will reduce the result set," however, in new vu-find this is not (or does not appear to be) the case.

We have conducted the same search "Green" in both instances of vu-find (specifically TIU, not-I-Share) and have two very different results for the listing of location limits. I am attaching screen shots of the location limit results.

https://i-share.carli.illinois.edu/vf-tiu/Search/Results?lookfor=green&type=AllFields

https://vufind.carli.illinois.edu/vf-tiu/Search/Home?lookfor=green&type=all&start_over=1&submit=Find

Do you know how location limits are arranged in new Vu-find? Is there anything we can do to make it more consistent for examples, list by either by number of records or alphabetical, etc)? 

RT 99266

**Comment by gibsonjc** [comment]
These are not sorted by number of hits, ID, Code, or Name.
We are unable to sort them by number of hits in New VuFind.
We will sort them by Name.

**Comment by gibsonjc** [comment]
Need to determine if it is more efficient/possible for Gordon to try to sort the data alphabetically by Name in loc_limit_grps.txt before giving it to Chris, or for Chris to sort the data in loc_limit_grps.txt after receiving it from Gordon.

**Comment by cedelis** [comment]
@gibsonjc I've already sorted it in code. In Test.

**Comment by cedelis** [comment]
In prod.
