### ISSUE TITLE
shield user's barcode from being auto-remembered by the browser

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#33]
The Username is the barcode, and the Password is the last name.  Modern browsers often remember and auto-fill text typed into a Username box even when you don't have them specifically save the credentials.  This would mean that a user's barcode is the thing that is being remembered and displayed.  Can VuFind2+ shield the barcode like WebVoyage does?  On the WebVoyage MyAccount log in screen, the Library Borrower ID box shows dots when you type in it and the Last Name box shows the text.

**Comment by cedelis** [comment]
I've been meaning to do this. Thanks for reminding me! Done.
