### ISSUE TITLE
Checked Out Items do not show serial volume information

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#332]
UIU - Patrons with multiple volumes of same serial can't tell which specific volume number is in their account.  See "North nord" and "House beautiful;" examples in one patron's account:

![screen shot 2018-06-01 at 1 07 09 pm](https://user-images.githubusercontent.com/17598357/40856218-b75f0da4-659c-11e8-8c64-7f8c13d1d32c.png)

![screen shot 2018-06-01 at 1 22 39 pm](https://user-images.githubusercontent.com/17598357/40856857-ee4fc64e-659e-11e8-96ff-73f5ea502300.png)

RT 99729

**Comment by gibsonjc** [comment]
LFC - I don't think there is a way for me to tell which item is which .... I have three items with the same title and author checked out from Bradley: the textbook, the CD, and a DVD. One of the items renewed, but not the others. Is there an easy way for me to figure out which item renewed?
![screen shot 2018-09-11 at 12 48 47 pm](https://user-images.githubusercontent.com/17598357/45377752-132f9080-b5c1-11e8-8dd5-4fa82cea2338.png)

I can tell by going searching it and looking at the item information, since due dates display there (the text is the item that renewed). However, most patrons wouldn't know how to do this.
![screen shot 2018-09-11 at 12 49 24 pm](https://user-images.githubusercontent.com/17598357/45377766-27738d80-b5c1-11e8-84a0-1df131701830.png)


RT 101944

**Comment by gibsonjc** [comment]
@cedelis Is there an SQL query or similar that pulls the data for display in the Checked Out Item list?  If so, do you think we could add ITEM_ENUM, ITEM_CHRON, LOCATION, and some form of the Call Number to the information that displays?

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD

**Comment by gibsonjc** [comment]
In addition to adding serial volume information, we also added Location and Call Number to the Checked Out Items page display.
![screen shot 2018-10-08 at 12 15 57 pm](https://user-images.githubusercontent.com/17598357/46623702-17819780-caf4-11e8-9719-129343783a20.png)
