### ISSUE TITLE
RETURNDATE not providing useful information in Holdings tab display SQL

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#334]
RT 99886 - This information may be useful for simple transactions, but for overdue items, the date remains the last time the item was discharged from a patron's account, which is confusing.

The "returned date" from circ_trans_archive was in the original SQL that was used by New VuFind. 

Debbie added in an "AS" before the "RETURNDATE" alias label because it was missing. Did adding in that "as" activate the display?

-----from GitHub 242: https://github.com/CARLI/vufind/issues/242:

to_char(CIRC_TRANSACTIONS.CURRENT_DUE_DATE, 'MM-DD-YY') as duedate,
(SELECT TO_CHAR(MAX(CIRC_TRANS_ARCHIVE.DISCHARGE_DATE), 'MM-DD-YY HH24:MI')
FROM ${sid}DB.CIRC_TRANS_ARCHIVE
WHERE CIRC_TRANS_ARCHIVE.ITEM_ID = ITEM.ITEM_ID) RETURNDATE,

-----from Chris's version he sent back to Debbie after he updated it for New
VuFind specific language:

to_char(CIRC_TRANSACTIONS.CURRENT_DUE_DATE, 'MM-DD-YY') as duedate,
(SELECT TO_CHAR(MAX(CIRC_TRANS_ARCHIVE.DISCHARGE_DATE), 'MM-DD-YY HH24:MI')
FROM ${sid}DB.CIRC_TRANS_ARCHIVE
WHERE CIRC_TRANS_ARCHIVE.ITEM_ID = ITEM.ITEM_ID) as RETURNDATE,

**Comment by cedelis** [comment]
Commit f5b748ecd2c96e155ce60bbc6d8124c66d0db409
[I accidentally referenced Issue #344 instead of #334 (typo) in comments.]

**Comment by cedelis** [comment]
@gibsonjc This was a simply one-liner. It's in PROD. [btw, I commented-out the RETURNDATE column; the inclusion (or omission) of 'AS' does not affect anything.]
