### ISSUE TITLE
Renew box for individual items in Your Checked Out Items not showing on mobile/small size

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#336]
New VuFind is supposed to have responsive design so that the screen scales at any size.  However, when you view Your Checked Out Items on Mobile, the checkbox to renew an individual item is missing.  

You can reproduce this if you slowly shrink a full size browser window:

<img width="771" alt="screen shot 2018-06-12 at 2 40 45 pm" src="https://user-images.githubusercontent.com/17598357/41313128-b1698b80-6e4e-11e8-8ec5-135eb0de1530.png">

As soon as the horizontal size gets small enough (about 767 across, I think), the Search boxes stacks above the list and the right hand navigation menu stacks below the list, but the renew box for each item in the list disappears.  (The "Select Page" box at the top to renew some/all still appears.)

<img width="742" alt="screen shot 2018-06-12 at 2 41 11 pm" src="https://user-images.githubusercontent.com/17598357/41313130-b5e057ac-6e4e-11e8-89ac-e85a5a243a70.png">

Smaller still:

<img width="288" alt="screen shot 2018-06-12 at 2 42 30 pm" src="https://user-images.githubusercontent.com/17598357/41313183-e8123538-6e4e-11e8-98ee-22c4e7d70eae.png">

**Comment by gibsonjc** [comment]
This is a problem on the vufind.org Demo site as well:

![screen shot 2018-06-12 at 2 48 23 pm](https://user-images.githubusercontent.com/17598357/41313506-b8befad6-6e4f-11e8-8a0f-62a6d0ae8096.png)

**Comment by gibsonjc** [comment]
https://vufind.org/jira/browse/VUFIND-1119 says this was fixed on the "Holds" page but it appears to be broken again if you go to the example given for the Demo.  It has the same problem that the Your Checked Out Items page has.

**Comment by gibsonjc** [comment]
When the individual checkboxes disappear, the user's only choice on mobile is to click the "Renew All Items" button, which we know can time out if there are too many items to be renewed, and that causes confusion and trouble.

**Comment by cedelis** [comment]
In TEST

**Comment by dmcmpbll** [comment]
Yes, this looks and functions correctly on TEST on Safari on my cell phone.
I checked both as a Shibboleth patron (with 2 charged items), and as last name/barcode patron (with more than 100 charged items). 

Things remain looking fine on my computer in Chrome, Safari, and Firefox.
Also, it remains that if the patron has > the set number of items, only the "Renew Selected" button shows; if they have < the number, they see both the "Renew Selected" and "Renew All" buttons.

Looks good!

Screenshot from my phone below.
![screenshottestrenewcheckboxes181012](https://user-images.githubusercontent.com/20848151/46890983-1e7b1380-ce2e-11e8-893d-73f1194be840.png)

**Comment by dmcmpbll** [comment]
Oh-I should make sure I checked charged items with a cover image to make sure. One moment.

**Comment by dmcmpbll** [comment]
Nevermind- looks like we don't have cover images show in the Checked Out items list.

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD
