### ISSUE TITLE
Checked Out Item status display hierarchy (was: Recall status missing from Your Checked Out Items screen)

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#337]
UIU- patrons can not see that an item has been recalled in their checked-out items in VuFind 4.1 (like they can in 0.6).

Examples of New VuFind and 0.6 are included in RT100007.

**Comment by gibsonjc** [comment]
This Issue is being broadened to be a comprehensive review of the item status hierarchy information displaying for items on the Checked Out Items page.  (Similar to #172 but for a different page in the system.)

Examples will need to be set up on DEVEL and TEST.  @dmcmpbll will work on this.

**Comment by cedelis** [comment]
In TEST.

**Comment by dmcmpbll** [comment]
This looks good for both local and I-Share items.

I like how the status is now listed for all checked out items, with the 4 statuses that require patron action being set as "alert" statuses.

**Comment by gibsonjc** [comment]
This is a great improvement to the item statuses of checked out items, nice work! Ready for Prod.

**Comment by cedelis** [comment]
In PROD
