### ISSUE TITLE
Change Username and Password Text

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#34]
Request from CARLI staff to change Login text for all libraries:

 from **Username:** to **Library Borrower ID:**
 from **Password:** to **Last Name:**

**Comment by cedelis** [comment]
Change implemented.

**Comment by gibsonjc** [comment]
Could you comment here the location(s) and/or file(s) where this change was made for the historical record?  :)  Thanks!

**Comment by cedelis** [comment]
I referenced this Issue in the git commit (see above).

**Comment by bgant** [comment]
I think this is an example of what Jessica is asking:

https://coderwall.com/p/r21inw/reference-commits-and-issues-in-github

That allows those of us watching Issues to see the code change.

**Comment by cedelis** [comment]
Commit 90629ab9a2afdceb266094155833d8208f9f3379 closes #34
