### ISSUE TITLE
Improve holdings tab display for multiple 856s

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#341]
If multiple 856s in MFHD, New VuFind holdings display data does not match Voyager MFHD 856 data:
Note, all test records are viewable at: https://i-share-test.carli.illinois.edu/vf-npu/Record/NPUdb.201801 and in the attached file.
[856 holdings test records_180621.docx](https://github.com/CARLI/vufind/files/2124428/856.holdings.test.records_180621.docx)

In short, if a MFHD has multiple 856 field in it, each one should display its data individually in the Holdings with to the subfields that each 856 field has.  Currently, the system appears to be displaying incorrectly some 856 field subfields in other 856 fields causing duplicate data to display inappropriately.  Specific examples follow:

A) If multiple MFHD 856s, and first 856 contains $u and $y, any following 856s will display first $y data even though they don’t have $y data in them. The $y data from one 856 field should NOT be repeated for other 856 fields in the same MFHD.  Note holdings test 1.	

Note, if multiple 856s contain $y, the last 856 with $y will continue into other 856s if they lack $y. The $3 data doesn’t display at all when this happens. Note holdings test 5. 

B) If multiple MFHD 856s and the first 856 contains $u and $3, any following 856s will display $3 data even though they don’t have the $3 data in the 856 fields, unless an 856 with a $y is included. In that case, both $y and $z data from the line above display even though $z data was not in the final 856 field. Note holdings test record 2.

C) In VuFind 0.6, if 856s contained $u, $3, $y, the $3 and $y displayed hyperlinked. In holdings test 3, only the $y y1 is displaying without the $3 (2). This is similar to the last 856 in holdings test 4 as well. If 856s contained $u, $3, $y, and $z3 and $z4. In VuFind 0.6 the $3 and $y displayed hyperlinked with the $z displaying as text, but the $3 is not displaying at all (as well as the first $z which is an issue mentioned below). 

D) If 856 contains $u, y1, z1, and z2, only $y1, z2 display. $z1 is skipped. Note MFHD Test 4.

[This is what displayed in 0.6:
• If the 856 contains $u only: the $u will be hyperlinked. 
• If the 856 contains $u and $y: the $y will be hyperlinked. 
• If the 856 contains $u and $z: the $u will be hyperlinked and the $z will display as text. 
• If the 856 contains $u and $3: the $3 will be hyperlinked. 
• If the 856 contains $u, $3 and $y: the $3 and the $y will be hyperlinked, in that order, separated by a space. 
• If the 856 contains $u, $3 and $z: the $3 will be hyperlinked and the $z will display as text. 
• If the 856 contains $u, $y and $z: the $y will be hyperlinked and the $z will display as text. 
• If the 856 contains $u, $3, $y and $z: the $3 and $y will be hyperlinked, in that order, with a space between them, and the $z will display as text. 
• Any 856 $z’s display as plain text after the hyperlink.]

This may be related to closed issue #192

**Comment by nmswanson** [comment]
Ted looked into multiple 856 $z examples and pointed out that Voyager's typical approach to displaying URLs in the OPAC depends on the ELINK_INDEX table. He noticed when looking at UIU's data that sometimes the link_text field picks only the second 856 $z and other times it picks the first $z.

**Comment by gibsonjc** [comment]
@cedelis New priority issue.  New VuFind Holdings tab 856 processing for display needs to be refined to handle a MFHD with multiple 856 fields in it, which likely have different combinations of $u $y $z and $3 subfields.  Can you look into making them smarter?

I think there also may be a fix in here to something that I told you to do wrongly in #192 .  The list of what VuFind 0.6 displays for each subfield combination above is what we want New VuFind to do as well.

There are a lot of details here, so if you need additional explanations or want this spec-ed out differently, let us know and we'll try to help!

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
Holdings tab 856 improvements are Ready for Prod!

**Comment by cedelis** [comment]
In PROD
