### ISSUE TITLE
Consolidate three "Find" buttons on Course Reserve page

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#342]
ISU- Request to consolidate the three “Find” on the [Course Reserve search page](https://i-share.carli.illinois.edu/vf-isu/Search/Reserves) to one, folks found the multiple buttons confusing, especially when choosing items from more than one drop down box

Details:
The Course Reserves page has Find buttons after every dropdown
menu (course, instructor, department). It seems confusing to have
a Find button after every dropdown because it makes the user think
that only one dropdown can be used to search at a time, and I'm not
clear from testing it whether that is the case or not. It would be
great if this Course Reserve page would function the same way as
the current one, with only one Find button and the ability to search
for course and instructor simultaneously in one single search.

4/19/18 email

**Comment by gibsonjc** [comment]
This Issue was made irrelevant by #252 , the new Course Reserves search and display format. Closing.
