### ISSUE TITLE
Alternative terms for Item Status Charged 

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#344]
ISU - prefer the terms "Checked Out" instead of "Charged" for item status represented on the holdings tab. Also, closed ticket [#173](https://github.com/CARLI/vufind/issues/173) changed red “Checked Out” icon to “Not Available”, for consistency should item record page say the same?

Details:
I like that the new VuFind uses colors to help show whether an item
is checked out or not (green = available, red = checked out).
However, it would be really helpful if the new VuFind could be
changed to say "Checked out" like the current VuFind catalog
instead of "Charged," since charged tends to be a library jargon
term that most patrons may not be familiar with.

4/19/18 email

[[Current example from record page](https://i-share.carli.illinois.edu/vf-uiu/Record/UIUdb.8460561) and 
Current example from search results page](https://i-share.carli.illinois.edu/vf-uiu/Search/Results?lookfor=English&type=AllFields&page=2) ]

![screen shot 2018-06-29 at 2 35 02 pm](https://user-images.githubusercontent.com/17598357/42111333-b54b3646-7ba9-11e8-9f60-2d2d057c8165.png)

![screen shot 2018-06-29 at 2 37 08 pm](https://user-images.githubusercontent.com/17598357/42111384-eec53bec-7ba9-11e8-9054-0dc4dee2a338.png)

**Comment by gibsonjc** [comment]
Unfortunately, "Charged" does NOT appear to be in languages/en.ini

**Comment by gibsonjc** [comment]
@cedelis Given your recent work on #172 would it be easy to change the status words displaying "Charged" on the record pages to display as "Checked Out" instead?

Examples on TEST:
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.3910116
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.5436242

**Comment by cedelis** [comment]
In TEST.

**Comment by dmcmpbll** [comment]
I have tested this on i-share-test; it looks good to me!

**Comment by cedelis** [comment]
In PROD.
