### ISSUE TITLE
"Too-fast" requesting leads to PICKUP_LOCATION_ID of zero

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#347]
UIU reported in RT 99951 that they had received a call slip with no Pick Up Location in the request. 

It appears it is possible to click the "Place Request" button in the request screen when the Pick Up Location box is not yet populated with the default/preference in account. When a patron clicks that fast, the request is created with the pick up location as "0" (zero).

![requestwpickuplocnotready](https://user-images.githubusercontent.com/20848151/41874572-e1de78ae-788d-11e8-90da-935887a7ad0e.png)

**Comment by cedelis** [comment]
In TEST.

**Comment by dmcmpbll** [comment]
Yes, this fix worked great.

Checked in Firefox, Chrome, IE, and Safari for a patron with preferences set, and one using the defaults.
In all tests, the Request button did not display until the Pick-Up location field was populated.

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD
