### ISSUE TITLE
Add link if multiple locations / multiple call numbers

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#349]
ISU requests “multiple locations” be a link to Item record [main record display with holdings tab selected], like the “Click for details” is in 0.6 [VF 0.6 links to the similar record display with the location & availability tab selected]. 

[Note, in 0.6 “multiple call numbers” also has the same linking capability to the main record display with holdings information.]

[VuFind 0.6 display](https://vufind.carli.illinois.edu/vf-isu/Search/Home?lookfor=%28OCoLC%29ocm07980056&type=all&start_over=1&submit=Find)
[New VuFind display](https://i-share.carli.illinois.edu/vf-isu/Search/Results?lookfor=%28OCoLC%29ocm07980056&type=AllFields&limit=20&sort=relevance )

ISU would also like the multiple holdings verbiage to be improved: "Click title to display information" message somewhere.

4/19/18 email

**Comment by gibsonjc** [comment]
@cedelis Can we make the multiple locations and multiple call numbers lines that appear on the Results page when there are multiple copies with different information into clickable links to the record's Holdings tab (similar to VuFind 0.6)?

For example:
![screen shot 2018-11-29 at 9 06 13 am](https://user-images.githubusercontent.com/17598357/49230782-0d726b80-f3b6-11e8-9d50-18f60a629e9f.png)

15 would say
**Call Number:** 512.13 V27M
**Located:** Click for details
And the words "Click for details" would be a hotlink to 
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.274066/Holdings#tabnav

17 would say
**Call Number:** Click for details
**Located:** Click for details
And the words "Click for details" would be a hotlink to 
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.510913/Holdings#tabnav

Example search results with several titles having multiple locations:
https://i-share-test.carli.illinois.edu/vf-uiu/Search/Results?lookfor=algebra+modern&type=Title&filter%5B%5D=-institutions%3A%22HAT%22&limit=20&sort=relevance

You can easily change the default text in languages/en.ini to
`Multiple Call Numbers = "Click for details"`
`Multiple Locations = "Click for details"`

------------------------------------------------------

If the above seems too fiddly, please just change the following two lines in languages/en.ini:
`Multiple Call Numbers = "Multiple Call Numbers"`
`Multiple Locations = "Multiple Locations"`
to
`Multiple Call Numbers = "Click title for details"`
`Multiple Locations = "Click title for details"`
and we'll see how that looks.  Thanks!

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
The "Click for details" links appear to be in the correct places and they do make links, but they go to the top of the single record page instead of the Holdings tab where the Call Number and Location info are.

The Holdings tab appears to be accessible if you use the base bib record URL with
**/Holdings#tabnav**
at the end, so
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.274066/Holdings#tabnav

Is it possible to make both "Click for details" links for multiple Call Numbers and/or Locations go directly to the Holdings tab URL?  Thanks!

**Comment by cedelis** [comment]
@gibsonjc I added "/Holdings#tabnav" to the links.

**Comment by gibsonjc** [comment]
Yes, that did it! Ready for Prod!

**Comment by cedelis** [comment]
In PROD
