### ISSUE TITLE
Text message didn't work

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#35]

**Comment by gibsonjc** [comment]
Some people reported earlier (possibly under VuFind2) that the Text feature said "Message Sent" but the message never came through to their phones.

I just tried to text myself with AT&T and received this error (I have blanked out my personal number with pound signs; the error displays my number correctly):

5.1.1 <##########@mms.att.net>: Recipient address rejected: Only carli.illinois.edu e-mails are allowed

**Comment by cedelis** [comment]
commit 2f8d1aba6084589d14cff191a7c12d38a9038b46 closes Issue #35.

**Comment by cedelis** [comment]
commit e13cf3f819df8a4f2befc9a316d73b16c3459d7c was also necessary for Issue #35

**Comment by gibsonjc** [comment]
Can you change the From address to be noreply@carli.illinois.edu instead of support@carli?  noreply is what text messages from 0.6 currently come from so it seems like we should be consistent!  Thanks!

**Comment by cedelis** [comment]
commit aba421d2797fab4061ef8777b77409d9986199aa made to change from (reply-to) address to noreply@carli.illinois.edu
