### ISSUE TITLE
I-Share catalog view /all/vf/ shouldn't have "Local Catalog Only" option

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#350]
The I-Share catalog view at https://i-share.carli.illinois.edu/all/vf/ presents the two options after the search box for "All I-Share Libraries" and "Local Catalog Only".  RT 100111  Doing a search and choosing "Local Catalog Only" provides results in I-Share only, and switches the drop-down to say "All I-Share Libraries" on the results page, so a user is getting the correct results, but it may be confusing and the "Local Catalog Only" choice probably shouldn't be there in the first place.

Can we remove the option for "Local Catalog Only" if a user is in the /all/vf/ view?  Or suppress the appearance of this choice box altogether in /all/vf/ like VuFind 0.6 does?

**Comment by eschell** [comment]
I think I have it please take a look

https://vufind4-mockup.carli.illinois.edu/vf-eiu/ <- local dropdown yes

https://vufind4-mockup.carli.illinois.edu/all/vf-eiu/ <- local dropdown yes

https://vufind4-mockup.carli.illinois.edu/all/vf/ <- local dropdown no

Is this what you're looking for?

**Comment by gibsonjc** [comment]
@eschell Yes, this is behaving as we want it to!

**Comment by eschell** [comment]
This has been moved to production.
