### ISSUE TITLE
Modify holdings tab display - 866 and 853/863 pairs

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#355]
SIC requests New VuFind holdings display of 853/863 exclude 863’s with a second indicator of 2 like the logic in VuFind 0.6: [https://www.carli.illinois.edu/products-services/i-share/opac/vf-hldg-cfg](https://www.carli.illinois.edu/products-services/i-share/opac/vf-hldg-cfg). 

SIC has included 866 summaries in a holdings level above 853/863 pairs in MFHDs, and only wants the 866s to display in the OPAC. In VuFind 0.6 this was possible by coding 863’s with a second indicator of 2. Only 863 second indicators of _, 0, or 1 were included in the display configuration in VuFind 0.6, so these 863 42's representing individual volumes were hidden from OPAC display.

In New VuFind, 866 summaries are currently displaying at the very end of the 863 individual volumes list.

New VuFind Example:
American mathematical monthly
[https://i-share.carli.illinois.edu/vf-sic/Record/SICdb.1139538](https://i-share.carli.illinois.edu/vf-sic/Record/SICdb.1139538)
holding 1374824
bib 1139538

VuFind 0.6 example:
[https://vufind.carli.illinois.edu/vf-sic/Record/sic_1139538](https://vufind.carli.illinois.edu/vf-sic/Record/sic_1139538)

RT100364

**Comment by gibsonjc** [comment]
MFHD 863 enumeration data display in the Volume Holdings area without their corresponding 853 caption data.

NIU - RT 104375

**Comment by cedelis** [comment]
@gibsonjc Just an FYI, VuFind currently handles this in a very crude fashion. It simply pulls maps fields and subfields that you supply. I.e., It does not do processing whatsoever regarding "pairs". E.g., here's what we have defined today:

; Fields to include in notes. Default is "852z".
notes = "845a:852az" ; CARLI
; Fields to include in summary. Default is "866a".
summary = "863abiz:866az" ; CARLI
; Fields to include in supplements. Default is none.
supplements = "867az" ; CARLI
; Fields to include in indexes. Default is none.
indexes = "868az" ; CARLI

This would require implementing our own handler from scratch. Or, more likely, translating the VuFind 0.6 code (in Perl) into New VuFind code (in PHP).

**Comment by gibsonjc** [comment]
@cedelis As promised at our meeting today, here are some examples of MFHDs with "standard-ish" 853/863 pairs:

https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.39530 - MFHD IDs 5225244 and 5225236 and 8155868 and 8706304 and 8029317 
https://i-share-test.carli.illinois.edu/vf-niu/Record/NIUdb.247589 - MFHD ID 283662
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.3505294 - MFHD ID 4459684
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.523864 - MFHD IDs 679794 and 2302536
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.535092- MFHD ID 693563

**Comment by cedelis** [comment]
@gibsonjc , I have translated 0.6 code into the new VuFind. Things look better for some cases, e.g., https://i-share-test.carli.illinois.edu/vf-sic/Record/SICdb.1139538

However, for others, it seems we need to suppress more of the 866az fields, because there are still lots of ugly data showing (e.g., https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.39530 ). BTW, I'm currently only suppressing 866az fields if the second indicator is either 2 or 3. Do I need to filter out more? (Or should I, instead of filtering *out* ind2 = 2 or 3, should I only *keep* certain valid values of ind2, e.g., ind2 = _, 0, or 1?)

**Comment by cedelis** [comment]
@gibsonjc FYI, for fun, I decided to *keep* 866az iff ind2 = _, 0, or 1, but it made no difference to bib https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.39530

**Comment by cedelis** [comment]
@gibsonjc Never mind my previous questions (for now). Apparently, I need to fix some of the new code since the 0.6 code seems to display much better https://vufind-test.carli.illinois.edu/vf-uiu/Record/uiu_39530

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Changes include:
- caption data now appears with enumeration data
- 863 second indicator of 2 or 3 now suppresses field from display
- MFHD notes fields that we had in 0.6 display with custom labels (506, 538, 541, 561, 562, 563, 583, 843, 845), see also Issue #193 
- separated the 866s displays from the 853/863s displays with labels “Library Has (Summary)” vs. “Library Has (Volumes)”
- Indexes 867 and 854/864 and Supplements 868 and 855/865 display with their own labels as well

**Comment by gibsonjc** [comment]
This all looks great. Ready for Prod!

Added today:
- Logic added so that MFHD 541 first indicator 1 is the only one that displays.
- 863$z notes now displaying
- 852$z notes fixed

**Comment by cedelis** [comment]
In PROD
