### ISSUE TITLE
Remove color of former "Live Status Unavailable" gray box on results page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#357]
In #161 we decided to remove the wording from the "Live Status Unavailable" box on the results page because it was confusing and didn't add any value.  However, that will leave us with a small, gray box (see example in 11 and 12 in screenshot below).  Can we remove the color from that box or hide it?

![screen shot 2018-07-03 at 9 24 49 am](https://user-images.githubusercontent.com/17598357/42592281-a600d09c-850e-11e8-8a48-b65667fb20ee.png)

The CSS that controls that gray color appears to be:
  < span class="status">
  < span class="label label-default">< /span>
  < /span>
  
  .label-default {
              background-color: #777;
  }

**Comment by eschell** [comment]
Added to /themes/carli/css/carli.css

/* 'Live Status Unavailable' box was removed so the box behind it needed to be removed */
.status .label-default { 
  background-color: transparent;
}

Will move to test prior to production.

**Comment by eschell** [comment]
This change has been moved to production.
