### ISSUE TITLE
Emailing a record does not work

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#36]
When I click on the "Email this" link at the top of any record and enter my address in the To: line, my address in the From: line, and some Message text and click Send, I receive this error:

5.1.1 <oram@uillinois.edu>: Recipient address rejected: Only carli.illinois.edu e-mails are allowed

**Comment by gibsonjc** [comment]
Same error occurs when attempting to email a search.

**Comment by cedelis** [comment]
commit 2f8d1aba6084589d14cff191a7c12d38a9038b46 closes Issue #36

**Comment by gibsonjc** [comment]
I confirm that this works, I just emailed a record to myself with "Email this".
