### ISSUE TITLE
Update Syndetics subscriptions for FY19

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#360]
Some libraries dropped.
Some libraries added.
In the spreadsheet, note that Harper College is now under H in FY19 where previously in FY18 it was William Rainey Harper College under W.

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
I checked some that added and some that deleted and all seems well.  Ready for Prod.

**Comment by cedelis** [comment]
In PROD.
