### ISSUE TITLE
AAA "On Hold" and "In Transit-On Hold" requested items able to be canceled by patron

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#362]
UIU- RT 100504

New VuFind is allowing local call slips [AAA] to be cancelled after the call slip request has been filled (so the item is either in an "In Transit-On Hold" or an "On Hold" status). This is an undesirable change in behavior. 

New VuFind should not allow requested items with a status of "In Transit-On Hold", or "On Hold" to be canceled by the patron from the Requested Items tab.

(New VuFind is correctly preventing UB requests in an "In Transit-On Hold" or "On Hold" status from being canceled [ABB, ABA, ABC, and AAB].)

**Comment by cedelis** [comment]
@dmcmpbll or @gibsonjc  Can you set up scenarios in DEVEL? Thanks!

**Comment by dmcmpbll** [comment]
I have sent @cedelis some examples via email.

**Comment by cedelis** [comment]
In TEST.

**Comment by dmcmpbll** [comment]
Yes- your fix appeared to appropriately limit which requests I could cancel. Yay!

Thoughts on removing the "Cancel All Requests" button and leaving only the "Cancel Selected Requests" button?

I note that the "Cancel All Requests" button did function properly in that it correctly did NOT allow me to cancel the "AAA On Hold" or "AAA In Transit On Hold" items in my list, but I am not sure the button is needed since its wording is now inaccurate (by design- since we don't want all types of requests to be cancelable).

**Comment by gibsonjc** [comment]
@cedelis Yes, please remove the "Cancel All Requests" button completely.  Thanks!

**Comment by cedelis** [comment]
'Cancel All Requests' button has been removed (in TEST).

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD
