### ISSUE TITLE
Media subtitles (546) and region information

### ISSUE THREAD

**Issue by CorinneStevens** [CARLI/vufind#371]
Example: https://i-share.carli.illinois.edu/vf-lfc/Record/LFCdb.484445

- This DVD has German and English audio, and English and Spanish subtitles (see field 546).
- It is also a Region 1 DVD (see field 538).

Even in the "description" tab, the language doesn't display.

Contrast this with the old vufind's "more details" display:
https://vufind.carli.illinois.edu/vf-lfc/Record/lfc_484445/Description

Any chance of adding the language info to the first display page, or at least to the "description" display?  Region information would be great to have on the first display page as well, but is less essential in our opinion, and it does appear in the "description" view.
thanks!

**Comment by gibsonjc** [comment]
Field 546 was added to the Description Tab display in Phase 1 of #265  on Jan. 11, 2019.  
Field 538 already displayed on the Description Tab.  
Languages from 041 already displayed in the Core section of the single record.  
We do not have plans to move either 546 or 538 to the Core section of the single record display. 
Closing this Issue.
