### ISSUE TITLE
If Single Sign-On patron logs in before requesting, patron is not automatiaclly prompted to profile account with Voyager credentials

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#372]
This workflow does not result in the SSO patron being prompted to profile their New VuFind account with their Voyager credentials:
1) Patron logs into their to their account (New VuFind forwards to SSO for authentication); patron is then on basic favorites screen.
2) Patron searches for item.
3) Patron clicks "check to see if item is requestable" link, or the "Request Item" or "Request from I-Share Libraries" buttons.
4) Patron is not automatically prompted to profile their account with their Voyager credentials, so New VuFind does not know the patron's permissions. Patron is told that "item cannot be requested."

ROU - RT 101658

**Comment by gibsonjc** [comment]
In contrast, here are two workflows found that do correctly result in the SSO patron being prompted to profile with their barcode:

Workflow 1:
1) Patron searches for item.
2) Patron clicks "check to see if item is requestable" link, or the "Request Item" or "Request from I-Share Libraries" buttons.
3) Patron is prompted to login.
4) Patron is next prompted to profile their account with their Voyager information.

Workflow 2:
1) Patron logs into their to their account.
2) Patron chooses to view any of their account-related information, such as the "Checked Out Items", "Requested Items", "Fines", or "Profile" information.
3) Patron is next prompted to profile their account with their Voyager information.
4) Patron can then search for and request material.

**Comment by cedelis** [comment]
In TEST.

commit 16fdf7bbb5c9bcc637f2c19a4525824c1f968967

**Comment by gibsonjc** [comment]
Testing shows this loophole has been fixed. Ready for Prod!

**Comment by cedelis** [comment]
In PROD.
