### ISSUE TITLE
Internet Explorer (IE) does not finish checking for requestability process

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#373]
BRA - I tried requesting items through VuFind yesterday and this morning & it still got stuck on the "checking". I refreshed the page & it still got stuck. I was using Internet Explorer. I moved over to Chrome to request the item and got an immediate response when I asked to check availability. Before the update, I was able to request items through VuFind from Internet Explorer.

RT 101616

**Comment by cedelis** [comment]
I performed the following one-liner hotfixes (in devel/test/prod):

replace 
    startsWith() 
with
     indexOf()==0

for IE compatibility 


$ git show 54e24ea34855719af1d954df71a63906cbadf807
commit 54e24ea34855719af1d954df71a63906cbadf807
Author: Chris Delis (CARLI) <cedelis@uillinois.edu>
Date:   Wed Aug 29 10:33:22 2018 -0500

    IE Bug: change startsWith() to indexOf() for IE-compatibility

diff --git a/themes/carli/js/carli.js b/themes/carli/js/carli.js
index 4b3a28e..d899a3c 100644
--- a/themes/carli/js/carli.js
+++ b/themes/carli/js/carli.js
@@ -68,7 +68,7 @@ function carli_checkRequestIsValid(element, requestType) {
   var vars = deparam(href);
   vars.id = recordId;

-  if (recordId.startsWith(patronHomeLibrary + '.')) {
+  if (recordId.indexOf(patronHomeLibrary + '.') == 0) { // IE
     requestType = 'StorageRetrievalRequest';
   }
   //console.log('carli_checkRequestIsValid requestType = ' + requestType);
diff --git a/themes/carli/js/check_requestable.js b/themes/carli/js/check_requestable.js
index c128396..6279082 100644
--- a/themes/carli/js/check_requestable.js
+++ b/themes/carli/js/check_requestable.js
@@ -103,7 +103,7 @@ function runCheckRequestableItemAjaxForQueue() {
   vars.id = id;

   var requestType = 'ILLRequest';
-  if (id.startsWith(patronHomeLibrary + '.')) {
+  if (id.indexOf(patronHomeLibrary + '.') == 0) { // IE
     requestType = 'StorageRetrievalRequest';
   }
