### ISSUE TITLE
Local or I-Share catalog dropdown choice box doesn't work in Safari

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#374]
In Safari 11.1.2 on Mac OS Sierra 10.12.6:
If you are in a local catalog /vf-xyz/ and enter a search term in the box and choose "All I-Share Libraries" and click Find, the search should run in the /all/vf-xyz/ view.  It does not, it remains in the /vf-xyz/ view.  Opposite behavior is true if you are in I-Share and want to run a new search in local.

Replication steps:

1. Start in any local catalog /vf-xyz/
2. input search term(s)
3. change catalog selection box to "All I-Share Libraries"
4. Click Find - search is done in local catalog only

OR

1. Start in any I-Share view /all/vf-xyz/
2. input search term(s)
3. change catalog selection box to the local catalog xyz
4. Click Find - search is done in I-Share catalog instead of local

**Comment by cedelis** [comment]
Unfortunately, I was unable to reproduce this issue using Safari 11.1.2 on Mac OS Sierra 10.12.6 (which is the OS and web browser I happen to have installed on my MacBook).

For whoever currently experiences this issue, it would be interesting to see if there are any Javascript errors. To see the Javascript console, you can select the "Develop" menu in Safari, then select "Show JavaScript Console"

For the record, I started in UIU's local catalog, and searched for "dog":

https://i-share.carli.illinois.edu/vf-uiu/Search/Results?lookfor=dog&type=AllFields&limit=20&sort=relevance

then changed the "Local Catalog Only" option to "All I-Share Libraries" before finally clicking on "Find," which resulted in the following catalog correctly:

https://i-share.carli.illinois.edu/all/vf-uiu/Search/Results?lookfor=dog&type=AllFields&limit=20&sort=relevance

**Comment by gibsonjc** [comment]
Ah ha, unbeknownst to me, JavaScript was disabled in my Safari browser. Once I enabled JavaScript, the catalog choice box worked as expected.  Good to know.  I saw no warnings or errors or notifications about it being disabled or being required by the New VuFind catalog from the browser or when using the Console.  I'll close this, thanks
