### ISSUE TITLE
In IE only, Request Item pop-up box not displaying from "Request This Item" links

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#375]
In Internet Explorer, the Request Item pop-up box is not displaying from the "Request This Item" link on the individual items.  (It does properly display when using the Request buttons in local and I-Share.) 

Replication steps:
1.	Go to https://i-share.carli.illinois.edu/all/vf/
2.	Log in 
3.	Look up an item - for example, https://i-share.carli.illinois.edu/all/vf-uiu/Record/349654193 
4.	Click on “ Check if item can be requested…” and find one that is requestable
5.	Click on “Request this item” 
6.	Click on that and wait
7.	Nothing happens.

In contrast: If you click on “Request from I-Share libraries” button, processes normally and requests.

RT 101497

Testing has also found that if you right-click the "Request This Item" link it will open in a new tab/window and work.

**Comment by cedelis** [comment]
In PROD. Hotfix commit 941d2aaddf7b20ecb7d5529210f71cfb4ef45874
