### ISSUE TITLE
Saved Items from the I-Share union catalog are not hotlinked/capitalized in the list in local catalog view

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#378]
Items saved from a user's local catalog appear hotlinked in their Saved Items lists in the local catalog view and the I-Share union catalog view.

Items saved from the I-Share union catalog only appear hotlinked in their Saved Items list in the I-Share catalog.  When in the local catalog view, the title of such items appears in all lowercase and not hotlinked.

Local view (first and fourth items were saved from I-Share catalog):
![screen shot 2018-08-31 at 8 10 22 am](https://user-images.githubusercontent.com/17598357/44914296-6e29d380-acf5-11e8-956f-ccf695919aed.png)
I-Share view:
![screen shot 2018-08-31 at 8 10 35 am](https://user-images.githubusercontent.com/17598357/44914300-71bd5a80-acf5-11e8-9c96-8a48ce219046.png)

Preferred behavior:
Wherever the data are displaying, they should be consistently presented and hotlinked. 

One solution may be the one that is currently employed in the VuFind 0.6 catalog, where local and I-Share favorites are only seen in their respective views.

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
All items in Saved Items lists will now click through to the appropriate bib record.  The catalog view (header/branding) will remain the same as the catalog the user was in when he/she clicked.

Ready for Prod

**Comment by cedelis** [comment]
In PROD
