### ISSUE TITLE
Cite/Text/Email/Export/Save options do not appear under MFHDs without call numbers

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#379]
These options are not displaying when the MFHD doesn't have a call number in it.
![screen shot 2018-08-31 at 1 51 52 pm](https://user-images.githubusercontent.com/17598357/44930785-0c815d80-ad25-11e8-8e80-f3e45821bf15.png)

Expected result:
These options should display beneath each MFHD in local catalogs and the I-Share union catalog whether or not there is a call number in it.  The link created by these options refers to a BIB ID, it shouldn't matter if there is call number.

Examples where it is not displaying:
https://i-share.carli.illinois.edu/vf-grn/Record/GRNdb.290089
https://i-share.carli.illinois.edu/all/vf-uiu/Search/Results?lookfor=(OCoLC)876854108&type=oclc_num&limit=20&sort=relevance
Any CARLI eBook - https://i-share.carli.illinois.edu/vf-uiu/Search/Results?lookfor=&type=AllFields&filter%5B%5D=institutions%3A%22EBL%22&limit=20&sort=relevance
Any OTL item - https://i-share.carli.illinois.edu/all/vf-uiu/Search/Results?lookfor=&type=AllFields&filter%5B%5D=institutions%3A%22OTL%22&limit=20&sort=relevance 

Proof it is likely occurring of the missing call number: I added a call number to this same GRN record on TEST and the options now display:
https://i-share-test.carli.illinois.edu/vf-grn/Record/GRNdb.290089

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Current fix creates a Call Number: line with N/A
![screen shot 2018-10-15 at 12 59 57 pm](https://user-images.githubusercontent.com/17598357/46968982-51b1e280-d07a-11e8-8f7a-9bc312c32969.png)

**Comment by cedelis** [comment]
@gibsonjc The "N/A" was added by me. It was an easy way to "solve" this issue. If this is not acceptable, then I will go back to the drawing board :)

**Comment by cedelis** [comment]
@gibsonjc I added code that checks for and ignores these dummy (N/A) call numbers. They should no longer show up.

**Comment by gibsonjc** [comment]
The options are now displaying as expected on MFHDs w/o call numbers, and no Call Number line is displaying.  Ready for Prod.

**Comment by cedelis** [comment]
In PROD
