### ISSUE TITLE
Add note to New Items page that 1000 items are retrieved

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#380]
Please add a note to the text of the New Items page for every library
https://i-share.carli.illinois.edu/vf-___/Search/NewItem

Put this new text after the existing text "Select a range, then click the Find button." :

Select a range, then click the Find button.  If more than 1000 new items are found, only the most recent 1000 new items will be displayed.

**Comment by eschell** [comment]
Is this what you're looking for?

https://vufind4-mockup.carli.illinois.edu/vf-uiu/Search/NewItem

**Comment by gibsonjc** [comment]
> Is this what you're looking for?
> https://vufind4-mockup.carli.illinois.edu/vf-uiu/Search/NewItem

@eschell Yes, that's great, thank you!

**Comment by cedelis** [comment]
In PROD.
