### ISSUE TITLE
Default title sort for Reserves Searches

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#381]
KNX- I noticed that in the new VuFind the results lists for a Reserves Course 
search, the Reserves Instructor search, and Reserves Department search does not present the results in 
alphabetical order. It is very much preferable, IMO, to have the results 
lists in alpa-by-title order as in the old VuFind. The default sort order 
of 'relevance' really doesn't make a whole lot of sense in the case of a 
reserves results list. See screenshots below: 

New VuFind:
![image](https://user-images.githubusercontent.com/30537243/45320406-2c283b00-b508-11e8-92c8-26c53682b997.png)

VuFind 0.6:
![image](https://user-images.githubusercontent.com/30537243/45320420-35b1a300-b508-11e8-915c-b5904780e9ab.png)

RT101928

**Comment by gibsonjc** [comment]
@cedelis The default sort order for results from the Course Reserves search is Relevance.  We want this to be Title.

In ...vufind/config/vufind/**reserves.ini**, can we try to change

[General]
default_sort = relevance

to 

default_sort = sort_title

and see if that will sort the Course Reserves results (only) by Title instead?

**Comment by gibsonjc** [comment]
@cedelis Correction! I think In ...vufind/config/vufind/reserves.ini we want

[General]
default_sort = relevance

to

default_sort = title

; Values on the **left of the equal sign** are either the reserved term "relevance"
; or the **name of a Solr index to use for sorting**; asc and desc modifiers may be
; used in combination with index names, but not relevance.  To allow secondary
; sorting, you may include a comma-separated list of options (for example,
; "year desc,title asc"), but this list may NOT include the special "relevance"
; value.  Values on the right of the equal sign are text that will be run
; through the translation module and displayed on screen.

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
This title sort is working as expected on TEST. Ready for Prod.

**Comment by cedelis** [comment]
In PROD.
