### ISSUE TITLE
HAT, EBL, and OTL holdings do not have Library name so holdings look like they are for other libraries

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#384]
HAT, EBL, and OTL holdings in RESdb do not have Library name line above them--only the Location line--so these holdings tend to blend in with other Library holdings and make it look like they belong to the library listed above them.  Examples:

(On Prod) https://i-share.carli.illinois.edu/all/vf-uiu/Search/Results?lookfor=cat&type=AllFields&filter%5B%5D=institutions%3A%22OTL%22
![screen shot 2018-10-03 at 8 57 36 am](https://user-images.githubusercontent.com/17598357/46415229-6f7e5f80-c6ea-11e8-9411-abb8a2784f22.png)

(On Test) https://i-share-test.carli.illinois.edu/all/vf-uiu/Search/Results?lookfor=+This+is+not+a+firedrill+%3A+crisis+intervention+and+prevention+on+college+campuses&type=AllFields&filter%5B%5D=institutions%3A%22EBL%22&limit=20&sort=relevance
![screen shot 2018-10-03 at 8 59 48 am](https://user-images.githubusercontent.com/17598357/46415360-b9674580-c6ea-11e8-8618-e1c79c1d4a8e.png)

Can we assign different "Library" names to each of these three sets of records (HAT, EBL, and OTL) to display above the Location: line?

If we cannot assign three different "Library" names, can we assign one "Library" name to everything coming from RESdb?

**Comment by cedelis** [comment]
@gibsonjc We can assign them any value we wish. For now, on TEST, I set the "Library" name to be the same as its location for HAT/EBL/OTL.

**Comment by cedelis** [comment]
In TEST (for real this time)

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD
