### ISSUE TITLE
Can HAT, EBL, and OTL e-book holdings be prioritized at the top in the I-Share union catalog?

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#385]
In the I-Share union catalog, a user's local library affiliation causes holdings from their local library to be at the top of the holdings display list, and then the remaining holdings are listed in a random order.  Could HAT, EBL, and OTL holdings also be given priority to float to the top of a list of holdings?  A user's local library should be first in the holdings list, if present, then HAT/EBL/OTL holdings beneath that, if present, then the remaining holdings from other libraries randomized as they are now.

**Comment by cedelis** [comment]
@gibsonjc Yes, that is possible.

**Comment by cedelis** [comment]
In TEST.

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD

**Comment by cedelis** [comment]
In TEST (again).

**Comment by cedelis** [comment]
In PROD.
