### ISSUE TITLE
Unfilled call slips that are not yet promoted or archived should not present the "cancel" checkbox option

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#388]
In Voyager, when a call slip has been unfilled by the library whose database it currently sits in, there is a period of limbo between when the call slip is unfilled by library staff/expires, and when the call slip is either promoted on to the next I-Share library by Circjob 32, or, if the call slip is unable to be promoted--until the request is archived in Voyager.

In VuFind 0.6, requests in this state do not present the "cancel" checkbox.

![requestwaitingtopromoteorexpire-vufind06](https://user-images.githubusercontent.com/20848151/46636073-4d3a7680-cb1c-11e8-83d3-7e242bc6dfe5.PNG)

In New VuFind, requests in this state do present the "cancel" checkbox, and give the error message: "Your request was not canceled. Please contact the circulation desk for further assistance. Request does not exist."

![requestwaitingtopromoteorexpire-newvufind](https://user-images.githubusercontent.com/20848151/46636083-54618480-cb1c-11e8-800f-ebb96965cecf.PNG)

Ideally, New VuFind should not offer the "cancel" checkboxes, since Voyager will not allow the requests in this limbo state to be canceled. 
If the "cancel" checkboxes are unable to prevent from showing in this scenario, an alternative could be for the error wording to be adjusted to be more accurate.

**Comment by dmcmpbll** [comment]
@cedelis I have some examples for this scenario set up on test and devel as a part of https://github.com/CARLI/vufind/issues/277; you can let me know when you're ready for me to send the specific details along for testing.

**Comment by cedelis** [comment]
In PROD
