### ISSUE TITLE
Google Analytics in New VuFind

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#389]
We currently allow libraries to embed Google Analytics in VuFind 0.6 (header or footer?)  Can we also enable this to be done in New VuFind?

**Comment by eschell** [comment]
This is something we can do yes. If you want to assign this to me, please
do.

**Comment by gibsonjc** [comment]
There was a decision in 2014 by the CARLI Board that Google Analytics may not be run in Voyager search interfaces. Closing.
