### ISSUE TITLE
User is not returned to the page they were on after logging in

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#392]
SIC - There are a few scenarios when in Vufind 4 we are unable to use the browser's back button after logging into shibboleth. Is there any way that when the user goes through Shibboleth, the VuFind session is not broken up by VuFind authentication? The VuFind authentication results in the user having only one browser tab with the account info and no way to get back to the search results.

Here are a few cases:

1. User runs a search,
2. search results are displayed
3. User realizes they are not logged in so they cannot request an item,
4. User clicks on "log in with your network ID" in upper right,
5. user logs in with network ID at which point s/he is taken to their Vufind 4 account
6. If the user wants to get back to the original search and request an item or just examine the results again, it is impossible.
7. Hitting the browser's back button results in the error above. This is a complete dead end.
8. User has to restart a completely new catalog session.

A little modification of the steps above results in a different outcome
but brings up another problem. If the user opted to look at a record and
then decided to take an action, for example request the item, the
browser, at least on campus would have automatically logged them in when
they clicked on "request item" for the first time. The request item
button in essence functions as the shibboleth log in button. The request
would not have been processed though until the user clicked on the
Request item button the second time.  This is problematic as
the user may not have realized that the first "request item" click did
not process the request, and that they need to click on that button the
second time for the process to start and to get the pop up window where
they can confirm pick up location and click on submit.

We also link from EBSCO Discovery to VuFind 4 and are having issue
related to the same session break up leaving users unable to request
items without starting a new VuFind 4 session or running a new search.

RT 102679

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Login improvements and fixes to return users to the page they came from ready for prod!

**Comment by cedelis** [comment]
In PROD
