### ISSUE TITLE
Sorting on Requested Items Tab

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/vufind#393]
Currently the default sort for the Requested Items tab seems to be a combination of request scenario (whether it's an AAA, AAB, ABB, ABA, or ABC), and request status. 
(Let me know if you'd like me to list that specific list-order I'm seeing).

Is it possible to set the the default sort to request status then item title, and/or to allow patrons to apply a sort?

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Request Items Tab improvements Ready for Prod

**Comment by cedelis** [comment]
In PROD
