### ISSUE TITLE
MFHD 856 data should display once per holdings record, not per Item

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#395]
When a MFHD has an 856 field (or multiple 856 fields), each 856 field is displaying in the Holdings tab once for every Item.  This unnecessarily repeats the same data.

We'd like for any MFHD 856 data to display once per MFHD, preferably above any/all Items like 852$z (Notes:) and 866 or 853/863 data (Volume Holdings:) do.

Examples:
https://i-share-devel.carli.illinois.edu/vf-npu/Record/NPUdb.201801 - "TEST RECORD 6" and "TEST 7" and "TEST 8"
https://i-share-test.carli.illinois.edu/vf-npu/Record/NPUdb.201801 - "TEST RECORD 6"
https://i-share.carli.illinois.edu/vf-alp/Record/ALPdb.20422

![screen shot 2018-12-14 at 11 58 37 am](https://user-images.githubusercontent.com/17598357/50019247-a77e0a80-ff97-11e8-9fa9-aee3df4f42c1.png)

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
This has corrected the problem and does not seem to have caused any other problems.  The MFHD URLs are only displaying once per MFHD now.  Ready for Prod

Examples:
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.490799
https://i-share-test.carli.illinois.edu/vf-alp/Record/ALPdb.20422
https://i-share-test.carli.illinois.edu/vf-alp/Record/ALPdb.63187
https://i-share-test.carli.illinois.edu/vf-alp/Record/ALPdb.82660

**Comment by cedelis** [comment]
In PROD
