### ISSUE TITLE
Convert tags to Saved Items List

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#396]
If tags are applied by a particular user, are they associated with that user in the database, and can we programmatically "convert" a set of records with the same tag into a List that belongs to that user?

**Comment by gibsonjc** [comment]
This script exists on DEVEL and is waiting for more testing.

**Comment by gibsonjc** [comment]
@cedelis Debbie and I have set up our tags on DEVEL and are ready for you to run the script again to see how they convert to lists at your convenience.

**Comment by cedelis** [comment]
@gibsonjc I ran the script on DEVEL.

**Comment by gibsonjc** [comment]
@dmcmpbll tags-to-lists on DEVEL is ready for testing (sorry I forgot to "at" you on my earlier comment)

**Comment by gibsonjc** [comment]
Testing completed on DEVEL. It went well.
Currently awaiting feedback from selected users and committees.

To Do:
- look for configuration file on/off
- decide on automatically generated text
- decide if this is a "go" and if so, when

**Comment by gibsonjc** [comment]
If/when we turn off tags we'll need to adjust the following settings:

In config.ini

Line 1226-1228
```
[Browse]
result_limit    = 100
tag = true ; allow browsing of Tags
```
Line 1546-1566
```
; Tags may be "enabled" or "disabled" (default = "enabled")
; When disabling tags, don't forget to also turn off tag search in searches.ini.
tags = enabled
```

In searches.ini
Line 106-125

```
; This section shows which search types will display in the basic search box at
; the top of most pages.  The name of each setting below corresponds with a
; search handler (either DisMax or from conf/searchspecs.yaml).  The value of
; each setting is the text to display on screen.  All on-screen text will be run
; through the translator, so be sure to update language files if necessary.  The
; order of these settings will be maintained in the drop-down list in the UI.
;
; Note: The search type of "tag" is a special case that gets handled differently
;       because tags are not stored in the same index as everything else.  Treat
;       this as a reserved word if you create your own custom search handlers.
[Basic_Searches]
AllFields           = "All Fields"
Title               = Title
;JournalTitle        = "Journal Title"
Author              = Author
Subject             = Subject
CallNumber          = "Call Number"
ISN                 = "ISBN/ISSN"
;Coordinate        = Coordinates
tag = Tag
```

**Comment by gibsonjc** [comment]
At our 5/9 meeting we decided that given the short life of New VuFind, the work necessary to turn off tags now is not worth the payoff.  I will close this Issue.
