### ISSUE TITLE
Display MFHD 852$t copy number when no Items attached

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#397]
In Issues #169 and #299 , we adjusted New VuFind defaults so that it would display the copy number from the MFHD 852$t.  However, the copy number information only displays when there are Items attached.  Some I-Share libraries do not create Items for their non-circulating serials, but they would still like to see the Copy number information displaying to the user.

Can we display the 852$t copy number from the MFHD as a separate line in the Holdings data? This line would ideally display after the Call Number line but before any Notes or Volume Holdings, like so:

**Location:** NIU--Spec Coll Oversze--4th FL--Founders --Non-Circulating  _(852$b)_
**Call Number:** AP3 .S774 _(852 $khim)_
**Copy:** 1  _(852$t)_
**Notes:** Edward T. LeBlanc Collection; Flat oversize. _(852$z)_
**Volume Holdings:** v.25 no.24 _(853/863 and 86X)_

Examples of MFHD with 852$t but no Items:
https://i-share-test.carli.illinois.edu/vf-niu/Record/NIUdb.856822
https://i-share-test.carli.illinois.edu/vf-niu/Record/NIUdb.857721
https://i-share-test.carli.illinois.edu/vf-niu/Record/NIUdb.868570

NIU - RT 103104

**Comment by gibsonjc** [comment]
This needs research to know if it is possible or a good/bad idea.  Note that some MFHDs will not have an 852$t at all because in the past they've been omitted and previous OPACs have displayed a Copy 1 if no 852$t was present.

**Comment by cedelis** [comment]
In TEST

**Comment by cedelis** [comment]
@gibsonjc I was not able to place this in the ideal location, however.

**Comment by gibsonjc** [comment]
This looks much better, ready for Prod!

**Comment by cedelis** [comment]
In PROD
