### ISSUE TITLE
Add new Technical Specifications field to Description Tab

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#398]
This is to add a new field to the Description tab in CARLI's RecordDataFormatterFactory.php similar to the "Description of Work" field (SolrMarc.php function getDescriptionOfWork):

M5. New suggested function name: getTechnicalSpecifications

Field Label: Technical Specifications

Fields [Indicators] [Subfields] to display:

344 [any indicators] ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
345 [any indicators] ['a', 'b', '3']
346 [any indicators] ['a', 'b', '3']
347 [any indicators] ['a', 'b', 'c', 'd', 'e', 'f']
348 [any indicators] ['a', 'b', '3']

Placement of new $spec line: after Scale

Part of Phase 2 #265

**Comment by gibsonjc** [comment]
Example records on Test/Devel:

344 - https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451171#description
345 - https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451176#description
346 - https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451176#description
347 - https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451171#description
348 - ?

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
@cedelis Thanks, your part looks good!  We have three changes to make to my specification:

1. I have improperly conflated too many fields together here. Please remove 347 and 348 from getTechnicalSpecifications, leaving 344, 345, and 346 only.  (347 will be addressed below; 348 will be addressed at another time in another way.)


2. We'd like to change the Field Label: Technical Specifications to
A/V Characteristics
instead.


3. We need a new field set up just for 347 because it really doesn't belong with the others:

S10. New suggested function name: getDigitalCharacteristics
Field Label: Digital Characteristics
Field [Indicators] [Subfields] to display:
347 [any indicators] ['a', 'b', 'c', 'd', 'e', 'f']
Placement of new $spec line: after A/V Characteristic (name changed above!)

    /**
     * Get an array of digital characteristics information.
     *
     * @return array
     */
    public function getDigitalCharacteristics()
    {
        return $this->getFieldArray('347', ['a', 'b', 'c', 'd', 'e', 'f']);
    }

**Comment by cedelis** [comment]
@gibsonjc I've made these changes and they are now in TEST

**Comment by gibsonjc** [comment]
This looks good, Ready for Prod

**Comment by cedelis** [comment]
In PROD
