### ISSUE TITLE
Add 690 to subjects displaying in core single record

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#399]
The 690 field is for local subject headings.  This field needs to be added to the single record display under the label "Subject" in the core record information to appear along with other subject headings (6XX fields) when present in the **Local Catalog Only**.  

690 is already indexed in the "topic" solr field, but it isn't currently displaying...

In SolrMarc.php:

    public function getAllSubjectHeadings($extended = false)
    {
        $headings = [];
        foreach (['topic', 'geographic', 'genre', 'era'] as $field) {
            if (isset($this->fields[$field])) {
                $headings = array_merge($headings, $this->fields[$field]);
            }
        }

Maybe part of why it is missing because it isn't in the list of "protected $subjectFields" in SolrMarc.php?  Maybe if we add it to that list as something like '690' => 'local'?  Not sure.

    /**
     * Fields that may contain subject headings, and their descriptions
     *
     * @var array
     */
    protected $subjectFields = [
        '600' => 'personal name',
        '610' => 'corporate name',
        '611' => 'meeting name',
        '630' => 'uniform title',
        '648' => 'chronological',
        '650' => 'topic',
        '651' => 'geographic',
        '653' => '',
        '655' => 'genre/form',
        '656' => 'occupation'
    ];

Example record with 690 field (though no other 6XX fields): 
https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.98757#details

Part of Phase 2 #265

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Looks good, Ready for Prod

Additional examples:
https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.163788#details
https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.170249#details
https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.265714#details

**Comment by cedelis** [comment]
In PROD
