### ISSUE TITLE
No way to cancel a request?

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/vufind#4]
JIRA issue created by: Jessica Gibson (gibsonjc)
Originally opened: 2016-03-24 09:36 AM

Once a request has been placed, there doesn't appear to be a way to cancel the request through Your Account.

In WebVoyage and VuFind 0.6, a user cannot cancel a request when it is at certain stages of the fulfillment process, but there are some stages at which point they can cancel the request through My Account to indicate that they no longer want the item.

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-04-05 12:46 PM

In config.ini:

; Determines if storage retrieval requests can be cancelled or not.
; Options are true or false.
; default is false
cancel_storage_retrieval_requests_enabled = false

**Comment by patrickzurek** [comment]
JIRA User: Chris Delis (cedelis)
JIRA Timestamp: 2016-04-05 01:46 PM

Yay! Now the button / action shows up. But the actual cancel operation itself does not work. Working on it...

**Comment by patrickzurek** [comment]
JIRA User: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2016-04-06 07:14 AM

Debbie just stated this information yesterday in an unrelated RT ticket, so I thought I would note it here for reference:

The only time a request can be cancelled is when it has the status of "request submitted". This status happens at two occasions, 
1) when you first place your request, before the lending library prints the pull-slip, and 2) when the request is not filled by one library and it is promoted overnight to the next library, before that new library prints the pull-slip.

**Comment by patrickzurek** [comment]
JIRA User: Chris Delis (cedelis)
JIRA Timestamp: 2016-04-06 11:22 AM


I noticed that the AgencyId was missing in VuFind2's driver (XCNCIP.php):

<ns1:RequestId>
        <ns1:AgencyId>SICdb</ns1:AgencyId>
        <ns1:RequestIdentifierValue>487897</ns1:RequestIdentifierValue>
      </ns1:RequestId>

This is needed in order to handle consortial environments.

Below, for reference, is the whole puzzle:

<ns1:NCIPMessage xmlns:ns1="http://www.niso.org/2008/ncip" ns1:version="http://www.niso.org/schemas/ncip/v2_0/imp1/xsd/ncip_v2_0.xsd">
    <ns1:CancelRequestItem>
      <ns1:InitiationHeader>
        <ns1:ToAgencyId>
          <ns1:AgencyId>MILdb</ns1:AgencyId>
        </ns1:ToAgencyId>
      </ns1:InitiationHeader>
      <ns1:AuthenticationInput>
        <ns1:AuthenticationInputData>21111008578000</ns1:AuthenticationInputData>
        <ns1:AuthenticationDataFormatType>text</ns1:AuthenticationDataFormatType>
        <ns1:AuthenticationInputType>Username</ns1:AuthenticationInputType>
      </ns1:AuthenticationInput>
      <ns1:AuthenticationInput>
        <ns1:AuthenticationInputData>Orvis</ns1:AuthenticationInputData>
        <ns1:AuthenticationDataFormatType>text</ns1:AuthenticationDataFormatType>
        <ns1:AuthenticationInputType>Password</ns1:AuthenticationInputType>
      </ns1:AuthenticationInput>
      <ns1:RequestId>
        <ns1:AgencyId>SICdb</ns1:AgencyId>
        <ns1:RequestIdentifierValue>487897</ns1:RequestIdentifierValue>
      </ns1:RequestId>
      <ns1:RequestType>Stack Retrieval</ns1:RequestType>
    </ns1:CancelRequestItem>
  </ns1:NCIPMessage>


...which translates to the following voyager resttful DELETE method:


http://voyager-pooled-test.carli.illinois.edu:19913/mil/vxws/patron/189/circulationActions/requests/callslips/SICDB20020422101735%7C487897?patron_homedb=1@MILDB20020507031103


/mil/ - patron's agency

vxws/patron/189/ - patron's ID

circulationActions/requests/callslips/SICDB20020422101735 - item's agency

%7C - delimiter

487897 - RequestIdentifierValue

?patron_homedb=1@MILDB20020507031103 - patron's agency (again!)

**Comment by patrickzurek** [comment]
Resolved: 2016-04-06 11:23 AM

**Comment by dmcmpbll** [comment]
The cancel requests functionality appears to be working correctly from tests, but it falsely reports that it was successful in canceling requests that it did not cancel.

For the four items below, two are in "In Transit- On Hold" status, and two are in "On Hold" status (aka "Available for Pickup"). These statuses should (and do) prevent the patron from canceling their request in the OPAC.

Both the "Cancel Selected Requests" and "Cancel All Requests" functions give the notice that "4 request(s) were successfully canceled" even though the 4 requests correctly remained uncanceled, and remain in the "Requested Items" list after the attempted cancel.

![image](https://user-images.githubusercontent.com/20848151/34313212-2f3c7d9e-e72f-11e7-9d4b-6618fc39bca3.png)

**Comment by dmcmpbll** [comment]
@gibsonjc, please reopen this ticket when you have the chance after the holidays. thanks!

**Comment by gibsonjc** [comment]
@dmcmpbll can you set up a patron record with examples of requested items in states that cannot be canceled but say that they are when you use the cancel function so that @cedelis can troubleshoot?  (Please provide patron info to him via email not on this Issue.)

@cedelis Since this is request-related, should examples be set up on TEST or DEVEL?

**Comment by cedelis** [comment]
@gibsonjc probably TEST

**Comment by dmcmpbll** [comment]
I have a new batch of requests set up on TEST. 
I will email @cedelis with the patron and item information.

![image](https://user-images.githubusercontent.com/20848151/35409398-b362d272-01d7-11e8-8ed7-d527e97b5d6c.png)

**Comment by gibsonjc** [comment]
Transferred the 2017-2018 conversation to new Issue: #293 
Re-Closing this one.
