### ISSUE TITLE
Institution dropdown page defaults to I-Share instead of local catalog that was chosen

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#40]
When I choose EIU from the institution dropdown menu on this page, the URL I am taken to is this: 
https://vufind3-test.carli.illinois.edu/all/vf-eiu/
So when I browse or search it gives me all of I-Share.

This is the URL I want, so I browse and search only EIU [to start]
https://vufind3-test.carli.illinois.edu/vf-eiu/

**Comment by gibsonjc** [comment]
#69 duplicated this, so comments have been moved here:

UIS - Could our local catalog be set as the default?

EIU - When I chose Eastern, I expected to be able to search in my local catalog

**Comment by gibsonjc** [comment]
@cedelis This appears to be going to the local catalog in prod and test already, but it was not doing so last week.  Did you already change this?

**Comment by cedelis** [comment]
Yes, I edited the static HTML welcome page (which is not in source control, so I cannot reference it here). I simply changed the URLs from /all/vf-xxx to /vf-xxx.
