### ISSUE TITLE
Specification for Bib 856 field display on New VuFind single record page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#401]
Bibliographic 856 fields do not display in the New VuFind union catalog but do display in local catalogs.

A Bib may have multiple 856 fields.  Each one should display independently with its own label.

In RecordDataFormatterFactory.php, the Bib 856s seem to be controlled by default by:

`$spec->setTemplateLine('Online Access', true, 'data-onlineAccess.phtml');`

**Subfields**

This is the same as what is already in place for MFHD 856 subfields in the Holdings tab. If you can copy from that logic, please do!

•	If the 856 contains $u only: the $u will be hyperlinked.
•	If the 856 contains $u and $y: the $y will be hyperlinked.
•	If the 856 contains $u and $z: the $u will be hyperlinked and the $z will display as text.
•	If the 856 contains $u and $3: the $3 will be hyperlinked.
•	If the 856 contains $u, $3 and $y: the $3 and the $y will be hyperlinked, in that order, separated by a space.
•	If the 856 contains $u, $3 and $z: the $3 will be hyperlinked and the $z will display as text.
•	If the 856 contains $u, $y and $z: the $y will be hyperlinked and the $z will display as text.
•	If the 856 contains $u, $3, $y and $z: the $3 and $y will be hyperlinked, in that order, with a space between them, and the $z will display as text. 
•	Any 856 $z’s display as plain text after the hyperlink.

Some example Bibs with $uyz3 combinations:
856 40 $u - Ex. 2 https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451171
856 40 $uy - Ex. 3 https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451172
856 40 $uz - Ex. 4 https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451173
856 40 $u3 - Ex. 6 https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451175
856 40 $u3y - Ex. 8 https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451177
856 40 $u3z - Ex. 9 https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451178
856 40 $uyz - Ex. 10 https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451179
856 40 $u3yz - Ex. 11 https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451180

**Indicators should customize the Label that displays before the data**

Ideally, we’d like for Labels to change based on Indicator in the Bib 856 single record display and also in the Holdings tab MFHD 856 displays (local and uc) if at all possible!

If the First Indicator is (blank), 0, 1, 2, 3, or 4
And the Second Indicator is 0 or 1
Label = Online Access:

If the First Indicator is 0 or 4
And the Second Indicator is (blank) or 2
Label = Related Information:

If the First Indicator is 2 or 3
And the Second Indicator is (blank) or 2
Label = Connect:

If the First Indicator is 1
And the Second Indicator is (blank) or 2
Label = Download

If the First Indicator is 7
Regardless of Second Indicator
Label = Connect via subf2:

Full list:  (where b is blank)

856 b0	Online Access:
856 b1	Online Access:
856 00	Online Access:
856 01	Online Access:
856 10	Online Access:
856 11	Online Access:
856 20	Online Access:
856 21	Online Access:
856 30	Online Access:
856 31	Online Access:
856 40	Online Access:
856 41	Online Access:
856 0b	Related Information:
856 02	Related Information:
856 42	Related Information:
856 4b	Related Information:
856 22	Connect:
856 2b	Connect:
856 32	Connect:
856 3b	Connect:
856 12	Download:
856 1b	Download:
856 7b	Connect via subf2:
856 70	Connect via subf2:
856 71	Connect via subf2:
856 72	Connect via subf2:

Example Bib with all Indicator combinations:
https://i-share-test.carli.illinois.edu/vf-ben/Record/BENdb.108074#details

Part of Phase 2 #265

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
@cedelis  1. There was an oversight on my part in this specification.  For the four conditions (first indicator 7) that cause the label "Connect via _subf2_:" the text should not actually include the word "subf2".  That's a placeholder for text found in the 856 field's subfield 2, whatever that may be, so for example:

856 70 $u http://www.carli.illinois.edu $2 **Text string**
Connect via **Text string**: http://www.carli.illinois.edu

I updated the examples in the Voyager Test Bib record for https://i-share-test.carli.illinois.edu/vf-ben/Record/BENdb.108074#details yesterday but I see no change to the record this morning.  If you could manually update this record in TEST New VuFind, the examples for $2 will be more diverse like the example above.  Thanks!

2. The only other oddity that we noticed is that there is a extra space before the Bib 856 $z (that is not present in the MFHD 856 $z).  If it is obvious and easy to remove this extra space, please do.  If it is a big hassle, just leave it alone, it's not critical.  
Online Access:     y  z
vs.
Online Access:     y z

You can see the slight difference in these example records:
https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451173
https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451178
https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451179
https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451180

**Comment by cedelis** [comment]
@gibsonjc Actually, I do reference the value of the $2. I figured you did not intend to have 'subf2' as a label ;-)

**Comment by gibsonjc** [comment]
Looks GREAT! Ready for Prod!

**Comment by cedelis** [comment]
In PROD
