### ISSUE TITLE
Add new Credits field to Description Tab

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#402]
Add a new field to the Description tab area in CARLI's RecordDataFormatterFactory.php with a new function in SolrMarc.php similar to many of the other new fields we have recently added.

S11. New suggested function name: getCredits

Field Label: Credits

Field [Indicators] [Subfields] to display:
508 [any indicators] ['a']

Placement of new $spec line: before Performer

    /**
     * Get an array of credits information.
     *
     * @return array
     */
    public function getCredits()
    {
        return $this->getFieldArray('508', ['a']);
    }

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
This looks good, Ready for Prod!

Example: https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451177#description

**Comment by cedelis** [comment]
In PROD
