### ISSUE TITLE
Move "Description of Work" from Description tab to Core

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#403]
We'd like to move

`$spec->setLine('Description of Work', 'getDescriptionOfWork'); // CARLI added new method`

from the Description tab section up to the Core section for display on the record page.  It should be positioned after "Other Authors" and before "Format".

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Made-up example: https://i-share-test.carli.illinois.edu/vf-aru/Record/ARUdb.451176#description
looks good but...
@nmswanson Does this general placement look ok to you? Do you have any other examples of real data we could evaluate?  Thanks!

**Comment by nmswanson** [comment]
This example looks good, I'll add a few others: [(https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.270744#details)](https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.270744#details)

**Comment by nmswanson** [comment]
Other author examples: 
[https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.343833](https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.343833)

[https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.358472](https://i-share-test.carli.illinois.edu/vf-rou/Record/ROUdb.358472)

**Comment by gibsonjc** [comment]
Ready for Prod

**Comment by cedelis** [comment]
In PROD
