### ISSUE TITLE
Make I-Share logo a link to the splash page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#404]
In the header, change the link of the CARLI I-Share logo on all _https://i-share.carli.illinois.edu/all/vf-xxx_ catalogs and the _https://i-share.carli.illinois.edu/all/vf/_ catalog.

Currently, the link is back to the catalog itself, so if you are in the /all/vf-sai/ view clicking this logo takes you back to the front page of this same view.  Instead, we'd like it to be a link to https://i-share.carli.illinois.edu/ so that users could choose a different library from the dropdown menu like they can in VuFind 0.6.

![screen shot 2019-02-15 at 7 51 48 am](https://user-images.githubusercontent.com/17598357/52860965-9b790b00-30f6-11e9-9644-3bed3a9ad7b4.png)

SAI - RT 104318

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
This works as desired and can go to PROD, my only concern is that on TEST I expected it to go to the TEST splash page i-share-test.carli.illinois.edu but instead it goes to the PROD splash page i-share.carli.illinois.edu.  (Other things on TEST go to TEST, things on DEVEL go to DEVEL, etc. so I just want to make sure that this won't cause a hiccup for us later down the line.)

**Comment by cedelis** [comment]
In PROD
