### ISSUE TITLE
Why is there one Item line above the Most Recent Received Issues line(s) in Holdings tab?

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#405]
In Issue #150 , we changed the VoyagerRestful.ini setting so that the Most Recent Received Issues appear with each MFHD instead of below all the holdings.  This is still working correctly, however, it seems that ONE Item Record line is always appearing before the Most Recent Received Issues line, which looks very odd.

Can we figure out why the system is doing this and maybe correct it so that in the order of Holding tab data the Most Recently Received Issues appears above all of the Items?

Examples:
https://i-share-test.carli.illinois.edu/vf-isu/Record/ISUdb.494649
https://i-share.carli.illinois.edu/vf-lcc/Record/LCCdb.59193
https://i-share.carli.illinois.edu/vf-uiu/Record/UIUdb.3920282
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.3920282
https://i-share.carli.illinois.edu/vf-niu/Record/NIUdb.247589

![screen shot 2019-02-19 at 9 47 04 am](https://user-images.githubusercontent.com/17598357/53027877-61c43f00-342b-11e9-8c19-065eb3f88e11.png)

We'd prefer this be:
**Location:** Floor 2 Current Periodicals: Building Use Only 
**Call Number:** | F806 .A762 
**Notes:** | IF THERE ARE ANY PRESENT
**Volume Holdings:** | IF THERE ARE ANY PRESENT                                         
**Most Recent Received Issues:** | v. 58, no. 1 (2017 Spring)
___________________________________v. 57, no. 4 (2016 Winter)
___________________________________v. 57, no. 3 (2016 Autumn)
___________________________________v. 57, no. 2 (2016 Summer)
___________________________________v. 57, no. 1 (2016 Spring)
___________________________________v. 56, no. 4 (2015 Winter)
___________________________________v. 56, no. 3 (2015 Autumn)
___________________________________v. 56, no. 2 (2015 Summer)
___________________________________v. 56, no. 1 (2015 Spring)
**Copy 1 Test item 1 (2019)** | Available | Check if item can be requested             
**Copy 1 Test item 2 (2019)** | Available | Check if item can be requested
**Copy 1 Test item 3 (2019)** | Available | Check if item can be requested
View more items (IF THERE ARE MORE PRESENT)

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Looks good, Ready for Prod!

**Comment by cedelis** [comment]
In PROD
