### ISSUE TITLE
Library default pick-up location not being honored in UB requests starting in Jan. 2019

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#406]
Each library has a default pick-up location established in SysAdmin.  This location should be used by the system for local and UB requests when a user has not specifically chosen another location and Saved it in their New VuFind Profile.  

Problem:
BHC's default location is .QUAD CITIES LIBRARY.  They are reporting that the default is appearing correctly for local requests and those default to .QUAD CITIES LIBRARY, but it is NOT appearing correctly for UB requests.  Instead, pick-up locations for UB requests are sorting alphabetically, thus defaulting to .EAST CAMPUS LIBRARY. 

Expected Behavior:
Requesting any item, local or UB, to be picked up at BHC should always default to .QUAD CITIES LIBRARY (unless the user has set another default in their Profile).

Workaround:
If a BHC user goes into their Profile and purposefully clicks Save on .QUAD CITIES LIBRARY, then the system remember this and uses if for UB requests.  However, they should not have to do this because .QUAD CITIES LIBRARY should be the default already.

Who is affected?
We think this affecta BHC, DPU, HRT, SIE, and maybe OAK because 1) they have more than one pick-up location, and 2) alphabetical order including leading punctuation does not put their preferred pick-up location at the top of the list.

Replication steps:
While logged in as any user who has NOT already set a pick-up location preference, try to request any item.  On the Request This Item pop up, choose Black Hawk College.  The default Location will be .EAST CAMPUS LIBRARY instead of .QUAD CITIES LIBRARY.

We think that this behavior changed after something we did late in 2018, very possibly Issue #284 in December.  BHC is reporting this was not a problem during fall semester, they only noticed it starting in January.

Issue #333 was also about defaults not being honored, but that was resolved in June 2018.

If a fix in New VuFind is not easily possible, we can suggest leading punctuation options for adjusting the alphabetical order in Voyager SysAdmin to move the default to the top of the list. 

BHC - RT 104040

**Comment by cedelis** [comment]
In TEST

**Comment by dmcmpbll** [comment]
This looks good on test to me. I think it is ready for prod.

**Comment by gibsonjc** [comment]
Thanks @dmcmpbll! Ready for Prod!

**Comment by cedelis** [comment]
In PROD
