### ISSUE TITLE
Results list sometimes shows word "Published" with no date on DEVEL

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#407]
The change we made on DEVEL to use getPublicationDate in the marc properties definitions for publishDate and publishDateSort has been an improvement.  However, there is one place with dates in the results list displays where I didn’t see everything that I expected.

Example:
https://i-share-devel.carli.illinois.edu/vf-nby/Search/Results?sort=year+asc&filter%5B%5D=-institutions%3A%22HAT%22&filter%5B%5D=-format%3A%22Electronic%22&filter%5B%5D=-format%3A%22Microform%22&filter%5B%5D=author_facet%3A%22Terence%22&lookfor=Terence&type=Author

The first 14 results have the word “Published” but no date after it.  It looks weird.  I’m wildly guessing it is because the 260$c data are more than just a four-digit year and it doesn’t know what to do with it? But I really don’t know for sure.

![Screen Shot 2019-04-04 at 10 59 20 AM](https://user-images.githubusercontent.com/17598357/55570294-c16b6680-56c8-11e9-99bd-5d4f7cc45fb1.png)

The system is sorting results by **mostly** oldest first because when I go into each record and look at the 008 bytes 07-10 I see that the system appears to know that these are the oldest records in the results (I hope/think because we are now using getPublicationDate in marc.prop publishDateSort = custom, getPublicationDate) but it isn’t displaying anything after the word “Published”.  Ideally, it should display some kind of date there, or, it shouldn’t show the word “Published” at all.

@cedelis Can you look into this results list display (is it in /usr/local/vufind/themes/CARLI/templates/RecordDriver/SolrDefault/result-list.phtml?) and see what it is using to display here?  I see a call to getPublicationDates that I wonder if we want to change to getPublicationDate instead, but I cannot read this code well enough to know what it is doing or not.

**Comment by cedelis** [comment]
@gibsonjc in result-list.phtml, you're correct in that it calls getPublicationDates:

, which in turn calls upon the indexed field, publishDate:

 https://github.com/CARLI/vufind/blob/carli-release-4.1/module/VuFind/src/VuFind/RecordDriver/SolrDefault.php#L1113

, which in turn calls upon SolrMarc's pre-defined method, getPublishedDate:

https://github.com/solrmarc/solrmarc/blob/master/src/org/solrmarc/index/SolrIndexerShim.java#L391

, which ultimately results in the following spec:

```
AbstractValueIndexer<?> indexer = 
getOrCreateIndexerFullSpec("008[7-10]:008[11-14]:260c:264c?(ind2=1||ind2=4),clean, first, " +
                    "map(\"(^|.*[^0-9])((20|1[5-9])[0-9][0-9])([^0-9]|$)=>$2\",\".*[^0-9].*=>\")");
```


But, why doesn't 'publishDate' get populated in the example?:

https://i-share-devel.carli.illinois.edu/vf-nby/Record/NBYdb.172745#details

It appears that:

008[7-10] = 1489
008[11-14] = 1493

so, I would expect publishDate should be '1489', wouldn't you?

EDIT: It appears that the "map" might be causing this. I changed our 'publishDate' definition from:

```
publishDate = custom, getPublicationDate
publishDateSort = custom, getPublicationDate

```
to:

```
publishDate = 008[7-10]:008[11-14]:260c:264c?(ind2=1||ind2=4), clean, first
publishDateSort = 008[7-10]:008[11-14]:260c:264c?(ind2=1||ind2=4), clean, first

```

and now, for this example, Published displays:

https://i-share-devel.carli.illinois.edu/vf-nby/Search/Results?lookfor=Therencius+poeta+%3A+cum+comento+donati+grammatici.&type=AllFields&limit=20&sort=year+asc

Should I make this change permanent and re-index?

**Comment by gibsonjc** [comment]
@cedelis getPublishedDate seems to work well in all other respects.  Before we scrap it entirely, what is this "map" line supposed to do, do you think?  Normalize the date numbers somehow?

In this example NBYdb.172745, yes, I'd have expected it to show Published 1489 because the 008[7-10] is present and comes first in the list of 
`AbstractValueIndexer<?> indexer = 
getOrCreateIndexerFullSpec("008[7-10]:008[11-14]:260c:264c?(ind2=1||ind2=4),clean, first, " +
                    "map(\"(^|.*[^0-9])((20|1[5-9])[0-9][0-9])([^0-9]|$)=>$2\",\".*[^0-9].*=>\")");`

But the comment just above that section of code intrigues me where it says
`* @return 260c or 008[7-10] or 008[11-14], "cleaned" per org.solrmarc.tools.Utils.cleanDate()`
listing the 260c **first** in the comment.  Is something giving preference to the 260c?  The 260c of this particular record NBYdb.172745 is somewhat unusual, having the text "between 1489 and 1493]" so maybe the system is unable to parse it because it isn't a date-like number as expected?

**Comment by cedelis** [comment]
@gibsonjc I'm running a few tests comparing two bibs, where the first bib displays correctly and the second incorrectly displays an empty Published date.

First, let me attempt to answer your questions: I do not believe the comments in the code are accurate. I am pretty certain that order or precedence is based on the order in which they are listed in spec, e.g., 008[7-11] takes precedence over 008[11-14]. Also, I haven't fully analyzed what "clean" is doing. Nor do I completely understand why it i listed before "first" (Some questions I have about "clean": does "clean" work on each element in an array? if "clean" results in an empty string, does it return an empty string or a null (empty) element?). 

In any case, I thought I'd share what I've testing so far. I'll continue analyzing this later. 

Comparing publishDate displays for two bibs, A and B:

A) NBYdb.112062 
B) NBYdb.172745 

Displays:

A) "Published 1503"
B) "Published"

MARC data:

A)

008[7-10]: "1503"
008[11-14]: "    "
260c: "anno 1503. XV Kalendas Aprilis."
264c(ind2=1||ind2=4): [empty]

B)

008[7-10]: "1489"
008[11-14]: "1493"
260c: "between 1489 and 1493]"
264c(ind2=1||ind2=4): [empty]


—————————

Test 1: Original spec:

publishDate = custom, getPublicationDate

Displays:

A) "Published 1503"
B) "Published"

Solr data:

A)
      <arr name="publishDate">
        <str>1503</str>
      </arr>

B)
      <arr name="publishDate">
        <str/>
      </arr>

—————————

Test 2: Translate original spec to the following (near) equivalent in Index Specification Language

translated spec:

publishDate = 008[7-10]:008[11-14]:260c:264c?(ind2=1||ind2=4), clean, first, (pattern_map.pdate)
pattern_map.pdate.pattern_0 = (^|.*[^0-9])((20|1[5-9])[0-9][0-9])([^0-9]|$)=>$2
pattern_map.pdate.pattern_1 = .*[^0-9].*=>

Displays:

A) "Published 1503"
B) [empty]

Solr data:

A)
      <arr name="publishDate">
        <str>1503</str>
      </arr>

B) [empty]

—————————

Test 3: Let's only use 008[7-10]

spec:

publishDate = 008[7-10], clean, first, (pattern_map.pdate)
pattern_map.pdate.pattern_0 = (^|.*[^0-9])((20|1[5-9])[0-9][0-9])([^0-9]|$)=>$2
pattern_map.pdate.pattern_1 = .*[^0-9].*=>

Displays:

A) "Published 1503"
B) [empty]

Solr data:

A)
      <arr name="publishDate">
        <str>1503</str>
      </arr>

B) [empty]

**Comment by cedelis** [comment]
@gibsonjc I finally figured it out. It had to do with the date being older than 1500, the following map regex was clobbering it:

`publishDate = 008[7-10]:008[11-14]:260c:264c?(ind2=1||ind2=4),clean, first, map("(^|.*[^0-9])((20|1[5-9])[0-9][0-9])([^0-9]|$)=>$2",".*[^0-9].*=>")
`
When I change the "1[5-9]" to "1[0-9]" below, things work as expected:

`publishDate = 008[7-10]:008[11-14]:260c:264c?(ind2=1||ind2=4),clean, first, map("(^|.*[^0-9])((20|1[0-9])[0-9][0-9])([^0-9]|$)=>$2",".*[^0-9].*=>")
`

Therefore, the solution to my problem is to use the following Index Specification Language setting instead of the built-in method, getPublishedDate:

`publishDate = 008[7-10]:008[11-14]:260c:264c?(ind2=1||ind2=4),clean, first, map("(^|.*[^0-9])((20|1[0-9])[0-9][0-9])([^0-9]|$)=>$2",".*[^0-9].*=>")
`

**Comment by gibsonjc** [comment]
Yes, dates look better! 

At our 4/25 meeting we decided to move this and all DEVEL changes (indexing changes, searchspecs.yaml changes, 880s displays, and Issue #94 ) to TEST.  @cedelis will start a reindex of TEST today.

**Comment by gibsonjc** [comment]
This was completed with the reindex on 5/13/19.
