### ISSUE TITLE
Remove subfields from getDescriptionOfWork

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#408]
I believe the current definition in /usr/local/vufind/module/CARLI/src/CARLI/RecordDriver/SolrMarc.php :

    public function getDescriptionOfWork()
    {
        $results = $this->getFieldArray('383', ['a', 'b', 'c', 'd', 'e', '3']);
        $results = array_merge($results, $this->getFieldArray('384', ['a', '3']));
        $results = array_merge($results, $this->getFieldArray('380', ['a', '3']));
        $results = array_merge($results, $this->getFieldArray('381', ['a']));
        $results = array_merge($results, $this->getFieldArray('382', ['a', 'b', 'd', 'e', 'n', 'p', 'r', 's', 't', 'v', '3']));
        return $results;
    }

Please adjust the 382 line to remove subfields r, s, and t:

$results = array_merge($results, $this->getFieldArray('382', ['a', 'b', 'd', 'e', 'n', 'p', 'v', '3']));

**Comment by cedelis** [comment]
In TEST

**Comment by gibsonjc** [comment]
Ready for Prod!

Found examples with 382 $s now correctly not displaying:
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.8421034#details 
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.8326066#details
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.8421041#details

**Comment by cedelis** [comment]
In PROD
