### ISSUE TITLE
Add UPC to Syndetics Solutions image URLs

### ISSUE THREAD

**Issue by nmswanson** [CARLI/vufind#409]
Through ftp to Syndetics Solutions, EIU has shared Folkmanis puppet images with UPCs in the file names with Syndetics and the images were added to Syndetics cover image database. The identifier to display these puppet images within EIU’s MARC records is not ISBN like we see with many Syndetics cover images, but instead the UPC itself noted in the MARC record’s 024a containing a first indicator=1 (for UPC). Note that these items to don’t have ISBNs.

The Folkmanis puppet images are not properly displaying in VuFind through our setup of the Classic Syndetics Solutions package. 

Syndetics support initially thought specifying the UPC parameter in the Admin settings that only they had access to for our Syndetics Classic package. This did not solve the problem. 

They have asked us to adjust the image URLs to include UPCs using the instructions (shared through email). Also, EIU has shared some examples where they have edited the URL to include the UPCs to make the images display. 

Here are the search, record, and image URLs for a duckling puppet example that do not currently work.
Search result display:
[https://i-share.carli.illinois.edu/vf-eiu/Search/Results?lookfor=duckling+puppet&type=AllFields](https://i-share.carli.illinois.edu/vf-eiu/Search/Results?lookfor=duckling+puppet&type=AllFields)
Record display:
[https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.1529729](https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.1529729)
Large image URL: 
[https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL696.A52+D825+2012x&size=large&title=Duckling+puppet.&recordid=EIUdb.1529729&source=Solr&oclc=1020408054](https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL696.A52+D825+2012x&size=large&title=Duckling+puppet.&recordid=EIUdb.1529729&source=Solr&oclc=1020408054)
Medium image URL:
[https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL696.A52+D825+2012x&size=medium&title=Duckling+puppet.&recordid=EIUdb.1529729&source=Solr&oclc=1020408054 ](https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL696.A52+D825+2012x&size=medium&title=Duckling+puppet.&recordid=EIUdb.1529729&source=Solr&oclc=1020408054 )

Here is an example where EIU added the UPC to the URL and it does seem to work:
Large image URL:
[https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL696.A52+D825+2012x&size=large&title=Duckling+puppet.&recordid=EIUdb.1529729&source=Solr&upc=638348029225&oclc=1020408054 ](https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL696.A52+D825+2012x&size=large&title=Duckling+puppet.&recordid=EIUdb.1529729&source=Solr&upc=638348029225&oclc=1020408054 )
Medium image URL:
[https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL696.A52+D825+2012x&size=medium&title=Duckling+puppet.&recordid=EIUdb.1529729&source=Solr&upc=638348029225&oclc=1020408054
](https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL696.A52+D825+2012x&size=medium&title=Duckling+puppet.&recordid=EIUdb.1529729&source=Solr&upc=638348029225&oclc=1020408054
)

**Comment by nmswanson** [comment]
Additional example:

Search result display:
[https://i-share.carli.illinois.edu/vf-eiu/Search/Results?lookfor=Camel+puppet&type=Title&limit=20&sort=relevance](https://i-share.carli.illinois.edu/vf-eiu/Search/Results?lookfor=Camel+puppet&type=Title&limit=20&sort=relevance)
Record display:
[https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.1462844](https://i-share.carli.illinois.edu/vf-eiu/Record/EIUdb.1462844)
Large and medium image URLs without UPC that do not work:
Large image URL:
[https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL737.U54+C27+2013x&size=large&title=Camel+puppet.&recordid=EIUdb.1462844&source=Solr&oclc=973419762](https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL737.U54+C27+2013x&size=large&title=Camel+puppet.&recordid=EIUdb.1462844&source=Solr&oclc=973419762)
Medium image URL: [https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL737.U54+C27+2013x&size=medium&title=Camel+puppet.&recordid=EIUdb.1462844&source=Solr&oclc=973419762](https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL737.U54+C27+2013x&size=medium&title=Camel+puppet.&recordid=EIUdb.1462844&source=Solr&oclc=973419762)
Large and Medium image URLs with UPC that do work:
Large image URL:
[https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL737.U54+C27+2013x&size=large&title=Camel+puppet.&recordid=EIUdb.1462844&source=Solr&upc=638348029799](https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL737.U54+C27+2013x&size=large&title=Camel+puppet.&recordid=EIUdb.1462844&source=Solr&upc=638348029799)
Medium image URL:
[https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL737.U54+C27+2013x&size=medium&title=Camel+puppet.&recordid=EIUdb.1462844&source=Solr&upc=638348029799](https://i-share.carli.illinois.edu/vf-eiu/Cover/Show?author=&callnumber=QL737.U54+C27+2013x&size=medium&title=Camel+puppet.&recordid=EIUdb.1462844&source=Solr&upc=638348029799)

**Comment by gibsonjc** [comment]
This was completed with the reindex on 5/13/19.
