### ISSUE TITLE
035 field display links in I-Share results list are confusing

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#41]
EIU - In I-Share view, on the results page under the title and a few other lines of information for each item, the display of the 035 fields is confusing to users and the links do not always work.  Can these be hidden or the link text more descriptive?

SXU - The brief display of book information is VERY confusing to patrons: The call number does not show, but the meaningless OCLC number/code does show.

ISL - What does the (CARLI) link mean and then the other sources?  They both seemed to map to the same location, so what is the point of it being located on the main search results screen?

**Comment by gibsonjc** [comment]
Example:  (CARLI) (Other Sources: (CSUdb)601692, (EBZ)ebs39311e, (TIUdb)414016) 

(CARLI) is a link to the record in the I-Share view, duplicating the same link as the title.

Links of the form (ABCdb)nnnnnn link to the record in that database: (CSUdb)601692, (TIUdb)414016)  

But other 035 fields also display here and those links do not work: (EBZ)ebs39311e

**Comment by gibsonjc** [comment]
EIU -I don’t like seeing the cryptic “(CARLI) (Other Sources:…) in the brief record. I guess the (LEWdb)136472) is a database control number that will be confusing and not useful to patrons. (moved from #52  )

**Comment by gibsonjc** [comment]
Trinity Christian College - - The source bits in the results lists seem pointless from a patron standpoint and clutters up the display when there are a lot of source libraries. (e.g. (CARLI) (Other Sources: (CODdb)247785, (ELMdb)353142, (ISUdb)1759100, (IVCdb)193984, (MMCdb)92959, (NEIdb)751586, (OAKdb)121188, (WRHdb)347264) –and that’s a shorter one!)

[From a librarian perspective, I find them interesting, but not enough to make their presence in the results worth the screen space they take up.]
(moved from #52 )

**Comment by gibsonjc** [comment]
Moved from #73 
UIS - Other sources could be hidden from view to give it a cleaner view and reduce the length of the results page.

**Comment by gibsonjc** [comment]
These 035 fields are currently set to display in the results list in order to assist with debugging and finding examples in the I-Share view of the catalog.  We will be able to remove them from display when their assistance is no longer needed by CARLI staff.

**Comment by gibsonjc** [comment]
IWU - when you search all I-Share libraries, there is a lot of information in “Other Sources” that is very confusing

**Comment by gibsonjc** [comment]
SXU - I-Share library locations display (layers and codes)
Is it correct to have the codes show to the public as in the example below?
Will users know what they are and that they should click into them?
Are we expecting them to guess that the CARLI entry will show all holdings?
Perhaps we could at least have a HOLDINGS header for that area?

(CARLI) (Other Sources: (CODdb)251208, (COLdb)498914, (EIUdb)1138242, (ISUdb)1664212, (NBYdb)875928, (UIUdb)7184449)

**Comment by gibsonjc** [comment]
As @cedelis suggested in today's meeting, please comment out the html display of the 035 fields in the Results list displays of the I-Share union catalog.  This way CARLI staff can still "view source" to easily see the records in the match sets.

**Comment by cedelis** [comment]
Ready for testing (on vufind3-devel server)

**Comment by bgant** [comment]
Commenting out the html is a good stopgap solution for now. Eventually we will most likely want to avoid the "Location" calls in the Search Results page entirely to improve performance. I'm not sure about the trade-off between performance and staff being able to "view source" right now.

**Comment by cedelis** [comment]
There aren't any "location" calls being made. This info is coming from the solr record (the 035s are indexed already; no further lookups are occurring).

**Comment by gibsonjc** [comment]
This looks good, "Other Sources" can be seen in the "view source" of the results page.  Ready to be put on vufind3-test for the final check.

**Comment by gibsonjc** [comment]
Looks good on vufind3-test, ready for prod

**Comment by cedelis** [comment]
Pulled carli-release-3.1.3 changes into Prod server.
