### ISSUE TITLE
Uncomment getDateSpan

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#410]
In the recent work on "Published" data, it looks like getDateSpan was accidentally commented out of the CARLI SolrMarc.php file

        //$spec->setLine('Published', 'getDateSpan');

This is for displaying the 362 field, not the 260/264 fields, and needs to be uncommented so it will display.  To avoid confusion, let's change the label to "Dates of Publication"

        $spec->setLine('Dates of Publication', 'getDateSpan');

**Comment by cedelis** [comment]
@gibsonjc Can you please provide an e.g. bib that has a 362 field? Thanks

**Comment by gibsonjc** [comment]
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.4114809
https://i-share-test.carli.illinois.edu/vf-uiu/Record/UIUdb.3891432

**Comment by cedelis** [comment]
Ready for Testing

**Comment by gibsonjc** [comment]
Looks good, ready for Prod!

**Comment by cedelis** [comment]
In PROD
