### ISSUE TITLE
Add Google Fi to list of cell carriers for Text Me function

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#411]
Google Fi user would like Text Me option (UIC - RT 105984)

vufind/config/vufind/sms.ini 

Google Fi Help - Send and receive emails over text message:
https://support.google.com/fi/answer/6356597?hl=en

**Comment by gibsonjc** [comment]
Can we just port the list of carriers currently used by VuFind 0.6?  It has even more choices.

**Comment by cedelis** [comment]
In TEST (can't really test it though, unless someone actually has a Google Fi phone).

**Comment by gibsonjc** [comment]
@cedelis Can you also see about adding the others that are in VuFind 0.6 but aren't in New? (see list below)  If you can just copy the config definitions from 0.6 to New I was hoping that might be easy enough to do.  If not, oh well. Thanks!
Boost Mobile
Cellular One
Cingular
SunCom
US Celluar
Ting CDMA
Ting GSM

**Comment by cedelis** [comment]
@gibsonjc Yes, my mistake. I have now added all of the definitions from 0.6 into New VuFind

**Comment by cedelis** [comment]
In PROD.
