### ISSUE TITLE
adjust UIC stackmap setup

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#413]
UIC needs to test some change to their StackMap.  Please make this change on TEST first:

Change these two stackmap files:

* https://www.stackmap.com/integration/uic-vufindv4/StackMap.css
* https://www.stackmap.com/integration/uic-vufindv4/StackMap.js

To these two stackmap files:

* https://library.webhost.uic.edu/stackmap/test_files/StackMap.css
* https://library.webhost.uic.edu/stackmap/test_files/StackMap.js 

When done, I'll have them review it on TEST.  Thanks!

RT 106579

**Comment by cedelis** [comment]
@gibsonjc I made the change to TEST and the new files simply do not work. No error messages. They just do not work. You can compare the current version in DEVEL (which works: https://i-share-devel.carli.illinois.edu/vf-uic/Record/UICdb.1082396 ) to the new version in TEST (which does not work: https://i-share-test.carli.illinois.edu/vf-uic/Record/UICdb.1082396 ).

**Comment by gibsonjc** [comment]
For the record, I sent this information to UIC on RT 106579 and he said they'll look into it and why it doesn't work.

**Comment by gibsonjc** [comment]
Allan sent additional files in Sept. on RT 106579 that Chris added to Test.  Allan approved and Chris moved them to Prod on 10/3. Closing.
