### ISSUE TITLE
Update Syndetics subscriptions for FY20

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#415]
@cedelis It's time again to update the subscriptions in New VuFind and VuFind 0.6!  
(Did this last year and the year before in #360 and #228, respectively.)

Some libraries added, some libraries dropped.
Some libraries changed what they subscribe to.
See the spreadsheet that I sent you directly via email (to protect the innocent).

**Comment by gibsonjc** [comment]
Looks good on Test, ready for Prod!

**Comment by cedelis** [comment]
In PROD
