### ISSUE TITLE
Update I-Share Catalog button links in WebVoyage

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#416]
We completed #288 but forgot to have @fellowsgl change the I-Share Catalog button links.  Gordon needs to do this on voyager-prod for all libraries except the 8 that opted out:
CSU, JUD, LLC, NBY, NEI, SML, UIU, WHE

Example of change for WIU:

voyager-prod:/m1/voyager/custom_webs/WIU_webvoyage/etc/webvoyage/local/opac.ini

Btn02Text=Search all I-Share libraries" TITLE="Search all I-Share libraries
Btn02GraphicUp=UpUC.gif
Btn02Function=URL
Btn02Link=https://i-share.carli.illinois.edu/uc/cgi-bin/Pwebrecon.cgi?DB=local&PAGE=First&aff=wiu

change the last line

Btn02Link=https://i-share.carli.illinois.edu/uc/cgi-bin/Pwebrecon.cgi?DB=local&PAGE=First&aff=wiu

to

Btn02Link=https://i-share.carli.illinois.edu/all/vf-wiu

WIU RT 108341

**Comment by fellowsgl** [comment]
This has been completed for all 83.
