### ISSUE TITLE
Suppress local requesting for COL (not SAI)

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#418]
COL (not SAI) is using New VuFind as of this summer but does not support local requesting. Please disable local requesting for COL (not SAI)  Thanks!

Last I knew there was a list of institutions is in create_local_vufind_instances.sh under "my %not_requestable" according to Issue #59

**Comment by gibsonjc** [comment]
@cedelis I somehow bungled the creation of this issue, sorry about that.  I have edited it accordingly to have actual details! :)

COL (not SAI) RT 108453

**Comment by cedelis** [comment]
In PROD.

**Comment by cedelis** [comment]
Just making sure we mean SAIdb and not COLdb. Re-opening...

**Comment by gibsonjc** [comment]
@cedelis We definitely mean COL, I got really mixed up. Please undo SAI and set up for COL.

**Comment by cedelis** [comment]
In PROD
