### ISSUE TITLE
Location facet and/or Voyager Location Limit Groups

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#42]
Location Limit Groups--as set up in Voyager SysAdmin and currently available in VuFind 0.6 (https://www.carli.illinois.edu/products-services/i-share/opac/vf-loc-facets) --are not currently present in VuFind 3.

UIU - As someone who works on the reference desk/frequently with the catalog, ...locally we need to retain a search limit in the advanced search interface and on the right side of the search results screen for item location (in addition to institution which is already present). Particularly at UIUC this is a concern given the number of libraries on campus.

**Comment by gibsonjc** [comment]
A comment from SXU: We spent a good deal of time creating local locations for easier access (paper books, special locations, etc.) How do we return these Location facets to the results screen?

**Comment by slknight** [comment]
EIU also wants location limits/facets available.

**Comment by bgant** [comment]
SWI - At our institution, we use the ‘Location’ filters all the time since we have three separate campuses.  This allows our students to easily locate a book at their own location.

Also, it allows us to narrow by collection.  This is helpful when trying to connect our Early Childhood Students to our collection of Children’s books.

**Comment by cedelis** [comment]
Related to https://github.com/CARLI/vufind/issues/108

**Comment by gibsonjc** [comment]
MIL - Location facet in local catalog as in current version (this has been a very useful feature for us, at least) should be added.

**Comment by gibsonjc** [comment]
IWU - One thing that I would like to have added back is the limiter for location (SpColl, etc.).

**Comment by gibsonjc** [comment]
SXU - Missing some of our local Locations
We created a few complex locations <see below example> such as Print Books… which is a combination of various other locations, but they do not appear on the new VuFind interface. Is this something we need to recreate under a new tool?  We use this because the Book designator does not distinguish between print book and ebook.
 
Location

HathiTrust eResources (public domain)
Print Books
CARLI eBooks
Juvenile Literature
Haddad Room

**Comment by gibsonjc** [comment]
ONU - My favorite part (so far) is that all of the item locations are available as options on the right side.  Before there were only specialty locations available.  You could always limit by format (book) – but that would include print books and ebooks.  Now we can actually see what lives in the library.

ONU - Yes—all physical locations are nice!  Also, book –v- electronic (format)

**Comment by gibsonjc** [comment]
SXU - Location facet on the right of results -- where too many odd things appear. We need to reduce but not remove all locations.

**Comment by gibsonjc** [comment]
SIC - We have lots of e-resource location codes used in the catalog but we will not want all of those locations to be used as facets under the location facet. Can we assign several location codes to one location facet?

**Comment by gibsonjc** [comment]
NBY - A comparison on how our Voyager locations appear in the current VuFind and in VuFind I hope will demonstrate how much more fragmented and unhelpful VuFInd 3. I can pinpoint in Vufind the following, but not in VuFind 3. Each of these locations contain certain types of material that when selected provide useful more focused faceting.
Ayer Collection (All)
Wing Collection (All)
MapRecon
French Revolution Collection
Bonaparte Collection (All)
Greenlee Collection (All)

**Comment by gibsonjc** [comment]
ISU - major concern that Milner Library has before making a switch to VuFind3.  In the Location Facets on the search results page, we would like to drop Floor designations from unique collections like Special Collections (SpecColl) and Teaching Materials Center (TMC)

Example: https://vufind3.carli.illinois.edu/vf-isu/Search/Results?lookfor=children%27s+literature&type=AllFields

**Comment by gibsonjc** [comment]
LNC - I had to change the OPAC descriptions for a couple of locations (electronic and ebsco) to provide useful descriptions to use in the facets.

**Comment by gibsonjc** [comment]
NPU - Location Facet Questions: does the location facet feature work the same in VuFind 4? I think I’m seeing all locations (and not the location groups I defined in SysAdmin).

**Comment by gibsonjc** [comment]
ISU - While the display of the Location facets in the New VuFind search for ISU is technically correct, we've used the same 'OPAC Location Name' for several different 'Voyager Location Name's and each Voyager Location Name is being displayed as a separate Location facet but with its respective OPAC location name. This presents as many as 8 different location facets - all with the same name but with a different number of (unique) results. Milner has collapsed 22 Voyager location names into 5 OPAC location names. Some, like the TMC OPAC location names, might be resolved by changing all 8 OPAC location name to make them more specific and therefore unique. But that solution wouldn't make sense for others, such as Electronic Resources.

**OPAC location name _Voyager location name_**
Electronic Resources E-Resources _Online_
Electronic Resources E-Resources _PatrDrivenAcq_
Floor 6 Shelves Teaching Materials Center _TMC Dewey_
Floor 6 Shelves Teaching Materials Center _TMC Easy_
Floor 6 Shelves Teaching Materials Center _TMC Fiction_
Floor 6 Shelves Teaching Materials Center _TMC Nonbook_
Floor 6 Shelves Teaching Materials Center _TMC Professional_
Floor 6 Shelves Teaching Materials Center _TMC Textbooks_
Floor 6 Shelves Teaching Materials Center: Building Use Only _TMC Dewey Noncirc_
Floor 6 Shelves Teaching Materials Center: Building Use Only _TMC Professional Noncirc_
Storage Basement: Building Use Only: Request Online Storage _Bsmt Annex Per_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Building Use Only: Request Online Storage _Bsmt Book Noncirc_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Building Use Only: Request Online Storage _Bsmt Docs Noncirc_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Building Use Only: Request Online Storage _Bsmt Ovsz Noncirc_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Building Use Only: Request Online Storage _Bsmt Periodicals_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Request Online Docs Microforms Noncirc
Storage Basement: Request Online Storage _Bsmt Annex_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Request Online Storage _Bsmt Book_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Request Online Storage _Bsmt Docs_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Request Online Storage _Bsmt Microforms_
Storage Basement: Request Online Storage _Bsmt Nonbook_ [currently: Unavailable until 2018: Building improvements in process]
Storage Basement: Request Online Storage _Bsmt Oversize_ [currently: Unavailable until 2018: Building improvements in process]

[moved problem 2 to its own Issue #275 ]

We have resolved these two problem in EDS by providing EBSCO with a map from our Voyager locations to one we ask them to use for our EDS location facet display (called "Where is it?). So, for example, all the Floor locations (whether circulating or noncirculating) display simply as "Milner Library Stacks". We have also asked that they display temporary locations when they are present.

What solutions might be possible to simplify the display of Milner's locations in the VuFind Location facet?

**Comment by gibsonjc** [comment]
CSC - 12/15/2017 open call (recommended contacting CARLI support for reports instead of using location facets)

**Comment by dmcmpbll** [comment]
SXU - SXU remains interested in being able to view Voyager's location limit groups in new VuFind. See comments above on June 7, 2017 and June 3, 2016 for additional details. RT 96677

**Comment by jenhm** [comment]
MBI - Moody is also interested in location limit groups, as they have multiple campuses in multiple physical locations. RT 97891

**Comment by gibsonjc** [comment]
Voyager Location Limit Groups now displaying as expected, when present.  When not present, no local locations will display as facets, only CARLI eBooks and HathiTrust (if they are in local catalogs).  Ready for prod.

**Comment by cedelis** [comment]
In prod.

Commits f7d725e6db86197c9d0ab01168b2c5e176cfe65e
028b353d871f7bc11baace20c0ff50b47795d72b
56f05422a45bcd2c842e612092c9bfeed6e5e47c
357fd459a27eeffb9c53ade5ea9706f7064fe36d
c756ad435aa0a63e368543d9fed9d73b7ae7c30e
8647d6da1959e0133f59f126d21371c995d6aa44
ba1a06bd1c4b859f1db53836c924f5a9615a8ce8
c9aac9241e36b7e9a3c08790f38e6c7d14262088
