### ISSUE TITLE
Request First Available

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#43]
NIU - The option to "Request First Available" is not currently an option in VuFind 3.

**Comment by gibsonjc** [comment]
MIL - The "Request 1st Available" option seems to be missing from the union catalog. That is usually our preferred way of showing patrons how to request I-Share items in the current VuFind catalog.

**Comment by gibsonjc** [comment]
ICC - Will there be something similar to “Request 1st Available”

**Comment by gibsonjc** [comment]
TRN - Will there be a “request first available” sort of functionality at all? My users are accustomed to using that feature rather than try to pick from the list of holding libraries. If that feature will not be present, then the order of display for the holding libraries will be important, as I would expect patrons will fairly consistently pick from the top of the list (however the top of the list is determined), which could affect ILL traffic statistics/workload.

**Comment by gibsonjc** [comment]
LFC - The “request first available” feature that is in the current version of VuFind is very popular with our patrons.  Will that option be possible in the new version, or will patrons need to select which library’s copy of an item they want to request?

**Comment by gibsonjc** [comment]
CSC - I-Share “Request 1st available” option

**Comment by gibsonjc** [comment]
SWI - Just wondering if there is a "Request first Available" in the new VuFind like we had in the old VuFind?

**Comment by gibsonjc** [comment]
MON - 12/14/2017 open call

**Comment by gibsonjc** [comment]
DAC - We were taking a look at the New VuFind interface and noticed that there
doesn't appear to be a Request 1st Available link or button. Is this option
gone for good? Does that mean that requests will no longer be possible by
record, but only by specific copy? I hope not, unless the system also will
send an email if a request is unfilled... RT 97217

**Comment by dgree1** [comment]
SIC, ILC and KNX all interested in "Request 1st Available" in new VuFind.

**Comment by cedelis** [comment]
I thought it might be useful if I put together a comparison of the steps for requesting items between the old and new versions of VuFind.

In the old version of VuFind, the "Request 1st Available," (which is a feature that exists only in the Union Catalog) works like the following:

1. In the Holdings display ("Location & Availability" tab), If there exists a holding for the patron's library, the software lists it at the very top
2. The software randomizes any additional holdings from other libraries
3. The software checks each holding, one-by-one, until it encounters the first requestable item (i.e., the patron has acceptable borrowing privileges for this item)
4. The software presents a selection page where the patron chooses item copy, pick-up library, and pick-up location
5. The patron clicks on the "Request" button

In the current version of VuFind, it is true that there is no specific feature called "Request 1st Available." However, there are some important commonalities with that of the old version of VuFind, specifically in steps 1 thru 3.

Here are the steps for requesting in the new version of VuFind:

1. In the Holdings display ("Holdings" tab), if there exists a holding for the patron's library, the software lists it at the very top
2. The software randomizes any additional holdings from other libraries
3. The patron needs to check each holding (presumably, one-by-one, until the patron notices an item that is "Available")
4. The patron clicks on "Request Item"
5. The software presents a selection page where the patron chooses pick-up library, and pick-up location
6. The patron clicks on the "Place Request" button

**Comment by gibsonjc** [comment]
ROU, MBI, and a third institution - requested this feature at the 5/9/2018 webinar

**Comment by gibsonjc** [comment]
Let's further discuss adding a tab/option/feature to request a system-selected copy in the near future.

**Comment by nmswanson** [comment]
SAI - No Request First Available. This is especially hard with records with
MANY items in the I-Share catalog. Additionally the flag is not very
pronounced and is hard to find amongst the layout.

RT 99380

**Comment by dgree1** [comment]
Principia PRC also supports adding "Request First Available", see RT 100110.

**Comment by gibsonjc** [comment]
@cedelis Wording updates as discussed at our 7/26 meeting:

In local catalogs, the button text for this feature should say: 
Request Item

In I-Share union catalog, the button text for this feature should say: 
Request from I-Share Libraries

Change the "Request Item" link text that appears with every Item in the list under each MFHD to say: 
Request This Item

Debbie will be performing final end-to-end request testing of this feature on Monday 7/30 to make sure that all the data is being passed as expected.

**Comment by cedelis** [comment]
I have changed the labeling. In TEST now.

**Comment by gibsonjc** [comment]
Phase 1 in production as of 8/13/2018.  
https://www.carli.illinois.edu/improved-request-functionality-new-vufind-catalog

**Comment by gibsonjc** [comment]
Phase 2 in TEST as of 8/13/2018 includes:

- new "Check Requestability" link (in place of "Request This Item" in the item listings) that returns immediate feedback if the item chosen is not able to be requested

- ability to select more than one item or a range of items in "Select Item:" list for multi-part titles

**Comment by gibsonjc** [comment]
Phase 2 in PRODUCTION as of 8/27/2018.
https://www.carli.illinois.edu/improved-request-functionality-phase-2-new-vufind-catalog
Closing.
