### ISSUE TITLE
Can call number be added to the search results display?

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#52]
SXU - The brief display of book information is VERY confusing to patrons: 
The call number does not show, but the meaningless OCLC number/code does show.
Can you change the brief display to show call numbers?

ISL - Can a Call number be added to the main results screen?

**Comment by gibsonjc** [comment]
I note that when the results page is still loading, a line labeled

Call Number: Loading...

appears but then disappears

**Comment by gibsonjc** [comment]
However, a call number would not be useful in the results displays for I-Share view.

**Comment by bgant** [comment]
EIU -I don’t like seeing the cryptic “(CARLI) (Other Sources:…) in the brief record.  I guess the (LEWdb)136472) is a database control number that will be confusing and not useful to patrons.

**Comment by bgant** [comment]
EIU - The Sort by Call number would be nice if we could see the call number.

**Comment by bgant** [comment]
Trinity Christian College - - The source bits in the results lists seem pointless from a patron standpoint and clutters up the display when there are a lot of source libraries. (e.g. (CARLI) (Other Sources: (CODdb)247785, (ELMdb)353142, (ISUdb)1759100, (IVCdb)193984, (MMCdb)92959, (NEIdb)751586, (OAKdb)121188, (WRHdb)347264) –and that’s a shorter one!)

[From a librarian perspective, I find them interesting, but not enough to make their presence in the results worth the screen space they take up.]

**Comment by gibsonjc** [comment]
Related to #64 ? "Can Location be added to the search results display?"

**Comment by gibsonjc** [comment]
TRN - Actually, I notice that the available/unavailable status doesn’t show in our individual library results lists at all, nor does the call number/location. Both of those pieces of information are essential for quick item retrieval for both library staff and patrons (especially when the system loads so slowly that having to go into the item record is a real pain!). [And it seems like it starts out like it’s loading the Call Number and Location, but then those disappear when the page finishes displaying… why?]

**Comment by cedelis** [comment]
This requires that VuFind index MFHDs. It currently does not do this.

**Comment by cedelis** [comment]
Related to https://github.com/CARLI/vufind/issues/108

**Comment by gibsonjc** [comment]
MIL - Before, it was easy to see at a glance what was going to be available and write down call numbers.  Now it says “loading” on call number and availability while the search results are being generated, but they disappear in the final, resolved results screen.  As it is formatted now it is too many clicks to get pertinent details.

**Comment by gibsonjc** [comment]
IWU - ...it's helpful to have the call number included on the list of results. This was helpful in the version we have now. 

...the more information you have on the first screen – the results list – the better; including call number, location and availability

I agree with the other comments about call numbers and floor locations needing to be visible in brief results.

...when you do a search and the page is loading, it actually flashes "Call number: loading" up on the screen briefly as if you'll get the call number on the results page. It makes me wonder if that will be available in the live environment.

**Comment by gibsonjc** [comment]
Closing. Call number displays now.
