### ISSUE TITLE
"Browse Alphabetically" option in footer does not work

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#53]
RSH
ISL

Click Browse Alphabetically in the footer and try to use any of the for "By" options.  All return this error:

Error 

An error has occurred

An error occurred during execution; please try again later.

Please contact the Library Reference Department for assistance
noreply@carli.illinois.edu

**Comment by cedelis** [comment]
This is not turned on at the moment. It requires an extra step to the nightly indexing:

https://vufind.org/wiki/indexing:alphabetical_heading_browse

cd /usr/local/vufind
export VUFIND_HOME=/usr/local/vufind
./index-alphabetic-browse.sh

It seems to take a few hours (2-3), but since it is building a separate index for this, it's possible that it won't have too much of an impact on the main bib searching index. We need to decide if it's worth implementing. I have run it once on devel, so you may take a look at it here (firewalled): 

https://vufind3-devel.carli.illinois.edu/vf-eiu

**Comment by gibsonjc** [comment]
At our meeting on June 23, we decided that @cedelis should enable the alphabetical heading browse to run regularly on all three servers (prod, test, and devel) so we can see exactly how it works and also how it reacts to nightly updates.  Once it is turned on and updating regularly we can best evaluate if the Browse options that use it are useful/desirable.  

(This doesn't include Call Number browsing, which we decided to hide/turn off in Issue #56 )

**Comment by cedelis** [comment]
I've enabled alpha browsing to all solr servers (prod, test, and devel). It should be available tomorrow.

**Comment by gibsonjc** [comment]
This seems to be working correctly now on prod and devel, but on test I still get the error when I try to Browse Alphabetically any of the options.

**Comment by gibsonjc** [comment]
Still receive an error on vufind3-test today.  (Prod and devel working ok.)

**Comment by gibsonjc** [comment]
A follow-up question: The documentation on https://vufind.org/wiki/indexing:alphabetical_heading_browse  says "The AlphaBrowse module provides a traditional alphabetical heading browse which allows users to see all of the authors, subjects and titles in your collection, including cross-references extracted from authority data."  I assume our current implementation is only able to use the headings in the bibliographic records and that we do not have access to cross-references (authority data) since we have not loaded/indexed authority records?

**Comment by gibsonjc** [comment]
SIE - It doesn’t appear that the Browse alphabetically search works.  If I do a search, e.g. **By Author** starting from **Austen, Jane**  I get a nice list of results, but when I click on a heading, I get:
No Results!
https://vufind3.carli.illinois.edu/vf-sie/Alphabrowse/Home?source=author&from=Austen%2C+Jane
I also tried a title and a topic search with the same results.

CARLI follow-up: I don't understand what information this list is indexing.  Some of the links are performing a search where _type=AuthorBrowse_, others are doing what looks to be a search on 035 field or ID where _type=ids&lookfor=_ .  The ID searches always fail.  The AuthorBrowse searches fail most of the time but once in a while match some data, as with:
**Austin, Jane, 1775-1817.** https://vufind3.carli.illinois.edu/vf-sie/Search/Results?type=AuthorBrowse&lookfor=%22Austen,%20Jane,%201775-1817.%22

**Comment by gibsonjc** [comment]
This appears to be functioning correctly. Closing.
