### ISSUE TITLE
856 fields display links in the results list but should not display in I-Share view /all/vf*

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#54]
These links come from the bib record and may not be appropriate for all library users using the I-Share view.

These links would be appropriate to display in the local view only because the 856s would be appropriate for that local catalog.

We need to suppress/remove/hide the 856 fields links from display in the results list in the VuFind 3 I-Share union catalog (but not the local catalogs).

**Comment by gibsonjc** [comment]
Moved comment from #86 
Trinity Christian College - -It looks like all 856 fields are being included as part of the result lists, which also looks cluttered. This is especially confusing when none of the links seen on the result screen are displayed when you look at the item record itself (they’re only in the Staff View). e.g. https://vufind3.carli.illinois.edu/all/vf-trn/Record/220843425 What’s the logic there?

**Comment by gibsonjc** [comment]
Current examples in I-Share union catalog:
https://vufind3.carli.illinois.edu/all/vf-uiu/Search/Results?lookfor=harvard+business+review&type=Title&filter%5B%5D=format%3A%22Electronic%22

shows results with links like

"Available only to UIC users"
"Access may be restricted to RUMC users only."
"Available for Chicago State University via EBSCO. Click here to view book."

which are not appropriate for all library users.

**Comment by gibsonjc** [comment]
TRN - Why are those links [bib records 856 links] displaying on the results screen? I can see why the results screen might include 856_40 entries, since that’s theoretically a link to the item, but why would ToC links display? They’re 856_41 entries.

I maintain my comment from the last time around that it is bizarre to have links displayed on the results screen that appear nowhere on the record screen except in the Staff View. This makes no sense to me and will make no sense to my users.

e.g. https://vufind3.carli.illinois.edu/vf-trn/Search/Results?lookfor=jewish&type=AllFields&limit=20&sort=relevance TRNdb.89475 and TRNdb.88840

**Comment by cedelis** [comment]
The SolrMarc record driver now returns no URLs for universal catalog, e.g., /all/vf*.

**Comment by gibsonjc** [comment]
I confirm that 856 fields are no longer displaying in the /all/vf/ results list.  **Ready for Prod.**

Photographic evidence:

Before: (the "Click here for ebook" and "Available online to SIUC..." entries)
![screen shot 2017-07-31 at 9 57 14 am](https://user-images.githubusercontent.com/17598357/28784563-6b724784-75d9-11e7-8d93-6c385a620883.png)

After: (also with # 198 hiding "Get full text" and # 103 hiding "No Image Available" image in place)
![screen shot 2017-07-31 at 10 10 15 am](https://user-images.githubusercontent.com/17598357/28784586-77c385e8-75d9-11e7-8f10-592c6e55be9f.png)
