### ISSUE TITLE
Call number search functions search the Bib call number fields, not MFHD call numbers

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#56]
ISL 

All call number search functions (which already default to LC only, see #45 ) are searching the call number fields in the bibliographic record.  

I-Share libraries might not maintain the call numbers in the bibliographic records since our Voyager system stores functioning call numbers in the MFHD.

**Comment by gibsonjc** [comment]
I think that we should disable the current default call number search, browse, limit, and sort options because they are using call numbers from bib records.  This would "resolve" #45 and #82 .  If/when we index MFHDs (issue #108 ), we can then look at turning these options back on.

**Comment by gibsonjc** [comment]
@cedelis , as we discussed at our meeting today, please hide or turn off the options to Search/Browse by Call Number on vufind3-devel to start.

Here are the places I have seen it:

1. Search by Call Number in the main drop down after the main search box

2. "Browse by Call Number" section on the main front page for each library - https://vufind3-devel.carli.illinois.edu/vf-eiu/

3. Limit to call number on the Advanced search page - https://vufind3-devel.carli.illinois.edu/vf-eiu/Search/Advanced

4. "Call Number" option on the Browse the Catalog page - https://vufind3-devel.carli.illinois.edu/vf-eiu/Browse/Home

5. Sort by Call Number in the drop down menu at the top of any results page - https://vufind3.carli.illinois.edu/vf-eiu/Search/Results?lookfor=cats&type=AllFields

**Comment by cedelis** [comment]
commit a1d52f174b3c71ffdc72335c0be2bd1dafa1e0ec
commit bf2484c300f4ec0fdeed0b9cebaee73420dfc328

**Comment by cedelis** [comment]
I have removed references to Call Number searching in vufind3-devel

commit bf2484c300f4ec0fdeed0b9cebaee73420dfc328
commit a1d52f174b3c71ffdc72335c0be2bd1dafa1e0ec

**Comment by gibsonjc** [comment]
Thanks! I confirm that 1), 2), and 3) are done.

_4) "Call Number" option on the Browse the Catalog page - https://vufind3-devel.carli.illinois.edu/vf-eiu/Browse/Home._  This looks to be gone as an option from the page--which is correct and what I expected--but the whole "Browse the Catalog" link is now gone from the footer, which is not necessary so long as the call number option has been removed from it.  Can we bring the "Browse the Catalog" link back to the "Find More" column of the footer so people can try out the other six options (Tag, Author, Topic, Genre, Region, Era) and see if they are worthwhile?

_5) Sort by Call Number in the drop down menu at the top of any results page - https://vufind3.carli.illinois.edu/vf-eiu/Search/Results?lookfor=cats&type=AllFields_
I still see Call Number as a sort choice.  Can that be removed from the search results **Sort** options lists?

6) I found Call Number hiding in one more place to be hidden: on the "Browse Alphabetically" page it is listed as an option in the drop down: https://vufind3-devel.carli.illinois.edu/vf-bra/Alphabrowse/Home

**Comment by cedelis** [comment]
Sorry about that. Hopefully now all of the call number references are now gone (and the Browse by Catalog link restored):

commit 5421d091cbb94a8b7c09e2a7746c26e23dd89109

**Comment by cedelis** [comment]
In "in Browse the Catalog," I found one more situation where "By Call Number" was showing up: when you expand the Author menu. I removed it.

commit 9fae6978494a1a5467e9bb76f2d462c8a17fbd3a

**Comment by gibsonjc** [comment]
Good catch finding that 7) secondary Browse menu option!

I confirm 4), 5), and 6) are done.  

8) Drat, just noticed there is a Call Number LIMIT on the Advanced Search page that should also probably be hidden: i.e. https://vufind3-devel.carli.illinois.edu/vf-lac/Search/Advanced

**Comment by cedelis** [comment]
OK, I think 8) is fixed too.

Took way too many edits than it should've ;-)

commit 317717ed21e95e0debde8280a5c1c716506c000c
commit 822407153dac0ccd8dffbb8550847d5eaed7840c
commit 155bd72fffaed70db71368d796ed889c2d890140

**Comment by gibsonjc** [comment]
8) appears to be fixed but now, thanks, but I see 2) displaying again on devel when it didn't before:  "_Browse by Call Number" section on the main front page for each library - https://vufind3-devel.carli.illinois.edu/vf-eiu/_

**Comment by cedelis** [comment]
Ugh. By editing a config file I was able to forgo having to edit the template file... or so I thought. 2) should now be gone (again).

commit fbf8c5ca757eaf22141a6c7191c48a6d52407aac

**Comment by gibsonjc** [comment]
I think that did it.  :-) Go ahead and push the removal of call number functions to production and test!
