### ISSUE TITLE
Request Item link needs suppressed for many local catalogs

### ISSUE THREAD

**Issue by slknight** [CARLI/vufind#59]
EIU does not allow requests for EIU items, as we have open stacks. I think many other libraries will also need the request link suppressed in the local catalog.

**Comment by bgant** [comment]
EIU - Items at EIU are not requestable locally.  Is this a setting we can control locally?

**Comment by slknight** [comment]
Hi Brandon,

I just spoke with John Whisler, and he remembers that suppressing the request link for the local catalog was something CARLI did for us in the current iteration of VuFind.

Stacey Knight-Davis
Head of Library Technology Services

Booth Library
Eastern Illinois University                 Office Phone: 217-581-7549
Charleston, IL  61920                       Library Technology Services: 217-581-6091
http://works.bepress.com/stacey_knight-davis/

**Comment by bgant** [comment]
I am not sure if that functionality exists in the VuFind 3.x code, but we have not prioritized and researched this issue yet. 

The documentation can be found at https://vufind.org/wiki/.

**Comment by slknight** [comment]
This is something that should be covered in config.ini, but I did not see a variable there for it.

The code that writes in the storage retrieval links is in holds.php

https://github.com/vufind-org/vufind/blob/0c085090f18e0539a0cb511fbbb88a96f84947e8/module/VuFind/src/VuFind/ILS/Logic/Holds.php#L371

Stacey Knight-Davis
Head of Library Technology Services

Booth Library
Eastern Illinois University                 Office Phone: 217-581-7549
Charleston, IL  61920                       Library Technology Services: 217-581-6091
http://works.bepress.com/stacey_knight-davis/

**Comment by bgant** [comment]
If there isn't a config setting to enable/disable this function, it will probably need to be developed and submitted to Villanova for a future software release.

If you do run across a config setting though, please let us know.

**Comment by slknight** [comment]
Does each institution get its own stylesheet? If so,

class=" placeStorageRetrievalRequest"

could be set to visibility: hidden;

Stacey Knight-Davis
Head of Library Technology Services

Booth Library
Eastern Illinois University                 Office Phone: 217-581-7549
Charleston, IL  61920                       Library Technology Services: 217-581-6091
http://works.bepress.com/stacey_knight-davis/

**Comment by slknight** [comment]
Found the config for this here:

https://github.com/vufind-org/vufind/blob/master/config/vufind/Demo.ini

**Comment by cedelis** [comment]
Just an FYI, but, commenting out the [StorageRetrievalRequests] stanza does not turn off storage retrieval requests. Stanzas (which are denoted by being surrounded by square brackets) are a mechanism for grouping a set of related configuration options; it is not a configuration option in and of itself. Also: we are currently configured to use the XCNCIP2 driver (not the Voyager or VoyagerRestful drivers). Thanks


Edit (June 13, 2017): We've since moved from the XCNCIP2 driver to the VoyagerRestful driver. In the VoyagerRestful driver, I've noticed that commenting out the [ILLRequests] stanza along with a particular library's entry in the [ILLRequestSources] stanza will remove the Request Item link and prevent requests in the local catalog.

**Comment by slknight** [comment]
Chris, thank you for the explanation and pointing out the correct driver. I was not sure which of the many ini files in /vufind/config/vufind in were in use in the CARLI environment. This is a much bigger and more complex project than I usually work with.

I'm not sure if I am in the right part of the source tree yet, but this looks promising
https://github.com/CARLI/vufind/blob/master/module/VuFind/src/VuFind/ILS/Driver/XCNCIP2.php#L313

313   'storageRetrievalRequest' => 'auto',

**Comment by slknight** [comment]
I have a very basic question. Was the Storage Retrieval functionality re-purposed to allow ILL in the consortial environment, or is it still a storage request?

**Comment by eschell** [comment]
I can make the 'Request Item' link not display via an individual institutions css, display: none;. The problem is that the tables of items in the Holdings tab have no way to tell between local and non-local, or even one institution from the other. If we could put a class on the table or row then I could style for the individual institution.

<table class='eiu'>
or in the table row
<tr class='eiu'> or <tr class='local'>

**Comment by cedelis** [comment]
I just wanted to update this ticket since circumstances have changed since this was initially opened. 

We are now using a subclassed VoyagerRestful ILS driver (in place of the XCNCIP2 driver).

**Comment by cedelis** [comment]
The following two steps seem to address this issue. I've tested it in development for a single library. Next, I will need to add this configuration to our administrative scripts (once this has been completed, I will change the status to "Ready for Testing.")

1. to remove link, comment out the [ILLRequests] stanza in VoyagerRestful.ini (actually, since we're using MultiBackend, you need to edit the library's version of this file, e.g., EIUdb.ini):

;[ILLRequests]

I also comment out the rest of the stanza's variables for completeness:

;HMACKeys = item_id:holdings_id
;extraFields = pickUpLibrary:pickUpLibraryLocation:requiredByDate
;defaultRequiredDate = 0:1:0


2. ensure that ILL requests are prevented even if a savvy user were to figure out the URL parameters (and tries to bypass the user interface):

In "[ILLRequestSources]" stanza, comment out the library's entry, e.g.,

;EIUdb = "1@EIUDB20020620112224"

**Comment by gibsonjc** [comment]
@cedelis just to confirm for testing: this is in place now on devel in all local catalogs of institutions that we know at present do not support local requesting in VuFind 0.6, correct?  I believe the list of institutions is in create_local_vufind_instances.sh under "my %not_requestable", but please correct me if that's not right.  Thanks!

These libraries are:
my %not_requestable = (
"adl" => 1,
"aru" => 1,
"cod" => 1,
"con" => 1,
"ctu" => 1,
"dom" => 1,
"eiu" => 1,
"erk" => 1,
"hcd" => 1,
"icc" => 1,
"ilc" => 1,
"ims" => 1,
"ivc" => 1,
"jkm" => 1,
"ken" => 1,
"kis" => 1,
"knx" => 1,
"lac" => 1,
"lew" => 1,
"lfc" => 1,
"mmc" => 1,
"mon" => 1,
"nby" => 1,
"ncc" => 1,
"sfm" => 1,
"sml" => 1,
"ssc" => 1,
"trt" => 1,
"whe" => 1,
"wrh" => 1,)

**Comment by cedelis** [comment]
Correct, @gibsonjc

**Comment by gibsonjc** [comment]
@cedelis Please put this on vufind3-test when possible and I'll ask staff to have a look for any unexpected results.

**Comment by dmcmpbll** [comment]
Checking this on vufind3-test, it appears that all EIU items are not requestable, to either EIU patrons or to I-Share patrons when in the "All I-Share Libraries" view.

Logged in as myself on UIU and as a request-eligible DPU patron, the "request link" does not show for the EIU versions of requestable titles.  So I-Share patrons cannot place I-Share requests for EIU books.

The in-use calendar for EIU runs through 2020, so it is not a calendar permissions issue.

look at EIU title in list, when logged in as DPU:
https://vufind3-test.carli.illinois.edu/all/vf-dpu/Record/275230872
https://vufind3-test.carli.illinois.edu/all/vf-dpu/Record/277144337
https://vufind3-test.carli.illinois.edu/all/vf-dpu/Record/274930878

look at EIU title in list, when logged in as UIU:
https://vufind3-test.carli.illinois.edu/all/vf-uiu/Record/274930878
https://vufind3-test.carli.illinois.edu/all/vf-uiu/Record/277144337
https://vufind3-test.carli.illinois.edu/all/vf-uiu/Record/275230872

---------------------------

When logged in to vufind3-test as a request-eligible EIU patron, no titles at any I-Share library have the request link in the "All I-Share Libraries" search, so EIU patrons cannot place I-Share requests on test.

look at all titles in list when logged in as EIU:
https://vufind3-test.carli.illinois.edu/all/vf-eiu/Record/275230872
https://vufind3-test.carli.illinois.edu/all/vf-eiu/Record/274930878
https://vufind3-test.carli.illinois.edu/all/vf-eiu/Record/277144337

Logging in as a request-eligible COD patron, there are no requests links in the "All I-Share Libraries" search for the same three titles from the "All I-Share Libraries" search, so COD patrons cannot place I-Share requests on test. 
https://vufind3-test.carli.illinois.edu/all/vf-cod/Record/275230872
https://vufind3-test.carli.illinois.edu/all/vf-cod/Record/274930878
https://vufind3-test.carli.illinois.edu/all/vf-cod/Record/277144337

----------------------------

Looking at the holdings on those three titles that are also missing the "Request" links for requestable titles, it looks like the same for LFC, ILC, and KNX; those libraries also do not offer local call slip to their patrons (based on checking current prod VuFind 0.6).

**Comment by dmcmpbll** [comment]
Noticed the "Requested Items" tab is missing in the "Your Account" for the libraries that do not allow local call slip. See screenshot for COD login (no local call slip) vs DPU login (allows local call slip).

![cod-vufind3test-norequesteditemstab](https://user-images.githubusercontent.com/20848151/27710217-8aab0b8a-5ce4-11e7-85a0-93923ceab3cb.PNG)

![dpu-vufind3test-requesteditemstab](https://user-images.githubusercontent.com/20848151/27710225-8d54e356-5ce4-11e7-8294-3492b5537358.PNG)

**Comment by cedelis** [comment]
Thanks, @dmcmpbll 

It is apparent that simply turning off ILLRequesting capabilities via configuration options is not an acceptable solution here.

Back to the drawing board...

**Comment by cedelis** [comment]
Just to be clear:

For institutions such as EIU, is the following the 

in their local catalog (/vf-eiu), which searches only EIU items: Requesting is (completely) disabled

in the "universal" catalogs (/all/vf and /all/vf-xxx), which search all I-Share items (including EIU items): Requesting for EIU items is disabled for EIU patrons only; other I-Share libraries may request them. 

Apparently, disabling Requesting via config.ini settings has an additional undesirable effect of removing the "Requested Items" tabs in the My Account page.

**Comment by cedelis** [comment]
I reverted the code changes I've made since they did not solve this issue (and also added an additional issue).

The status of this issue is back to Accepted, Enhancement, Priority Issue.

More analysis will need to be done.

**Comment by slknight** [comment]
Chris has accurately described the need. EIU needs request functionality in I-Share and we need Requested Items in My Account. Request functionality needs to be suppressed for EIU owned items in both the local and I-Share catalogs.

Sorry to hear that this was not a simple .ini fix. If you need me to test anything let me know.

Stacey Knight-Davis
Head of Library Technology Services
Booth Library
Eastern Illinois University
Phone: 217-581-7549

**Comment by cedelis** [comment]
@gibsonjc This is available on DEVEL at the moment. If it looks okay, I can promote it to TEST.

**Comment by gibsonjc** [comment]
@slknight Stacy, please feel free to test our second try for suppressing local requesting for libraries that do not support it (like EIU) on the TEST server at https://vufind3-test.carli.illinois.edu and let us know how it goes (and if you find any unintended consequences) by commenting directly on this Issue! Thanks!

**Comment by slknight** [comment]
Thanks, I will look this over today. Do you want the Whislers to have a go as well?

Stacey Knight-Davis

**Comment by slknight** [comment]
I've checked this while logged in as me. I have a requested items option in Your Account. However, I do not see request links on most of the titles I've checked in the UC. The one I did get a request button for was a Oak Street.

![image](https://user-images.githubusercontent.com/15163837/28543165-82e33b80-7084-11e7-877f-a991d72e4904.png)

No request link here
![image](https://user-images.githubusercontent.com/15163837/28543248-c50e1d90-7084-11e7-85ce-854120b85005.png)

Oak street without a request link
![image](https://user-images.githubusercontent.com/15163837/28543331-053b36b4-7085-11e7-853d-5a290bba9684.png)

**Comment by dmcmpbll** [comment]
What distinction is VuFind3-test making as the distinction between "Not Charged" and "Available"?
The "Not Charged" items seem to be missing the request links; the "Available" items have the request links. 

In record: https://vufind3-test.carli.illinois.edu/all/vf-cod/Record/284574999, it initially looked like the screenshot below before I charged both TRT items to a COD test patron. Both copies (0 & 1, which really were 1 & 2 in circ) charged with no issues to the patron. 
![thecat](https://user-images.githubusercontent.com/20848151/28592711-8562bef0-714f-11e7-8beb-cd8cf183e695.PNG)

Here's an example I have not tested, so the titles maintain their original statuses. 
Look at the two IEC items, one at OCC and one at WVC stacks. 
Both have item type of Book so should be requestable/chargeable: 
https://vufind3-test.carli.illinois.edu/all/vf-cod/Record/275826677 
![alfranken](https://user-images.githubusercontent.com/20848151/28593262-58508b3e-7151-11e7-9a97-c47d3836626b.PNG)

My initial thought was that if a Copy 0 displayed, the request link was missing. But in the book example above, other copy 0s are "Not Charged" and missing the request link, while some copy 1s are also "Not Charged" with no request link.

**Comment by cedelis** [comment]
@dmcmpbll I was able to reproduce the problems @slknight has been experiencing. And I believe it might be related to what you are now seeing in TEST.

I recently - a few minutes ago - created a bug fix which I think will solve these issues. It's currently in DEVEL, but I'm in the process of pulling down the bug fix on TEST soon (in a few minutes).

**Comment by slknight** [comment]
Much improved. Request is suppressed for local material, shows for UC material.

![image](https://user-images.githubusercontent.com/15163837/28626925-f3df259e-71e5-11e7-9f17-bc65263d9993.png)

Retest of earlier test showing request links

![image](https://user-images.githubusercontent.com/15163837/28627061-56fa1fa8-71e6-11e7-8ae1-a6135c31fb03.png)

**Comment by dmcmpbll** [comment]
Agreed. I reviewed as a COD-test patron and it appears to be working as expected. 

Any COD item viewed in the I-Share catalog or in the local displays with a status of "Not Charged" with no Request Item link. Other library's items are listed with a status of "Available" and a Request Item link.

**Comment by tschwitz** [comment]
Checking in CSU-test right now. For materials in their "ROVER" storage location, the Request Item link appears correctly. Both for copy 1 and copy 0.

**Comment by gibsonjc** [comment]
Suppression of request link for libraries that do not support it is Ready for Production.

**Comment by dmcmpbll** [comment]
Is this fix also on devel? 
Asking re: testing I'm doing for https://github.com/CARLI/vufind/issues/240

**Comment by cedelis** [comment]
@dmcmpbll It should be fixed on devel if it's already in prod.

**Comment by dmcmpbll** [comment]
thanks!
