### ISSUE TITLE
Cover Images

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#61]
ISL 
Cover Images are not currently configured.  Can we enable our existing Syndetics subscriptions to show cover images?

There are so many items with No Image Available. Can that be removed when there is no picture?

The Similar Items tab at the bottom of an Item view is not very helpful if it only relies on pictures and there aren't any pictures.

**Comment by bgant** [comment]
UIS -   Cover images don’t load

**Comment by bgant** [comment]
EIU - Are the book images not displaying because this is a test system?

**Comment by bgant** [comment]
EIU - The link to the Cover Image located near the call number looks like a link to an eBook – very confusing.

**Comment by gibsonjc** [comment]
From Vufind.org: https://vufind.org/wiki/configuration:external_content

We have some Syndetic subscriptions for I-Share and then individual libraries have their own subscriptions for local catalogs.  Latest info to the best of my knowledge is in the CARLI staff wiki:
https://wiki.carli.illinois.edu/us/index.php/Syndetics_Info  Although I presume that whatever is currently configured and working in VuFind production is appropriate.

**Comment by cedelis** [comment]
Commit f9939302cb378ceaa3e938587c37ffa4384d4f44 adds initial Syndetics support. 
Local libraries' settings used for local catalog https://vufind3-devel.carli.illinois.edu/vf-xxx
CARLI's settings used for I-Share catalog https://vufind3-devel.carli.illinois.edu/all/vf-xxx

**Comment by slknight** [comment]
Looking Good! Since I'm fussy, can we get a blank placeholder image instead of the "No Image Available" one? I like the 1x1 blank gif in the current version better.

**Comment by gibsonjc** [comment]
@cedelis when you created the internal file of which library subscribes to which Syndetics content, did you use the FY16 spreadsheet or did you update it when the FY17 was provided to us?  I notice there are a few changes (mostly subscriptions were dropped) for about 6 libraries.  Since tomorrow is FY17 I thought I would check to see if this needed any updating before we push this to production.

**Comment by cedelis** [comment]
FY17

**Comment by gibsonjc** [comment]
Excellent, then these Syndetics improvements are a "go" to production!

**Comment by gibsonjc** [comment]
Syndetics subscriptions implemented June 30/July 1:
- author notes
- cover images
- first chapters (excerpts)
- * reviews

File is at /usr/local/vufind/carli_scripts/SyndeticsSubscribersFY17.txt
