### ISSUE TITLE
Can Location be added to the search results display?

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/vufind#64]
When the results page is still loading, a line labeled

Location: Loading...

appears but then disappears.

**However,  a Location would not be desirable in the results displays for I-Share view.**

**Comment by bgant** [comment]
EIU - I would prefer seeing the call number and location in the Brief Record for a Local Catalog search.  It looks like they are trying to load, but they don’t make it to the finished display.

**Comment by bgant** [comment]
Trinity Christian College - Actually, I notice that the available/unavailable status doesn’t show in our individual library results lists at all, nor does the call number/location. Both of those pieces of information are essential for quick item retrieval for both library staff and patrons (especially when the system loads so slowly that having to go into the item record is a real pain!). [And it seems like it starts out like it’s loading the Call Number and Location, but then those disappear when the page finishes displaying… why?]

**Comment by gibsonjc** [comment]
Related to #52 ? "Can call number be added to the search results display?"

**Comment by cedelis** [comment]
This requires that VuFind index MFHDs. It currently does not do this.

**Comment by cedelis** [comment]
Related to https://github.com/CARLI/vufind/issues/108

**Comment by gibsonjc** [comment]
IWU - ...the more information you have on the first screen – the results list – the better; including call number, location and availability

I agree with the other comments about call numbers and floor locations needing to be visible in brief results.

**Comment by gibsonjc** [comment]
Closing. Location displays now.
