### ISSUE TITLE
Local Items listed first in "All I-Share Libraries" Search

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#68]
UIS - After going to the URL and selecting my university it defaults to searching all I-Share libraries, would it be possible for items that we hold to be given more weight than other universities? I’d imagine the average patron would do their search (without changing anything), click the first result, and request the book from the first library without knowing we had the item available at our institution.

**Comment by bgant** [comment]
Trinity Christian College - - In the current implementation, when our library has a book and someone searches I-Share for that book, our holding is displayed first. That does not currently seem to be the case on this new version, which appears to list holding libraries alphabetically by code (e.g. https://vufind3.carli.illinois.edu/all/vf-trn/Record/252250584), which could lead to unnecessary ILL requests (especially for those of us near the end of the alphabet :-) ). If ours could appear at the top for our patrons, that would be fantastic.

**Comment by gibsonjc** [comment]
Closing; this was added with the fix for Issue #171
