### ISSUE TITLE
Search Words Highlighting in Results

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#72]
UIS - The results has keywords highlighted which, to me, ruins the visual appeal of the page

**Comment by bgant** [comment]
ISL - Highlighting, in bright yellow, the original search terms in the list of results makes it easier for the user to tell which ones might be the most closely related, particularly if the one the database deems “most relevant” is not, in fact, what the user needs. Indicating whether the search terms appear elsewhere in the item (the table of contents or the text) can guide a user who is researching a very specific topic that may not be included in the title, or even the subject heading.

**Comment by gibsonjc** [comment]
See also Issue #135

**Comment by cedelis** [comment]
Done and in devel.

**Comment by cedelis** [comment]
Highlighting reinstated.

**Comment by gibsonjc** [comment]
IWU- There are a lot of colors that seem to distract from the content. Is it necessary to have yellow highlighting of terms?

**Comment by gibsonjc** [comment]
ONU - When you do a search, the search results page seems cluttered and distracting with the search term highlighted multiple times for every result.  Do we really need a partial excerpt from the table of comments showing where my search word was found?

ONU - I don’t mind the highlighting

**Comment by gibsonjc** [comment]
MIL  - personally prefer cleaner look of search results screen on current VF  version, though I appreciate the attempt to highlight where the search  term(s) are being found (TOC, subjects, etc.).

**Comment by gibsonjc** [comment]
We have decided to leave the highlighting feature on and "as is" for now.

**Comment by gibsonjc** [comment]
SAI - We really don't like the bright yellow highlight that appears in search results page. Is there a way to get rid of that OR tone it down by using a different hex color? I don't see that option in the New VuFind Customization form.
RT 98490

SAI - can we also make a plea for getting rid of the obnoxious yellow highlighting of terms? That should either be able to be tailored to your color scheme OR be the more standard selected in *bold *like in EBSCO databases or Summon results. I think our preference is for BOLD.
RT 99468
