### ISSUE TITLE
Suggested Topics

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#76]
EIU - I am going to have to work with the suggested topics to see how they work – not sure about them yet. They seem to be the most generic topics…

**Comment by gibsonjc** [comment]
IWU - Searches return some odd offerings. For example, I just searched Oxford Handbook of Religion and the Arts (a title I know we do not own...). The search returned a number of Oxford Handbooks and the "suggested topics" then keyed off the returned titles - so for example we see "science fiction" (because one of the titles it returned was the Oxford Handbook of Science Fiction.) Something of a distraction...

**Comment by gibsonjc** [comment]
By default, all searches except Author searches will show "Suggested Topics" above the search results based on the subject headings found in the records of the search results.

Author searches display author names above the search results based on the author names found in the records of the search results.  (seems to duplicate Author facet info)

From searches.ini [General] section:

; These are the default recommendations modules to use when no specific setting
; are found in the [TopRecommendations], [SideRecommendations] or
; [NoResultsRecommendations] sections below.
; See the comments above those sections for details on legal settings.  You may
; repeat these lines to load multiple recommendations.
;default_top_recommend[] = MapSelection ; see [MapSelection] below for details
default_top_recommend[] = TopFacets:ResultsTop
default_top_recommend[] = SpellingSuggestions
;default_top_recommend[] = VisualFacets:Visual_Settings
default_side_recommend[] = SideFacets:Results:CheckboxFacets
;default_noresults_recommend[] = SwitchTab
default_noresults_recommend[] = SwitchType
default_noresults_recommend[] = SwitchQuery:::fuzzy
default_noresults_recommend[] = SpellingSuggestions
default_noresults_recommend[] = RemoveFilters
...
[SideRecommendations]
; No search-specific settings by default -- add your own here.
;Subject[]          = SideFacets
;Subject[]          = OpenLibrarySubjectsDeferred:lookfor:5:true:topic,place,person,time

[TopRecommendations]
Author[]            = AuthorFacets
Author[]            = SpellingSuggestions
;Author[]           = WorldCatIdentities
CallNumber[]        = "TopFacets:ResultsTop"    ; disable spelling in this context

[NoResultsRecommendations]
CallNumber[] = SwitchQuery::wildcard:truncatechar
CallNumber[] = RemoveFilters
;CallNumber[] = AlphaBrowseLink:lcc


From facets.ini:
; Facets that will appear at the top of search results when the TopFacets
; recommendations module is used.  See the [TopRecommendations] section of
; searches.ini for more details.
[ResultsTop]
topic_facet = "Suggested Topics"

**Comment by gibsonjc** [comment]
KNX - The search interface will need to be really, really cleaned up before we'd be happy to release this to our patrons. It is much too busy with needless information the way it is now, causing confusion. 

For example, one thing that is most distressing to the eye and brain is the list of suggested topics at the top of a results list. This is clutter. Most users do not know what "topics" are or what it would mean if you clicked on one of the links, and their main goal is to see the results, not be tempted to be taken off in another direction before being presented with their results. 

Also, when you do a known title search and the item is not found, the list of topics still appears even when the topics have nothing, or very little, to do with what you searched for:
https://vufind3.carli.illinois.edu/vf-knx/Search/Results?lookfor=cambridge+history+of+the+second+world+war&type=Title&limit=20&sort=relevance

The system is not capable of generating meaningful topics/subject headings from the search I entered. If it worked well, I would have expected a list of topics related to the second world war. It may be that the system is not capable of determining meaning from a given search and presenting the user with valid, relevant options. If that's the case, then we shouldn't try to present something that looks like it has meaning but really doesn't. 

Students really do have trouble understanding what subject headings are and they mostly do not use them to search, or to re-do a search. They simply cannot understand them. It would be much better if you buried these "topics" back in the limiters list on the side. 

The numbers in the bubbles are also clutter. Could you not make these appear less prominently? --that's all my eye sees is the number bubbles. 

More clutter: There is very little distinction between the headings and the data in the limiters list on the side. Those should be more distinct.

**Comment by gibsonjc** [comment]
ONU - I like the “suggested topics” (they must be LCSH) at the top of the page

**Comment by gibsonjc** [comment]
MIL --Suggested searches: Librarian 1: like this feature, but seems to be entirely based on title word matches, with no inclusion of author or subject matches, which I have seen matched in similar features in other databases (e.g., Ebsco’s ASC or CINAHL). Therefore, if I search an author (e.g., Mark Twain or Jane Austen), I am getting suggested items about them rather than any by them.

**Comment by gibsonjc** [comment]
We decided to turn off Suggested Topics above the search results for now.

Does this just require commenting out this line in facets.ini?

; Facets that will appear at the top of search results when the TopFacets
; recommendations module is used. See the [TopRecommendations] section of
; searches.ini for more details.
[ResultsTop]
topic_facet = "Suggested Topics"

**Comment by gibsonjc** [comment]
LFC - 12/14/2017 open call

**Comment by dgree1** [comment]
Let me know if I can assist. SFX committee discussed Feb. 14.

**Comment by cedelis** [comment]
"Suggested Topics" have been removed from the top of the Search Results page.

Ready for Testing.


Diff:

diff --git a/LOCAL_VF_TEMPLATE/config/vufind/facets.ini b/LOCAL_VF_TEMPLATE/config/vufind/facets.ini
index 996fab4..80e3f73 100644
--- a/LOCAL_VF_TEMPLATE/config/vufind/facets.ini
+++ b/LOCAL_VF_TEMPLATE/config/vufind/facets.ini
@@ -22,7 +22,7 @@
 ; recommendations module is used.  See the [TopRecommendations] section of
 ; searches.ini for more details.
 [ResultsTop]
-topic_facet        = "Suggested Topics"
+;topic_facet        = "Suggested Topics"

 ; This section is used to specify labels for facets that may be applied by parts
 ; of VuFind other than the facet lists defined in this file (for example, the

**Comment by dgree1** [comment]
Great, thanks. Since its on "test" I'll let the SFX committee know.

**Comment by gibsonjc** [comment]
Looks good, ready for Prod!
