### ISSUE TITLE
Author Results above the search results list

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#78]
EIU - Search alternatives might be useful, but I find the list of authors at the top of an author search confusing.  The author list is available in the facets.

**Comment by tschwitz** [comment]
It seems to be retrieving 7XX data from records that contain the same heading as the author searched. For example, a search on "Augustine, Saint, Bishop of Hippo." (in NBT) sends back a number of personal names that aren't see references, then a couple corporate names, including "NetLibrary, Inc."

As a librarian, I probably expect that area to return authority data, such as other name headings that might apply. I'm not sure what a patron would expect there.

**Comment by gibsonjc** [comment]
We decided to turn off the "Author Results" above the search results list for now.

Could this be accomplished by commenting out the Top Recommendations in searches.ini?

[TopRecommendations]
Author[] = AuthorFacets
Author[] = SpellingSuggestions
;Author[] = WorldCatIdentities
CallNumber[] = "TopFacets:ResultsTop" ; disable spelling in this context

**Comment by cedelis** [comment]
In Test.

**Comment by cedelis** [comment]
This one is very trivial. Closing issue.
