### ISSUE TITLE
Disable "Browse by ..." options on Default Search Page

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#79]
EIU - I don’t understand how the Browse by Call Number, Browse by Language, Browse by Format work.

I tried searching for the subject Autism and using the Browse by Call number as a limit and it did not work.

What is the utility of browsing and getting thousands of matches?

**Comment by slknight** [comment]
The search Karen mentions is now working
Advanced search for 
Autism - All Fields
Limit to Call Number R
Returns acceptable results

Also now works to search in all fields on the home screen and then limit with the Call Number facet panel on the Right.

**Comment by gibsonjc** [comment]
On the front page (i.e. https://vufind3.carli.illinois.edu/vf-uiu/) that has a search box and the Browse by Call Number, Browse by Language, and Browse by Format options beneath it, the search box and the "Browse by" options are not meant to be used at the same time.  The "Browse by" choices on that page are not limits.  Either the search box can be used to do a search, or one of the "Browse by" options can be used to browse.  Limits are available to be applied to a search in the Advanced Search options, or Facets can be applied from the "Narrow Search" side bar after a search is run.
