### ISSUE TITLE
“Hide eResources to which I don’t have access”

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#81]
EIU - Where is the “Hide eResources to which I don’t have access box”?  It would be useful to see the note in eBook bibs stating that Access is Restricted to whatever Library owns the eBook like we do now

**Comment by bgant** [comment]
Trinity Christian College - Is there going to be a “Hide eResources to which I don’t have access” option like there is now? That can be quite helpful.

**Comment by bgant** [comment]
First we need to get eResources working properly in VuFind 3.x.

**Comment by gibsonjc** [comment]
MIL - Add the “Hide eResources to which I don’t have access” option back into union catalog.

**Comment by gibsonjc** [comment]
SIE - Is there any way that eBooks from other libraries that can’t be shared could be blocked from the search results? We currently have that function in I-Share. What we have now is perfect and is exactly what we want in VuFind3.

**Comment by gibsonjc** [comment]
TRN - I am still holding out hope that there can be some sort of functionality similar to the current “Hide eResources to which I don’t have access” checkbox. Student confusion abounds when they come across ebooks that they can’t log into.

**Comment by gibsonjc** [comment]
BHC - In the All I-Share Libraries catalog, the “Hide eResources to which I don't have access” check box seems to have disappeared.  I thought it was very useful.  The local codes list displayed in the record would not help my students identify whether or not they have access.

**Comment by gibsonjc** [comment]
IWU - How is this system handling e-books? Including ebooks from other CARLI libraries is my biggest pet peeve. It is useless and frustrating information.  If the default can always be to exclude ebooks from other libraries unless it is a consortial title that would be my preference.

**Comment by gibsonjc** [comment]
TIU - We have not seen an option for searching the I-Share VuFind 3 that can "hide e-resources I don't have access to". Will this feature be added to VuFind 3?

**Comment by gibsonjc** [comment]
MIL - Things we view as obstacles to adopting VF3--IShare hide eResources feature:  The “Hide eResources to which I don’t have access” option is gone when searching IShare.  Would definitely need this feature back.

**Comment by gibsonjc** [comment]
SIC - One of our reference librarians had a question. Will we still be able to filter out other library’s e-resource holdings, like we can now?

**Comment by gibsonjc** [comment]
LFC - Are they getting rid of: Hide eResources to which I don't have access?

**Comment by gibsonjc** [comment]
IIT - Can we get a button that hides eresources that we don't have access to
when doing an ishare search?

**Comment by gibsonjc** [comment]
CSC - Option to check mark “Hide eResources to which I don’t have access”

**Comment by dgree1** [comment]
Relaying message from SFX committee discussion today. Librarians from ILC, SIM and SIC confirming still a major issue to them. ILC not likely to switch until can filter out other library's e-resource holdings in searching all I-Share.

**Comment by gibsonjc** [comment]
Filter to "Hide eResources to which I don't have access" is working as expected as part of the Narrow Search options on the right hand side.  Ready for prod.

**Comment by cedelis** [comment]
In prod.

Commits 
40287d77cded98667db8bbbe81ee7b45df1ac595   
d1139f3449cb3ff5bc1ec39feda462ee8f6541d5   
a8bf3cd20773542de22332209f9264674a795561
