### ISSUE TITLE
"Browse by Call Number" is not working

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#82]
EIU - I tried Browse by call number and got an error message.

An error has occurred

An error occurred during execution; please try again later

Please contact the Library Reference Department for assistance
noreply@carli.illinois.edu

**Comment by cedelis** [comment]
Once I created the browse index on devel, this no longer seems to fail. Related to issue #53.

**Comment by cedelis** [comment]
commit efb1673c3a907403557673b0338bc145480e5ed1
adds alpha browse indexing to nightly update script.

**Comment by cedelis** [comment]
Commit efb1673c3a907403557673b0338bc145480e5ed1 adds alpha browse indexing to nightly update script.

**Comment by cedelis** [comment]
FYI: This feature currently refers to Call Number information in the bib, not the MFHD. I'm not sure if this is useful in our configuration as is. Related to Issues 108.

**Comment by cedelis** [comment]
FYI: This feature currently refers to Call Number information in the bib, not the MFHD. I'm not sure if this is useful in our configuration as is. Related to Issue 108.

**Comment by gibsonjc** [comment]
Closing since changes on #56 removed the option altogether.
