### ISSUE TITLE
"My Account" Logout is Broken

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#84]
EIU - I logged in to My Account and when I tried to log out, I got an error message: "You must be logged in first"

**Comment by bgant** [comment]
Can anyone duplicate this?

**Comment by gibsonjc** [comment]
Is there a login timeout after a certain length of time that might cause the user to be logged out without knowing it and when they then click on Logout it gives this message?

**Comment by dmcmpbll** [comment]
I let my VuFind3 sit idle for 19 minutes and it did not time out.

**Comment by gibsonjc** [comment]
Today I let my logged in browser sit for 3.5 hours and when I clicked the Logout button I did not get an error, the page refreshed, and the Link in the upper right changed to Login.  I am going to close this for now.
