### ISSUE TITLE
All 856 Fields are included in Results List

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#86]
Trinity Christian College - -It looks like all 856 fields are being included as part of the result lists, which also looks cluttered. This is especially confusing when none of the links seen on the result screen are displayed when you look at the item record itself (they’re only in the Staff View). e.g. https://vufind3.carli.illinois.edu/all/vf-trn/Record/220843425 What’s the logic there?

**Comment by gibsonjc** [comment]
Moved to #54
