### ISSUE TITLE
New VuFind is Slow

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#88]
Trinity Christian College - - The new system is noticeably slower to load (so… slow…), which is frustrating.

**Comment by bgant** [comment]
ISL - Perhaps this is specific to the test version, but it seems as if it takes a while for some tabs to load.

**Comment by bgant** [comment]
I will create graphs to chart response time.

**Comment by bgant** [comment]
Response time graphs are now available at: http://orca.carli.illinois.edu/vufind3.html

Next step is to figure out why some servers are faster than others.

**Comment by gibsonjc** [comment]
MIL - Everything is very slow (e.g., promising feature such as auto-populating the search box is too slow to be useful).

**Comment by bgant** [comment]
I have noticed response time problems in our redundant switches in the Production Data Center. I have a meeting on July 14th with campus networking staff to see what options are available. 

In the meantime, on Friday, July 1st, I reconfigured the networking in the new VuFind 3.x servers (Apache, MySQL, Solr) to allow them to talk to each other in a way that avoids the problem. Essentially they now talk directly to each other within a VMware vSwitch without touching real network hardware. 

This had a noticeable effect on response time in the graphs: http://orca.carli.illinois.edu/vufind3-week.html

Moving the XC and Voyager servers to the same vSwitch should improve performance even more, but those changes have not been made yet.

**Comment by bgant** [comment]
We discovered that Jumbo Frames (MTU 9000) was not enabled on one of the new Production VLAN's that this server is on. It was enabled just now and it looks like that change has also helped improve performance when displaying a random record on Production.

**Comment by gibsonjc** [comment]
Closing this older Issue about slowness in vufind 3 from 2016.
