### ISSUE TITLE
self-referring directory in /usr/local/vufind2/public/

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/vufind#9]
JIRA issue created by: Jessica Gibson (gibsonjc)
Originally opened: 2016-03-23 12:57 PM

I happened upon this directory that is referring to itself:

oram@vufind2-test:*/usr/local/vufind2/public*$ ls -la
total 20
drwxr-xr-x   2 root root  4096 Feb  1 15:21 .
drwxr-xr-x 104 root root 12288 Mar 21 11:26 ..
-rw-r--r--   1 root root  2981 Feb  1 15:21 index.php
lrwxrwxrwx   1 root root    25 Sep 14  2015 public -> /usr/local/vufind2/public

I also noticed that each of the /usr/local/vufind2/public-vf-xxx/public/ directories refers to it, too.

oram@vufind2-test:/usr/local/vufind2/public-all-vf-adl/public$ ls -la
total 20
drwxr-xr-x   2 root root  4096 Feb  1 15:21 .
drwxr-xr-x 104 root root 12288 Mar 21 11:26 ..
-rw-r--r--   1 root root  2981 Feb  1 15:21 index.php
lrwxrwxrwx   1 root root    25 Sep 14  2015 public -> /usr/local/vufind2/public

I don't know what this is for, but thought I should point out the endless loop!

**Comment by gibsonjc** [comment]
Investigated and found to be unimportant.
