### ISSUE TITLE
Mobile Login Not Working Properly

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#90]
Trinity Christian College - I also tried the new version on a mobile device. When I tried logging in to my account, it just sat there thinking and never seemed to complete, so I clicked the X and refreshed and found it had managed to log me in even though it still seemed to be loading. Otherwise, the system seems to behave much the same on mobile as it does on desktop (complete with slow load times…).

**Comment by gibsonjc** [comment]
Have not been able to reproduce this.  Closing.
