### ISSUE TITLE
Option to Include/Exclude HathiTrust Records

### ISSUE THREAD

**Issue by bgant** [CARLI/vufind#95]
SIE - Currently we are able to set the local catalog and I-Share to include or exclude Government publications and HathiTrust records. Is there a way to do that in VuFind 3

**Comment by bgant** [comment]
First we need to figure out how to add HathiTrust records to VuFind 3.x.

**Comment by gibsonjc** [comment]
MIL - In advanced search, I’d like the option to remove HathiTrust results back.  Sometimes these results are useful, but other times they overwhelm a search.

**Comment by gibsonjc** [comment]
NBY - We'll begin evaluating it [vufind 3]. Not being able to exclude effectively the HathiTrust titles presents a bit of a challenge. The current VuFind at least allows a user to exclude them from searches in Advanced Search.

**Comment by gibsonjc** [comment]
MIL - would like the option to remove HathiTrust results back.

**Comment by gibsonjc** [comment]
LFC - I find the advanced search not as useful as the old one.  You cannot exclude HathiTrust items or government documents.  I really loved the version line

**Comment by gibsonjc** [comment]
WHE - In VuFind 0.6, in advanced search, there is the ability to define whether or not to include HathiTrust public domain results in the search. I don’t see that capability in VuFind 4.x and wondered if that is a deliberate choice, if I overlooked something, or if this is in the works? Sorry if I’ve missed a prior communication about it.

**Comment by cedelis** [comment]
Ready for Testing

**Comment by gibsonjc** [comment]
Documented on differences page.  Ready for Prod!
